iPlug 2: APIBitmap Class Reference
APIBitmap Class Reference
A base class interface for a bitmap abstraction around the different drawing back end bitmap representations.
#include <IGraphicsPrivate.h>
Public Member Functions
APIBitmap (BitmapData pBitmap, int w, int h, float scale, float drawScale)
APIBitmap constructor.
APIBitmap (const APIBitmap &)=delete
APIBitmap & operator= (const APIBitmap &)=delete
void SetBitmap (BitmapData pBitmap, int w, int h, float scale, float drawScale)
Used to initialise the members after construction.
BitmapData GetBitmap () const
int GetWidth () const
int GetHeight () const
float GetScale () const
float GetDrawScale () const
Detailed Description
A base class interface for a bitmap abstraction around the different drawing back end bitmap representations.
In most cases it does own the bitmap data, the exception being with NanoVG, where the image is loaded onto the GPU as a texture, but still needs to be freed. Most of the time end-users will deal with IBitmap rather than APIBitmap, which is used behind the scenes.
Definition at line 91 of file IGraphicsPrivate.h.
Constructor & Destructor Documentation
APIBitmap() [1/2]
APIBitmap::APIBitmap (BitmapData pBitmap, int w, int h, float scale, float drawScale) inline
APIBitmap constructor.
Parameters
pBitmap pointer or integer index (NanoVG) to the image data
w The width of the bitmap
h The height of the bitmap
scale An integer representing the scale of this bitmap in relation to a 1:1 pixel screen, e.g. 2 for an @2x bitmap
drawScale The draw scale at which this API bitmap was created (used in the context of layers)
Definition at line 101 of file IGraphicsPrivate.h.
APIBitmap() [2/2]
APIBitmap::APIBitmap () inline
Definition at line 109 of file IGraphicsPrivate.h.
~APIBitmap()
virtual APIBitmap::~APIBitmap () inline virtual
Definition at line 117 of file IGraphicsPrivate.h.
Member Function Documentation
GetBitmap()
BitmapData APIBitmap::GetBitmap () const inline
Returns
BitmapData Get the Bitmap data linked to this APIBitmap
Definition at line 138 of file IGraphicsPrivate.h.
Referenced by IGraphicsCanvas::ApplyShadowMask(), IGraphicsCanvas::DrawBitmap(), IGraphicsNanoVG::DrawBitmap(), IGraphicsSkia::DrawBitmap(), IGraphicsCanvas::GetLayerBitmapData(), and IGraphicsNanoVG::GetLayerBitmapData().
GetDrawScale()
float APIBitmap::GetDrawScale () const inline
Returns
the draw scale of the bitmap
Definition at line 150 of file IGraphicsPrivate.h.
Referenced by IGraphicsCanvas::ApplyShadowMask(), IGraphicsNanoVG::ApplyShadowMask(), IGraphics::CheckLayer(), IGraphicsNanoVG::DrawBitmap(), and IBitmap::GetDrawScale().
GetHeight()
int APIBitmap::GetHeight () const inline
Returns
the height of the bitmap
Definition at line 144 of file IGraphicsPrivate.h.
Referenced by IGraphicsCanvas::ApplyShadowMask(), IGraphicsNanoVG::ApplyShadowMask(), IGraphicsCanvas::GetLayerBitmapData(), and IGraphicsNanoVG::GetLayerBitmapData().
GetScale()
float APIBitmap::GetScale () const inline
Returns
the scale of the bitmap
Definition at line 147 of file IGraphicsPrivate.h.
Referenced by IGraphicsCanvas::ApplyShadowMask(), IGraphicsNanoVG::ApplyShadowMask(), IGraphics::CheckLayer(), IGraphicsNanoVG::DrawBitmap(), IBitmap::GetScale(), and IGraphics::LoadBitmap().
GetWidth()
int APIBitmap::GetWidth () const inline
Returns
the width of the bitmap
Definition at line 141 of file IGraphicsPrivate.h.
Referenced by IGraphicsCanvas::ApplyShadowMask(), IGraphicsNanoVG::ApplyShadowMask(), IGraphicsCanvas::GetLayerBitmapData(), and IGraphicsNanoVG::GetLayerBitmapData().
SetBitmap()
void APIBitmap::SetBitmap (BitmapData pBitmap, int w, int h, float scale, float drawScale) inline
Used to initialise the members after construction.
Parameters
pBitmap pointer or integer index (NanoVG) to the image data
w The width of the bitmap
h The height of the bitmap
scale The scale of this bitmap in relation to a 1:1 pixel screen, e.g. 2 for an @2x bitmap
drawScale The draw scale at which this API bitmap was created (used in the context of layers)
Definition at line 128 of file IGraphicsPrivate.h.
The documentation for this class was generated from the following file:
IGraphicsPrivate.h