iPlug 2: IGraphicsSkia Class Reference
IGraphicsSkia Class Reference
IGraphics::DrawClasses
IGraphics draw class using Skia.
#include <IGraphicsSkia.h>
Classes
class Bitmap
struct Font
Public Member Functions
IGraphicsSkia (IGEditorDelegate &dlg, int w, int h, int fps, float scale)
const char * GetDrawingAPIStr () override
void BeginFrame () override
Called at the beginning of drawing.
void EndFrame () override
Called by some drawing API classes to finally blit the draw bitmap onto the screen or perform other cleanup after drawing.
void OnViewInitialized (void *pContext) override
Called after platform view initialization, so that drawing classes can e.g.
void OnViewDestroyed () override
Called after a platform view is destroyed, so that drawing classes can e.g.
void DrawResize () override
void DrawBitmap (const IBitmap &bitmap, const IRECT &dest, int srcX, int srcY, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context.
void PathClear () override
Clear the stack of path drawing commands.
void PathClose () override
Close the path that is being specified.
void PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding) override
Add an arc to the current path.
void PathMoveTo (float x, float y) override
Move the current point in the current path.
void PathLineTo (float x, float y) override
Add a line to the current path from the current point to the specified location.
void PathCubicBezierTo (float x1, float y1, float x2, float y2, float x3, float y3) override
Add a cubic bezier to the current path from the current point to the specified location.
void PathQuadraticBezierTo (float cx, float cy, float x2, float y2) override
Add a quadratic bezier to the current path from the current point to the specified location.
void PathStroke (const IPattern &pattern, float thickness, const IStrokeOptions &options, const IBlend *pBlend) override
Stroke the current current path.
void PathFill (const IPattern &pattern, const IFillOptions &options, const IBlend *pBlend) override
Fill the current current path.
void DrawFastDropShadow (const IRECT &innerBounds, const IRECT &outerBounds, float xyDrop, float roundness, float blur, IBlend *pBlend) override
NanoVG only.
IColor GetPoint (int x, int y) override
Get the color at an X, Y location in the graphics context.
void * GetDrawContext () override
Gets a void pointer to underlying drawing context, for the IGraphics backend See draw class implementation headers (e.g.
bool BitmapExtSupported (const char *ext) override
Checks a file extension and reports whether this drawing API supports loading that extension.
int AlphaChannel () const override
bool FlippedBitmap () const override
APIBitmap * CreateAPIBitmap (int width, int height, float scale, double drawScale, bool cacheable=false) override
Creates a new API bitmap, either in memory or as a GPU texture.
void ApplyLayerDropShadow (ILayerPtr &layer, const IShadow &shadow) override
Applies a drop shadow directly onto a layer.
void GetLayerBitmapData (const ILayerPtr &layer, RawBitmapData &data) override
Get the contents of a layer as Raw RGBA bitmap data NOTE: you should only call this within IControl::Draw()
void ApplyShadowMask (ILayerPtr &layer, RawBitmapData &mask, const IShadow &shadow) override
Implemented by a graphics backend to apply a calculated shadow mask to a layer, according to the shadow settings specified.
void UpdateLayer () override
Implemented by a graphics backend to prepare for drawing to the layer at the top of the stack.
void DrawMultiLineText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend) override
Draw some multi-line text to the graphics context in a specific rectangle (NanoVG only)
Public Member Functions inherited from IGraphics
virtual void BeginFrame ()
Called at the beginning of drawing.
virtual void OnViewInitialized (void *pContext)
Called after platform view initialization, so that drawing classes can e.g.
virtual void OnViewDestroyed ()
Called after a platform view is destroyed, so that drawing classes can e.g.
virtual void EndFrame ()
Called by some drawing API classes to finally blit the draw bitmap onto the screen or perform other cleanup after drawing.
virtual void DrawSVG (const ISVG &svg, const IRECT &bounds, const IBlend *pBlend=0, const IColor *pStrokeColor=nullptr, const IColor *pFillColor=nullptr)
Draw an SVG image to the graphics context.
virtual void DrawRotatedSVG (const ISVG &svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend *pBlend=0)
Draw an SVG image to the graphics context with rotation.
virtual void DrawBitmap (const IBitmap &bitmap, const IRECT &bounds, int srcX, int srcY, const IBlend *pBlend=0)=0
Draw a bitmap (raster) image to the graphics context.
virtual void DrawFittedBitmap (const IBitmap &bitmap, const IRECT &bounds, const IBlend *pBlend=0)
Draw a bitmap (raster) image to the graphics context, scaling the image to fit the bounds.
virtual void DrawRotatedBitmap (const IBitmap &bitmap, float destCentreX, float destCentreY, double angle, const IBlend *pBlend=0)
Draw a bitmap (raster) image to the graphics context with rotation.
virtual void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend=0)
Fill a rectangle corresponding to a pixel on a 1:1 screen with a color.
virtual void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend=0, float thickness=1.f)
Draw a line to the graphics context.
virtual void DrawDottedLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend=0, float thickness=1.f, float dashLen=2.f)
Draw a dotted line to the graphics context.
virtual void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend=0, float thickness=1.f)
Draw a triangle to the graphics context.
virtual void DrawRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0, float thickness=1.f)
Draw a rectangle to the graphics context.
virtual void DrawRoundRect (const IColor &color, const IRECT &bounds, float cornerRadius=5.f, const IBlend *pBlend=0, float thickness=1.f)
Draw a rounded rectangle to the graphics context.
virtual void DrawRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend=0, float thickness=1.f)
Draw a rounded rectangle to the graphics context with individual corner roundness.
virtual void DrawArc (const IColor &color, float cx, float cy, float r, float a1, float a2, const IBlend *pBlend=0, float thickness=1.f)
Draw an arc to the graphics context.
virtual void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend=0, float thickness=1.f)
Draw a circle to the graphics context.
virtual void DrawEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0, float thickness=1.f)
Draw an ellipse within a rectangular region of the graphics context.
virtual void DrawEllipse (const IColor &color, float x, float y, float r1, float r2, float angle=0.0, const IBlend *pBlend=0, float thickness=1.f)
Draw an ellipse around a central point given two radii and an angle of orientation.
virtual void DrawConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend=0, float thickness=1.f)
Draw a convex polygon to the graphics context.
virtual void DrawDottedRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0, float thickness=1.f, float dashLen=2.f)
Draw a dotted rectangle to the graphics context.
virtual void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend=0)
Fill a triangle with a color.
virtual void FillRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0)
Fill a rectangular region of the graphics context with a color.
virtual void FillRoundRect (const IColor &color, const IRECT &bounds, float cornerRadius=5.f, const IBlend *pBlend=0)
Fill a rounded rectangle with a color.
virtual void FillRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend=0)
Fill a rounded rectangle with a color.
virtual void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend=0)
Fill a circle with a color.
virtual void FillEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend=0)
Fill an ellipse within a rectangular region of the graphics context.
virtual void FillEllipse (const IColor &color, float x, float y, float r1, float r2, float angle=0.0, const IBlend *pBlend=0)
Fill an ellipse.
virtual void FillArc (const IColor &color, float cx, float cy, float r, float a1, float a2, const IBlend *pBlend=0)
Fill an arc segment with a color.
virtual void FillConvexPolygon (const IColor &color, float *x, float *y, int nPoints, const IBlend *pBlend=0)
Fill a convex polygon with a color.
void DrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=0)
Draw some text to the graphics context in a specific rectangle.
void DrawText (const IText &text, const char *str, float x, float y, const IBlend *pBlend=0)
Draw some text to the graphics context at a point.
virtual float MeasureText (const IText &text, const char *str, IRECT &bounds) const
Measure the rectangular region that some text will occupy.
virtual void DrawMultiLineText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=0)
Draw some multi-line text to the graphics context in a specific rectangle (NanoVG only)
virtual IColor GetPoint (int x, int y)=0
Get the color at an X, Y location in the graphics context.
virtual void * GetDrawContext ()=0
Gets a void pointer to underlying drawing context, for the IGraphics backend See draw class implementation headers (e.g.
virtual const char * GetDrawingAPIStr ()=0
virtual IBitmap ScaleBitmap (const IBitmap &inBitmap, const char *cacheName, int targetScale)
Returns a new IBitmap, an integer scaled version of the input, and adds it to the cache.
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
Adds an IBitmap to the cache/static storage.
virtual void ReleaseBitmap (const IBitmap &bitmap)
Releases an IBitmap from the cache/static storage.
IBitmap GetScaledBitmap (IBitmap &inBitmap)
Get a version of the input bitmap from the cache that corresponds to the current screen scale For example, when IControl::OnRescale() is called bitmap-based IControls can load in.
virtual bool BitmapExtSupported (const char *ext)=0
Checks a file extension and reports whether this drawing API supports loading that extension.
virtual void DrawFastDropShadow (const IRECT &innerBounds, const IRECT &outerBounds, float xyDrop=5.f, float roundness=0.f, float blur=10.f, IBlend *pBlend=nullptr)
NanoVG only.
void DrawBitmap (const IBitmap &bitmap, const IRECT &bounds, int frame=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (const IBitmap &bitmap, const IRECT &bounds, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws mono spaced bitmap text.
void DrawLineAcross (const IColor &color, const IRECT &bounds, EDirection dir, float pos, const IBlend *pBlend=0, float thickness=1.f)
Draw a horzional or vertical line, within a rectangular region of the graphics context.
void DrawVerticalLine (const IColor &color, const IRECT &bounds, float x, const IBlend *pBlend=0, float thickness=1.f)
Draw a vertical line, within a rectangular region of the graphics context.
void DrawHorizontalLine (const IColor &color, const IRECT &bounds, float y, const IBlend *pBlend=0, float thickness=1.f)
Draw a horizontal line, within a rectangular region of the graphics context.
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0, float thickness=1.f)
Draw a clipped vertical line at a position bounds.
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0, float thickness=1.f)
Draw a clipped horizontal line at a position bounds.
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0, float thickness=1.f)
Draw a radial line to the graphics context, useful for pointers on dials.
virtual void DrawGrid (const IColor &color, const IRECT &bounds, float gridSizeH, float gridSizeV, const IBlend *pBlend=0, float thickness=1.f)
Draw a grid to the graphics context.
virtual void DrawData (const IColor &color, const IRECT &bounds, float *normYPoints, int nPoints, float *normXPoints=nullptr, const IBlend *pBlend=0, float thickness=1.f, const IColor *pFillColor=nullptr)
Draw a line between a collection of normalized points.
virtual bool LoadFont (const char *fontID, const char *fileNameOrResID)
Load a font to be used by the graphics context.
virtual bool LoadFont (const char *fontID, void *pData, int dataSize)
Load a font from in-memory data to be used by the graphics context.
bool LoadFont (const char *fontID, const char *fontName, ETextStyle style)
Load a font with a particular style (bold, italic) from a font file.
void StartLayer (IControl *pOwner, const IRECT &r, bool cacheable=false)
Create an IGraphics layer.
void ResumeLayer (ILayerPtr &layer)
If a layer already exists, continue drawing to it.
ILayerPtr EndLayer ()
End an IGraphics layer.
bool CheckLayer (const ILayerPtr &layer)
Test to see if a layer needs drawing, for instance if the control's bounds were changed.
void DrawLayer (const ILayerPtr &layer, const IBlend *pBlend=nullptr)
Draw a layer to the main IGraphics context.
void DrawFittedLayer (const ILayerPtr &layer, const IRECT &bounds, const IBlend *pBlend)
Draw a layer to the main IGraphics context, fitting it to a rectangle that is different to the layer's bounds.
void DrawRotatedLayer (const ILayerPtr &layer, double angle)
Draw a layer to the main IGraphics context, with rotation.
virtual void ApplyLayerDropShadow (ILayerPtr &layer, const IShadow &shadow)
Applies a drop shadow directly onto a layer.
virtual void GetLayerBitmapData (const ILayerPtr &layer, RawBitmapData &data)=0
Get the contents of a layer as Raw RGBA bitmap data NOTE: you should only call this within IControl::Draw()
virtual void PathClear ()=0
Clear the stack of path drawing commands.
virtual void PathClose ()=0
Close the path that is being specified.
void PathLine (float x1, float y1, float x2, float y2)
Add a line to the current path.
void PathRadialLine (float cx, float cy, float angle, float rMin, float rMax)
Add a radial line to the current path.
void PathTriangle (float x1, float y1, float x2, float y2, float x3, float y3)
Add a triangle to the current path.
void PathRect (const IRECT &bounds)
Add a rectangle to the current path.
void PathRoundRect (const IRECT &bounds, float ctl, float ctr, float cbl, float cbr)
Add a rounded rectangle to the current path, with independent corner roundness.
void PathRoundRect (const IRECT &bounds, float cornerRadius=5.f)
Add a rounded rectangle to the current path.
virtual void PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding=EWinding::CW)=0
Add an arc to the current path.
void PathCircle (float cx, float cy, float r)
Add a circle to the current path.
void PathEllipse (const IRECT &bounds)
Add an ellipse to the current path, specifying the rectangular region.
void PathEllipse (float x, float y, float r1, float r2, float angle=0.0)
Add an ellipse to the current path.
void PathConvexPolygon (float *x, float *y, int nPoints)
Add a convex polygon to the current path.
virtual void PathMoveTo (float x, float y)=0
Move the current point in the current path.
virtual void PathLineTo (float x, float y)=0
Add a line to the current path from the current point to the specified location.
virtual void PathSetWinding (bool clockwise)
NanoVG only.
virtual void PathCubicBezierTo (float c1x, float c1y, float c2x, float c2y, float x2, float y2)=0
Add a cubic bezier to the current path from the current point to the specified location.
virtual void PathQuadraticBezierTo (float cx, float cy, float x2, float y2)=0
Add a quadratic bezier to the current path from the current point to the specified location.
virtual void PathStroke (const IPattern &pattern, float thickness, const IStrokeOptions &options=IStrokeOptions(), const IBlend *pBlend=0)=0
Stroke the current current path.
virtual void PathFill (const IPattern &pattern, const IFillOptions &options=IFillOptions(), const IBlend *pBlend=0)=0
Fill the current current path.
void PathTransformSave ()
Save the current affine transform of the current path.
void PathTransformRestore ()
Restore the affine transform of the current path, to the previously saved state.
void PathTransformReset (bool clearStates=false)
Reset the affine transform of the current path, to the default state.
void PathTransformTranslate (float x, float y)
Apply a translation transform to the current path.
void PathTransformScale (float x, float y)
Apply a scale transform to the current path, with independant x, y scales.
void PathTransformScale (float scale)
Apply a scale transform to the current path, with independant x, y scales.
void PathTransformRotate (float angle)
Apply a rotation transform to the current path.
void PathTransformSkew (float xAngle, float yAngle)
Apply a skew transform to the current path.
void PathTransformMatrix (const IMatrix &matrix)
Apply an arbitary affine transform matrix to the current path.
void PathClipRegion (const IRECT r=IRECT())
Clip the current path to a particular region.
virtual void PathTransformSetMatrix (const IMatrix &matrix)=0
void DoTextRotation (const IText &text, const IRECT &bounds, const IRECT &rect)
virtual void AttachPlatformView (const IRECT &r, void *pView)
Add an OS view as a sub-view, on top of the IGraphics view.
virtual void RemovePlatformView (void *pView)
Remove a previously attached platform view from the IGraphics view.
virtual void HidePlatformView (void *pView, bool hide)
Hide a previously attached platform view from the IGraphics view.
virtual void GetMouseLocation (float &x, float &y) const =0
Get the x, y position of the mouse cursor.
virtual void HideMouseCursor (bool hide=true, bool lock=true)=0
Call to hide/show the mouse cursor.
virtual void MoveMouseCursor (float x, float y)=0
Force move the mouse cursor to a specific position.
virtual ECursor SetMouseCursor (ECursor cursorType=ECursor::ARROW)
Sets the mouse cursor to one of ECursor (implementations should return the result of the base implementation)
virtual void ForceEndUserEdit ()=0
Call to force end text entry (will cancel any half input text.
virtual void * OpenWindow (void *pParentWnd)=0
Open a new platform view for this graphics context.
virtual void CloseWindow ()=0
Close the platform view for this graphics context.
virtual void * GetWindow ()=0
Get a pointer to the platform view e.g.
virtual bool WindowIsOpen ()
virtual bool GetTextFromClipboard (WDL_String &str)=0
Get text from the clipboard.
virtual bool SetTextInClipboard (const char *str)=0
Set text in the clipboard.
virtual bool SetFilePathInClipboard (const char *path)
Set a file path in the clipboard.
virtual bool InitiateExternalFileDragDrop (const char *path, const IRECT &iconBounds)
Initiate an drag-n-drop operation of an existing file, to be dropped outside of the current window.
virtual void UpdateTooltips ()=0
Call this if you modify control tool tips at runtime.
virtual EMsgBoxResult ShowMessageBox (const char *str, const char *title, EMsgBoxType type, IMsgBoxCompletionHandlerFunc completionHandler=nullptr)=0
Pop up a modal platform message box dialog.
virtual void PromptForFile (WDL_String &fileName, WDL_String &path, EFileAction action=EFileAction::Open, const char *ext="", IFileDialogCompletionHandlerFunc completionHandler=nullptr)=0
Create a platform file prompt dialog to choose a path for opening/saving a single file.
virtual void PromptForDirectory (WDL_String &dir, IFileDialogCompletionHandlerFunc completionHandler=nullptr)=0
Create a platform file prompt dialog to choose a directory path for opening/saving a directory.
virtual bool PromptForColor (IColor &color, const char *str="", IColorPickerHandlerFunc func=nullptr)=0
Create a platform color chooser dialog.
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
Open a URL in the platforms default browser.
virtual const char * GetPlatformAPIStr ()
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)
virtual void SetWinModuleHandle (void *pHinstance)
Used on Windows to set the HINSTANCE module handle, which allows graphics APIs to load resources from the binary.
virtual void * GetWinModuleHandle ()
void SetPlatformContext (void *pContext)
Set the platform draw context Used in order to set the platform level draw context - CGContextRef context on macOS and the GDI HDC draw context handle on Windows.
void * GetPlatformContext ()
Get the platform level draw context - an HDC or CGContextRef.
virtual void ClientToScreen (float &x, float &y)
Convert an x, y position in the view to screen coordinates.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, const char *fileNameOrResID)=0
Load a font from disk or resource in a platform format.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, void *pData, int dataSize)=0
Load a font from data in memory.
virtual PlatformFontPtr LoadPlatformFont (const char *fontID, const char *fontName, ETextStyle style)=0
Load a system font in a platform format.
virtual void CachePlatformFont (const char *fontID, const PlatformFontPtr &font)=0
Called to indicate that the platform should cache data about the platform font if needed.
virtual const char * GetBundleID () const
Get the bundle ID on macOS and iOS, returns emtpy string on other OSs.
virtual const char * GetAppGroupID () const
Get the app group ID on macOS and iOS, returns emtpy string on other OSs.
IGraphics (IGEditorDelegate &dlg, int w, int h, int fps=DEFAULT_FPS, float scale=1.)
IGraphics (const IGraphics &)=delete
IGraphics & operator= (const IGraphics &)=delete
void SetScreenScale (float scale)
Called by the platform IGraphics class when moving to a new screen to set DPI.
void SetTranslation (float x, float y)
Called by some platform IGraphics classes in order to translate the graphics context, in response to e.g.
bool IsDirty (IRECTList &rects)
Called repeatedly at frame rate by the platform class to check what the graphics context says is dirty.
void Draw (IRECTList &rects)
Called by the platform class indicating a number of rectangles in the UI that need to redraw.
void PromptUserInput (IControl &control, const IRECT &bounds, int valIdx=0)
Prompt for user input either using a text entry or pop up menu.
void CreatePopupMenu (IControl &control, IPopupMenu &menu, const IRECT &bounds, int valIdx=0)
Shows a pop up/contextual menu in relation to a rectangular region of the graphics context.
void CreatePopupMenu (IControl &control, IPopupMenu &menu, float x, float y, int valIdx=0)
Shows a pop up/contextual menu at point.
void CreateTextEntry (IControl &control, const IText &text, const IRECT &bounds, const char *str="", int valIdx=0)
Create a text entry box.
void SetControlValueAfterTextEdit (const char *str)
Called by the platform class after returning from a text entry in order to update a control with a new value.
void SetControlValueAfterPopupMenu (IPopupMenu *pMenu)
Called by PopupMenuControl in order to update a control with a new value after returning from the non-blocking menu.
void DeleteFromPopupMenu (IPopupMenu *pMenu, int itemIdx)
Called by IOS platform (or other supported platforms) in order to update a control with a deletion interaction on a popup menu.
void SetScaleConstraints (float lo, float hi)
Sets the minimum and maximum (draw) scaling values.
void Resize (int w, int h, float scale, bool needsPlatformResize=true)
void SetStrictDrawing (bool strict)
Enables strict drawing mode.
void SetLayoutOnResize (bool layoutOnResize)
int Width () const
Gets the width of the graphics context.
int Height () const
Gets the height of the graphics context.
int WindowWidth () const
Gets the width of the graphics context including draw scaling.
int WindowHeight () const
Gets the height of the graphics context including draw scaling.
int FPS () const
Gets the drawing frame rate.
float GetDrawScale () const
Gets the graphics context scaling factor.
float GetScreenScale () const
Gets the screen/display scaling factor, e.g.
int GetRoundedScreenScale () const
Gets the screen/display scaling factor, rounded up.
float GetTotalScale () const
Gets the combined draw and screen/display scaling factor.
IRECT GetPixelSnapped (IRECT &r) const
Gets the nearest backing pixel aligned rect to the input IRECT.
IGEditorDelegate * GetDelegate ()
Gets a pointer to the delegate class that handles communication to and from this graphics context.
IPopupMenu & GetPromptMenu ()
bool IsInPlatformTextEntry ()
IControl * GetControlInTextEntry ()
void ClearInTextEntryControl ()
Called when the text entry is dismissed, to reset mInTextEntry.
bool TooltipsEnabled () const
EUIResizerMode GetResizerMode () const
bool GetResizingInProcess () const
bool EnableMultiTouch (bool enable)
Enable/disable multi touch, if platform supports it.
bool MultiTouchEnabled () const
virtual bool PlatformSupportsMultiTouch () const
void EnableTooltips (bool enable)
void AssignParamNameToolTips ()
Call this method in order to create tool tips for every IControl that show the associated parameter's name.
void ShowControlBounds (bool enable)
void ShowAreaDrawn (bool enable)
bool ShowAreaDrawnEnabled () const
bool ShowControlBoundsEnabled () const
void EnableLiveEdit (bool enable)
Live edit mode allows you to relocate controls at runtime in debug builds.
bool LiveEditEnabled () const
IRECT GetBounds () const
Returns an IRECT that represents the entire UI bounds This is useful for programatically arranging UI elements by slicing up the IRECT using the various IRECT methods.
void SetDisplayTickFunc (IDisplayTickFunc func)
Sets a function that is called at the frame rate, prior to checking for dirty controls.
void SetUIAppearanceChangedFunc (IUIAppearanceChangedFunc func)
Sets a function that is called when the OS appearance (light/dark mode) is changed.
void SetKeyHandlerFunc (IKeyHandlerFunc func)
Set a function that is called when key presses are not intercepted by any controls.
void SetQwertyMidiKeyHandlerFunc (std::function< void(const IMidiMsg &msg)> func=nullptr)
A helper to set the IGraphics KeyHandlerFunc in order to make an instrument playable via QWERTY keys.
bool RespondsToGesture (float x, float y)
Called by platform class to see if the point at x, y is linked to a gesture recognizer.
void OnGestureRecognized (const IGestureInfo &info)
Called by platform class when a gesture is recognized.
virtual float GetPlatformWindowScale () const
Returns a scaling factor for resizing parent windows via the host/plugin API.
void ForAllControlsFunc (IControlFunction func)
For all controls, including the "special controls" call a method.
template<typename T , typename... Args>
void ForAllControls (T method, Args... args)
For all controls, including the "special controls" call a method.
void ForStandardControlsFunc (IControlFunction func)
For all standard controls in the main control stack perform a function.
template<typename T , typename... Args>
void ForMatchingControls (T method, int paramIdx, Args... args)
For all standard controls in the main control stack that are linked to a specific parameter, call a method.
void ForControlWithParam (int paramIdx, IControlFunction func)
For all standard controls in the main control stack that are linked to a specific parameter, execute a function.
void ForControlWithParam (const std::initializer_list< int > &params, IControlFunction func)
For all standard controls in the main control stack that are linked to one of several parameters, execute a function.
void ForControlInGroup (const char *group, IControlFunction func)
For all standard controls in the main control stack that are linked to a group, execute a function.
void AttachBackground (const char *fileName)
Attach an IBitmapControl as the lowest IControl in the control stack to be the background for the graphics context.
void AttachSVGBackground (const char *fileName)
Attach an ISVGControl as the lowest IControl in the control stack to be the background for the graphics context.
void AttachPanelBackground (const IPattern &color)
Attach an IPanelControl as the lowest IControl in the control stack to fill the background with a solid color.
void AttachCornerResizer (EUIResizerMode sizeMode=EUIResizerMode::Scale, bool layoutOnResize=false, const IColor &color=COLOR_TRANSLUCENT, const IColor &mouseOverColor=COLOR_BLACK, const IColor &dragColor=COLOR_BLACK, float size=20.f)
Attach the default control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachCornerResizer (ICornerResizerControl *pControl, EUIResizerMode sizeMode=EUIResizerMode::Scale, bool layoutOnResize=false)
Attach your own control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachPopupMenuControl (const IText &text=DEFAULT_TEXT, const IRECT &bounds=IRECT())
Attach a control for pop-up menus, to override platform style menus.
void RemovePopupMenuControl ()
Remove the IGraphics popup menu, use platform popup menu if available.
void AttachTextEntryControl ()
Attach a control for text entry, to override platform text entry.
void RemoveTextEntryControl ()
Remove the IGraphics text entry, use platform text entry if available.
void AttachBubbleControl (const IText &text=DEFAULT_TEXT)
Attach the default control to show text as a control changes.
void AttachBubbleControl (IBubbleControl *pControl)
Attach a custom control to show text as a control changes.
void ShowBubbleControl (IControl *pCaller, float x, float y, const char *str, EDirection dir=EDirection::Horizontal, IRECT minimumContentBounds=IRECT())
void SetFPSDisplayBounds (const IRECT &bounds)
void ShowFPSDisplay (bool enable)
Shows a control to display the frame rate of drawing.
bool ShowingFPSDisplay ()
IControl * AttachControl (IControl *pControl, int ctrlTag=kNoTag, const char *group="")
Attach an IControl to the graphics context and add it to the top of the control stack.
IControl * GetControl (int idx)
Get the control at a certain index in the control stack.
int GetControlIdx (IControl *pControl) const
Get the index of a particular IControl in the control stack.
int GetIdxOfTaggedControl (int ctrlTag) const
Gets the index of a tagged control.
IControl * GetControlWithTag (int ctrlTag) const
Get the control with a particular tag.
int GetControlTag (const IControl *pControl) const
Get the tag given to a control.
IControl * GetControlWithParamIdx (int paramIdx)
Get the first control with a parameter index that matches paramIdx.
bool ControlIsCaptured () const
Check to see if any control is captured.
bool ControlIsCaptured (IControl *pControl) const
Check to see if the control is already captured.
void GetTouches (IControl *pControl, std::vector< ITouchID > &touchesOnThisControl) const
Populate a vector with the touchIDs active on pControl.
IControl * GetBackgroundControl ()
IPopupMenuControl * GetPopupMenuControl ()
ITextEntryControl * GetTextEntryControl ()
IBubbleControl * GetBubbleControl (int i=0)
int NBubbleControls () const
void StyleAllVectorControls (const IVStyle &style)
Helper method to style all of the controls which inherit IVectorBase.
void UpdatePeers (IControl *pCaller, int callerValIdx)
This method is called after interacting with a control, so that any other controls linked to the same parameter index, will also be set dirty, and have their values updated.
int NControls () const
void RemoveControlWithTag (int ctrlTag)
Remove controls from the control list with a particular tag.
void RemoveControls (int fromIdx)
Remove controls from the control list above a particular index, (frees memory).
void RemoveControl (int idx)
Remove a control at a particular index, (frees memory).
void RemoveControl (IControl *pControl)
Remove a control at using ptr, (frees memory).
void RemoveAllControls ()
Removes all regular IControls from the control list, as well as special controls (frees memory).
void HideControl (int paramIdx, bool hide)
Hide controls linked to a specific parameter.
void DisableControl (int paramIdx, bool diable)
Disable or enable controls linked to a specific parameter.
void SetAllControlsDirty ()
Calls SetDirty() on every control.
void SetAllControlsClean ()
Calls SetClean() on every control.
void SetControlPosition (IControl *pControl, float x, float y)
Reposition a control, redrawing the interface correctly.
void SetControlSize (IControl *pControl, float w, float h)
Resize a control, redrawing the interface correctly.
void SetControlBounds (IControl *pControl, const IRECT &r)
Set a controls target and draw rect to r, redrawing the interface correctly.
void OnMouseDown (const std::vector< IMouseInfo > &points)
Called when the platform class sends mouse down events.
void OnMouseUp (const std::vector< IMouseInfo > &points)
Called when the platform class sends mouse up events.
void OnMouseDrag (const std::vector< IMouseInfo > &points)
Called when the platform class sends drag events.
void OnTouchCancelled (const std::vector< IMouseInfo > &points)
Called when the platform class sends touch cancel events.
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
bool OnMouseWheel (float x, float y, const IMouseMod &mod, float delta)
bool OnKeyDown (float x, float y, const IKeyPress &key)
bool OnKeyUp (float x, float y, const IKeyPress &key)
bool OnMouseOver (float x, float y, const IMouseMod &mod)
void OnMouseOut ()
Called when the mouse leaves the graphics context.
void OnSetCursor ()
Called when the mouse enters the graphics context, to update the cursor to mCursorType.
void OnDrop (const char *str, float x, float y)
void OnDropMultiple (const std::vector< const char * > &paths, float x, float y)
void OnGUIIdle ()
This is an idle timer tick call on the GUI thread, only active if USE_IDLE_CALLS is defined.
void OnDragResize (float x, float y)
Called by ICornerResizerControl as the corner is dragged to resize.
void OnAppearanceChanged (EUIAppearance appearance)
Called by the platform class if the view changes to dark/light mode.
virtual EUIAppearance GetUIAppearance () const
Get the UI Appearance (Light/Dark mode)
void EnableMouseOver (bool enable)
void ReleaseMouseCapture ()
Used to tell the graphics context to stop tracking mouse interaction with a control.
bool MouseOverEnabled () const
int GetMouseOver () const
void GetMouseDownPoint (float &x, float &y) const
Get the x, y position of the last mouse down message.
void SetTabletInput (bool tablet)
Set by the platform class if the mouse input is coming from a tablet/stylus.
int GetParamIdxForPTAutomation (float x, float y)
[AAX only] This can be called by the ProTools API class (e.g.
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only] See AAX_CEffectGUI::SetControlHighlightInfo()
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily] In VST3 plug-ins this enable support for the IContextMenu interface, which allows the host to add contextual options to e.g.
void PopupHostContextMenuForParam (IControl *pControl, int paramIdx, float x, float y)
[VST3 primarily] In VST3 plug-ins this enable support for the IContextMenu interface, which allows the host to add contextual options to e.g.
const char * GetSharedResourcesSubPath () const
Gets the name of the shared resources subpath.
void SetSharedResourcesSubPath (const char *sharedResourcesSubPath)
Sets the name of the shared resources subpath.
virtual IBitmap LoadBitmap (const char *fileNameOrResID, int nStates=1, bool framesAreHorizontal=false, int targetScale=0)
Load a bitmap image from disk or from windows resource.
virtual IBitmap LoadBitmap (const char *name, const void *pData, int dataSize, int nStates=1, bool framesAreHorizontal=false, int targetScale=0)
Load a bitmap image from memory.
virtual ISVG LoadSVG (const char *fileNameOrResID, const char *units="px", float dpi=72.f)
Load an SVG from disk or from windows resource.
virtual ISVG LoadSVG (const char *name, const void *pData, int dataSize, const char *units="px", float dpi=72.f)
Load an SVG image from memory.
virtual WDL_TypedBuf< uint8_t > LoadResource (const char *fileNameOrResID, const char *fileType)
Load a resource from the file system, the bundle, or a Windows resource, and returns its data.
virtual void AttachGestureRecognizer (EGestureType type)
Registers a gesture recognizer with the graphics context.
void AttachGestureRecognizerToRegion (const IRECT &bounds, EGestureType type, IGestureFunc func)
Attach a gesture recognizer to a rectangular region of the GUI, i.e.
void ClearGestureRegions ()
Remove all gesture recognizers linked to regions.
Protected Member Functions
float DoMeasureText (const IText &text, const char *str, IRECT &bounds) const override
void DoDrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend) override
bool LoadAPIFont (const char *fontID, const PlatformFontPtr &font) override
Drawing API method to load a font from a PlatformFontPtr, called internally.
APIBitmap * LoadAPIBitmap (const char *fileNameOrResID, int scale, EResourceLocation location, const char *ext) override
Drawing API method to load a bitmap, called internally.
APIBitmap * LoadAPIBitmap (const char *name, const void *pData, int dataSize, int scale) override
Drawing API method to load a bitmap from binary data, called internally.
Protected Member Functions inherited from IGraphics
virtual void ApplyShadowMask (ILayerPtr &layer, RawBitmapData &mask, const IShadow &shadow)=0
Implemented by a graphics backend to apply a calculated shadow mask to a layer, according to the shadow settings specified.
virtual void UpdateLayer ()
Implemented by a graphics backend to prepare for drawing to the layer at the top of the stack.
void PushLayer (ILayer *pLayer)
Push a layer on to the stack.
ILayer * PopLayer ()
Pop a layer off the stack.
virtual void ActivateGLContext ()
virtual void DeactivateGLContext ()
virtual void CreatePlatformTextEntry (int paramIdx, const IText &text, const IRECT &bounds, int length, const char *str)=0
Creates a platform native text entry field.
virtual IPopupMenu * CreatePlatformPopupMenu (IPopupMenu &menu, const IRECT bounds, bool &isAsync)=0
Calls the platform backend to create the platform popup menu.
virtual APIBitmap * LoadAPIBitmap (const char *fileNameOrResID, int scale, EResourceLocation location, const char *ext)=0
Drawing API method to load a bitmap, called internally.
virtual APIBitmap * LoadAPIBitmap (const char *name, const void *pData, int dataSize, int scale)=0
Drawing API method to load a bitmap from binary data, called internally.
virtual APIBitmap * CreateAPIBitmap (int width, int height, float scale, double drawScale, bool cacheable=false)=0
Creates a new API bitmap, either in memory or as a GPU texture.
virtual bool LoadAPIFont (const char *fontID, const PlatformFontPtr &font)=0
Drawing API method to load a font from a PlatformFontPtr, called internally.
virtual int AlphaChannel () const =0
virtual bool FlippedBitmap () const =0
EResourceLocation SearchImageResource (const char *fileName, const char *type, WDL_String &result, int targetScale, int &sourceScale)
Search for a bitmap image resource matching the target scale.
APIBitmap * SearchBitmapInCache (const char *fileName, int targetScale, int &sourceScale)
Search the static storage cache for a bitmap image resource matching the target scale.
virtual float DoMeasureText (const IText &text, const char *str, IRECT &bounds) const =0
virtual void DoDrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=nullptr)=0
void DoMeasureTextRotation (const IText &text, const IRECT &bounds, IRECT &rect) const
void CalculateTextRotation (const IText &text, const IRECT &bounds, IRECT &rect, double &tx, double &ty) const
virtual float GetBackingPixelScale () const
IMatrix GetTransformMatrix () const
Additional Inherited Members
Protected Attributes inherited from IGraphics
IGEditorDelegate * mDelegate
bool mCursorHidden = false
bool mCursorLock = false
bool mTabletInput = false
float mCursorX = -1.f
float mCursorY = -1.f
float mXTranslation = 0.f
float mYTranslation = 0.f
std::stack< ILayer * > mLayers
IRECT mClipRECT
IMatrix mTransform
std::stack< IMatrix > mTransformStates
Detailed Description
IGraphics draw class using Skia.
Definition at line 48 of file IGraphicsSkia.h.
Constructor & Destructor Documentation
IGraphicsSkia()
IGraphicsSkia::IGraphicsSkia (IGEditorDelegate & dlg, int w, int h, int fps, float scale)
Definition at line 345 of file IGraphicsSkia.cpp.
~IGraphicsSkia()
IGraphicsSkia::~IGraphicsSkia ()
Definition at line 367 of file IGraphicsSkia.cpp.
Member Function Documentation
AlphaChannel()
int IGraphicsSkia::AlphaChannel () const inline override virtual
Returns
int The index of the alpha component in a drawing backend's pixel (RGBA or ARGB)
Implements IGraphics.
Definition at line 120 of file IGraphicsSkia.h.
ApplyLayerDropShadow()
void IGraphicsSkia::ApplyLayerDropShadow (ILayerPtr & layer, const IShadow & shadow) override virtual
Applies a drop shadow directly onto a layer.
Parameters
layer - the layer to add the shadow to
shadow - the shadow to add
Reimplemented from IGraphics.
Definition at line 983 of file IGraphicsSkia.cpp.
References IGraphics::ApplyLayerDropShadow(), and IPattern::GetStop().
ApplyShadowMask()
void IGraphicsSkia::ApplyShadowMask (ILayerPtr & layer, RawBitmapData & mask, const IShadow & shadow) override virtual
Implemented by a graphics backend to apply a calculated shadow mask to a layer, according to the shadow settings specified.
Parameters
layer The layer to apply the shadow to
mask The mask of the shadow as raw bitmap data
shadow The shadow specification
Implements IGraphics.
Definition at line 1046 of file IGraphicsSkia.cpp.
BeginFrame()
void IGraphicsSkia::BeginFrame () override virtual
Called at the beginning of drawing.
Call base implementation if overridden.
Reimplemented from IGraphics.
Definition at line 499 of file IGraphicsSkia.cpp.
References IGraphics::BeginFrame(), IGraphics::GetScreenScale(), IGraphics::WindowHeight(), and IGraphics::WindowWidth().
BitmapExtSupported()
bool IGraphicsSkia::BitmapExtSupported (const char * ext) override virtual
Checks a file extension and reports whether this drawing API supports loading that extension.
Implements IGraphics.
Definition at line 373 of file IGraphicsSkia.cpp.
References ToLower().
CreateAPIBitmap()
APIBitmap * IGraphicsSkia::CreateAPIBitmap (int width, int height, float scale, double drawScale, bool cacheable = false) override virtual
Creates a new API bitmap, either in memory or as a GPU texture.
Parameters
width The desired width
height The desired height
scale The scale in relation to 1:1 pixels
drawScale
Todo:
Parameters
cacheable Used to make sure the underlying bitmap can be shared between plug-in instances
Returns
APIBitmap* The new API Bitmap
Implements IGraphics.
Definition at line 949 of file IGraphicsSkia.cpp.
DoDrawText()
void IGraphicsSkia::DoDrawText (const IText & text, const char * str, const IRECT & bounds, const IBlend * pBlend) override protected virtual
Todo:
Parameters
text
Todo:
Parameters
str
Todo:
Parameters
bounds
Todo:
Parameters
pBlend
Todo:
Implements IGraphics.
Definition at line 741 of file IGraphicsSkia.cpp.
References IGraphics::PathTransformRestore(), and IGraphics::PathTransformSave().
DoMeasureText()
float IGraphicsSkia::DoMeasureText (const IText & text, const char * str, IRECT & bounds) const override protected virtual
Todo:
Parameters
text
Todo:
Parameters
str
Todo:
Parameters
bounds
Todo:
Returns
The width of the text
Implements IGraphics.
Definition at line 729 of file IGraphicsSkia.cpp.
References IGraphics::DoMeasureTextRotation(), and IRECT::W().
DrawBitmap()
void IGraphicsSkia::DrawBitmap (const IBitmap & bitmap, const IRECT & bounds, int srcX, int srcY, const IBlend * pBlend) override virtual
Draw a bitmap (raster) image to the graphics context.
Parameters
bitmap The bitmap image to draw to the graphics context
bounds The rectangular region to draw the image in
srcX The X offset in the source image to draw from
srcY The Y offset in the source image to draw from
pBlend Optional blend method
Implements IGraphics.
Definition at line 590 of file IGraphicsSkia.cpp.
References Clip(), IBitmap::GetAPIBitmap(), APIBitmap::GetBitmap(), IBitmap::GetDrawScale(), and IBitmap::GetScale().
DrawFastDropShadow()
void IGraphicsSkia::DrawFastDropShadow (const IRECT & innerBounds, const IRECT & outerBounds, float xyDrop, float roundness, float blur, IBlend * pBlend) override virtual
NanoVG only.
Reimplemented from IGraphics.
Definition at line 1089 of file IGraphicsSkia.cpp.
References IRECT::GetTranslated().
DrawMultiLineText()
void IGraphicsSkia::DrawMultiLineText (const IText & text, const char * str, const IRECT & bounds, const IBlend * pBlend) override virtual
Draw some multi-line text to the graphics context in a specific rectangle (NanoVG only)
Parameters
text An IText struct containing font and text properties and layout info
str The text string to draw
bounds The rectangular region in the graphics where you would like to draw the text
pBlend Optional blend method
Reimplemented from IGraphics.
Definition at line 1100 of file IGraphicsSkia.cpp.
References IGraphics::DrawText(), IRECT::H(), and IRECT::W().
DrawResize()
void IGraphicsSkia::DrawResize () override virtual
Todo:
Reimplemented from IGraphics.
Definition at line 457 of file IGraphicsSkia.cpp.
References IGraphics::GetScreenScale(), IGraphics::WindowHeight(), and IGraphics::WindowWidth().
Referenced by OnViewInitialized().
EndFrame()
void IGraphicsSkia::EndFrame () override virtual
Called by some drawing API classes to finally blit the draw bitmap onto the screen or perform other cleanup after drawing.
Reimplemented from IGraphics.
Definition at line 547 of file IGraphicsSkia.cpp.
References IGraphics::GetPlatformContext(), IGraphics::GetScreenScale(), IGraphics::GetWindow(), IGraphics::WindowHeight(), and IGraphics::WindowWidth().
FlippedBitmap()
bool IGraphicsSkia::FlippedBitmap () const inline override virtual
Returns
bool true if the drawing backend flips images (e.g. OpenGL)
Implements IGraphics.
Definition at line 121 of file IGraphicsSkia.h.
GetDrawContext()
void * IGraphicsSkia::GetDrawContext () inline override virtual
Gets a void pointer to underlying drawing context, for the IGraphics backend See draw class implementation headers (e.g.
IGraphicsNanoVG.h) for what you can cast the void pointer to
Implements IGraphics.
Definition at line 117 of file IGraphicsSkia.h.
GetDrawingAPIStr()
const char * IGraphicsSkia::GetDrawingAPIStr () override virtual
Returns
A CString representing the Drawing API in use e.g. "NanoVG"
Implements IGraphics.
Definition at line 1170 of file IGraphicsSkia.cpp.
GetLayerBitmapData()
void IGraphicsSkia::GetLayerBitmapData (const ILayerPtr & layer, RawBitmapData & data) override virtual
Get the contents of a layer as Raw RGBA bitmap data NOTE: you should only call this within IControl::Draw()
Parameters
layer The layer to get the data from
data The pixel data extracted from the layer
Implements IGraphics.
Definition at line 1031 of file IGraphicsSkia.cpp.
GetPoint()
IColor IGraphicsSkia::GetPoint (int x, int y) override virtual
Get the color at an X, Y location in the graphics context.
Parameters
x The X coordinate of the pixel
y The Y coordinate of the pixel
Returns
An IColor specifiying the color of the pixel at x, y
Implements IGraphics.
Definition at line 654 of file IGraphicsSkia.cpp.
LoadAPIBitmap() [1/2]
APIBitmap * IGraphicsSkia::LoadAPIBitmap (const char * fileNameOrResID, int scale, EResourceLocation location, const char * ext) override protected virtual
Drawing API method to load a bitmap, called internally.
Parameters
fileNameOrResID A CString absolute path or resource ID
scale Integer to identify the scale of the resource, for multi-scale bitmaps
location Identifies the kind of resource location
ext CString for the file extension
Returns
APIBitmap* Drawing API bitmap abstraction
Implements IGraphics.
Definition at line 380 of file IGraphicsSkia.cpp.
References IGraphics::GetWinModuleHandle(), and LoadWinResource().
LoadAPIBitmap() [2/2]
APIBitmap * IGraphicsSkia::LoadAPIBitmap (const char * name, const void * pData, int dataSize, int scale) override protected virtual
Drawing API method to load a bitmap from binary data, called internally.
Parameters
name CString for the name of the resource
pData Raw pointer to the binary data
dataSize Size of the data in bytes
scale Integer to identify the scale of the resource, for multi-scale bitmaps
Returns
APIBitmap* Drawing API bitmap abstraction
Implements IGraphics.
Definition at line 411 of file IGraphicsSkia.cpp.
LoadAPIFont()
bool IGraphicsSkia::LoadAPIFont (const char * fontID, const PlatformFontPtr & font) override protected virtual
Drawing API method to load a font from a PlatformFontPtr, called internally.
Parameters
fontID A CString that will be used to reference the font
font Valid PlatformFontPtr, loaded via LoadPlatformFont
Returns
bool true if the font was loaded successfully
Implements IGraphics.
Definition at line 663 of file IGraphicsSkia.cpp.
OnViewDestroyed()
void IGraphicsSkia::OnViewDestroyed () override virtual
Called after a platform view is destroyed, so that drawing classes can e.g.
free any resources
Reimplemented from IGraphics.
Definition at line 441 of file IGraphicsSkia.cpp.
References IGraphics::RemoveAllControls().
OnViewInitialized()
void IGraphicsSkia::OnViewInitialized (void * pContext) override virtual
Called after platform view initialization, so that drawing classes can e.g.
create an OpenGL context.
Reimplemented from IGraphics.
Definition at line 416 of file IGraphicsSkia.cpp.
References DrawResize().
PathArc()
void IGraphicsSkia::PathArc (float cx, float cy, float r, float a1, float a2, EWinding winding) override virtual
Add an arc to the current path.
Parameters
cx The X coordinate of the centre of the circle on which the arc lies
cy The Y coordinate of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
a1 the start angle of the arc at in degrees clockwise where 0 is up
a2 the end angle of the arc at in degrees clockwise where 0 is up
Implements IGraphics.
Definition at line 624 of file IGraphicsSkia.cpp.
PathClear()
void IGraphicsSkia::PathClear () inline override virtual
Clear the stack of path drawing commands.
Implements IGraphics.
Definition at line 67 of file IGraphicsSkia.h.
PathClose()
void IGraphicsSkia::PathClose () inline override virtual
Close the path that is being specified.
Implements IGraphics.
Definition at line 68 of file IGraphicsSkia.h.
PathCubicBezierTo()
void IGraphicsSkia::PathCubicBezierTo (float c1x, float c1y, float c2x, float c2y, float x2, float y2) inline override virtual
Add a cubic bezier to the current path from the current point to the specified location.
Parameters
c1x Control point 1 X coordinate
c1y Control point 1 Y coordinate
c2x Control point 2 X coordinate
c2y Control point 2 Y coordinate
x2 The X coordinate of the end of the line
y2 The Y coordinate of the end of the line
Implements IGraphics.
Definition at line 74 of file IGraphicsSkia.h.
PathFill()
void IGraphicsSkia::PathFill (const IPattern & pattern, const IFillOptions & options, const IBlend * pBlend) override virtual
Fill the current current path.
Parameters
pattern The IPattern to use, for e.g. color or gradient
options Optional IFillOptions to specify fill rule and preserve options
pBlend Optional blend method
Implements IGraphics.
Definition at line 803 of file IGraphicsSkia.cpp.
PathLineTo()
void IGraphicsSkia::PathLineTo (float x, float y) inline override virtual
Add a line to the current path from the current point to the specified location.
Parameters
x The X coordinate of the end of the line
y The Y coordinate of the end of the line
Implements IGraphics.
Definition at line 72 of file IGraphicsSkia.h.
PathMoveTo()
void IGraphicsSkia::PathMoveTo (float x, float y) inline override virtual
Move the current point in the current path.
Parameters
x The X coordinate
y The Y coordinate
Implements IGraphics.
Definition at line 71 of file IGraphicsSkia.h.
PathQuadraticBezierTo()
void IGraphicsSkia::PathQuadraticBezierTo (float cx, float cy, float x2, float y2) inline override virtual
Add a quadratic bezier to the current path from the current point to the specified location.
Parameters
cx Control point X coordinate
cy Control point Y coordinate
x2 The X coordinate of the end of the line
y2 The Y coordinate of the end of the line
Implements IGraphics.
Definition at line 79 of file IGraphicsSkia.h.
PathStroke()
void IGraphicsSkia::PathStroke (const IPattern & pattern, float thickness, const IStrokeOptions & options, const IBlend * pBlend) override virtual
Stroke the current current path.
Parameters
pattern The IPattern to use, for e.g. color or gradient
thickness The line thickness
options Optional IStrokeOptions to specify dash, join and path preserve options
pBlend Optional blend method
Implements IGraphics.
Definition at line 759 of file IGraphicsSkia.cpp.
UpdateLayer()
void IGraphicsSkia::UpdateLayer () override virtual
Implemented by a graphics backend to prepare for drawing to the layer at the top of the stack.
Reimplemented from IGraphics.
Definition at line 972 of file IGraphicsSkia.cpp.
The documentation for this class was generated from the following files:
IGraphicsSkia.h
IGraphicsSkia.cpp