iPlug 2: IRECTList Class Reference
IRECTList Class Reference
IGraphics::Structs
Used to manage a list of rectangular areas and optimize them for drawing to the screen.
#include <IGraphicsStructs.h>
Public Member Functions
IRECTList (const IRECTList &)=delete
IRECTList & operator= (const IRECTList &)=delete
int Size () const
void Add (const IRECT &rect)
Add a rectangle to the list.
void Set (int idx, const IRECT &rect)
Set a specific rectangle in the list (will crash if idx is invalid)
const IRECT & Get (int idx) const
Get an IRECT from the list (will crash if idx is invalid)
void Clear ()
Clear the list.
IRECT Bounds ()
Get a union of all rectangles in the list.
void PixelAlign ()
Align the rectangles to pixel boundaries.
void PixelAlign (float scale)
Pixel-align the IRECTs at the given scale factor then scale them back down.
int Find (float x, float y) const
Find the first index of the rect that contains point x, y, if it exists.
void Optimize ()
Remove rects that are contained by other rects and intersections and merge any rects that can be merged.
Static Public Member Functions
static bool GetFracGrid (const IRECT &input, IRECTList &rects, const std::initializer_list< float > &rowFractions, const std::initializer_list< float > &colFractions, EDirection layoutDir=EDirection::Horizontal)
Fill an IRECTList with divisons of an input IRECT.
Detailed Description
Used to manage a list of rectangular areas and optimize them for drawing to the screen.
Definition at line 1740 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IRECTList()
IRECTList::IRECTList () inline
Definition at line 1743 of file IGraphicsStructs.h.
Member Function Documentation
Add()
void IRECTList::Add (const IRECT & rect) inline
Add a rectangle to the list.
Parameters
rect The IRECT to add
Definition at line 1754 of file IGraphicsStructs.h.
Referenced by IGraphics::AttachGestureRecognizerToRegion(), GetFracGrid(), and IGraphics::IsDirty().
Bounds()
IRECT IRECTList::Bounds () inline
Get a union of all rectangles in the list.
Returns
IRECT Union of all rectangles in the list
Definition at line 1783 of file IGraphicsStructs.h.
References Get(), and IRECT::Union().
Referenced by IGraphics::Draw(), and GetFracGrid().
Clear()
void IRECTList::Clear () inline
Clear the list.
Definition at line 1776 of file IGraphicsStructs.h.
Referenced by IGraphics::ClearGestureRegions().
Find()
int IRECTList::Find (float x, float y) const inline
Find the first index of the rect that contains point x, y, if it exists.
Parameters
x Horizontal position to check
y Vertical position to check
Returns
integer index of rect that contains point x,y or -1 if not found
Definition at line 1818 of file IGraphicsStructs.h.
References IRECT::Contains(), Get(), and Size().
Referenced by IGraphics::OnGestureRecognized(), and IGraphics::RespondsToGesture().
Get()
const IRECT & IRECTList::Get (int idx) const inline
Get an IRECT from the list (will crash if idx is invalid)
Parameters
idx The index to get
Returns
const IRECT& The IRECT at idx
Definition at line 1770 of file IGraphicsStructs.h.
Referenced by Bounds(), IGraphics::Draw(), Find(), Optimize(), and PixelAlign().
GetFracGrid()
static bool IRECTList::GetFracGrid (const IRECT & input, IRECTList & rects, const std::initializer_list< float > & rowFractions, const std::initializer_list< float > & colFractions, EDirection layoutDir = EDirection::Horizontal) inline static
Fill an IRECTList with divisons of an input IRECT.
Parameters
input The input rectangle
rects The output IRECTList
rowFractions Initializer list of fractions for the grid rows (should sum to 1.0)
colFractions Initializer list of fractions for the grid columns (should sum to 1.0)
layoutDir By default the cell idx increases horizontally (by row). If set to EDirection::Vertical, cell idx increases vertically (by column).
Returns
true if the row and column fractions summed to 1.0, and grid creation was successful
Definition at line 1836 of file IGraphicsStructs.h.
References Add(), Bounds(), IRECT::FracRectHorizontal(), IRECT::FracRectVertical(), IRECT::GetTranslated(), IRECT::H(), IRECT::Intersect(), and IRECT::W().
Optimize()
void IRECTList::Optimize () inline
Remove rects that are contained by other rects and intersections and merge any rects that can be merged.
Definition at line 1898 of file IGraphicsStructs.h.
References IRECT::Contains(), Get(), IRECT::Intersect(), IRECT::Intersects(), IRECT::Mergeable(), Set(), and Size().
Referenced by IGraphics::Draw().
PixelAlign() [1/2]
void IRECTList::PixelAlign () inline
Align the rectangles to pixel boundaries.
Definition at line 1792 of file IGraphicsStructs.h.
References Get(), IRECT::PixelAlign(), Set(), and Size().
Referenced by IGraphics::Draw().
PixelAlign() [2/2]
void IRECTList::PixelAlign (float scale) inline
Pixel-align the IRECTs at the given scale factor then scale them back down.
Parameters
scale Scale value for the alignment
Definition at line 1804 of file IGraphicsStructs.h.
References Get(), IRECT::PixelAlign(), Set(), and Size().
Set()
void IRECTList::Set (int idx, const IRECT & rect) inline
Set a specific rectangle in the list (will crash if idx is invalid)
Parameters
idx The index to set
rect The new IRECT
Definition at line 1762 of file IGraphicsStructs.h.
Referenced by Optimize(), and PixelAlign().
Size()
int IRECTList::Size () const inline
Returns
int The number of rectangles in the list
Definition at line 1750 of file IGraphicsStructs.h.
Referenced by IGraphics::AttachGestureRecognizerToRegion(), IGraphics::Draw(), Find(), Optimize(), PixelAlign(), and IGraphics::RespondsToGesture().
The documentation for this class was generated from the following file:
IGraphicsStructs.h