iPlug 2: IEditorDelegate Class Reference
IEditorDelegate Class Reference abstract
IPlug::EditorDelegates
This pure virtual interface delegates communication in both directions between a UI editor and something else (which is usually a plug-in) It is also the class that owns parameter objects (for historical reasons) - although it's not necessary to allocate them.
#include <IPlugEditorDelegate.h>
Public Member Functions
IEditorDelegate (int nParams)
IEditorDelegate (const IEditorDelegate &)=delete
IEditorDelegate & operator= (const IEditorDelegate &)=delete
IParam * AddParam ()
Adds an IParam to the parameters ptr list Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
void RemoveParam (int idx)
Remove an IParam at a particular index Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
const IParam * GetParam (int paramIdx) const
Get a const pointer to one of the delegate's IParam objects (for const methods)
int NParams () const
virtual void * OpenWindow (void *pParent)
If you are not using IGraphics, you can implement this method to attach to the native parent view e.g.
virtual void CloseWindow ()
If you are not using IGraphics you can if you need to free resources etc when the window closes.
virtual void OnParentWindowResize (int width, int height)
Called by app wrappers when the OS window scaling buttons/resizers are used.
virtual void OnUIOpen ()
Override this method to do something before the UI is opened.
virtual void OnUIClose ()
Override this method to do something before the UI is closed.
virtual void OnParamChange (int paramIdx, EParamSource source, int sampleOffset=-1)
Override this method to do something to your DSP when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
virtual void OnParamChangeUI (int paramIdx, EParamSource source=kUnknown)
Override this method to do something when a parameter changes on the main/UI thread Like OnParamChange, OnParamChangeUI will be called when a parameter changes.
virtual void OnParamReset (EParamSource source)
Called when parameters have changed to inform the plugin of the changes Override only if you need to handle notifications and updates in a specialist manner (e.g.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
Handle incoming MIDI messages sent to the user interface.
virtual void OnSysexMsgUI (const ISysEx &msg)
Handle incoming SysEx messages sent to the user interface.
virtual bool OnMessage (int msgTag, int ctrlTag, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginBase::RestorePreset().
virtual bool OnKeyDown (const IKeyPress &key)
KeyDown handler, in order to get keystrokes from certain hosts/plugin formats that send key press messages through the plug-in API, rather than the view.
virtual bool OnKeyUp (const IKeyPress &key)
KeyDown handler, in order to get keystrokes from certain hosts/plugin formats that send key press messages through the plug-in API rather than the view.
void SendCurrentParamValuesFromDelegate ()
Loops through all parameters, calling SendParameterValueFromDelegate() with the current value of the parameter This is important when modifying groups of parameters, restoring state and opening the UI, in order to update it with the latest values.
virtual void SendControlValueFromDelegate (int ctrlTag, double normalizedValue)
SendControlValueFromDelegate (Abbreviation: SCVFD) WARNING: should not be called on the realtime audio thread.
virtual void SendControlMsgFromDelegate (int ctrlTag, int msgTag, int dataSize=0, const void *pData=nullptr)
SendControlMsgFromDelegate (Abbreviation: SCMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendArbitraryMsgFromDelegate (int msgTag, int dataSize=0, const void *pData=nullptr)
SendArbitraryMsgFromDelegate (Abbreviation: SAMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendMidiMsgFromDelegate (const IMidiMsg &msg)
SendMidiMsgFromDelegate (Abbreviation: SMMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendSysexMsgFromDelegate (const ISysEx &msg)
SendSysexMsgFromDelegate (Abbreviation: SSMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendParameterValueFromDelegate (int paramIdx, double value, bool normalized)
SendParameterValueFromDelegate (Abbreviation: SPVFD) WARNING: should not be called on the realtime audio thread.
virtual void DirtyParametersFromUI ()
When modifying a range of parameters in the editor, it can be necessary to broadcast that fact via the host, for instance in a distributed plug-in.
virtual void BeginInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual void SendParameterValueFromUI (int paramIdx, double normalizedValue)
SPVFUI Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
virtual void EndInformHostOfParamChangeFromUI (int paramIdx)=0
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
virtual bool EditorResizeFromUI (int viewWidth, int viewHeight, bool needsPlatformResize)
If the editor changes UI dimensions, e.g.
virtual void SendMidiMsgFromUI (const IMidiMsg &msg)
SendMidiMsgFromUI (Abbreviation: SMMFUI) This method should be used when sending a MIDI message from the UI.
virtual void SendSysexMsgFromUI (const ISysEx &msg)
SendSysexMsgFromUI (Abbreviation: SSMFUI) If a plug-in can send Sysex data as a result of actions in the user interface, this method can be used.
virtual void SendArbitraryMsgFromUI (int msgTag, int ctrlTag=kNoTag, int dataSize=0, const void *pData=nullptr)
SendArbitraryMsgFromUI (Abbreviation: SAMFUI)
virtual void DeferMidiMsg (const IMidiMsg &msg)
This method is needed, for remote editors to avoid a feedback loop.
virtual void DeferSysexMsg (const ISysEx &msg)
This method is needed, for remote editors to avoid a feedback loop.
void SetEditorSize (int width, int height)
void SetSizeConstraints (int widthLo, int widthHi, int heightLo, int heightHi)
Sets the minimum and maximum size constraints for the editor window.
int GetEditorWidth () const
int GetEditorHeight () const
int GetMinWidth () const
int GetMaxWidth () const
int GetMinHeight () const
int GetMaxHeight () const
virtual bool ConstrainEditorResize (int &w, int &h) const
Constrain the incoming editor width and height values based on the minimum and maximum.
virtual bool SerializeEditorState (IByteChunk &chunk) const
Serializes the editor state (such as scale) into a binary chunk.
virtual int UnserializeEditorState (const IByteChunk &chunk, int startPos)
Unserializes editor state (such as scale).
virtual void SetScreenScale (float scale)
Can be used by a host API to inform the editor of screen scale changes.
Friends
class IPlugAPP
class IPlugAAX
class IPlugVST2
class IPlugVST3
class IPlugVST3Controller
class IPlugVST3Processor
class IPlugAU
class IPlugAUv3
class IPlugWEB
class IPlugWAM
class IPlugAPIBase
class IPluginBase
Detailed Description
This pure virtual interface delegates communication in both directions between a UI editor and something else (which is usually a plug-in) It is also the class that owns parameter objects (for historical reasons) - although it's not necessary to allocate them.
This is the lowest level base class in iPlug 2 that facilitates distributing editor and DSP parts for plug-in formats that need that, but also allowing non-distributed plug-ins to use the same API. In distributed plug-in architectures certain methods will be overridden in order to pipe messages to various places, using whatever mechanism that plug-in format requires. In this case, there are actually two classes that implement the IEditorDelegate interface, but only one which is directly connected to the user interface (IGraphics etc.), the other being connected to a class inheriting IPlugAPIBase that deals with processing audio, see for example IPlugVST3Processor
Note on method names:
"FromUI" in a method name, means that that method is called by something in the UI i.e. when the user interacts with a control.
"FromDelegate" in a method name means that method is called from a class that implements the IEditorDelegate interface, which is usually your plug-in base class, but may not be in the case of an isolated editor class, or if you are using IGraphics without IPlug, and your IEditorDelegate is not a plug-in
NOTES: A parameter VALUE is a floating point number linked to an integer parameter index. TODO: Normalised ? A parameter OBJECT (IParam) is an instance of the IParam class as defined in IPlugParameter.h A parameter OBJECT is also referred to as a "param", in method names such as IEditorDelegate::GetParam(int paramIdx) and IControl::GetParam().
Definition at line 48 of file IPlugEditorDelegate.h.
Constructor & Destructor Documentation
IEditorDelegate()
IEditorDelegate::IEditorDelegate (int nParams) inline
Definition at line 51 of file IPlugEditorDelegate.h.
~IEditorDelegate()
virtual IEditorDelegate::~IEditorDelegate () inline virtual
Definition at line 57 of file IPlugEditorDelegate.h.
Member Function Documentation
AddParam()
IParam * IEditorDelegate::AddParam () inline
Adds an IParam to the parameters ptr list Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
Returns
Ptr to the newly created IParam object
Definition at line 68 of file IPlugEditorDelegate.h.
BeginInformHostOfParamChangeFromUI()
virtual void IEditorDelegate::BeginInformHostOfParamChangeFromUI (int paramIdx) pure virtual
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Referenced by WebViewEditorDelegate::OnMessageFromWebView(), IGraphics::OnMouseDown(), and IVNumberBoxControl::OnMouseDown().
CloseWindow()
virtual void IEditorDelegate::CloseWindow () inline virtual
If you are not using IGraphics you can if you need to free resources etc when the window closes.
Call base implementation.
Reimplemented in IGEditorDelegate, CocoaEditorDelegate, and WebViewEditorDelegate.
Definition at line 93 of file IPlugEditorDelegate.h.
References OnUIClose().
Referenced by IGEditorDelegate::CloseWindow().
ConstrainEditorResize()
virtual bool IEditorDelegate::ConstrainEditorResize (int & w, int & h) const inline virtual
Constrain the incoming editor width and height values based on the minimum and maximum.
Parameters
w the incoming width value to test/set if clipping needed
h the incoming height value to test/set if clipping needed
Returns
true if the parameters fell withing the permitted range
Definition at line 321 of file IPlugEditorDelegate.h.
References Clip().
Referenced by IGraphics::Resize().
DeferMidiMsg()
virtual void IEditorDelegate::DeferMidiMsg (const IMidiMsg & msg) inline virtual
This method is needed, for remote editors to avoid a feedback loop.
Definition at line 285 of file IPlugEditorDelegate.h.
DeferSysexMsg()
virtual void IEditorDelegate::DeferSysexMsg (const ISysEx & msg) inline virtual
This method is needed, for remote editors to avoid a feedback loop.
Definition at line 288 of file IPlugEditorDelegate.h.
DirtyParametersFromUI()
virtual void IEditorDelegate::DirtyParametersFromUI () inline virtual
When modifying a range of parameters in the editor, it can be necessary to broadcast that fact via the host, for instance in a distributed plug-in.
You can use it if you restore a preset using a custom preset mechanism.
Definition at line 233 of file IPlugEditorDelegate.h.
EditorResizeFromUI()
virtual bool IEditorDelegate::EditorResizeFromUI (int viewWidth, int viewHeight, bool needsPlatformResize) inline virtual
If the editor changes UI dimensions, e.g.
from clicking a button to choose a size or dragging a corner resizer, it needs to call into the plug-in API to resize the window in the plugin returns a bool to indicate whether the DAW or plugin class has resized the host window
Definition at line 262 of file IPlugEditorDelegate.h.
Referenced by IGraphics::Resize(), and IGraphics::SetScreenScale().
EndInformHostOfParamChangeFromUI()
virtual void IEditorDelegate::EndInformHostOfParamChangeFromUI (int paramIdx) pure virtual
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Referenced by WebViewEditorDelegate::OnMessageFromWebView(), IGraphics::OnMouseUp(), IVNumberBoxControl::OnMouseUp(), and IGraphics::SetControlValueAfterPopupMenu().
GetEditorHeight()
int IEditorDelegate::GetEditorHeight () const inline
Returns
The height of the plug-in editor in pixels
Definition at line 310 of file IPlugEditorDelegate.h.
GetEditorWidth()
int IEditorDelegate::GetEditorWidth () const inline
Returns
The width of the plug-in editor in pixels
Definition at line 307 of file IPlugEditorDelegate.h.
GetMaxHeight()
int IEditorDelegate::GetMaxHeight () const inline
Definition at line 315 of file IPlugEditorDelegate.h.
GetMaxWidth()
int IEditorDelegate::GetMaxWidth () const inline
Definition at line 313 of file IPlugEditorDelegate.h.
GetMinHeight()
int IEditorDelegate::GetMinHeight () const inline
Definition at line 314 of file IPlugEditorDelegate.h.
GetMinWidth()
int IEditorDelegate::GetMinWidth () const inline
Definition at line 312 of file IPlugEditorDelegate.h.
GetParam() [1/2]
IParam * IEditorDelegate::GetParam (int paramIdx) inline
Get a pointer to one of the delegate's IParam objects.
Parameters
paramIdx The index of the parameter object to be got
Returns
A pointer to the IParam object at paramIdx or nullptr if paramIdx is invalid
Definition at line 78 of file IPlugEditorDelegate.h.
Referenced by IControl::GetParam(), CocoaEditorDelegate::OnParamChangeUI(), WebViewEditorDelegate::OnWebContentLoaded(), SendCurrentParamValuesFromDelegate(), IGEditorDelegate::SendParameterValueFromDelegate(), WebViewEditorDelegate::SendParameterValueFromDelegate(), SendParameterValueFromUI(), and IVTrackControlBase::SetParamsByGroup().
GetParam() [2/2]
const IParam * IEditorDelegate::GetParam (int paramIdx) const inline
Get a const pointer to one of the delegate's IParam objects (for const methods)
Parameters
paramIdx The index of the parameter object to be got
Returns
A pointer to the IParam object at paramIdx or nullptr if paramIdx is invalid
Definition at line 83 of file IPlugEditorDelegate.h.
NParams()
int IEditorDelegate::NParams () const inline
Returns
Returns the number of parameters that belong to the plug-in.
Definition at line 86 of file IPlugEditorDelegate.h.
Referenced by OnParamReset(), WebViewEditorDelegate::OnWebContentLoaded(), SendCurrentParamValuesFromDelegate(), SendParameterValueFromUI(), and IVTrackControlBase::SetParamsByGroup().
OnKeyDown()
virtual bool IEditorDelegate::OnKeyDown (const IKeyPress & key) inline virtual
KeyDown handler, in order to get keystrokes from certain hosts/plugin formats that send key press messages through the plug-in API, rather than the view.
Parameters
key Information about the key that was pressed
Returns
true if the key was handled by the plug-in
Reimplemented in IGEditorDelegate, and WebViewEditorDelegate.
Definition at line 157 of file IPlugEditorDelegate.h.
OnKeyUp()
virtual bool IEditorDelegate::OnKeyUp (const IKeyPress & key) inline virtual
KeyDown handler, in order to get keystrokes from certain hosts/plugin formats that send key press messages through the plug-in API rather than the view.
Parameters
key Information about the key that was released
Returns
true if the key was handled by the plug-in
Reimplemented in IGEditorDelegate, and WebViewEditorDelegate.
Definition at line 162 of file IPlugEditorDelegate.h.
OnMessage()
virtual bool IEditorDelegate::OnMessage (int msgTag, int ctrlTag, int dataSize, const void * pData) inline virtual
This could be implemented in either DSP or EDITOR to receive a message from the other one.
Reimplemented in CocoaEditorDelegate.
Definition at line 147 of file IPlugEditorDelegate.h.
Referenced by SendArbitraryMsgFromDelegate(), and SendControlMsgFromDelegate().
OnMidiMsgUI()
virtual void IEditorDelegate::OnMidiMsgUI (const IMidiMsg & msg) inline virtual
Handle incoming MIDI messages sent to the user interface.
Parameters
msg The MIDI message to process
Reimplemented in CocoaEditorDelegate.
Definition at line 140 of file IPlugEditorDelegate.h.
Referenced by SendMidiMsgFromDelegate().
OnParamChange() [1/2]
virtual void IEditorDelegate::OnParamChange (int paramIdx) inline virtual
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
WARNING: this method can in some cases be called on the realtime audio thread
Definition at line 118 of file IPlugEditorDelegate.h.
OnParamChange() [2/2]
virtual void IEditorDelegate::OnParamChange (int paramIdx, EParamSource source, int sampleOffset = -1) inline virtual
Override this method to do something to your DSP when a parameter changes.
WARNING: this method can in some cases be called on the realtime audio thread
Parameters
paramIdx The index of the parameter that changed
source One of the EParamSource options to indicate where the parameter change came from.
sampleOffset For sample accurate parameter changes - index into current block
Definition at line 110 of file IPlugEditorDelegate.h.
References OnParamChange().
Referenced by OnParamChange(), and OnParamReset().
OnParamChangeUI()
virtual void IEditorDelegate::OnParamChangeUI (int paramIdx, EParamSource source = kUnknown) inline virtual
Override this method to do something when a parameter changes on the main/UI thread Like OnParamChange, OnParamChangeUI will be called when a parameter changes.
However, whereas OnParamChange may be called on the audio thread and should be used to update DSP state, OnParamChangeUI is always called on the low-priority thread, should be used to update UI (e.g. for hiding or showing controls). You should not update parameter objects using this method.
Parameters
paramIdx The index of the parameter that changed
Reimplemented in CocoaEditorDelegate.
Definition at line 124 of file IPlugEditorDelegate.h.
Referenced by OnParamReset(), SendParameterValueFromDelegate(), and SendParameterValueFromUI().
OnParamReset()
virtual void IEditorDelegate::OnParamReset (EParamSource source) inline virtual
Called when parameters have changed to inform the plugin of the changes Override only if you need to handle notifications and updates in a specialist manner (e.g.
if the ordering of updating parameters has an effect or if you need to avoid multiple settings of linked parameters). This must update both DSP and UI. The default implementation calls OnParamChange() and OnParamChangeUI() for each parameter.
Parameters
source Specifies the source of the parameter changes
Definition at line 129 of file IPlugEditorDelegate.h.
References NParams(), OnParamChange(), and OnParamChangeUI().
OnParentWindowResize()
virtual void IEditorDelegate::OnParentWindowResize (int width, int height) inline virtual
Called by app wrappers when the OS window scaling buttons/resizers are used.
Reimplemented in IGEditorDelegate, and WebViewEditorDelegate.
Definition at line 96 of file IPlugEditorDelegate.h.
OnRestoreState()
virtual void IEditorDelegate::OnRestoreState () inline virtual
This is called by API classes after restoring state and by IPluginBase::RestorePreset().
Typically used to update user interface, where multiple parameter values have changed. If you need to do something when state is restored you can override it If you override this method you should call this parent, or implement the same functionality in order to get controls to update, when state is restored.
Definition at line 152 of file IPlugEditorDelegate.h.
References SendCurrentParamValuesFromDelegate().
OnSysexMsgUI()
virtual void IEditorDelegate::OnSysexMsgUI (const ISysEx & msg) inline virtual
Handle incoming SysEx messages sent to the user interface.
Parameters
msg The SysEx message to process
Reimplemented in CocoaEditorDelegate.
Definition at line 144 of file IPlugEditorDelegate.h.
Referenced by SendSysexMsgFromDelegate().
OnUIClose()
virtual void IEditorDelegate::OnUIClose () inline virtual
Override this method to do something before the UI is closed.
Definition at line 103 of file IPlugEditorDelegate.h.
Referenced by CloseWindow().
OnUIOpen()
virtual void IEditorDelegate::OnUIOpen () inline virtual
Override this method to do something before the UI is opened.
You must call the base implementation to make sure controls linked to parameters get updated correctly.
Definition at line 100 of file IPlugEditorDelegate.h.
References SendCurrentParamValuesFromDelegate().
Referenced by WebViewEditorDelegate::OnWebContentLoaded(), and OpenWindow().
OpenWindow()
virtual void * IEditorDelegate::OpenWindow (void * pParent) inline virtual
If you are not using IGraphics, you can implement this method to attach to the native parent view e.g.
NSView, UIView, HWND. Defer calling OnUIOpen() if necessary.
Reimplemented in IGEditorDelegate, CocoaEditorDelegate, and WebViewEditorDelegate.
Definition at line 90 of file IPlugEditorDelegate.h.
References OnUIOpen().
RemoveParam()
void IEditorDelegate::RemoveParam (int idx) inline
Remove an IParam at a particular index Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
Parameters
idx The index of the parameter to remove
Definition at line 73 of file IPlugEditorDelegate.h.
SendArbitraryMsgFromDelegate()
virtual void IEditorDelegate::SendArbitraryMsgFromDelegate (int msgTag, int dataSize = 0, const void * pData = nullptr) inline virtual
SendArbitraryMsgFromDelegate (Abbreviation: SAMFD) WARNING: should not be called on the realtime audio thread.
This method can be used to send opaque data from a class implementing IEditorDelegate to the IEditorDelegate connected to the user interface The message can be handled at the destination via IEditorDelegate::OnMessage()
Parameters
msgTag A unique tag to identify the message
dataSize The size in bytes of the data payload pointed to by pData. Note: if this is nonzero, pData must be valid.
pData Ptr to the opaque data payload for the message
Reimplemented in WebViewEditorDelegate.
Definition at line 201 of file IPlugEditorDelegate.h.
References OnMessage().
SendArbitraryMsgFromUI()
virtual void IEditorDelegate::SendArbitraryMsgFromUI (int msgTag, int ctrlTag = kNoTag, int dataSize = 0, const void * pData = nullptr) inline virtual
SendArbitraryMsgFromUI (Abbreviation: SAMFUI)
Parameters
msgTag A unique tag to identify the message
ctrlTag A unique tag to identify the control that sent the message, if desired
dataSize The size in bytes of the data payload pointed to by pData. Note: if this is nonzero, pData must be valid.
pData Ptr to the opaque data payload for the message
Definition at line 281 of file IPlugEditorDelegate.h.
Referenced by WebViewEditorDelegate::OnMessageFromWebView(), IVBarGraphSpectrumAnalyzerControl< MAXNC, MAX_FFT_SIZE >::OnPopupMenuSelection(), IVSpectrumAnalyzerControl< MAXNC, MAX_FFT_SIZE >::OnPopupMenuSelection(), and IWheelControl::OnPopupMenuSelection().
SendControlMsgFromDelegate()
virtual void IEditorDelegate::SendControlMsgFromDelegate (int ctrlTag, int msgTag, int dataSize = 0, const void * pData = nullptr) inline virtual
SendControlMsgFromDelegate (Abbreviation: SCMFD) WARNING: should not be called on the realtime audio thread.
This method can be used to send opaque data from a class implementing IEditorDelegate to a specific control in the user interface. The message can be handled in the destination control via IControl::OnMsgFromDelegate
Parameters
ctrlTag A unique tag to identify the control that is the destination of the message
msgTag A unique tag to identify the message
dataSize The size in bytes of the data payload pointed to by pData. Note: if this is nonzero, pData must be valid.
pData Ptr to the opaque data payload for the message
Reimplemented in CocoaEditorDelegate, WebViewEditorDelegate, and IGEditorDelegate.
Definition at line 192 of file IPlugEditorDelegate.h.
References OnMessage().
Referenced by ISender< MAXNC, QUEUE_SIZE, T >::TransmitData(), and ISender< MAXNC, QUEUE_SIZE, T >::TransmitDataToControlsWithTags().
SendControlValueFromDelegate()
virtual void IEditorDelegate::SendControlValueFromDelegate (int ctrlTag, double normalizedValue) inline virtual
SendControlValueFromDelegate (Abbreviation: SCVFD) WARNING: should not be called on the realtime audio thread.
In IGraphics plug-ins, this method is used to update controls in the user interface from a class implementing IEditorDelegate, when the control is not linked to a parameter. A typical use case would be a meter control. In OnIdle() your plug-in would call this method to update the IControl's value.
Parameters
ctrlTag A tag for the control
normalizedValue The normalised value to set the control to. This will modify IControl::mValue;
Reimplemented in IGEditorDelegate, CocoaEditorDelegate, and WebViewEditorDelegate.
Definition at line 182 of file IPlugEditorDelegate.h.
SendCurrentParamValuesFromDelegate()
void IEditorDelegate::SendCurrentParamValuesFromDelegate () inline
Loops through all parameters, calling SendParameterValueFromDelegate() with the current value of the parameter This is important when modifying groups of parameters, restoring state and opening the UI, in order to update it with the latest values.
Definition at line 167 of file IPlugEditorDelegate.h.
References GetParam(), NParams(), and SendParameterValueFromDelegate().
Referenced by OnRestoreState(), and OnUIOpen().
SendMidiMsgFromDelegate()
virtual void IEditorDelegate::SendMidiMsgFromDelegate (const IMidiMsg & msg) inline virtual
SendMidiMsgFromDelegate (Abbreviation: SMMFD) WARNING: should not be called on the realtime audio thread.
This method can be used to send regular MIDI data from the class implementing IEditorDelegate to the user interface The message can be handled at the destination via IEditorDelegate::OnMidiMsgUI()
Parameters
msg an IMidiMsg Containing the MIDI message to send to the user interface.
Reimplemented in IGEditorDelegate, and WebViewEditorDelegate.
Definition at line 208 of file IPlugEditorDelegate.h.
References OnMidiMsgUI().
Referenced by IGEditorDelegate::SendMidiMsgFromDelegate().
SendMidiMsgFromUI()
virtual void IEditorDelegate::SendMidiMsgFromUI (const IMidiMsg & msg) inline virtual
SendMidiMsgFromUI (Abbreviation: SMMFUI) This method should be used when sending a MIDI message from the UI.
For example clicking on a key in a virtual keyboard. Eventually the MIDI message can be handled in IPlugProcessor::ProcessMidiMsg(), from where it can be used to trigger sound and or forwarded to the API's MIDI output.
Parameters
msg The MIDI message to send.
Definition at line 268 of file IPlugEditorDelegate.h.
Referenced by IWheelControl::IWheelControl(), WebViewEditorDelegate::OnMessageFromWebView(), and IGraphics::SetQwertyMidiKeyHandlerFunc().
SendParameterValueFromDelegate()
virtual void IEditorDelegate::SendParameterValueFromDelegate (int paramIdx, double value, bool normalized) inline virtual
SendParameterValueFromDelegate (Abbreviation: SPVFD) WARNING: should not be called on the realtime audio thread.
This method is called by the class implementing the delegate interface (not the plug-in API class) in order to update the user interface with the new parameter values, typically after automation. The similarly named IPlugAPIBase::SendParameterValueFromAPI() should take care of queueing and deferring, if there is no main thread notification from the API If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered In IGraphics plug-ins, this will update any IControls that have their mParamIdx set > -1
Parameters
paramIdx The index of the parameter to be updated
value The new value of the parameter
normalized true if value is normalised
Reimplemented in IGEditorDelegate, CocoaEditorDelegate, and WebViewEditorDelegate.
Definition at line 226 of file IPlugEditorDelegate.h.
References OnParamChangeUI().
Referenced by SendCurrentParamValuesFromDelegate(), IGEditorDelegate::SendParameterValueFromDelegate(), and CocoaEditorDelegate::SendParameterValueFromDelegate().
SendParameterValueFromUI()
virtual void IEditorDelegate::SendParameterValueFromUI (int paramIdx, double normalizedValue) inline virtual
SPVFUI Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
Parameters
paramIdx The index of the parameter that is changing value
normalizedValue The new normalised value of the parameter
Definition at line 245 of file IPlugEditorDelegate.h.
References GetParam(), NParams(), OnParamChangeUI(), and IParam::SetNormalized().
Referenced by WebViewEditorDelegate::OnMessageFromWebView(), and IControl::SetDirty().
SendSysexMsgFromDelegate()
virtual void IEditorDelegate::SendSysexMsgFromDelegate (const ISysEx & msg) inline virtual
SendSysexMsgFromDelegate (Abbreviation: SSMFD) WARNING: should not be called on the realtime audio thread.
This method can be used to send SysEx data from the class implementing IEditorDelegate to the user interface The message can be handled at the destination via IEditorDelegate::OnSysexMsgUI()
Parameters
msg an ISysEx Containing the SysEx data to send to the user interface.
Definition at line 215 of file IPlugEditorDelegate.h.
References OnSysexMsgUI().
SendSysexMsgFromUI()
virtual void IEditorDelegate::SendSysexMsgFromUI (const ISysEx & msg) inline virtual
SendSysexMsgFromUI (Abbreviation: SSMFUI) If a plug-in can send Sysex data as a result of actions in the user interface, this method can be used.
Unlike SendMidiMsgFromUI, Sysex messages will not be received in IPlugProcessor::ProcessSysex()
Parameters
msg The Sysex message to send.
Definition at line 274 of file IPlugEditorDelegate.h.
SerializeEditorState()
virtual bool IEditorDelegate::SerializeEditorState (IByteChunk & chunk) const inline virtual
Serializes the editor state (such as scale) into a binary chunk.
Parameters
chunk The output chunk to serialize to. Will append data if the chunk has already been started.
Returns
true if the serialization was successful
Reimplemented in IGEditorDelegate.
Definition at line 338 of file IPlugEditorDelegate.h.
SetEditorSize()
void IEditorDelegate::SetEditorSize (int width, int height) inline
Definition at line 291 of file IPlugEditorDelegate.h.
SetScreenScale()
virtual void IEditorDelegate::SetScreenScale (float scale) inline virtual
Can be used by a host API to inform the editor of screen scale changes.
Parameters
scale The new screen scale
Reimplemented in IGEditorDelegate.
Definition at line 348 of file IPlugEditorDelegate.h.
SetSizeConstraints()
void IEditorDelegate::SetSizeConstraints (int widthLo, int widthHi, int heightLo, int heightHi) inline
Sets the minimum and maximum size constraints for the editor window.
Parameters
widthLo Minimum width
widthHi Maximum width
heightLo Minimum height
heightHi Maximum height
Definition at line 298 of file IPlugEditorDelegate.h.
UnserializeEditorState()
virtual int IEditorDelegate::UnserializeEditorState (const IByteChunk & chunk, int startPos) inline virtual
Unserializes editor state (such as scale).
Parameters
chunk The incoming chunk where editor data is stored to unserialize
startPos The start position in the chunk where parameter values are stored
Returns
The new chunk position (endPos)
Reimplemented in IGEditorDelegate.
Definition at line 344 of file IPlugEditorDelegate.h.
Friends And Related Function Documentation
IPlugAAX
friend class IPlugAAX friend
Definition at line 351 of file IPlugEditorDelegate.h.
IPlugAPIBase
friend class IPlugAPIBase friend
Definition at line 360 of file IPlugEditorDelegate.h.
IPlugAPP
friend class IPlugAPP friend
Definition at line 350 of file IPlugEditorDelegate.h.
IPlugAU
friend class IPlugAU friend
Definition at line 356 of file IPlugEditorDelegate.h.
IPlugAUv3
friend class IPlugAUv3 friend
Definition at line 357 of file IPlugEditorDelegate.h.
IPluginBase
friend class IPluginBase friend
Definition at line 361 of file IPlugEditorDelegate.h.
IPlugVST2
friend class IPlugVST2 friend
Definition at line 352 of file IPlugEditorDelegate.h.
IPlugVST3
friend class IPlugVST3 friend
Definition at line 353 of file IPlugEditorDelegate.h.
IPlugVST3Controller
friend class IPlugVST3Controller friend
Definition at line 354 of file IPlugEditorDelegate.h.
IPlugVST3Processor
friend class IPlugVST3Processor friend
Definition at line 355 of file IPlugEditorDelegate.h.
IPlugWAM
friend class IPlugWAM friend
Definition at line 359 of file IPlugEditorDelegate.h.
IPlugWEB
friend class IPlugWEB friend
Definition at line 358 of file IPlugEditorDelegate.h.
The documentation for this class was generated from the following file:
IPlugEditorDelegate.h