iPlug 2: IByteChunkReader Class Reference
IByteChunkReader Class Reference
IPlug::Structs
Helper class to maintain a read position whilst extracting data from an IByteChunk
#include <IPlugStructs.h>
Public Member Functions
IByteChunkReader (const IByteChunk &chunk, int startPos=0)
int GetBytes (void *pBuf, int nBytesToCopy)
Copy nBytesToCopy bytes from the managed IByteChunk into pBuf .
template<class T >
int Get (T *pDst)
Copy arbitary typed data out of the managed IByteChunk at the current position and update the position.
int GetStr (WDL_String &str)
Retrieve a string from the managed IByteChunk and put it in str .
int Tell () const
Return the current position in the managed IByteChunk.
void Seek (int pos)
Set the current position in the managed IByteChunk.
Detailed Description
Helper class to maintain a read position whilst extracting data from an IByteChunk
Definition at line 322 of file IPlugStructs.h.
Constructor & Destructor Documentation
IByteChunkReader()
IByteChunkReader::IByteChunkReader (const IByteChunk & chunk, int startPos = 0) inline
Definition at line 325 of file IPlugStructs.h.
Member Function Documentation
Get()
template<class T > int IByteChunkReader::Get (T * pDst) inline
Copy arbitary typed data out of the managed IByteChunk at the current position and update the position.
Template Parameters
T type of the variable to get
Parameters
pDst Pointer to the destination where the value will be stored
Returns
int Next read position in the IByteChunk
Definition at line 346 of file IPlugStructs.h.
References IByteChunk::Get().
GetBytes()
int IByteChunkReader::GetBytes (void * pBuf, int nBytesToCopy) inline
Copy nBytesToCopy bytes from the managed IByteChunk into pBuf .
Parameters
pBuf Destination buffer
nBytesToCopy Number of bytes to copy
Returns
Next read position in the IByteChunk
Definition at line 335 of file IPlugStructs.h.
References IByteChunk::GetBytes().
GetStr()
int IByteChunkReader::GetStr (WDL_String & str) inline
Retrieve a string from the managed IByteChunk and put it in str .
Parameters
str Destination for the string
Returns
int Next read position in the IByteChunk
Definition at line 355 of file IPlugStructs.h.
References IByteChunk::GetStr().
Seek()
void IByteChunkReader::Seek (int pos) inline
Set the current position in the managed IByteChunk.
Parameters
pos The new IByteChunk position
Definition at line 367 of file IPlugStructs.h.
Tell()
int IByteChunkReader::Tell () const inline
Return the current position in the managed IByteChunk.
Returns
The current position in the IByteChunk
Definition at line 363 of file IPlugStructs.h.
The documentation for this class was generated from the following file:
IPlugStructs.h