iPlug 2: IVKeyboardControl Class Reference
IVKeyboardControl Class Reference
Vectorial keyboard control.
#include <IVKeyboardControl.h>
Public Member Functions
IVKeyboardControl (const IRECT &bounds, int minNote=48, int maxNote=72, bool roundedKeys=false, const IColor &WK_COLOR=DEFAULT_WK_COLOR, const IColor &BK_COLOR=DEFAULT_BK_COLOR, const IColor &PK_COLOR=DEFAULT_PK_COLOR, const IColor &FR_COLOR=DEFAULT_FR_COLOR, const IColor &HK_COLOR=DEFAULT_HK_COLOR)
void OnMouseDown (float x, float y, const IMouseMod &mod) override
Implement this method to respond to a mouse down event on this control.
void OnMouseUp (float x, float y, const IMouseMod &mod) override
Implement this method to respond to a mouse up event on this control.
void OnMouseOut () override
Implement this method to respond to a mouseout event on this control.
void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod) override
Implement this method to respond to a mouse drag event on this control.
void OnMouseOver (float x, float y, const IMouseMod &mod) override
Implement this method to respond to a mouseover event on this control.
void OnTouchCancelled (float x, float y, const IMouseMod &mod) override
Implement this method to respond to a touch cancel event on this control.
void OnResize () override
Called when IControl is constructed or resized using SetRect().
void OnMidi (const IMidiMsg &msg) override
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
void DrawKey (IGraphics &g, const IRECT &bounds, const IColor &color)
void Draw (IGraphics &g) override
Draw the control to the graphics context.
void SetNoteRange (int min, int max, bool keepWidth=true)
void SetNoteFromMidi (int noteNum, bool played)
void SetKeyIsPressed (int key, bool pressed)
void SetKeyHighlight (int key)
void ClearNotesFromMidi ()
void SetBlackToWhiteRatios (float widthRatio, float heightRatio=0.6)
void SetHeight (float h, bool keepAspectRatio=false)
void SetWidth (float w, bool keepAspectRatio=false)
void SetShowNotesAndVelocity (bool show)
void SetColors (const IColor BKColor, const IColor &WKColor, const IColor &PKColor=DEFAULT_PK_COLOR, const IColor &FRColor=DEFAULT_FR_COLOR)
int GetMidiNoteNumberForKey (int key) const
Public Member Functions inherited from IControl
IControl (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction actionFunc=nullptr)
Constructor.
IControl (const IRECT &bounds, const std::initializer_list< int > &params, IActionFunction actionFunc=nullptr)
Constructor (range of parameters)
IControl (const IRECT &bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
IControl (const IControl &)=delete
void operator= (const IControl &)=delete
virtual ~IControl ()
Destructor.
virtual void OnMouseDown (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse down event on this control.
virtual void OnMouseUp (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse up event on this control.
virtual void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
Implement this method to respond to a mouse drag event on this control.
virtual void OnMouseDblClick (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse double click event on this control.
virtual void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
Implement this method to respond to a mouse wheel event on this control.
virtual bool OnKeyDown (float x, float y, const IKeyPress &key)
Implement this method to respond to a key down event on this control.
virtual bool OnKeyUp (float x, float y, const IKeyPress &key)
Implement this method to respond to a key up event on this control.
virtual void OnMouseOver (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouseover event on this control.
virtual void OnMouseOut ()
Implement this method to respond to a mouseout event on this control.
virtual void OnTouchCancelled (float x, float y, const IMouseMod &mod)
Implement this method to respond to a touch cancel event on this control.
virtual void OnDrop (const char *str)
Implement to do something when something was drag 'n dropped onto this control.
virtual void OnDropMultiple (const std::vector< const char * > &paths)
Implement to handle multiple items drag 'n dropped onto this control.
virtual void OnRescale ()
Implement to do something when graphics is scaled globally (e.g.
virtual void OnResize ()
Called when IControl is constructed or resized using SetRect().
virtual void OnInit ()
Called just prior to when the control is attached, after its delegate and graphics member variable set.
virtual void OnAttached ()
Called after the control has been attached, and its delegate and graphics member variable set.
virtual void OnMsgFromDelegate (int msgTag, int dataSize, const void *pData)
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
virtual void OnMidi (const IMidiMsg &msg)
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
virtual bool OnGesture (const IGestureInfo &info)
virtual void CreateContextMenu (IPopupMenu &contextMenu)
Called by default when the user right clicks a control.
virtual void OnPopupMenuSelection (IPopupMenu *pSelectedMenu, int valIdx)
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControlPromptUserInput.
virtual void OnDeleteFromPopupMenu (IPopupMenu *pMenu, int itemIdx)
Implement this method to handle popup menu deletion interactions (on IOS) after IGraphics::CreatePopupMenu/IControlPromptUserInput.
virtual void OnTextEntryCompletion (const char *str, int valIdx)
Implement this method to handle text input after IGraphics::CreateTextEntry/IControlPromptUserInput.
virtual void OnContextSelection (int itemSelected)
Implement this to respond to a menu selection from CreateContextMenu();.
virtual void Draw (IGraphics &g)=0
Draw the control to the graphics context.
virtual void DrawPTHighlight (IGraphics &g)
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
void PromptUserInput (int valIdx=0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
void PromptUserInput (const IRECT &bounds, int valIdx=0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter) specifying the bounds.
IControl * SetActionFunction (IActionFunction actionFunc)
Set an Action Function for this control.
IControl * SetAnimationEndActionFunction (IActionFunction actionFunc)
Set an Action Function to be called at the end of an animation.
IControl * SetTooltip (const char *str)
Set a tooltip for the control.
const char * GetTooltip () const
int GetParamIdx (int valIdx=0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
virtual void SetParamIdx (int paramIdx, int valIdx=0)
Set the index of a parameter that the control is linked to If you are calling this "manually" to reuse a control for multiple parameters, you probably want to call IEditorDelegate::SendCurrentParamValuesFromDelegate() afterward, to update the control values.
int LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
int NVals () const
virtual int GetValIdxForPos (float x, float y) const
Check to see which of the control's values relates to this x and y coordinate.
const IParam * GetParam (int valIdx=0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
virtual void SetValueFromDelegate (double value, int valIdx=0)
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
virtual void SetValueFromUserInput (double value, int valIdx=0)
Set the control's value after user input.
virtual void SetValueToDefault (int valIdx=kNoValIdx)
Set one or all of the control's values to the default value of the associated parameter.
virtual void SetValue (double value, int valIdx=0)
Set one of the control's values.
double GetValue (int valIdx=0) const
Get the control's value.
void SetGroup (const char *groupName)
Assign the control to a control group.
const char * GetGroup () const
Get the group that the control belongs to, if any.
const IText & GetText () const
Get the Text object for the control.
virtual void SetText (const IText &txt)
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
void SetBlend (const IBlend &blend)
Set the Blend for this control.
IBlend GetBlend () const
Get the Blend for this control.
int GetTextEntryLength () const
Get the max number of characters that are allowed in text entry.
void SetTextEntryLength (int len)
Set the max number of characters that are allowed in text entry.
const IRECT & GetRECT () const
Get the rectangular draw area for this control, within the graphics context.
void SetRECT (const IRECT &bounds)
Set the rectangular draw area for this control, within the graphics context.
const IRECT & GetTargetRECT () const
Get the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetRECT (const IRECT &bounds)
Set the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetAndDrawRECTs (const IRECT &bounds)
Set BOTH the draw rect and the target area, within the graphics context for this control.
virtual void SetPosition (float x, float y)
Set the position of the control, preserving the width and height.
virtual void SetSize (float w, float h)
Set the size of the control, preserving the current position.
void SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
bool GetMouseDblAsSingleClick () const
Get double click as single click By default, mouse double click has its own handler.
virtual void Hide (bool hide)
Shows or hides the IControl.
bool IsHidden () const
virtual void SetDisabled (bool disable)
Sets disabled mode for the control, the default implementation modifies the mBlend member.
bool IsDisabled () const
void SetMouseOverWhenDisabled (bool allow)
Specify whether the control should respond to mouse overs when disabled.
void SetMouseEventsWhenDisabled (bool allow)
Specify whether the control should respond to other mouse events when disabled.
bool GetMouseOverWhenDisabled () const
bool GetMouseEventsWhenDisabled () const
bool GetIgnoreMouse () const
virtual void SetIgnoreMouse (bool ignore)
Specify whether the control should respond to mouse events.
bool GetPromptShowsParamLabel () const
void SetPromptShowsParamLabel (bool enable)
Set if the control should show parameter labels/units e.g.
virtual bool IsHit (float x, float y) const
Hit test the control.
virtual void SetDirty (bool triggerAction=true, int valIdx=kNoValIdx)
Mark the control as dirty, i.e.
virtual void SetClean ()
void Animate ()
virtual bool IsDirty ()
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
void DisablePrompt (bool disable)
Disable/enable default prompt for user input.
virtual void OnGUIIdle ()
This is an idle timer tick call on the GUI thread, only active if USE_IDLE_CALLS is defined.
int GetTag () const
Get the control's tag.
void SetWantsMidi (bool enable=true)
Specify whether this control wants to know about MIDI messages sent to the UI.
bool GetWantsMidi () const
void SetWantsMultiTouch (bool enable=true)
Specify whether this control supports multiple touches.
bool GetWantsMultiTouch () const
IControl * AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
virtual bool GetWantsGestures () const
EGestureType GetLastGesture () const
IGEditorDelegate * GetDelegate ()
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
void SetDelegate (IGEditorDelegate &dlg)
Used internally to set the mDelegate (and mGraphics) variables.
IContainerBase * GetParent () const
void SetParent (IContainerBase *pParent)
IGraphics * GetUI ()
const IGraphics * GetUI () const
bool GetMouseIsOver () const
This can be used in IControl::Draw() to check if the mouse is over the control, without implementing mouse over methods.
virtual void SnapToMouse (float x, float y, EDirection direction, const IRECT &bounds, int valIdx=-1, double minClip=0., double maxClip=1.)
Set control value based on x, y position within a rectangle.
virtual void OnEndAnimation ()
void StartAnimation (int duration)
void SetAnimation (IAnimationFunction func)
Set the animation function.
void SetAnimation (IAnimationFunction func, int duration)
Set the animation function and starts it.
IAnimationFunction GetAnimationFunction ()
Get the control's animation function, if it exists.
IActionFunction GetActionFunction ()
Get the control's action function, if it exists.
double GetAnimationProgress () const
Get the progress in a control's animation, in the range 0-1.
Milliseconds GetAnimationDuration () const
Get the duration of animations applied to the control.
template<class T >
T * As ()
Helper function to dynamic cast an IControl to a subclass.
Static Public Attributes
static const IColor DEFAULT_BK_COLOR = IColor(255, 70, 70, 70)
static const IColor DEFAULT_WK_COLOR = IColor(255, 240, 240, 240)
static const IColor DEFAULT_PK_COLOR = IColor(60, 0, 0, 0)
static const IColor DEFAULT_FR_COLOR = COLOR_BLACK
static const IColor DEFAULT_HK_COLOR = COLOR_ORANGE
Protected Attributes
IColor mWK_COLOR
IColor mBK_COLOR
IColor mPK_COLOR
IColor mFR_COLOR
IColor mHK_COLOR
bool mRoundedKeys = false
float mRoundness = 5.f
bool mDrawShadows = false
bool mDrawFrame = true
float mFrameThickness = 1.f
bool mShowNoteAndVel = false
float mWKWidth = 0.f
float mBKWidthRatio = 0.6f
float mBKHeightRatio = 0.6f
float mBKAlpha = 100.f
int mLastTouchedKey = -1
float mLastVelocity = 0.f
int mMouseOverKey = -1
int mMinNote
int mMaxNote
WDL_TypedBuf< bool > mIsBlackKeyList
WDL_TypedBuf< bool > mPressedKeys
WDL_TypedBuf< float > mKeyXPos
int mHighlight = -1
Protected Attributes inherited from IControl
IRECT mRECT
IRECT mTargetRECT
WDL_String mGroup
Controls can be grouped for hiding and showing panels.
IText mText
IBlend mBlend
int mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN
bool mDirty = true
bool mHide = false
bool mDisabled = false
bool mDisablePrompt = true
bool mDblAsSingleClick = false
bool mMouseOverWhenDisabled = false
bool mMouseEventsWhenDisabled = false
bool mIgnoreMouse = false
bool mWantsMidi = false
bool mWantsMultiTouch = false
bool mPromptShowsParamLabel = false
bool mMouseIsOver = false
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
WDL_String mTooltip
IColor mPTHighlightColor = COLOR_RED
bool mPTisHighlighted = false
Additional Inherited Members
Protected Member Functions inherited from IControl
template<typename T , typename... Args>
void ForValIdx (int valIdx, T func, Args... args)
A helper template function to call a method for an individual value, or for all values.
void SetNVals (int nVals)
Detailed Description
Vectorial keyboard control.
Definition at line 59 of file IVKeyboardControl.h.
Constructor & Destructor Documentation
IVKeyboardControl()
IVKeyboardControl::IVKeyboardControl (const IRECT & bounds, int minNote = 48, int maxNote = 72, bool roundedKeys = false, const IColor & WK_COLOR = DEFAULT_WK_COLOR, const IColor & BK_COLOR = DEFAULT_BK_COLOR, const IColor & PK_COLOR = DEFAULT_PK_COLOR, const IColor & FR_COLOR = DEFAULT_FR_COLOR, const IColor & HK_COLOR = DEFAULT_HK_COLOR) inline
Definition at line 68 of file IVKeyboardControl.h.
Member Function Documentation
ClearNotesFromMidi()
void IVKeyboardControl::ClearNotesFromMidi () inline
Definition at line 403 of file IVKeyboardControl.h.
Draw()
void IVKeyboardControl::Draw (IGraphics & g) inline override virtual
Draw the control to the graphics context.
Parameters
g The graphics context to which this control belongs.
Implements IControl.
Definition at line 234 of file IVKeyboardControl.h.
References IGraphics::DrawLine(), IGraphics::DrawRect(), IGraphics::DrawText(), IGraphics::FillRect(), IGraphics::FillRoundRect(), IRECT::H(), IControl::IsDisabled(), IRECT::W(), and IColor::WithContrast().
DrawKey()
void IVKeyboardControl::DrawKey (IGraphics & g, const IRECT & bounds, const IColor & color) inline
Definition at line 224 of file IVKeyboardControl.h.
GetMidiNoteNumberForKey()
int IVKeyboardControl::GetMidiNoteNumberForKey (int key) const inline
Definition at line 506 of file IVKeyboardControl.h.
OnMidi()
void IVKeyboardControl::OnMidi (const IMidiMsg & msg) inline override virtual
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
Reimplemented from IControl.
Definition at line 204 of file IVKeyboardControl.h.
References IMidiMsg::ControlChangeIdx(), IMidiMsg::NoteNumber(), IControl::SetDirty(), IMidiMsg::StatusMsg(), and IMidiMsg::Velocity().
OnMouseDown()
void IVKeyboardControl::OnMouseDown (float x, float y, const IMouseMod & mod) inline override virtual
Implement this method to respond to a mouse down event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented from IControl.
Definition at line 95 of file IVKeyboardControl.h.
References IControl::SetDirty().
OnMouseDrag()
void IVKeyboardControl::OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod & mod) inline override virtual
Implement this method to respond to a mouse drag event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
dX The X delta (difference) since the last event
dY The Y delta (difference) since the last event
mod A struct indicating which modifier keys are held for the event
Reimplemented from IControl.
Definition at line 140 of file IVKeyboardControl.h.
References IControl::SetDirty().
OnMouseOut()
void IVKeyboardControl::OnMouseOut () inline override virtual
Implement this method to respond to a mouseout event on this control.
Implementations should call base class, if you wish to use mMouseIsOver.
Reimplemented from IControl.
Definition at line 129 of file IVKeyboardControl.h.
References IControl::SetDirty().
OnMouseOver()
void IVKeyboardControl::OnMouseOver (float x, float y, const IMouseMod & mod) inline override virtual
Implement this method to respond to a mouseover event on this control.
Implementations should call base class, if you wish to use mMouseIsOver.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented from IControl.
Definition at line 163 of file IVKeyboardControl.h.
References IControl::SetDirty().
OnMouseUp()
void IVKeyboardControl::OnMouseUp (float x, float y, const IMouseMod & mod) inline override virtual
Implement this method to respond to a mouse up event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented from IControl.
Definition at line 114 of file IVKeyboardControl.h.
References IControl::SetDirty().
OnResize()
void IVKeyboardControl::OnResize () inline override virtual
Called when IControl is constructed or resized using SetRect().
NOTE: if you call SetDirty() in this method, you should call SetDirty(false) to avoid triggering parameter changes
Reimplemented from IControl.
Definition at line 187 of file IVKeyboardControl.h.
References IControl::SetDirty(), and IRECT::W().
OnTouchCancelled()
void IVKeyboardControl::OnTouchCancelled (float x, float y, const IMouseMod & mod) inline override virtual
Implement this method to respond to a touch cancel event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented from IControl.
Definition at line 172 of file IVKeyboardControl.h.
References IControl::SetDirty().
SetBlackToWhiteRatios()
void IVKeyboardControl::SetBlackToWhiteRatios (float widthRatio, float heightRatio = 0.6) inline
Definition at line 409 of file IVKeyboardControl.h.
SetColors()
void IVKeyboardControl::SetColors (const IColor BKColor, const IColor & WKColor, const IColor & PKColor = DEFAULT_PK_COLOR, const IColor & FRColor = DEFAULT_FR_COLOR) inline
Definition at line 473 of file IVKeyboardControl.h.
SetHeight()
void IVKeyboardControl::SetHeight (float h, bool keepAspectRatio = false) inline
Definition at line 434 of file IVKeyboardControl.h.
SetKeyHighlight()
void IVKeyboardControl::SetKeyHighlight (int key) inline
Definition at line 397 of file IVKeyboardControl.h.
SetKeyIsPressed()
void IVKeyboardControl::SetKeyIsPressed (int key, bool pressed) inline
Definition at line 391 of file IVKeyboardControl.h.
SetNoteFromMidi()
void IVKeyboardControl::SetNoteFromMidi (int noteNum, bool played) inline
Definition at line 385 of file IVKeyboardControl.h.
SetNoteRange()
void IVKeyboardControl::SetNoteRange (int min, int max, bool keepWidth = true) inline
Definition at line 365 of file IVKeyboardControl.h.
SetShowNotesAndVelocity()
void IVKeyboardControl::SetShowNotesAndVelocity (bool show) inline
Definition at line 468 of file IVKeyboardControl.h.
SetWidth()
void IVKeyboardControl::SetWidth (float w, bool keepAspectRatio = false) inline
Definition at line 447 of file IVKeyboardControl.h.
Member Data Documentation
DEFAULT_BK_COLOR
const IColor IVKeyboardControl::DEFAULT_BK_COLOR = IColor(255, 70, 70, 70) static
Definition at line 62 of file IVKeyboardControl.h.
DEFAULT_FR_COLOR
const IColor IVKeyboardControl::DEFAULT_FR_COLOR = COLOR_BLACK static
Definition at line 65 of file IVKeyboardControl.h.
DEFAULT_HK_COLOR
const IColor IVKeyboardControl::DEFAULT_HK_COLOR = COLOR_ORANGE static
Definition at line 66 of file IVKeyboardControl.h.
DEFAULT_PK_COLOR
const IColor IVKeyboardControl::DEFAULT_PK_COLOR = IColor(60, 0, 0, 0) static
Definition at line 64 of file IVKeyboardControl.h.
DEFAULT_WK_COLOR
const IColor IVKeyboardControl::DEFAULT_WK_COLOR = IColor(255, 240, 240, 240) static
Definition at line 63 of file IVKeyboardControl.h.
mBK_COLOR
IColor IVKeyboardControl::mBK_COLOR protected
Definition at line 706 of file IVKeyboardControl.h.
mBKAlpha
float IVKeyboardControl::mBKAlpha = 100.f protected
Definition at line 720 of file IVKeyboardControl.h.
mBKHeightRatio
float IVKeyboardControl::mBKHeightRatio = 0.6f protected
Definition at line 719 of file IVKeyboardControl.h.
mBKWidthRatio
float IVKeyboardControl::mBKWidthRatio = 0.6f protected
Definition at line 718 of file IVKeyboardControl.h.
mDrawFrame
bool IVKeyboardControl::mDrawFrame = true protected
Definition at line 714 of file IVKeyboardControl.h.
mDrawShadows
bool IVKeyboardControl::mDrawShadows = false protected
Definition at line 713 of file IVKeyboardControl.h.
mFR_COLOR
IColor IVKeyboardControl::mFR_COLOR protected
Definition at line 708 of file IVKeyboardControl.h.
mFrameThickness
float IVKeyboardControl::mFrameThickness = 1.f protected
Definition at line 715 of file IVKeyboardControl.h.
mHighlight
int IVKeyboardControl::mHighlight = -1 protected
Definition at line 728 of file IVKeyboardControl.h.
mHK_COLOR
IColor IVKeyboardControl::mHK_COLOR protected
Definition at line 709 of file IVKeyboardControl.h.
mIsBlackKeyList
WDL_TypedBuf<bool> IVKeyboardControl::mIsBlackKeyList protected
Definition at line 725 of file IVKeyboardControl.h.
mKeyXPos
WDL_TypedBuf<float> IVKeyboardControl::mKeyXPos protected
Definition at line 727 of file IVKeyboardControl.h.
mLastTouchedKey
int IVKeyboardControl::mLastTouchedKey = -1 protected
Definition at line 721 of file IVKeyboardControl.h.
mLastVelocity
float IVKeyboardControl::mLastVelocity = 0.f protected
Definition at line 722 of file IVKeyboardControl.h.
mMaxNote
int IVKeyboardControl::mMaxNote protected
Definition at line 724 of file IVKeyboardControl.h.
mMinNote
int IVKeyboardControl::mMinNote protected
Definition at line 724 of file IVKeyboardControl.h.
mMouseOverKey
int IVKeyboardControl::mMouseOverKey = -1 protected
Definition at line 723 of file IVKeyboardControl.h.
mPK_COLOR
IColor IVKeyboardControl::mPK_COLOR protected
Definition at line 707 of file IVKeyboardControl.h.
mPressedKeys
WDL_TypedBuf<bool> IVKeyboardControl::mPressedKeys protected
Definition at line 726 of file IVKeyboardControl.h.
mRoundedKeys
bool IVKeyboardControl::mRoundedKeys = false protected
Definition at line 711 of file IVKeyboardControl.h.
mRoundness
float IVKeyboardControl::mRoundness = 5.f protected
Definition at line 712 of file IVKeyboardControl.h.
mShowNoteAndVel
bool IVKeyboardControl::mShowNoteAndVel = false protected
Definition at line 716 of file IVKeyboardControl.h.
mWK_COLOR
IColor IVKeyboardControl::mWK_COLOR protected
Definition at line 705 of file IVKeyboardControl.h.
mWKWidth
float IVKeyboardControl::mWKWidth = 0.f protected
Definition at line 717 of file IVKeyboardControl.h.
The documentation for this class was generated from the following files:
IVKeyboardControl.h
IControls.cpp