iPlug 2: IPluginBase Class Reference
IPluginBase Class Reference
Base class that contains plug-in info and state manipulation methods.
#include <IPlugPluginBase.h>
Public Member Functions
IPluginBase (int nParams, int nPresets)
IPluginBase (const IPluginBase &)=delete
IPluginBase & operator= (const IPluginBase &)=delete
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
EHost GetHost () const
void GetHostStr (WDL_String &str) const
Get the host name (name is normalized)
void GetRawHostStr (WDL_String &str) const
Get raw host name (as it is reported from the host)
int GetHostVersion (bool decimal) const
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str) const
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str, const char *date, const char *time) const
Get the build date of the plug-in and architecture/api details in one string.
bool HasUI () const
bool GetHostResizeEnabled () const
const char * GetBundleID () const
const char * GetAppGroupID () const
int NParamGroups () const
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx) const
Get the parameter group name as a particular index.
virtual void InformHostOfParameterDetailsChange ()
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
bool DoesStateChunks () const
bool SerializeParams (IByteChunk &chunk) const
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
virtual bool SerializeState (IByteChunk &chunk) const
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
virtual bool SerializeVST3CtrlrState (IByteChunk &chunk) const
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
virtual int UnserializeVST3CtrlrState (const IByteChunk &chunk, int startPos)
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
int GetCurrentPresetIdx () const
Get the index of the current, active preset.
void SetCurrentPresetIdx (int idx)
Set the index of the current, active preset.
virtual void InformHostOfPresetChange ()
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
IPreset * GetPreset (int idx)
Get a ptr to a factory preset @ param idx The index number of the preset you are referring to.
void ModifyCurrentPreset (const char *name=0)
This method should update the current preset with current values NOTE: This is only relevant for VST2 plug-ins, which is the only format to have the notion of banks?
int NPresets () const
Gets the number of factory presets.
bool RestorePreset (int idx)
Restore a preset by index.
bool RestorePreset (const char *name)
Restore a preset by name.
const char * GetPresetName (int idx) const
Get the name a preset.
void CopyPreset (IPreset *pSrc, int destIdx, bool copyname=false)
Copy source preset to preset at index.
void MakeDefaultPreset (const char *name=0, int nPresets=1)
This method can be used to initialize baked-in factory presets with the default parameter values.
void MakePreset (const char *name,...)
Create a baked-in factory preset, specifiying parameter values sequentially usage: MakePreset(name, param1, param2, ..., paramN) See DumpMakePresetSrc() which is a utility that can be used to create the code for MakePreset() calls.
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
Create a baked-in factory preset, specifiying parameter values with a list of parameter index and value pairs usage: MakePresetFromNamedParams(name, nParamsNamed, paramEnum1, paramVal1, paramEnum2, paramVal2, ..., paramEnumN, paramVal2) See DumpMakePresetFromNamedParamsSrc() which is a utility that can be used to create the code for MakePreset() calls nParamsNamed may be less than the total number of params.
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
Creates a preset from an IByteChunk containing serialized data.
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
Creates a preset from a base64 encoded CString.
void PruneUninitializedPresets ()
[AUV2 only] Removes any presets that weren't initialized
virtual void OnPresetsModified ()
[VST2 only] Called when the preset name is changed by the host
void EnsureDefaultPreset ()
[VST2 only] Called to fill uninitialzed presets
bool SerializePresets (IByteChunk &chunk) const
[VST2 only] Called when the VST2 host calls effGetChunk for a bank *
int UnserializePresets (const IByteChunk &chunk, int startPos)
[VST2 only] Called when the VST2 host calls effSetChunk for a bank *
void DumpMakePresetSrc (const char *file) const
Writes a call to MakePreset() for the current preset to a new text file.
void DumpMakePresetFromNamedParamsSrc (const char *file, const char *paramEnumNames[]) const
Writes a call to MakePresetFromNamedParams() for the current preset to a new text file.
void DumpPresetBlob (const char *file) const
Writes a call to MakePresetFromBlob() for the current preset to a new text file.
bool SavePresetAsFXP (const char *file) const
Save current state as a VST2 format preset.
bool SaveBankAsFXB (const char *file) const
Save current bank as a VST2 format bank [VST2 only].
bool LoadPresetFromFXP (const char *file)
Load VST2 format preset.
bool LoadBankFromFXB (const char *file)
Load VST2 format bank [VST2 only].
void InitParamRange (int startIdx, int endIdx, int countStart, const char *nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", const IParam::Shape &shape=IParam::ShapeLinear(), IParam::EParamUnit unit=IParam::kUnitCustom, IParam::DisplayFunc displayFunc=nullptr)
Initialise a range of parameters simultaneously.
void CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
void ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
void ForParamInGroup (const char *paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
void CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
void CopyParamValues (const char *inGroup, const char *outGroup)
Copy a range of parameter values for a parameter group.
void RandomiseParamValues ()
Randomise all parameters.
void RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
void RandomiseParamValues (const char *paramGroup)
Randomise parameter values for a parameter group.
void DefaultParamValues ()
Set all parameters to their default values.
void DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
void DefaultParamValues (const char *paramGroup)
Default parameter values for a parameter group.
void PrintParamValues ()
Default parameter values for a parameter group
Friends
class IPlugAPP
class IPlugAAX
class IPlugVST2
class IPlugVST3
class IPlugVST3Controller
class IPlugVST3Processor
class IPlugAU
class IPlugAUv3
class IPlugWEB
class IPlugWAM
class IPlugAPIBase
Detailed Description
Base class that contains plug-in info and state manipulation methods.
Definition at line 26 of file IPlugPluginBase.h.
Constructor & Destructor Documentation
IPluginBase()
IPluginBase::IPluginBase (int nParams, int nPresets)
Definition at line 22 of file IPlugPluginBase.cpp.
~IPluginBase()
IPluginBase::~IPluginBase () virtual
Definition at line 29 of file IPlugPluginBase.cpp.
Member Function Documentation
AddParamGroup()
int IPluginBase::AddParamGroup (const char * name) inline
Called to add a parameter group name, when a unique group name is discovered.
Parameters
name CString for the unique group name
Returns
Number of parameter groups
Definition at line 118 of file IPlugPluginBase.h.
References NParamGroups().
CloneParamRange()
void IPluginBase::CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char * searchStr = "", const char * replaceStr = "", const char * newGroup = "")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
Parameters
cloneStartIdx The index of the first parameter to clone
cloneEndIdx The index of the last parameter to clone
startIdx The start of the cloned range
searchStr A CString to search for in the input parameter name
replaceStr A CString to replace searchStr in the output parameter name
newGroup If the new parameter should have a different group, update here
Definition at line 154 of file IPlugPluginBase.cpp.
References IParam::Value().
CopyParamValues() [1/2]
void IPluginBase::CopyParamValues (const char * inGroup, const char * outGroup)
Copy a range of parameter values for a parameter group.
Parameters
inGroup The name of the group to copy from
outGroup The name of the group to copy to
Definition at line 177 of file IPlugPluginBase.cpp.
References IParam::GetGroup().
CopyParamValues() [2/2]
void IPluginBase::CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
Parameters
startIdx The index of the first parameter value to copy
destIdx The index of the first destination parameter
nParams The number of parameters to copy
Definition at line 165 of file IPlugPluginBase.cpp.
CopyPreset()
void IPluginBase::CopyPreset (IPreset * pSrc, int destIdx, bool copyname = false) inline
Copy source preset to preset at index.
Parameters
pSrc source preset
destIdx index of internal destination preset
Definition at line 209 of file IPlugPluginBase.h.
References IByteChunk::Clear(), and IByteChunk::PutChunk().
DefaultParamValues() [1/3]
void IPluginBase::DefaultParamValues ()
Set all parameters to their default values.
Definition at line 222 of file IPlugPluginBase.cpp.
References DefaultParamValues().
Referenced by DefaultParamValues().
DefaultParamValues() [2/3]
void IPluginBase::DefaultParamValues (const char * paramGroup)
Default parameter values for a parameter group.
Parameters
paramGroup The name of the group to modify
Definition at line 234 of file IPlugPluginBase.cpp.
References ForParamInGroup(), and IParam::SetToDefault().
DefaultParamValues() [3/3]
void IPluginBase::DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
Parameters
startIdx The index of the first parameter to modify
endIdx The index of the last parameter to modify
Definition at line 227 of file IPlugPluginBase.cpp.
References ForParamInRange(), and IParam::SetToDefault().
DoesStateChunks()
bool IPluginBase::DoesStateChunks () const inline
Returns
true if the plug-in has been set up to do state chunks, via config.h
Definition at line 130 of file IPlugPluginBase.h.
Referenced by LoadBankFromFXB(), LoadPresetFromFXP(), SaveBankAsFXB(), and SavePresetAsFXP().
DumpMakePresetFromNamedParamsSrc()
void IPluginBase::DumpMakePresetFromNamedParamsSrc (const char * file, const char * paramEnumNames[]) const
Writes a call to MakePresetFromNamedParams() for the current preset to a new text file.
Parameters
file The full path of the file to write or overwrite
paramEnumNames A list of all parameter names. e.g. const char* pParamNames[] = {"kParam1", "kParam2", "kParam3"};
Definition at line 581 of file IPlugPluginBase.cpp.
References IParam::Bool(), GetCurrentPresetIdx(), GetPresetName(), IParam::Int(), IParam::Type(), and IParam::Value().
DumpMakePresetSrc()
void IPluginBase::DumpMakePresetSrc (const char * file) const
Writes a call to MakePreset() for the current preset to a new text file.
Parameters
file The full path of the file to write or overwrite.
Definition at line 538 of file IPlugPluginBase.cpp.
References IParam::Bool(), GetCurrentPresetIdx(), GetPresetName(), IParam::Int(), IParam::Type(), and IParam::Value().
DumpPresetBlob()
void IPluginBase::DumpPresetBlob (const char * file) const
Writes a call to MakePresetFromBlob() for the current preset to a new text file.
Parameters
file The full path of the file to write or overwrite.
Definition at line 624 of file IPlugPluginBase.cpp.
References GetCurrentPresetIdx(), IByteChunk::GetData(), GetPresetName(), and IByteChunk::Size().
EnsureDefaultPreset()
void IPluginBase::EnsureDefaultPreset ()
[VST2 only] Called to fill uninitialzed presets
Definition at line 392 of file IPlugPluginBase.cpp.
References MakeDefaultPreset().
ForParamInGroup()
void IPluginBase::ForParamInGroup (const char * paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
Parameters
paramGroup The name of the group to modify
func A lambda function to modify the parameter. Ideas: you could randomise the parameter value or reset to default
Definition at line 210 of file IPlugPluginBase.cpp.
References IParam::GetGroup().
Referenced by DefaultParamValues(), and RandomiseParamValues().
ForParamInRange()
void IPluginBase::ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
Parameters
startIdx The index of the first parameter to modify
endIdx The index of the last parameter to modify
func A lambda function to modify the parameter. Ideas: you could randomise the parameter value or reset to default, modify certain params based on their group
Definition at line 202 of file IPlugPluginBase.cpp.
Referenced by DefaultParamValues(), PrintParamValues(), and RandomiseParamValues().
GetAPI()
EAPI IPluginBase::GetAPI () const inline
Returns
The The plug-in API, see EAPI enum for a list of possible APIs
Definition at line 84 of file IPlugPluginBase.h.
Referenced by GetAPIStr().
GetAPIStr()
const char * IPluginBase::GetAPIStr () const
Returns
Returns a CString describing the plug-in API, e.g. "VST2"
Definition at line 66 of file IPlugPluginBase.cpp.
References GetAPI().
Referenced by GetBuildInfoStr().
GetAppGroupID()
const char * IPluginBase::GetAppGroupID () const inline
Definition at line 108 of file IPlugPluginBase.h.
GetArchStr()
const char * IPluginBase::GetArchStr () const
Returns
Returns a CString either "x86" or "x64", "arm64" or "WASM" describing the binary architecture
Definition at line 83 of file IPlugPluginBase.cpp.
Referenced by GetBuildInfoStr().
GetBuildInfoStr()
void IPluginBase::GetBuildInfoStr (WDL_String & str, const char * date, const char * time) const
Get the build date of the plug-in and architecture/api details in one string.
Parameters
str WDL_String will be set with the Plugin name, architecture, api, build date, build time
date CString, use DATE macro
time CString, use TIME macro
Definition at line 100 of file IPlugPluginBase.cpp.
References GetAPIStr(), GetArchStr(), and GetPluginVersionStr().
GetBundleID()
const char * IPluginBase::GetBundleID () const inline
Definition at line 105 of file IPlugPluginBase.h.
GetCurrentPresetIdx()
int IPluginBase::GetCurrentPresetIdx () const inline
Get the index of the current, active preset.
Returns
The index of the current preset
Definition at line 167 of file IPlugPluginBase.h.
Referenced by DumpMakePresetFromNamedParamsSrc(), DumpMakePresetSrc(), DumpPresetBlob(), LoadPresetFromFXP(), IVBakedPresetManagerControl::OnAttached(), SaveBankAsFXB(), and SavePresetAsFXP().
GetHost()
EHost IPluginBase::GetHost () const inline
Returns
The host if it has been identified, see EHost enum for a list of possible hosts
Definition at line 64 of file IPlugPluginBase.h.
Referenced by GetHostStr(), and IPlugVST2::HostSpecificInit().
GetHostResizeEnabled()
bool IPluginBase::GetHostResizeEnabled () const inline
Returns
true if the plug-in allows reszing via the host's window chrome, as defined in config.h
Definition at line 102 of file IPlugPluginBase.h.
GetHostStr()
void IPluginBase::GetHostStr (WDL_String & str) const inline
Get the host name (name is normalized)
Parameters
str WDL_String into which to write the host name
Definition at line 68 of file IPlugPluginBase.h.
References GetHost(), and GetHostNameStr().
GetHostVersion()
int IPluginBase::GetHostVersion (bool decimal) const
Get the host version number as an integer.
Parameters
decimal true indicates decimal format = VVVVRRMM, otherwise hexadecimal 0xVVVVRRMM.
Returns
The host version number as an integer.
Definition at line 53 of file IPlugPluginBase.cpp.
References GetDecimalVersion().
GetHostVersionStr()
void IPluginBase::GetHostVersionStr (WDL_String & str) const
Get the host version number as a string.
Parameters
str string into which to write the host version
Definition at line 61 of file IPlugPluginBase.cpp.
References GetVersionStr().
GetMfrID()
int IPluginBase::GetMfrID () const inline
Returns
The plug-in manufacturer's unique four character ID as an integer
Definition at line 61 of file IPlugPluginBase.h.
GetMfrName()
const char * IPluginBase::GetMfrName () const inline
Get the manufacturer name as a CString.
Definition at line 52 of file IPlugPluginBase.h.
GetParamGroupName()
const char * IPluginBase::GetParamGroupName (int idx) const inline
Get the parameter group name as a particular index.
Parameters
idx The index to return
Returns
CString for the unique group name
Definition at line 123 of file IPlugPluginBase.h.
GetPluginName()
const char * IPluginBase::GetPluginName () const inline
Returns
the name of the plug-in as a CString
Definition at line 37 of file IPlugPluginBase.h.
GetPluginVersion()
int IPluginBase::GetPluginVersion (bool decimal) const
Get the plug-in version number.
Parameters
decimal Sets the output format
Returns
Effect version in VVVVRRMM (if decimal is true) or Hexadecimal 0xVVVVRRMM (if decimal is false) format
Definition at line 34 of file IPlugPluginBase.cpp.
References GetDecimalVersion().
Referenced by SaveBankAsFXB(), and SavePresetAsFXP().
GetPluginVersionStr()
void IPluginBase::GetPluginVersionStr (WDL_String & str) const
Gets the plug-in version as a string.
Parameters
str WDL_String to write to The output format is vX.M.m, where X - version, M - major, m - minor
Note
If _DEBUG is defined, D is appended to the version string
If TRACER_BUILD is defined, T is appended to the version string
Definition at line 42 of file IPlugPluginBase.cpp.
References GetVersionStr().
Referenced by GetBuildInfoStr().
GetPreset()
IPreset * IPluginBase::GetPreset (int idx) inline
Get a ptr to a factory preset @ param idx The index number of the preset you are referring to.
Definition at line 180 of file IPlugPluginBase.h.
GetPresetName()
const char * IPluginBase::GetPresetName (int idx) const
Get the name a preset.
Parameters
idx The index of the preset whose name to get
Returns
CString preset name
Definition at line 462 of file IPlugPluginBase.cpp.
Referenced by DumpMakePresetFromNamedParamsSrc(), DumpMakePresetSrc(), DumpPresetBlob(), IVBakedPresetManagerControl::OnAttached(), and SavePresetAsFXP().
GetProductName()
const char * IPluginBase::GetProductName () const inline
Get the product name as a CString.
A shipping product may contain multiple plug-ins, hence this. Not used in all APIs
Definition at line 55 of file IPlugPluginBase.h.
GetRawHostStr()
void IPluginBase::GetRawHostStr (WDL_String & str) const inline
Get raw host name (as it is reported from the host)
Parameters
str WDL_String into which to write the host name
Definition at line 72 of file IPlugPluginBase.h.
GetUniqueID()
int IPluginBase::GetUniqueID () const inline
Returns
The plug-in's unique four character ID as an integer
Definition at line 58 of file IPlugPluginBase.h.
Referenced by LoadBankFromFXB(), LoadPresetFromFXP(), SaveBankAsFXB(), and SavePresetAsFXP().
HasUI()
bool IPluginBase::HasUI () const inline
Returns
true if the plug-in is meant to have a UI, as defined in config.h
Definition at line 99 of file IPlugPluginBase.h.
Referenced by IPlugAAX::EditorResize(), IPlugCLAP::EditorResize(), IPlugVST2::EditorResize(), IPlugVST3::EditorResize(), and IPlugVST3Controller::EditorResize().
InformHostOfParameterDetailsChange()
virtual void IPluginBase::InformHostOfParameterDetailsChange () inline virtual
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
Reimplemented in IPlugAU, and IPlugVST3.
Definition at line 126 of file IPlugPluginBase.h.
InformHostOfPresetChange()
virtual void IPluginBase::InformHostOfPresetChange () inline virtual
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
Reimplemented in IPlugAAX, IPlugAPP, IPlugAU, IPlugAUv3, IPlugVST2, IPlugVST3, and IPlugVST3Controller.
Definition at line 174 of file IPlugPluginBase.h.
Referenced by LoadBankFromFXB(), and LoadPresetFromFXP().
InitParamRange()
void IPluginBase::InitParamRange (int startIdx, int endIdx, int countStart, const char * nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char * label = "", int flags = 0, const char * group = "", const IParam::Shape & shape = IParam::ShapeLinear(), IParam::EParamUnit unit = IParam::kUnitCustom, IParam::DisplayFunc displayFunc = nullptr)
Initialise a range of parameters simultaneously.
This mirrors the arguments available in IParam::InitDouble, for maximum flexibility
Parameters
startIdx The index of the first parameter to initialise
endIdx The index of the last parameter to initialise
countStart An integer representing the start of the count in the format string. If the first parameter should have "0" in its name, set this to 0
nameFmtStr A limited format string where i can be used to get the index + countStart, in the range of parameters specified
defaultVal A default real value for the parameter
minVal A minimum real value for the parameter
maxVal A Maximum real value for the parameter
step The parameter step
label A CString label for the parameter e.g. "decibels"
flags Any flags, see IParam::EFlags
group A CString group name for the parameter, e.g. "envelope"
shape A IParam::Shape class to determine how the parameter shape should be skewed
unit An IParam::EParamUnit which can be used in audiounit plug-ins to specify certain kinds of parameter
displayFunc An IParam::DisplayFunc lambda function to specify a custom display function
Definition at line 144 of file IPlugPluginBase.cpp.
LoadBankFromFXB()
bool IPluginBase::LoadBankFromFXB (const char * file)
Load VST2 format bank [VST2 only].
Parameters
file The full path of the file to load
Returns
/c true on success
Definition at line 918 of file IPlugPluginBase.cpp.
References DoesStateChunks(), IByteChunk::Get(), IByteChunk::GetBytes(), IByteChunk::GetData(), IByteChunk::GetIPlugVerFromChunk(), GetUniqueID(), InformHostOfPresetChange(), ModifyCurrentPreset(), IByteChunk::Resize(), RestorePreset(), and UnserializePresets().
LoadPresetFromFXP()
bool IPluginBase::LoadPresetFromFXP (const char * file)
Load VST2 format preset.
Parameters
file The full path of the file to load
Returns
/c true on success
Definition at line 827 of file IPlugPluginBase.cpp.
References DoesStateChunks(), IByteChunk::Get(), IByteChunk::GetBytes(), GetCurrentPresetIdx(), IByteChunk::GetData(), IByteChunk::GetIPlugVerFromChunk(), GetUniqueID(), InformHostOfPresetChange(), ModifyCurrentPreset(), IByteChunk::Resize(), RestorePreset(), and UnserializeState().
MakeDefaultPreset()
void IPluginBase::MakeDefaultPreset (const char * name = 0, int nPresets = 1)
This method can be used to initialize baked-in factory presets with the default parameter values.
It finds the first uninitialized preset and initializes nPresets that follow sequentially. Typically you would use it if you have configured you plugin bank to e.g. 32 presets, you provide e.g. 8 factory presets via MakePresetXXX, but you want to fill the rest of the 32 presets with default values
Parameters
name The name to give the presets
nPresets The number of presets to fill with default values
Definition at line 278 of file IPlugPluginBase.cpp.
References SerializeState().
Referenced by EnsureDefaultPreset().
MakePreset()
void IPluginBase::MakePreset (const char * name, ...)
Create a baked-in factory preset, specifiying parameter values sequentially usage: MakePreset(name, param1, param2, ..., paramN) See DumpMakePresetSrc() which is a utility that can be used to create the code for MakePreset() calls.
Parameters
name The preset name
... The list of parameter values, ordered sequentially according to paramIdx
Definition at line 292 of file IPlugPluginBase.cpp.
References IByteChunk::Put().
MakePresetFromBlob()
void IPluginBase::MakePresetFromBlob (const char * name, const char * blob, int sizeOfChunk)
Creates a preset from a base64 encoded CString.
This can be used when your plugin state includes arbitary data, other than just parameters. See DumpPresetBlob() which is a utility that can be used to create the code for DumpPresetBlob() calls
Parameters
name The preset name
blob The base64 encoded string
sizeOfChunk The binary string size
Definition at line 368 of file IPlugPluginBase.cpp.
References IByteChunk::GetData(), MakePresetFromChunk(), and IByteChunk::Resize().
MakePresetFromChunk()
void IPluginBase::MakePresetFromChunk (const char * name, IByteChunk & chunk)
Creates a preset from an IByteChunk containing serialized data.
This can be used when your plugin state includes arbitary data, other than just parameters.
Parameters
name The preset name
chunk An IByteChunk where the preset data has been serialized
Definition at line 356 of file IPlugPluginBase.cpp.
References IByteChunk::PutChunk().
Referenced by MakePresetFromBlob().
MakePresetFromNamedParams()
void IPluginBase::MakePresetFromNamedParams (const char * name, int nParamsNamed, ...)
Create a baked-in factory preset, specifiying parameter values with a list of parameter index and value pairs usage: MakePresetFromNamedParams(name, nParamsNamed, paramEnum1, paramVal1, paramEnum2, paramVal2, ..., paramEnumN, paramVal2) See DumpMakePresetFromNamedParamsSrc() which is a utility that can be used to create the code for MakePreset() calls nParamsNamed may be less than the total number of params.
Parameters
name The preset name
nParamsNamed The number of parameter index/value pairs. Parameters that are not set will be defaulted.
... The list of parameter index and value pairs
Definition at line 313 of file IPlugPluginBase.cpp.
ModifyCurrentPreset()
void IPluginBase::ModifyCurrentPreset (const char * name = 0)
This method should update the current preset with current values NOTE: This is only relevant for VST2 plug-ins, which is the only format to have the notion of banks?
Parameters
name CString name of the modified preset
Definition at line 471 of file IPlugPluginBase.cpp.
References IByteChunk::Clear(), and SerializeState().
Referenced by LoadBankFromFXB(), and LoadPresetFromFXP().
NParamGroups()
int IPluginBase::NParamGroups () const inline
Returns
The number of unique parameter groups identified
Definition at line 113 of file IPlugPluginBase.h.
Referenced by AddParamGroup().
NPresets()
int IPluginBase::NPresets () const inline
Gets the number of factory presets.
NOTE: some hosts don't like 0 presets, so even if you don't support factory presets, this method should return 1
Returns
The number of factory presets
Definition at line 189 of file IPlugPluginBase.h.
Referenced by IVBakedPresetManagerControl::OnAttached(), SaveBankAsFXB(), and SetCurrentPresetIdx().
OnPresetsModified()
virtual void IPluginBase::OnPresetsModified () inline virtual
[VST2 only] Called when the preset name is changed by the host
Definition at line 260 of file IPlugPluginBase.h.
Referenced by RestorePreset().
PrintParamValues()
void IPluginBase::PrintParamValues ()
Default parameter values for a parameter group
Definition at line 256 of file IPlugPluginBase.cpp.
References ForParamInRange(), and IParam::PrintDetails().
PruneUninitializedPresets()
void IPluginBase::PruneUninitializedPresets ()
[AUV2 only] Removes any presets that weren't initialized
Definition at line 398 of file IPlugPluginBase.cpp.
RandomiseParamValues() [1/3]
void IPluginBase::RandomiseParamValues ()
Randomise all parameters.
Definition at line 241 of file IPlugPluginBase.cpp.
References RandomiseParamValues().
Referenced by RandomiseParamValues().
RandomiseParamValues() [2/3]
void IPluginBase::RandomiseParamValues (const char * paramGroup)
Randomise parameter values for a parameter group.
Parameters
paramGroup The name of the group to modify
Definition at line 251 of file IPlugPluginBase.cpp.
References ForParamInGroup(), and IParam::SetNormalized().
RandomiseParamValues() [3/3]
void IPluginBase::RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
NOTE for more flexibility in terms of RNG etc, use ForParamInRange()
Parameters
startIdx The index of the first parameter to modify
endIdx The index of the last parameter to modify
Definition at line 246 of file IPlugPluginBase.cpp.
References ForParamInRange(), and IParam::SetNormalized().
RestorePreset() [1/2]
bool IPluginBase::RestorePreset (const char * name)
Restore a preset by name.
Parameters
CString name of the preset to restore
Returns
true on success
Definition at line 445 of file IPlugPluginBase.cpp.
References RestorePreset().
RestorePreset() [2/2]
bool IPluginBase::RestorePreset (int idx)
Restore a preset by index.
This should also update mCurrentPresetIdx
Parameters
idx The index of the preset to restore
Returns
true on success
Definition at line 416 of file IPlugPluginBase.cpp.
References OnPresetsModified(), SerializeState(), and UnserializeState().
Referenced by LoadBankFromFXB(), LoadPresetFromFXP(), RestorePreset(), and UnserializePresets().
SaveBankAsFXB()
bool IPluginBase::SaveBankAsFXB (const char * file) const
Save current bank as a VST2 format bank [VST2 only].
Parameters
file The full path of the file to write or overwrite
Returns
/c true on success
Definition at line 722 of file IPlugPluginBase.cpp.
References DoesStateChunks(), IByteChunk::Get(), GetCurrentPresetIdx(), IByteChunk::GetData(), GetPluginVersion(), GetUniqueID(), IByteChunk::InitChunkWithIPlugVer(), NPresets(), IByteChunk::Put(), IByteChunk::PutBytes(), SerializePresets(), and IByteChunk::Size().
SavePresetAsFXP()
bool IPluginBase::SavePresetAsFXP (const char * file) const
Save current state as a VST2 format preset.
Parameters
file The full path of the file to write or overwrite
Returns
/c true on success
Definition at line 649 of file IPlugPluginBase.cpp.
References DoesStateChunks(), GetCurrentPresetIdx(), IByteChunk::GetData(), GetPluginVersion(), GetPresetName(), GetUniqueID(), IByteChunk::InitChunkWithIPlugVer(), IByteChunk::Put(), IByteChunk::PutBytes(), SerializeState(), and IByteChunk::Size().
SerializeParams()
bool IPluginBase::SerializeParams (IByteChunk & chunk) const
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
Parameters
chunk The output chunk to serialize to. Will append data if the chunk has already been started.
Returns
true if the serialization was successful
Definition at line 109 of file IPlugPluginBase.cpp.
References IParam::GetName(), IByteChunk::Put(), and IParam::Value().
Referenced by SerializeState().
SerializePresets()
bool IPluginBase::SerializePresets (IByteChunk & chunk) const
[VST2 only] Called when the VST2 host calls effGetChunk for a bank *
Parameters
chunk IByteChunk where the presets will be serialized
Returns
/c true on success
Definition at line 489 of file IPlugPluginBase.cpp.
References IByteChunk::Put(), IByteChunk::PutChunk(), and IByteChunk::PutStr().
Referenced by SaveBankAsFXB().
SerializeState()
virtual bool IPluginBase::SerializeState (IByteChunk & chunk) const inline virtual
Override this method to serialize custom state data, if your plugin does state chunks.
Parameters
chunk The output bytechunk where data can be serialized
Returns
true if serialization was successful
Definition at line 146 of file IPlugPluginBase.h.
References SerializeParams().
Referenced by MakeDefaultPreset(), ModifyCurrentPreset(), RestorePreset(), SavePresetAsFXP(), and UnserializePresets().
SerializeVST3CtrlrState()
virtual bool IPluginBase::SerializeVST3CtrlrState (IByteChunk & chunk) const inline virtual
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
Parameters
chunk The output bytechunk where data can be serialized.
Returns
true if serialization was successful
Definition at line 158 of file IPlugPluginBase.h.
SetCurrentPresetIdx()
void IPluginBase::SetCurrentPresetIdx (int idx) inline
Set the index of the current, active preset.
Parameters
idx The index of the current preset
Definition at line 171 of file IPlugPluginBase.h.
References NPresets().
UnserializeParams()
int IPluginBase::UnserializeParams (const IByteChunk & chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
Parameters
chunk The incoming chunk where parameter values are stored to unserialize
startPos The start position in the chunk where parameter values are stored
Returns
The new chunk position (endPos)
Definition at line 124 of file IPlugPluginBase.cpp.
References IByteChunk::Get(), IParam::GetName(), IParam::Set(), and IParam::Value().
Referenced by UnserializeState().
UnserializePresets()
int IPluginBase::UnserializePresets (const IByteChunk & chunk, int startPos)
[VST2 only] Called when the VST2 host calls effSetChunk for a bank *
Parameters
chunk IByteChunk where the preset bank will be unserialized
startPos The starting position in the chunk for the preset bank
Returns
int The new chunk position (endPos).
Definition at line 510 of file IPlugPluginBase.cpp.
References IByteChunk::Clear(), IByteChunk::Get(), IByteChunk::GetStr(), RestorePreset(), SerializeState(), and UnserializeState().
Referenced by LoadBankFromFXB().
UnserializeState()
virtual int IPluginBase::UnserializeState (const IByteChunk & chunk, int startPos) inline virtual
Override this method to unserialize custom state data, if your plugin does state chunks.
Implementations should call UnserializeParams() after custom data is unserialized
Parameters
chunk The incoming chunk containing the state data.
startPos The position in the chunk where the data starts
Returns
The new chunk position (endPos)
Definition at line 153 of file IPlugPluginBase.h.
References UnserializeParams().
Referenced by LoadPresetFromFXP(), RestorePreset(), and UnserializePresets().
UnserializeVST3CtrlrState()
virtual int IPluginBase::UnserializeVST3CtrlrState (const IByteChunk & chunk, int startPos) inline virtual
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
Parameters
chunk chunk The incoming chunk containing the state data.
Returns
The new chunk position (endPos)
Definition at line 163 of file IPlugPluginBase.h.
Friends And Related Function Documentation
IPlugAAX
friend class IPlugAAX friend
Definition at line 388 of file IPlugPluginBase.h.
IPlugAPIBase
friend class IPlugAPIBase friend
Definition at line 397 of file IPlugPluginBase.h.
IPlugAPP
friend class IPlugAPP friend
Definition at line 387 of file IPlugPluginBase.h.
IPlugAU
friend class IPlugAU friend
Definition at line 393 of file IPlugPluginBase.h.
IPlugAUv3
friend class IPlugAUv3 friend
Definition at line 394 of file IPlugPluginBase.h.
IPlugVST2
friend class IPlugVST2 friend
Definition at line 389 of file IPlugPluginBase.h.
IPlugVST3
friend class IPlugVST3 friend
Definition at line 390 of file IPlugPluginBase.h.
IPlugVST3Controller
friend class IPlugVST3Controller friend
Definition at line 391 of file IPlugPluginBase.h.
IPlugVST3Processor
friend class IPlugVST3Processor friend
Definition at line 392 of file IPlugPluginBase.h.
IPlugWAM
friend class IPlugWAM friend
Definition at line 396 of file IPlugPluginBase.h.
IPlugWEB
friend class IPlugWEB friend
Definition at line 395 of file IPlugPluginBase.h.
The documentation for this class was generated from the following files:
IPlugPluginBase.h
IPlugPluginBase.cpp