iPlug2: IPlugAPIBase Class Reference
IPlugAPIBase Class Reference
The base class of an IPlug plug-in, which interacts with the different plug-in APIs.
#include <IPlugAPIBase.h>
Public Member Functions
IPlugAPIBase (IPlugConfig config, EAPI plugAPI)
virtual bool CompareState (const uint8_t *pIncomingState, int startPos) const
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual bool OnHostRequestingAboutBox ()
virtual bool OnHostRequestingProductHelp ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual void OnHostRequestingImportantParameters (int count, WDL_TypedBuf< int > &results)
Called by AUv3 plug-ins to get the "overview parameters".
virtual bool OnHostRequestingSupportedViewConfiguration (int width, int height)
Called by AUv3 plug-in hosts to query support for multiple UI sizes.
virtual void OnHostSelectedViewConfiguration (int width, int height)
Called by some AUv3 plug-in hosts when a particular UI size is selected.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
virtual void * GetAAXViewInterface ()
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
virtual void OnIdle ()
Override this method to get an "idle"" call on the main thread.
virtual void PrintDebugInfo () const
Helper method, used to print some info to the console in debug builds.
virtual void EditorPropertiesChangedFromDelegate (int width, int height, const IByteChunk &data)
Call this method from a delegate, for example if you wish to store graphics dimensions in your plug-in state in order to notify the API of a graphics resize or other layout change.
virtual void BeginInformHostOfParamChange (int paramIdx)
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
virtual void EndInformHostOfParamChange (int paramIdx)
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
virtual void GetTrackColor (int &r, int &g, int &b)
Get the color of the track that the plug-in is inserted on.
virtual void GetTrackName (WDL_String &str)
Get the name of the track that the plug-in is inserted on.
virtual void DirtyParametersFromUI () override
When modifying a range of parameters in the editor, it can be necessary to broadcast that fact, for instance in a distributed plug-in.
virtual void SendParameterValueFromAPI (int paramIdx, double value, bool normalized)
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange() NOTE: It may be called on the high priority audio thread.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known (calls on to HostSpecificInit() and OnHostIdentified()).
virtual void HostSpecificInit ()
This method is implemented in some API classes, in order to do specific initialisation for particular problematic hosts.
void BeginInformHostOfParamChangeFromUI (int paramIdx) override
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EndInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EditorPropertiesChangedFromUI (int viewWidth, int viewHeight, const IByteChunk &data) override
If the editor changes UI dimensions or other state we need to call into the plug-in API to store state or resize the window in the plugin This method is implemented in various classes that inherit this interface to implement that behaviour.
void SendParameterValueFromUI (int paramIdx, double normalisedValue) override
SPVFUI Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
void SendMidiMsgFromUI (const IMidiMsg &msg) override
SendMidiMsgFromUI (Abbreviation: SMMFUI) This method should be used when sending a MIDI message from the UI.
void SendSysexMsgFromUI (const ISysEx &msg) override
SendMidiMsgFromUI (Abbreviation: SSMFUI) If a plug-in can send Sysex data as a result of actions in the user interface, this method can be used.
void SendArbitraryMsgFromUI (int messageTag, int controlTag=kNoTag, int dataSize=0, const void *pData=nullptr) override
SendArbitraryMsgFromUI (Abbreviation: SAMFUI)
void DeferMidiMsg (const IMidiMsg &msg) override
This method is needed, for remote editors to avoid a feedback loop.
void DeferSysexMsg (const ISysEx &msg) override
This method is needed, for remote editors to avoid a feedback loop.
void CreateTimer ()
Public Member Functions inherited from IPluginBase
IPluginBase (int nParams, int nPresets)
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
EHost GetHost () const
int GetHostVersion (bool decimal) const
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str) const
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool HasUI () const
const char * GetBundleID () const
int NParamGroups () const
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx) const
Get the parameter group name as a particular index.
virtual void InformHostOfParameterDetailsChange ()
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
virtual void OnParamChange (int paramIdx, EParamSource source, int sampleOffset=-1)
Override this method to do something to your DSP when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
void OnParamReset (EParamSource source)
Calls OnParamChange() and OnParamChangeUI() for each parameter.
bool DoesStateChunks () const
bool SerializeParams (IByteChunk &chunk) const
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
virtual bool SerializeState (IByteChunk &chunk) const
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
virtual bool SerializeVST3CtrlrState (IByteChunk &chunk) const
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
virtual int UnserializeVST3CtrlrState (const IByteChunk &chunk, int startPos)
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
int GetCurrentPresetIdx () const
Get the index of the current, active preset.
void SetCurrentPresetIdx (int idx)
Set the index of the current, active preset.
virtual void InformHostOfProgramChange ()
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
void ModifyCurrentPreset (const char *name=0)
int NPresets () const
bool RestorePreset (int idx)
bool RestorePreset (const char *name)
const char * GetPresetName (int idx) const
void MakeDefaultPreset (const char *name=0, int nPresets=1)
void MakePreset (const char *name,...)
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
void PruneUninitializedPresets ()
virtual void OnPresetsModified ()
void EnsureDefaultPreset ()
bool SerializePresets (IByteChunk &chunk) const
int UnserializePresets (IByteChunk &chunk, int startPos)
void DumpPresetSrcCode (const char *file, const char *paramEnumNames[]) const
void DumpPresetBlob (const char *file) const
void DumpAllPresetsBlob (const char *filename) const
void DumpBankBlob (const char *file) const
bool SaveProgramAsFXP (const char *file) const
bool SaveBankAsFXB (const char *file) const
bool LoadProgramFromFXP (const char *file)
bool LoadBankFromFXB (const char *file)
bool SaveBankAsFXPs (const char *path) const
void MakeVSTPresetChunk (IByteChunk &chunk, IByteChunk &componentState, IByteChunk &controllerState) const
bool SaveProgramAsVSTPreset (const char *file) const
bool LoadProgramFromVSTPreset (const char *file)
bool SaveBankAsVSTPresets (const char *path)
bool SaveProgramAsAUPreset (const char *name, const char *file) const
bool LoadProgramFromAUPreset (const char *file)
bool SaveBankAsAUPresets (const char *path)
bool SaveProgramAsProToolsPreset (const char *presetName, const char *file, unsigned long pluginID) const
bool LoadProgramFromProToolsPreset (const char *file)
bool SaveBankAsProToolsPresets (const char *bath, unsigned long pluginID)
void InitParamRange (int startIdx, int endIdx, int countStart, const char *nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", IParam::Shape *shape=nullptr, IParam::EParamUnit unit=IParam::kUnitCustom, IParam::DisplayFunc displayFunc=nullptr)
Initialise a range of parameters simultaneously.
void CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
void ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
void ForParamInGroup (const char *paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
void CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
void CopyParamValues (const char *inGroup, const char *outGroup)
Copy a range of parameter values for a parameter group.
void RandomiseParamValues ()
Randomise all parameters.
void RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
void RandomiseParamValues (const char *paramGroup)
Randomise parameter values for a parameter group.
void DefaultParamValues ()
Set all parameters to their default values.
void DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
void DefaultParamValues (const char *paramGroup)
Default parameter values for a parameter group.
void PrintParamValues ()
Default parameter values for a parameter group.
Public Member Functions inherited from IEditorDelegate
IEditorDelegate (int nParams)
IParam * AddParam ()
Adds an IParam to the parameters ptr list Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
void RemoveParam (int idx)
Remove an IParam at a particular index Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
const IParam * GetParam (int paramIdx) const
Get a const pointer to one of the delegate's IParam objects (for const methods)
int NParams () const
void SendCurrentParamValuesFromDelegate ()
Loops through all parameters, calling SendParameterValueFromDelegate() with the current value of the parameter This is important when modifying groups of parameters, restoring state and opening the UI, in order to update it with the latest values.
virtual void * OpenWindow (void *pParent)
If you are not using IGraphics, you can implement this method to attach to the native parent view e.g.
virtual void CloseWindow ()
If you are not using IGraphics you can if you need to free resources etc when the window closes.
virtual void OnUIOpen ()
Override this method to do something before the UI is opened.
virtual void OnUIClose ()
Override this method to do something before the UI is closed.
virtual void OnParamChangeUI (int paramIdx, EParamSource source=kUnknown)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
Handle incoming MIDI messages sent to the user interface.
virtual void OnSysexMsgUI (const ISysEx &msg)
Handle incoming SysEx messages sent to the user interface.
virtual bool OnMessage (int messageTag, int controlTag, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginBase::RestorePreset().
virtual void SendControlValueFromDelegate (int controlTag, double normalizedValue)
SendControlValueFromDelegate (Abbreviation: SCVFD) WARNING: should not be called on the realtime audio thread.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize=0, const void *pData=nullptr)
SendControlMsgFromDelegate (Abbreviation: SCMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendArbitraryMsgFromDelegate (int messageTag, int dataSize=0, const void *pData=nullptr)
SendArbitraryMsgFromDelegate (Abbreviation: SAMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendMidiMsgFromDelegate (const IMidiMsg &msg)
SendMidiMsgFromDelegate (Abbreviation: SMMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendSysexMsgFromDelegate (const ISysEx &msg)
SendSysexMsgFromDelegate (Abbreviation: SSMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendParameterValueFromDelegate (int paramIdx, double value, bool normalized)
SendParameterValueFromDelegate (Abbreviation: SPVFD) WARNING: should not be called on the realtime audio thread.
int GetEditorWidth () const
int GetEditorHeight () const
const IByteChunk & GetEditorData () const
Protected Attributes
WDL_String mParamDisplayStr
Timer * mTimer = nullptr
IPlugQueue< IParamChange > mParamChangeFromProcessor {PARAM_TRANSFER_SIZE}
IPlugQueue< IMidiMsg > mMidiMsgsFromEditor {MIDI_TRANSFER_SIZE}
IPlugQueue< IMidiMsg > mMidiMsgsFromProcessor {MIDI_TRANSFER_SIZE}
IPlugQueue< SysExData > mSysExDataFromEditor {SYSEX_TRANSFER_SIZE}
IPlugQueue< SysExData > mSysExDataFromProcessor {SYSEX_TRANSFER_SIZE}
SysExData mSysexBuf
Protected Attributes inherited from IPluginBase
int mCurrentPresetIdx = 0
bool mStateChunks = false
true if the plug-in does opaque state chunks.
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
WDL_String mBundleID
macOS/iOS bundle ID
WDL_String mVST3ProductCategory
Saving VST3 format presets requires this see SaveProgramAsVSTPreset.
WDL_String mVST3ProcessorUIDStr
Saving VST3 format presets requires this see SaveProgramAsVSTPreset.
WDL_String mVST3ControllerUIDStr
Saving VST3 format presets requires this see SaveProgramAsVSTPreset.
bool mHasUI = false
true if the plug-in has a user interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IPreset > mPresets
Protected Attributes inherited from IEditorDelegate
int mEditorWidth = 0
The width of the plug-in editor in pixels.
int mEditorHeight = 0
The height of the plug-in editor in pixels.
IByteChunk mEditorData
Any arbitrary data that the editor need to store (e.g.
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
The base class of an IPlug plug-in, which interacts with the different plug-in APIs.
No UI framework code here. This interface does not handle audio processing, see
Definition at line 38 of file IPlugAPIBase.h.
Member Function Documentation
virtual void IPlugAPIBase::BeginInformHostOfParamChange (int paramIdx) inline virtual
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented in IPlugAAX, IPlugVST3Controller, IPlugAU, IPlugVST3, IPlugAPP, and IPlugVST2.
Definition at line 113 of file IPlugAPIBase.h.
Referenced by BeginInformHostOfParamChangeFromUI().
void IPlugAPIBase::BeginInformHostOfParamChangeFromUI (int paramIdx) inline override virtual
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implements IEditorDelegate.
Definition at line 151 of file IPlugAPIBase.h.
References BeginInformHostOfParamChange().
bool IPlugAPIBase::CompareState (const uint8_t * pIncomingState, int startPos) const virtual
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
The default implementation will compare the serialized parameters.
Parameters
pIncomingState The incoming state data
startPos The position to start in the incoming data in bytes
Returns
true in order to indicate that the states are equal.
Definition at line 69 of file IPlugAPIBase.cpp.
References IEditorDelegate::GetParam(), IEditorDelegate::NParams(), and IParam::Value().
void IPlugAPIBase::DirtyParametersFromUI () override virtual
When modifying a range of parameters in the editor, it can be necessary to broadcast that fact, for instance in a distributed plug-in.
You can use it if you restore a preset using a custom preset mechanism.
Reimplemented from IEditorDelegate.
Reimplemented in IPlugVST3Controller, and IPlugVST3.
Definition at line 122 of file IPlugAPIBase.cpp.
References IEditorDelegate::GetParam(), and IEditorDelegate::NParams().
Referenced by IPlugVST3::DirtyParametersFromUI(), and IPlugVST3Controller::DirtyParametersFromUI().
virtual void IPlugAPIBase::EditorPropertiesChangedFromDelegate (int width, int height, const IByteChunk & data) inline virtual
Call this method from a delegate, for example if you wish to store graphics dimensions in your plug-in state in order to notify the API of a graphics resize or other layout change.
If calling from a UI interaction use EditorPropertiesChangedFromUI() When this is overridden in subclasses the subclass should call this in order to update the member variables
Reimplemented in IPlugAAX, IPlugVST3Controller, IPlugVST3, IPlugAPP, and IPlugVST2.
Definition at line 109 of file IPlugAPIBase.h.
References IEditorDelegate::mEditorData, IEditorDelegate::mEditorHeight, and IEditorDelegate::mEditorWidth.
Referenced by IPlugAPP::EditorPropertiesChangedFromDelegate(), IPlugVST2::EditorPropertiesChangedFromDelegate(), IPlugVST3::EditorPropertiesChangedFromDelegate(), IPlugVST3Controller::EditorPropertiesChangedFromDelegate(), IPlugAAX::EditorPropertiesChangedFromDelegate(), and EditorPropertiesChangedFromUI().
virtual void IPlugAPIBase::EndInformHostOfParamChange (int paramIdx) inline virtual
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented in IPlugAAX, IPlugVST3Controller, IPlugAU, IPlugVST3, IPlugAPP, and IPlugVST2.
Definition at line 117 of file IPlugAPIBase.h.
Referenced by EndInformHostOfParamChangeFromUI().
void IPlugAPIBase::EndInformHostOfParamChangeFromUI (int paramIdx) inline override virtual
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
Parameters
paramIdx The index of the parameter that is changing value
Implements IEditorDelegate.
Definition at line 152 of file IPlugAPIBase.h.
References EndInformHostOfParamChange().
virtual void* IPlugAPIBase::GetAAXViewInterface () inline virtual
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
Returns
pointer to the class that implements the IAAXViewInterface
Definition at line 90 of file IPlugAPIBase.h.
Referenced by IPlugAAX::EditorPropertiesChangedFromDelegate().
virtual bool IPlugAPIBase::GetMidiNoteText (int noteNumber, char * str) const inline virtual
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
Parameters
noteNumber MIDI note to get the textual description for
str char array to set the text for the note. Should be less thatn kVstMaxNameLen (64) characters
Returns
true if you specified a custom textual description for this note
Definition at line 85 of file IPlugAPIBase.h.
virtual void IPlugAPIBase::HostSpecificInit () inline virtual
This method is implemented in some API classes, in order to do specific initialisation for particular problematic hosts.
This is not the same as OnHostIdentified(), which you may implement in your plug-in class to do your own specific initialisation after a host has been identified
Reimplemented in IPlugVST2.
Definition at line 148 of file IPlugAPIBase.h.
Referenced by SetHost().
virtual void IPlugAPIBase::OnHostIdentified () inline virtual
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
The method may get called multiple times.
Definition at line 62 of file IPlugAPIBase.h.
Referenced by SetHost().
void IPlugAPIBase::OnHostRequestingImportantParameters (int count, WDL_TypedBuf< int > & results) virtual
Called by AUv3 plug-ins to get the "overview parameters".
Parameters
count How many overview parameters
results You should populate this typed buf with the indexes of the overview parameters if the host wants to show count number of controls
Definition at line 55 of file IPlugAPIBase.cpp.
References IEditorDelegate::NParams().
virtual bool IPlugAPIBase::OnHostRequestingSupportedViewConfiguration (int width, int height) inline virtual
Called by AUv3 plug-in hosts to query support for multiple UI sizes.
Parameters
width The width the host offers
height The height the host offers
Returns
return true if your plug-in supports these dimensions
Definition at line 73 of file IPlugAPIBase.h.
virtual void IPlugAPIBase::OnHostSelectedViewConfiguration (int width, int height) inline virtual
Called by some AUv3 plug-in hosts when a particular UI size is selected.
Parameters
width The selected width
height The selected height
Definition at line 78 of file IPlugAPIBase.h.
void IPlugAPIBase::PrintDebugInfo () const virtual
Helper method, used to print some info to the console in debug builds.
Can be overridden in other IPlugAPIBases, for specific functionality, such as printing UI details.
Definition at line 90 of file IPlugAPIBase.cpp.
References IPluginBase::GetBuildInfoStr().
void IPlugAPIBase::SendArbitraryMsgFromUI (int messageTag, int controlTag = kNoTag, int dataSize = 0, const void * pData = nullptr) override virtual
SendArbitraryMsgFromUI (Abbreviation: SAMFUI)
Parameters
messageTag A unique tag to identify the message
controlTag A unique tag to identify the control that sent the message, if desired
dataSize The size in bytes of the data payload pointed to by pData. Note: if this is nonzero, pData must be valid.
pData Ptr to the opaque data payload for the message
Reimplemented from IEditorDelegate.
Reimplemented in IPlugVST3Controller, and IPlugWeb.
Definition at line 199 of file IPlugAPIBase.cpp.
References IEditorDelegate::OnMessage(), and IEditorDelegate::SendArbitraryMsgFromUI().
void IPlugAPIBase::SendMidiMsgFromUI (const IMidiMsg & msg) override virtual
SendMidiMsgFromUI (Abbreviation: SMMFUI) This method should be used when sending a MIDI message from the UI.
For example clicking on a key in a virtual keyboard. Eventually the MIDI message can be handled in IPlugProcessor::ProcessMidiMsg(), from where it can be used to trigger sound and or forwarded to the API's MIDI output.
Parameters
msg The MIDI message to send.
Reimplemented from IEditorDelegate.
Reimplemented in IPlugVST3Controller, and IPlugWeb.
Definition at line 187 of file IPlugAPIBase.cpp.
References DeferMidiMsg(), and IEditorDelegate::SendMidiMsgFromUI().
void IPlugAPIBase::SendParameterValueFromAPI (int paramIdx, double value, bool normalized) virtual
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange() NOTE: It may be called on the high priority audio thread.
Its purpose is to place parameter changes in a queue to defer to main thread for the UI
Parameters
paramIdx The index of the parameter that changed
value The new value
normalized /true if value is normalised
Definition at line 131 of file IPlugAPIBase.cpp.
void IPlugAPIBase::SendParameterValueFromUI (int paramIdx, double normalizedValue) inline override virtual
SPVFUI Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
Parameters
paramIdx The index of the parameter that is changing value
normalizedValue The new normalised value of the parameter
Reimplemented from IEditorDelegate.
Reimplemented in IPlugWeb.
Definition at line 154 of file IPlugAPIBase.h.
References IEditorDelegate::SendParameterValueFromUI(), and SetParameterValue().
Referenced by IPlugWeb::SendParameterValueFromUI().
void IPlugAPIBase::SendSysexMsgFromUI (const ISysEx & msg) override virtual
SendMidiMsgFromUI (Abbreviation: SSMFUI) If a plug-in can send Sysex data as a result of actions in the user interface, this method can be used.
Unlike SendMidiMsgFromUI, Sysex messages will not be received in IPlugProcessor::ProcessSysex() Since it is extremely unlikely that you would want to use Sysex to communicate between editor and processor
Todo:
is this correct?
Parameters
msg The Sysex message to send.
Reimplemented from IEditorDelegate.
Reimplemented in IPlugVST3Controller, and IPlugWeb.
Definition at line 193 of file IPlugAPIBase.cpp.
References DeferSysexMsg(), and IEditorDelegate::SendSysexMsgFromUI().
void IPlugAPIBase::SetHost (const char * host, int version)
Called to set the name of the current host, if known (calls on to HostSpecificInit() and OnHostIdentified()).
Parameters
host The name of the plug-in host
version The version of the plug-in host where version in hex = 0xVVVVRRMM
Definition at line 99 of file IPlugAPIBase.cpp.
References HostSpecificInit(), LookUpHost(), IPluginBase::mHost, IPluginBase::mHostVersion, and OnHostIdentified().
void IPlugAPIBase::SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
It will update mParams[paramIdx], call InformHostOfParamChange and IPlugAPIBase::OnParamChange();
Parameters
paramIdx The index of the parameter that changed
normalizedValue The new (normalised) value
Definition at line 114 of file IPlugAPIBase.cpp.
References IEditorDelegate::GetParam(), and IPluginBase::OnParamChange().
Referenced by SendParameterValueFromUI().
The documentation for this class was generated from the following files:
IPlugAPIBase.h
IPlugAPIBase.cpp