iPlug 2: OSCReceiver Class Reference
OSCReceiver Class Reference
OSCReceiver interface, implement in order to receive OSC messages.
#include <IPlugOSC.h>
Public Member Functions
OSCReceiver (int port=8000, OSCLogFunc logFunc=nullptr, OSCMessageReceivedFunc receiveFunc=nullptr)
Construct a new OSCReceiver.
void SetReceivePort (int port)
Set the port number on which to listen for OSC messages.
void SetLogFunc (OSCLogFunc logFunc)
Set a log function after construction.
virtual void OnOSCMessage (OscMessageRead &msg)
Override to handle incoming OSC messages in a derived class.
Detailed Description
OSCReceiver interface, implement in order to receive OSC messages.
Definition at line 61 of file IPlugOSC.h.
Constructor & Destructor Documentation
OSCReceiver()
OSCReceiver::OSCReceiver (int port = 8000, OSCLogFunc logFunc = nullptr, OSCMessageReceivedFunc receiveFunc = nullptr)
Construct a new OSCReceiver.
Parameters
port The port number on which to listen for messages
logFunc std::function to log connection details
Definition at line 39 of file IPlugOSC.cpp.
References SetReceivePort().
Member Function Documentation
OnOSCMessage()
virtual void OSCReceiver::OnOSCMessage (OscMessageRead & msg) inline virtual
Override to handle incoming OSC messages in a derived class.
Reimplemented from OSCInterface.
Definition at line 78 of file IPlugOSC.h.
SetLogFunc()
void OSCReceiver::SetLogFunc (OSCLogFunc logFunc) inline
Set a log function after construction.
Parameters
logFunc std::function to log connection details
Definition at line 75 of file IPlugOSC.h.
SetReceivePort()
void OSCReceiver::SetReceivePort (int port)
Set the port number on which to listen for OSC messages.
Parameters
port The port number on which to listen for messages
Definition at line 46 of file IPlugOSC.cpp.
References OSCInterface::RemoveDevice().
Referenced by OSCReceiver().
The documentation for this class was generated from the following files:
IPlugOSC.h
IPlugOSC.cpp