iPlug 2: IBubbleControl Class Reference
IBubbleControl Class Reference
IGraphics::IControls::SpecialControls
A special control to draw contextual info as a slider etc is moved If used in the main IControl stack, you probably want it to be the very last control that is added, so that it gets drawn on top.
#include <IBubbleControl.h>
Public Types
enum EPopupState { kCollapsed = 0 , kExpanding , kExpanded , kCollapsing }
An enumerated list, that is used to determine the state of the menu, mainly for animations.
enum EArrowDir { kNorth , kEast , kSouth , kWest }
Public Member Functions
IBubbleControl (const IText &text=DEFAULT_TEXT.WithAlign(EAlign::Center), const IColor &fillColor=COLOR_WHITE, const IColor &strokeColor=COLOR_BLACK, float roundness=5.f)
Create a new IBubbleControl.
void Draw (IGraphics &g) override
Draw the control to the graphics context.
void ResetBounds ()
If controls get moved, you may need to call this to avoid the wrong regions getting dirtied.
void SetMaxBounds (const IRECT &bounds)
Set the bounds that the menu can potentially occupy, if not the full graphics context.
void SetFillColor (const IColor &color)
Set the background color for the bubble.
void SetStrokeColor (const IColor &color)
Set the stroke color for the bubble.
Public Member Functions inherited from IControl
IControl (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction actionFunc=nullptr)
Constructor.
IControl (const IRECT &bounds, const std::initializer_list< int > &params, IActionFunction actionFunc=nullptr)
Constructor (range of parameters)
IControl (const IRECT &bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
IControl (const IControl &)=delete
void operator= (const IControl &)=delete
virtual ~IControl ()
Destructor.
virtual void OnMouseDown (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse down event on this control.
virtual void OnMouseUp (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse up event on this control.
virtual void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
Implement this method to respond to a mouse drag event on this control.
virtual void OnMouseDblClick (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse double click event on this control.
virtual void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
Implement this method to respond to a mouse wheel event on this control.
virtual bool OnKeyDown (float x, float y, const IKeyPress &key)
Implement this method to respond to a key down event on this control.
virtual bool OnKeyUp (float x, float y, const IKeyPress &key)
Implement this method to respond to a key up event on this control.
virtual void OnMouseOver (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouseover event on this control.
virtual void OnMouseOut ()
Implement this method to respond to a mouseout event on this control.
virtual void OnTouchCancelled (float x, float y, const IMouseMod &mod)
Implement this method to respond to a touch cancel event on this control.
virtual void OnDrop (const char *str)
Implement to do something when something was drag 'n dropped onto this control.
virtual void OnRescale ()
Implement to do something when graphics is scaled globally (e.g.
virtual void OnResize ()
Called when IControl is constructed or resized using SetRect().
virtual void OnInit ()
Called just prior to when the control is attached, after its delegate and graphics member variable set.
virtual void OnAttached ()
Called after the control has been attached, and its delegate and graphics member variable set.
virtual void OnMsgFromDelegate (int msgTag, int dataSize, const void *pData)
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
virtual void OnMidi (const IMidiMsg &msg)
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
virtual bool OnGesture (const IGestureInfo &info)
virtual void CreateContextMenu (IPopupMenu &contextMenu)
Called by default when the user right clicks a control.
virtual void OnPopupMenuSelection (IPopupMenu *pSelectedMenu, int valIdx)
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControlPromptUserInput.
virtual void OnTextEntryCompletion (const char *str, int valIdx)
Implement this method to handle text input after IGraphics::CreateTextEntry/IControlPromptUserInput.
virtual void OnContextSelection (int itemSelected)
Implement this to respond to a menu selection from CreateContextMenu();.
virtual void Draw (IGraphics &g)=0
Draw the control to the graphics context.
virtual void DrawPTHighlight (IGraphics &g)
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
void PromptUserInput (int valIdx=0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
void PromptUserInput (const IRECT &bounds, int valIdx=0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter) specifying the bounds.
IControl * SetActionFunction (IActionFunction actionFunc)
Set an Action Function for this control.
IControl * SetAnimationEndActionFunction (IActionFunction actionFunc)
Set an Action Function to be called at the end of an animation.
void SetTooltip (const char *str)
Set a tooltip for the control.
const char * GetTooltip () const
int GetParamIdx (int valIdx=0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
virtual void SetParamIdx (int paramIdx, int valIdx=0)
Set the index of a parameter that the control is linked to If you are calling this "manually" to reuse a control for multiple parameters, you probably want to call IEditorDelegate::SendCurrentParamValuesFromDelegate() afterward, to update the control values.
int LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
int NVals () const
virtual int GetValIdxForPos (float x, float y) const
Check to see which of the control's values relates to this x and y coordinate.
const IParam * GetParam (int valIdx=0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
virtual void SetValueFromDelegate (double value, int valIdx=0)
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
virtual void SetValueFromUserInput (double value, int valIdx=0)
Set the control's value after user input.
virtual void SetValueToDefault (int valIdx=kNoValIdx)
Set one or all of the control's values to the default value of the associated parameter.
virtual void SetValue (double value, int valIdx=0)
Set one of the control's values.
double GetValue (int valIdx=0) const
Get the control's value.
void SetGroup (const char *groupName)
Assign the control to a control group.
const char * GetGroup () const
Get the group that the control belongs to, if any.
const IText & GetText () const
Get the Text object for the control.
virtual void SetText (const IText &txt)
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
void SetBlend (const IBlend &blend)
Set the Blend for this control.
IBlend GetBlend () const
Get the Blend for this control.
int GetTextEntryLength () const
Get the max number of characters that are allowed in text entry.
void SetTextEntryLength (int len)
Set the max number of characters that are allowed in text entry.
const IRECT & GetRECT () const
Get the rectangular draw area for this control, within the graphics context.
void SetRECT (const IRECT &bounds)
Set the rectangular draw area for this control, within the graphics context.
const IRECT & GetTargetRECT () const
Get the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetRECT (const IRECT &bounds)
Set the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetAndDrawRECTs (const IRECT &bounds)
Set BOTH the draw rect and the target area, within the graphics context for this control.
virtual void SetPosition (float x, float y)
Set the position of the control, preserving the width and height.
virtual void SetSize (float w, float h)
Set the size of the control, preserving the current position.
void SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
bool GetMouseDblAsSingleClick () const
Get double click as single click By default, mouse double click has its own handler.
virtual void Hide (bool hide)
Shows or hides the IControl.
bool IsHidden () const
virtual void SetDisabled (bool disable)
Sets disabled mode for the control, the default implementation modifies the mBlend member.
bool IsDisabled () const
void SetMouseOverWhenDisabled (bool allow)
Specify whether the control should respond to mouse overs when disabled.
void SetMouseEventsWhenDisabled (bool allow)
Specify whether the control should respond to other mouse events when disabled.
bool GetMouseOverWhenDisabled () const
bool GetMouseEventsWhenDisabled () const
bool GetIgnoreMouse () const
void SetIgnoreMouse (bool ignore)
Specify whether the control should respond to mouse events.
bool GetPromptShowsParamLabel () const
void SetPromptShowsParamLabel (bool enable)
Set if the control should show parameter labels/units e.g.
virtual bool IsHit (float x, float y) const
Hit test the control.
virtual void SetDirty (bool triggerAction=true, int valIdx=kNoValIdx)
Mark the control as dirty, i.e.
virtual void SetClean ()
void Animate ()
virtual bool IsDirty ()
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
void DisablePrompt (bool disable)
Disable/enable default prompt for user input.
virtual void OnGUIIdle ()
This is an idle timer tick call on the GUI thread, only active if USE_IDLE_CALLS is defined.
int GetTag () const
Get the control's tag.
void SetWantsMidi (bool enable=true)
Specify whether this control wants to know about MIDI messages sent to the UI.
bool GetWantsMidi () const
void SetWantsMultiTouch (bool enable=true)
Specify whether this control supports multiple touches.
bool GetWantsMultiTouch () const
IControl * AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
bool GetWantsGestures () const
EGestureType GetLastGesture () const
IGEditorDelegate * GetDelegate ()
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
void SetDelegate (IGEditorDelegate &dlg)
Used internally to set the mDelegate (and mGraphics) variables.
IContainerBase * GetParent () const
void SetParent (IContainerBase *pParent)
IGraphics * GetUI ()
const IGraphics * GetUI () const
bool GetMouseIsOver () const
This can be used in IControl::Draw() to check if the mouse is over the control, without implementing mouse over methods.
virtual void SnapToMouse (float x, float y, EDirection direction, const IRECT &bounds, int valIdx=-1, double minClip=0., double maxClip=1.)
Set control value based on x, y position within a rectangle.
virtual void OnEndAnimation ()
void StartAnimation (int duration)
void SetAnimation (IAnimationFunction func)
Set the animation function.
void SetAnimation (IAnimationFunction func, int duration)
Set the animation function and starts it.
IAnimationFunction GetAnimationFunction ()
Get the control's animation function, if it exists.
IActionFunction GetActionFunction ()
Get the control's action function, if it exists.
double GetAnimationProgress () const
Get the progress in a control's animation, in the range 0-1.
Milliseconds GetAnimationDuration () const
Get the duration of animations applied to the control.
template<class T >
T * As ()
Helper function to dynamic cast an IControl to a subclass.
Protected Member Functions
virtual void DrawContent (IGraphics &g, const IRECT &r)
virtual void DrawBubble (IGraphics &g, const IRECT &r)
void DrawDropShadow (IGraphics &g, const IRECT &r)
virtual void MeasureText (const char *str, IRECT &contentBounds)
void ShowBubble (IControl *pCaller, float x, float y, const char *str, EDirection dir, IRECT minimumContentBounds, ITouchID touchID=0)
bool GetActive () const
ITouchID GetTouchID () const
Protected Member Functions inherited from IControl
template<typename T , typename... Args>
void ForValIdx (int valIdx, T func, Args... args)
A helper template function to call a method for an individual value, or for all values.
void SetNVals (int nVals)
Protected Attributes
ITouchID mTouchId = 0
EDirection mDirection = EDirection::Horizontal
IRECT mMaxBounds
IRECT mBubbleBounds
IControl * mCaller = nullptr
EArrowDir mArrowDir = EArrowDir::kWest
WDL_String mStr
IBlend mBlend = { EBlend::Default, 0.f }
float mRoundness = 5.f
float mDropShadowSize = 10.f
float mCalloutSize = 10.f
float mOpacity = 0.95f
float mStrokeThickness = 2.f
float mHorizontalPadding = 5.f
IColor mFillColor = COLOR_WHITE
IColor mStrokeColor = COLOR_BLACK
EPopupState mState = kCollapsed
Protected Attributes inherited from IControl
IRECT mRECT
IRECT mTargetRECT
WDL_String mGroup
Controls can be grouped for hiding and showing panels.
IText mText
IBlend mBlend
int mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN
bool mDirty = true
bool mHide = false
bool mDisabled = false
bool mDisablePrompt = true
bool mDblAsSingleClick = false
bool mMouseOverWhenDisabled = false
bool mMouseEventsWhenDisabled = false
bool mIgnoreMouse = false
bool mWantsMidi = false
bool mWantsMultiTouch = false
bool mPromptShowsParamLabel = false
bool mMouseIsOver = false
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
WDL_String mTooltip
IColor mPTHighlightColor = COLOR_RED
bool mPTisHighlighted = false
Friends
class IGraphics
Detailed Description
A special control to draw contextual info as a slider etc is moved If used in the main IControl stack, you probably want it to be the very last control that is added, so that it gets drawn on top.
Definition at line 27 of file IBubbleControl.h.
Member Enumeration Documentation
EArrowDir
enum IBubbleControl::EArrowDir
Definition at line 39 of file IBubbleControl.h.
EPopupState
enum IBubbleControl::EPopupState
An enumerated list, that is used to determine the state of the menu, mainly for animations.
Definition at line 31 of file IBubbleControl.h.
Constructor & Destructor Documentation
IBubbleControl()
IBubbleControl::IBubbleControl (const IText & text = DEFAULT_TEXT.WithAlign(EAlign::Center), const IColor & fillColor = COLOR_WHITE, const IColor & strokeColor = COLOR_BLACK, float roundness = 5.f) inline
Create a new IBubbleControl.
Parameters
text The IText style to use for the readout
fillColor The background color of the bubble
strokeColor The stroke color of the bubble
Definition at line 51 of file IBubbleControl.h.
References IGraphics::ControlIsCaptured(), IControl::GetUI(), IControl::Hide(), IControl::SetActionFunction(), IControl::SetAnimation(), IControl::SetAnimationEndActionFunction(), and IControl::SetDirty().
~IBubbleControl()
virtual IBubbleControl::~IBubbleControl () inline virtual
Definition at line 119 of file IBubbleControl.h.
Member Function Documentation
Draw()
void IBubbleControl::Draw (IGraphics & g) inline override virtual
Draw the control to the graphics context.
Parameters
g The graphics context to which this control belongs.
Implements IControl.
Definition at line 123 of file IBubbleControl.h.
References IRECT::GetPadded().
DrawBubble()
virtual void IBubbleControl::DrawBubble (IGraphics & g, const IRECT & r) inline protected virtual
Definition at line 155 of file IBubbleControl.h.
DrawContent()
virtual void IBubbleControl::DrawContent (IGraphics & g, const IRECT & r) inline protected virtual
Definition at line 150 of file IBubbleControl.h.
DrawDropShadow()
void IBubbleControl::DrawDropShadow (IGraphics & g, const IRECT & r) inline protected
Definition at line 204 of file IBubbleControl.h.
GetActive()
bool IBubbleControl::GetActive () const inline protected
Definition at line 294 of file IBubbleControl.h.
GetTouchID()
ITouchID IBubbleControl::GetTouchID () const inline protected
Definition at line 299 of file IBubbleControl.h.
MeasureText()
virtual void IBubbleControl::MeasureText (const char * str, IRECT & contentBounds) inline protected virtual
Definition at line 209 of file IBubbleControl.h.
ResetBounds()
void IBubbleControl::ResetBounds () inline
If controls get moved, you may need to call this to avoid the wrong regions getting dirtied.
Definition at line 133 of file IBubbleControl.h.
References IControl::SetTargetAndDrawRECTs().
SetFillColor()
void IBubbleControl::SetFillColor (const IColor & color) inline
Set the background color for the bubble.
Definition at line 144 of file IBubbleControl.h.
SetMaxBounds()
void IBubbleControl::SetMaxBounds (const IRECT & bounds) inline
Set the bounds that the menu can potentially occupy, if not the full graphics context.
Definition at line 141 of file IBubbleControl.h.
SetStrokeColor()
void IBubbleControl::SetStrokeColor (const IColor & color) inline
Set the stroke color for the bubble.
Definition at line 147 of file IBubbleControl.h.
ShowBubble()
void IBubbleControl::ShowBubble (IControl * pCaller, float x, float y, const char * str, EDirection dir, IRECT minimumContentBounds, ITouchID touchID = 0) inline protected
Definition at line 214 of file IBubbleControl.h.
Friends And Related Function Documentation
IGraphics
friend class IGraphics friend
Definition at line 305 of file IBubbleControl.h.
Member Data Documentation
mArrowDir
EArrowDir IBubbleControl::mArrowDir = EArrowDir::kWest protected
Definition at line 312 of file IBubbleControl.h.
mBlend
IBlend IBubbleControl::mBlend = { EBlend::Default, 0.f } protected
Definition at line 314 of file IBubbleControl.h.
mBubbleBounds
IRECT IBubbleControl::mBubbleBounds protected
Definition at line 310 of file IBubbleControl.h.
mCaller
IControl* IBubbleControl::mCaller = nullptr protected
Definition at line 311 of file IBubbleControl.h.
mCalloutSize
float IBubbleControl::mCalloutSize = 10.f protected
Definition at line 317 of file IBubbleControl.h.
mDirection
EDirection IBubbleControl::mDirection = EDirection::Horizontal protected
Definition at line 308 of file IBubbleControl.h.
mDropShadowSize
float IBubbleControl::mDropShadowSize = 10.f protected
Definition at line 316 of file IBubbleControl.h.
mFillColor
IColor IBubbleControl::mFillColor = COLOR_WHITE protected
Definition at line 321 of file IBubbleControl.h.
mHorizontalPadding
float IBubbleControl::mHorizontalPadding = 5.f protected
Definition at line 320 of file IBubbleControl.h.
mMaxBounds
IRECT IBubbleControl::mMaxBounds protected
Definition at line 309 of file IBubbleControl.h.
mOpacity
float IBubbleControl::mOpacity = 0.95f protected
Definition at line 318 of file IBubbleControl.h.
mRoundness
float IBubbleControl::mRoundness = 5.f protected
Definition at line 315 of file IBubbleControl.h.
mState
EPopupState IBubbleControl::mState = kCollapsed protected
Definition at line 323 of file IBubbleControl.h.
mStr
WDL_String IBubbleControl::mStr protected
Definition at line 313 of file IBubbleControl.h.
mStrokeColor
IColor IBubbleControl::mStrokeColor = COLOR_BLACK protected
Definition at line 322 of file IBubbleControl.h.
mStrokeThickness
float IBubbleControl::mStrokeThickness = 2.f protected
Definition at line 319 of file IBubbleControl.h.
mTouchId
ITouchID IBubbleControl::mTouchId = 0 protected
Definition at line 307 of file IBubbleControl.h.
The documentation for this class was generated from the following file:
IBubbleControl.h