iPlug 2: OSCSender Class Reference
OSCSender Class Reference
#include <IPlugOSC.h>
Public Member Functions
OSCSender (const char *destIP="127.0.0.1", int port=8000, OSCLogFunc logFunc=nullptr)
Construct a new OSCSender object.
void SetDestination (const char *ip, int port)
Set the Destination object.
void SendOSCMessage (OscMessageWrite &msg)
Public Member Functions inherited from OSCInterface
OSCInterface (OSCLogFunc logFunc=nullptr)
Construct a new OSCInterface object.
OSCInterface (const OSCInterface &)=delete
OSCInterface & operator= (const OSCInterface &)=delete
OSCDevice * CreateReceiver (WDL_String &log, int port=8000)
Create a Receiver object.
OSCDevice * CreateSender (WDL_String &log, const char *ip="127.0.0.1", int port=8000)
Create a Sender object.
virtual void OnOSCMessage (OscMessageRead &msg)
void SetLogFunc (OSCLogFunc logFunc)
Set the Log Func object.
Additional Inherited Members
Protected Attributes inherited from OSCInterface
OSCLogFunc mLogFunc
WDL_HeapBuf mIncomingEvents
WDL_Mutex mIncomingEvents_mutex
Static Protected Attributes inherited from OSCInterface
static std::unique_ptr< Timer > mTimer
static int sInstances = 0
Detailed Description
Todo:
Definition at line 154 of file IPlugOSC.h.
Constructor & Destructor Documentation
OSCSender()
OSCSender::OSCSender (const char * destIP = "127.0.0.1", int port = 8000, OSCLogFunc logFunc = nullptr)
Construct a new OSCSender object.
Parameters
destIP
port
logFunc
Definition at line 415 of file IPlugOSC.cpp.
References SetDestination().
Member Function Documentation
SendOSCMessage()
void OSCSender::SendOSCMessage (OscMessageWrite & msg)
Parameters
msg
Definition at line 442 of file IPlugOSC.cpp.
References OSCDevice::SendOSC().
SetDestination()
void OSCSender::SetDestination (const char * ip, int port)
Set the Destination object.
Parameters
ip
port
Definition at line 422 of file IPlugOSC.cpp.
References OSCInterface::CreateSender().
Referenced by OSCSender().
The documentation for this class was generated from the following files:
IPlugOSC.h
IPlugOSC.cpp