iPlug 2: OSCDevice Class Reference
OSCDevice Class Reference
#include <IPlugOSC.h>
Public Member Functions
OSCDevice (const char *dest, int maxpacket, int sendsleep, struct sockaddr_in *listen_addr)
Construct a new OSCDevice object.
void RunInput ()
void RunOutput ()
void AddInstance (void(*callback)(void *d1, int dev_idx, int msglen, void *msg), void *d1, int dev_idx)
void OnMessage (char type, const unsigned char *msg, int len)
void SendOSC (const char *src, int len)
Public Attributes
double mLastOpenTime = 0
bool mHasInput = false
bool mHasOutput = false
SOCKET mSendSocket
int mMaxMacketSize
int mSendSleep
WDL_String mDestination
struct sockaddr_in mSendAddress mReceiveAddress
WDL_Queue mSendQueue
WDL_Queue mReceiveQueue
Detailed Description
Todo:
Definition at line 42 of file IPlugOSC.h.
Constructor & Destructor Documentation
OSCDevice()
OSCDevice::OSCDevice (const char * dest, int maxpacket, int sendsleep, struct sockaddr_in * listen_addr)
Construct a new OSCDevice object.
Parameters
dest
maxpacket
sendsleep
listen_addr
Definition at line 15 of file IPlugOSC.cpp.
~OSCDevice()
OSCDevice::~OSCDevice () virtual
Definition at line 68 of file IPlugOSC.cpp.
Member Function Documentation
AddInstance()
void OSCDevice::AddInstance (void(*)(void *d1, int dev_idx, int msglen, void *msg) callback, void * d1, int dev_idx)
Todo:
Definition at line 172 of file IPlugOSC.cpp.
Referenced by OSCInterface::CreateReceiver(), and OSCInterface::CreateSender().
OnMessage()
void OSCDevice::OnMessage (char type, const unsigned char * msg, int len)
Todo:
Parameters
type
msg
len
Definition at line 178 of file IPlugOSC.cpp.
Referenced by RunInput().
RunInput()
void OSCDevice::RunInput ()
Todo:
Definition at line 78 of file IPlugOSC.cpp.
References OnMessage().
RunOutput()
void OSCDevice::RunOutput ()
Todo:
Definition at line 99 of file IPlugOSC.cpp.
SendOSC()
void OSCDevice::SendOSC (const char * src, int len)
Todo:
Parameters
src
len
Definition at line 186 of file IPlugOSC.cpp.
Referenced by OSCSender::SendOSCMessage().
Member Data Documentation
mDestination
WDL_String OSCDevice::mDestination
Definition at line 90 of file IPlugOSC.h.
mHasInput
bool OSCDevice::mHasInput = false
Definition at line 85 of file IPlugOSC.h.
mHasOutput
bool OSCDevice::mHasOutput = false
Definition at line 86 of file IPlugOSC.h.
mLastOpenTime
double OSCDevice::mLastOpenTime = 0
Definition at line 84 of file IPlugOSC.h.
mMaxMacketSize
int OSCDevice::mMaxMacketSize
Definition at line 89 of file IPlugOSC.h.
mReceiveAddress
struct sockaddr_in mSendAddress OSCDevice::mReceiveAddress
Definition at line 92 of file IPlugOSC.h.
mReceiveQueue
WDL_Queue OSCDevice::mReceiveQueue
Definition at line 93 of file IPlugOSC.h.
mSendQueue
WDL_Queue OSCDevice::mSendQueue
Definition at line 93 of file IPlugOSC.h.
mSendSleep
int OSCDevice::mSendSleep
Definition at line 89 of file IPlugOSC.h.
mSendSocket
SOCKET OSCDevice::mSendSocket
Definition at line 88 of file IPlugOSC.h.
The documentation for this class was generated from the following files:
IPlugOSC.h
IPlugOSC.cpp