iPlug 2: IParam Class Reference
IParam Class Reference
IPlug's parameter class.
#include <IPlugParameter.h>
Classes
struct Shape
Base struct for parameter shaping.
struct ShapeExp
Exponential parameter shaping.
struct ShapeLinear
Linear parameter shaping.
struct ShapePowCurve
PowCurve parameter shaping.
Public Types
enum EParamType {
kTypeNone , kTypeBool , kTypeInt , kTypeEnum ,
kTypeDouble
}
Defines types or parameter.
enum EParamUnit {
kUnitPercentage , kUnitSeconds , kUnitMilliseconds , kUnitSamples ,
kUnitDB , kUnitLinearGain , kUnitPan , kUnitPhase ,
kUnitDegrees , kUnitMeters , kUnitRate , kUnitRatio ,
kUnitFrequency , kUnitOctaves , kUnitCents , kUnitAbsCents ,
kUnitSemitones , kUnitMIDINote , kUnitMIDICtrlNum , kUnitBPM ,
kUnitBeats , kUnitCustom
}
Used by AudioUnit plugins to determine the appearance of parameters, based on the kind of data they represent.
enum EDisplayType {
kDisplayLinear , kDisplayLog , kDisplayExp , kDisplaySquared ,
kDisplaySquareRoot , kDisplayCubed , kDisplayCubeRoot
}
Used by AudioUnit plugins to determine the mapping of parameters.
enum EFlags {
kFlagsNone = 0 , kFlagCannotAutomate = 0x1 , kFlagStepped = 0x2 , kFlagNegateDisplay = 0x4 ,
kFlagSignDisplay = 0x8 , kFlagMeta = 0x10
}
Flags to determine characteristics of the parameter.
using DisplayFunc = std::function< void(double, WDL_String &)>
DisplayFunc allows custom parameter display functions, defined by a lambda matching this signature.
Public Member Functions
IParam (const IParam &)=delete
IParam & operator= (const IParam &)=delete
void InitBool (const char *name, bool defaultValue, const char *label="", int flags=0, const char *group="", const char *offText="off", const char *onText="on")
Initialize the parameter as boolean.
void InitEnum (const char *name, int defaultValue, int nEnums, const char *label="", int flags=0, const char *group="", const char *listItems=0,...)
Initialize the parameter as an enumerated list.
void InitEnum (const char *name, int defaultValue, const std::initializer_list< const char * > &listItems, int flags=0, const char *group="")
Initialize the parameter as enum.
void InitInt (const char *name, int defaultValue, int minVal, int maxVal, const char *label="", int flags=0, const char *group="")
Initialize the parameter as integer.
void InitDouble (const char *name, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", const Shape &shape=ShapeLinear(), EParamUnit unit=kUnitCustom, DisplayFunc displayFunc=nullptr)
Initialize the parameter as double.
void InitSeconds (const char *name, double defaultVal=1., double minVal=0., double maxVal=10., double step=0.1, int flags=0, const char *group="")
Initialize the parameter as seconds.
void InitMilliseconds (const char *name, double defaultVal=1., double minVal=0., double maxVal=100., int flags=0, const char *group="")
Initialize the parameter as milliseconds.
void InitFrequency (const char *name, double defaultVal=1000., double minVal=0.1, double maxVal=10000., double step=0.1, int flags=0, const char *group="")
Initialize the parameter as frequency.
void InitPitch (const char *name, int defaultVal=60, int minVal=0, int maxVal=128, int flags=0, const char *group="", bool middleCisC4=false)
Initialize the parameter as pitch.
void InitGain (const char *name, double defaultVal=0., double minVal=-70., double maxVal=24., double step=0.5, int flags=0, const char *group="")
Initialize the parameter as gain (units in decibels)
void InitPercentage (const char *name, double defaultVal=0., double minVal=0., double maxVal=100., int flags=0, const char *group="")
Initialize the parameter as percentage.
void InitAngleDegrees (const char *name, double defaultVal=0., double minVal=0., double maxVal=360., int flags=0, const char *group="")
Initialize the parameter as angle in degrees.
void Init (const IParam &p, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Initialize the parameter based on another parameter, replacing a CString in the name.
double StringToValue (const char *str) const
Convert a textual representation of the parameter value to a double (real value)
double Constrain (double value) const
Constrains the input value between mMin and mMax and apply stepping if relevant.
double ConstrainNormalized (double normalizedValue) const
Constrains a normalised input value similarly to Constrain()
double ToNormalized (double nonNormalizedValue) const
Convert a real value to normalized value for this parameter.
double FromNormalized (double normalizedValue) const
Convert a normalized value to real value for this parameter.
void Set (double value)
Sets the parameter value.
void SetNormalized (double normalizedValue)
Sets the parameter value from a normalized range (usually coming from the linked IControl)
void SetString (const char *str)
Set the parameter value using a textual representation.
void SetToDefault ()
Replaces the parameter's current value with the default one
void SetDefault (double value)
Set the parameter's default value, and set the parameter to that default.
void SetDisplayText (double value, const char *str)
Set some text to display for a particular value, e.g.
void SetDisplayPrecision (int precision)
Set the parameters display precision.
void SetLabel (const char *label)
Set the parameters label after creation.
void SetDisplayFunc (DisplayFunc func)
Set the function to translate display values.
double Value () const
Gets a readable value of the parameter.
bool Bool () const
Returns the parameter's value as a boolean.
int Int () const
Returns the parameter's value as an integer.
double DBToAmp () const
Gain based on parameter's current value in dB.
double GetNormalized () const
Returns the parameter's normalized value.
void GetDisplay (WDL_String &display, bool withDisplayText=true) const
Get the current textual display for the current parameter value.
void GetDisplay (double value, bool normalized, WDL_String &display, bool withDisplayText=true) const
Get the current textual display for a specified parameter value.
void GetDisplayWithLabel (WDL_String &display, bool withDisplayText=true) const
Fills the WDL_String the value of the parameter along with the label, e.g.
const char * GetName () const
Returns the parameter's name.
const char * GetLabel () const
Returns the parameter's label.
const char * GetGroup () const
Returns the parameter's group.
const char * GetCustomUnit () const
Get parameter's label (unit suffix)
int NDisplayTexts () const
Get the number of display texts for the parameter.
const char * GetDisplayText (double value) const
Get the display text for a particular value.
const char * GetDisplayTextAtIdx (int idx, double *pValue=nullptr) const
Get the display text at a particular index.
bool MapDisplayText (const char *str, double *pValue) const
Get the value of a particular display text.
EParamType Type () const
Get the parameter's type.
EParamUnit Unit () const
Get the parameter's unit.
EDisplayType DisplayType () const
Get the parameter's display type.
double GetDefault (bool normalized=false) const
Returns the parameter's default value.
double GetMin () const
Returns the parameter's minimum value.
double GetMax () const
Returns the parameter's maximum value.
void GetBounds (double &lo, double &hi) const
Get the minimum and maximum real value of the parameter's range in one method call.
double GetRange () const
Returns the parameter's range.
double GetStep () const
Returns the parameter's step size.
int GetDisplayPrecision () const
Returns the parameter's precision.
int GetFlags () const
Returns the parameter's flags.
bool GetCanAutomate () const
bool GetStepped () const
bool GetNegateDisplay () const
bool GetSignDisplay () const
bool GetMeta () const
void GetJSON (WDL_String &json, int idx) const
Get a JSON description of the parameter.
void PrintDetails () const
Helper to print the parameter details to debug console in debug builds.
Detailed Description
IPlug's parameter class.
Definition at line 30 of file IPlugParameter.h.
Member Typedef Documentation
DisplayFunc
using IParam::DisplayFunc = std::function<void(double, WDL_String&)>
DisplayFunc allows custom parameter display functions, defined by a lambda matching this signature.
Definition at line 61 of file IPlugParameter.h.
Member Enumeration Documentation
EDisplayType
enum IParam::EDisplayType
Used by AudioUnit plugins to determine the mapping of parameters.
Definition at line 41 of file IPlugParameter.h.
EFlags
enum IParam::EFlags
Flags to determine characteristics of the parameter.
Enumerator
kFlagsNone
No flags.
kFlagCannotAutomate
Indicates that the parameter is not automatable.
kFlagStepped
Indicates that the parameter is stepped
kFlagNegateDisplay
Indicates that the parameter should be displayed as a negative value.
kFlagSignDisplay
Indicates that the parameter should be displayed as a signed value.
kFlagMeta
Indicates that the parameter may influence the state of other parameters.
Definition at line 44 of file IPlugParameter.h.
EParamType
enum IParam::EParamType
Defines types or parameter.
Definition at line 35 of file IPlugParameter.h.
EParamUnit
enum IParam::EParamUnit
Used by AudioUnit plugins to determine the appearance of parameters, based on the kind of data they represent.
Definition at line 38 of file IPlugParameter.h.
Constructor & Destructor Documentation
IParam()
IParam::IParam ()
Definition at line 84 of file IPlugParameter.cpp.
Member Function Documentation
Bool()
bool IParam::Bool () const inline
Returns the parameter's value as a boolean.
Returns
true if value >= 0.5, else otherwise
Definition at line 341 of file IPlugParameter.h.
Referenced by IPluginBase::DumpMakePresetFromNamedParamsSrc(), and IPluginBase::DumpMakePresetSrc().
Constrain()
double IParam::Constrain (double value) const inline
Constrains the input value between mMin and mMax and apply stepping if relevant.
Parameters
value The input value to constrain
Returns
double The resulting constrained value
Definition at line 270 of file IPlugParameter.h.
References Clip(), and kFlagStepped.
Referenced by FromNormalized(), Set(), StringToValue(), and ToNormalized().
ConstrainNormalized()
double IParam::ConstrainNormalized (double normalizedValue) const inline
Constrains a normalised input value similarly to Constrain()
Parameters
value The normalised input value to constrain
Returns
double The resulting constrained value
Definition at line 278 of file IPlugParameter.h.
References ToNormalized().
Referenced by IKnobControlBase::OnMouseDrag(), and ISliderControlBase::OnMouseDrag().
DBToAmp()
double IParam::DBToAmp () const inline
Gain based on parameter's current value in dB.
Returns
double Gain calculated as an approximation of \(10^{\frac{x}{20}} \)
See also
IAMP_DB
Definition at line 351 of file IPlugParameter.h.
DisplayType()
EDisplayType IParam::DisplayType () const inline
Get the parameter's display type.
Note
This is only used for AU plugins to determine the mapping of parameters
Returns
EDisplayType
Definition at line 433 of file IPlugParameter.h.
FromNormalized()
double IParam::FromNormalized (double normalizedValue) const inline
Convert a normalized value to real value for this parameter.
Parameters
normalizedValue The normalized input value in the range 0. to 1.
Returns
The corresponding real value, for this parameter
Definition at line 294 of file IPlugParameter.h.
References Constrain().
Referenced by GetDisplay(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), SetNormalized(), IVNumberBoxControl::SetValueFromDelegate(), and IVNumberBoxControl::SetValueFromUserInput().
GetBounds()
void IParam::GetBounds (double & lo, double & hi) const
Get the minimum and maximum real value of the parameter's range in one method call.
Parameters
lo The minimum value will be put here
hi The maximum value will be put here
Definition at line 380 of file IPlugParameter.cpp.
GetCanAutomate()
bool IParam::GetCanAutomate () const inline
Returns
true If the parameter should be automateable
Definition at line 470 of file IPlugParameter.h.
References kFlagCannotAutomate.
GetCustomUnit()
const char * IParam::GetCustomUnit () const inline
Get parameter's label (unit suffix)
Returns
CString Parameter's label (unit suffix) or nullptr if it is not set
Definition at line 397 of file IPlugParameter.h.
GetDefault()
double IParam::GetDefault (bool normalized = false) const inline
Returns the parameter's default value.
Parameters
normalized Should the returned value be the default as a normalized or real value
Returns
double The parameter's default value
Definition at line 438 of file IPlugParameter.h.
References GetDefault(), and ToNormalized().
Referenced by GetDefault(), GetJSON(), IVNumberBoxControl::OnInit(), and IControl::SetValueToDefault().
GetDisplay() [1/2]
void IParam::GetDisplay (double value, bool normalized, WDL_String & display, bool withDisplayText = true) const
Get the current textual display for a specified parameter value.
Parameters
value The value to get the display for
normalized Is value normalized or real
display WDL_String to fill with the results
withDisplayText Should the output include display texts
Definition at line 262 of file IPlugParameter.cpp.
References FromNormalized(), GetDisplayText(), kFlagNegateDisplay, and kFlagSignDisplay.
GetDisplay() [2/2]
void IParam::GetDisplay (WDL_String & display, bool withDisplayText = true) const inline
Get the current textual display for the current parameter value.
Parameters
display WDL_String to fill with the results
withDisplayText Should the output include display texts
Definition at line 360 of file IPlugParameter.h.
References GetDisplay().
Referenced by ICaptionControl::Draw(), GetDisplay(), GetDisplayWithLabel(), IGraphics::PromptUserInput(), and IVSwitchControl::SetDirty().
GetDisplayPrecision()
int IParam::GetDisplayPrecision () const inline
Returns the parameter's precision.
Returns
int The number of decimal places that should be used to display the parameter's real value
Definition at line 463 of file IPlugParameter.h.
GetDisplayText()
const char * IParam::GetDisplayText (double value) const
Get the display text for a particular value.
Parameters
value The value to get the display text for
Returns
CString The display text
Definition at line 327 of file IPlugParameter.cpp.
Referenced by GetDisplay(), GetLabel(), and IGraphics::PromptUserInput().
GetDisplayTextAtIdx()
const char * IParam::GetDisplayTextAtIdx (int idx, double * pValue = nullptr) const
Get the display text at a particular index.
Parameters
idx The index of the display text
pValue The value linked to the display text will be put here
Returns
CString The display text
Definition at line 337 of file IPlugParameter.cpp.
Referenced by Init().
GetDisplayWithLabel()
void IParam::GetDisplayWithLabel (WDL_String & display, bool withDisplayText = true) const inline
Fills the WDL_String the value of the parameter along with the label, e.g.
units
Parameters
display WDL_String to fill with the results
withDisplayText Should the output include display texts
Definition at line 372 of file IPlugParameter.h.
References GetDisplay(), and GetLabel().
Referenced by IVSwitchControl::OnInit(), IVKnobControl::OnInit(), IVSliderControl::OnInit(), IVKnobControl::SetDirty(), IVSliderControl::SetDirty(), ShowBubbleHorizontalActionFunc(), and ShowBubbleVerticalActionFunc().
GetFlags()
int IParam::GetFlags () const inline
Returns the parameter's flags.
Returns
int The parameter's flags as an integer
Definition at line 467 of file IPlugParameter.h.
GetGroup()
const char * IParam::GetGroup () const
Returns the parameter's group.
Returns
CString with the parameter's group
Definition at line 317 of file IPlugParameter.cpp.
Referenced by IPluginBase::CopyParamValues(), IPluginBase::ForParamInGroup(), and IVTrackControlBase::SetParamsByGroup().
GetJSON()
void IParam::GetJSON (WDL_String & json, int idx) const
Get a JSON description of the parameter.
Parameters
json WDL_String to fill with the JSON
idx Index of the parameter, to place in the JSON
Definition at line 386 of file IPlugParameter.cpp.
References GetDefault(), GetMax(), GetMin(), GetName(), and Type().
GetLabel()
const char * IParam::GetLabel () const
Returns the parameter's label.
Returns
CString with the parameter's label
Definition at line 312 of file IPlugParameter.cpp.
References GetDisplayText().
Referenced by ICaptionControl::Draw(), GetDisplayWithLabel(), and IGraphics::PromptUserInput().
GetMax()
double IParam::GetMax () const inline
Returns the parameter's maximum value.
Returns
The maximum real value of the parameter's range
Definition at line 446 of file IPlugParameter.h.
Referenced by GetJSON(), IParam::ShapeExp::Init(), IParam::ShapePowCurve::NormalizedToValue(), IVNumberBoxControl::OnInit(), and IParam::ShapePowCurve::ValueToNormalized().
GetMeta()
bool IParam::GetMeta () const inline
Returns
true If the parameter is flagged as a "meta" parameter, e.g. one that could modify other parameters
Definition at line 482 of file IPlugParameter.h.
References kFlagMeta.
GetMin()
double IParam::GetMin () const inline
Returns the parameter's minimum value.
Returns
The minimum real value of the parameter's range
Definition at line 442 of file IPlugParameter.h.
Referenced by GetJSON(), IParam::ShapeExp::Init(), IParam::ShapePowCurve::NormalizedToValue(), IVNumberBoxControl::OnInit(), and IParam::ShapePowCurve::ValueToNormalized().
GetName()
const char * IParam::GetName () const
Returns the parameter's name.
Returns
CString with the parameter's name
Definition at line 307 of file IPlugParameter.cpp.
Referenced by GetJSON(), IVSwitchControl::OnInit(), IVTabSwitchControl::OnInit(), IVKnobControl::OnInit(), IVSliderControl::OnInit(), PrintDetails(), IGraphics::PromptUserInput(), IPluginBase::SerializeParams(), and IPluginBase::UnserializeParams().
GetNegateDisplay()
bool IParam::GetNegateDisplay () const inline
Returns
true If the parameter should be displayed as a negative value
Definition at line 476 of file IPlugParameter.h.
References kFlagNegateDisplay.
GetNormalized()
double IParam::GetNormalized () const inline
Returns the parameter's normalized value.
Returns
double The resulting normalized value
Definition at line 355 of file IPlugParameter.h.
References ToNormalized().
GetRange()
double IParam::GetRange () const inline
Returns the parameter's range.
Returns
double The difference between the parameter's maximum and minimum bounds
Definition at line 455 of file IPlugParameter.h.
Referenced by ISwitchControlBase::OnInit(), and IVTrackControlBase::SetParams().
GetSignDisplay()
bool IParam::GetSignDisplay () const inline
Returns
true If the parameter should be displayed as a signed value
Definition at line 479 of file IPlugParameter.h.
References kFlagSignDisplay.
GetStep()
double IParam::GetStep () const inline
Returns the parameter's step size.
Returns
The parameter's step size
Definition at line 459 of file IPlugParameter.h.
Referenced by IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), and IVTrackControlBase::SetParams().
GetStepped()
bool IParam::GetStepped () const inline
Returns
true If the parameter should be discrete (stepped)
Definition at line 473 of file IPlugParameter.h.
References kFlagStepped.
Referenced by IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), and IVTrackControlBase::SetParams().
Init()
void IParam::Init (const IParam & p, const char * searchStr = "", const char * replaceStr = "", const char * newGroup = "")
Initialize the parameter based on another parameter, replacing a CString in the name.
Parameters
p The existing parameter
searchStr Search string for modifying the parameter name
replaceStr Replace string for modifying the parameter name
newGroup Group for the new parameter
Definition at line 214 of file IPlugParameter.cpp.
References GetDisplayTextAtIdx(), InitDouble(), NDisplayTexts(), SetDisplayText(), and Type().
InitAngleDegrees()
void IParam::InitAngleDegrees (const char * name, double defaultVal = 0., double minVal = 0., double maxVal = 360., int flags = 0, const char * group = "")
Initialize the parameter as angle in degrees.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 209 of file IPlugParameter.cpp.
References InitDouble().
InitBool()
void IParam::InitBool (const char * name, bool defaultValue, const char * label = "", int flags = 0, const char * group = "", const char * offText = "off", const char * onText = "on")
Initialize the parameter as boolean.
Parameters
name The parameter's name
defaultValue The default value of the parameter
label The parameter's unit suffix. Has no effect for this type of parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
offText The display text when the parameter value == 0.
onText The display text when the parameter value == 1.
Definition at line 92 of file IPlugParameter.cpp.
References InitEnum(), kFlagStepped, and SetDisplayText().
InitDouble()
void IParam::InitDouble (const char * name, double defaultVal, double minVal, double maxVal, double step, const char * label = "", int flags = 0, const char * group = "", const Shape & shape = ShapeLinear(), EParamUnit unit = kUnitCustom, DisplayFunc displayFunc = nullptr)
Initialize the parameter as double.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
step The step size of the parameter
label The parameter's unit suffix (eg. dB, %)
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
shape A Parameter::Shape struct that determines the skewing of the parameters values across its range
unit Used by AudioUnit plugins to determine the appearance of parameters, based on the kind of data they represent
displayFunc Custom display function, conforming to DisplayFunc
Definition at line 140 of file IPlugParameter.cpp.
References IParam::Shape::Clone(), and Set().
Referenced by Init(), InitAngleDegrees(), InitFrequency(), InitGain(), InitInt(), InitMilliseconds(), InitPercentage(), and InitSeconds().
InitEnum() [1/2]
void IParam::InitEnum (const char * name, int defaultValue, const std::initializer_list< const char * > & listItems, int flags = 0, const char * group = "")
Initialize the parameter as enum.
Parameters
name The parameter's name
defaultValue The default value of the parameter
listItems An initializer list of CStrings for the list items
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 120 of file IPlugParameter.cpp.
References InitInt(), kFlagStepped, and SetDisplayText().
InitEnum() [2/2]
void IParam::InitEnum (const char * name, int defaultValue, int nEnums, const char * label = "", int flags = 0, const char * group = "", const char * listItems = 0, ...)
Initialize the parameter as an enumerated list.
Parameters
name The parameter's name
defaultValue The default value of the parameter
nEnums The number of elements in the enumerated list
label The parameter's unit suffix. Has no effect for this type of parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
listItems VARARG list of enum items, the length of which must match nEnums
Definition at line 102 of file IPlugParameter.cpp.
References InitInt(), kFlagStepped, and SetDisplayText().
Referenced by InitBool(), and InitPitch().
InitFrequency()
void IParam::InitFrequency (const char * name, double defaultVal = 1000., double minVal = 0.1, double maxVal = 10000., double step = 0.1, int flags = 0, const char * group = "")
Initialize the parameter as frequency.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
step The step size of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 173 of file IPlugParameter.cpp.
References InitDouble().
InitGain()
void IParam::InitGain (const char * name, double defaultVal = 0., double minVal = -70., double maxVal = 24., double step = 0.5, int flags = 0, const char * group = "")
Initialize the parameter as gain (units in decibels)
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
step The step size of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 199 of file IPlugParameter.cpp.
References InitDouble().
InitInt()
void IParam::InitInt (const char * name, int defaultValue, int minVal, int maxVal, const char * label = "", int flags = 0, const char * group = "")
Initialize the parameter as integer.
Parameters
name The parameter's name
defaultValue The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
label The parameter's unit suffix (eg. dB, %)
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 133 of file IPlugParameter.cpp.
References InitDouble(), and kFlagStepped.
Referenced by InitEnum().
InitMilliseconds()
void IParam::InitMilliseconds (const char * name, double defaultVal = 1., double minVal = 0., double maxVal = 100., int flags = 0, const char * group = "")
Initialize the parameter as milliseconds.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
step The step size of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 183 of file IPlugParameter.cpp.
References InitDouble().
InitPercentage()
void IParam::InitPercentage (const char * name, double defaultVal = 0., double minVal = 0., double maxVal = 100., int flags = 0, const char * group = "")
Initialize the parameter as percentage.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 204 of file IPlugParameter.cpp.
References InitDouble().
InitPitch()
void IParam::InitPitch (const char * name, int defaultVal = 60, int minVal = 0, int maxVal = 128, int flags = 0, const char * group = "", bool middleCisC4 = false)
Initialize the parameter as pitch.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 188 of file IPlugParameter.cpp.
References InitEnum(), MidiNoteName(), and SetDisplayText().
InitSeconds()
void IParam::InitSeconds (const char * name, double defaultVal = 1., double minVal = 0., double maxVal = 10., double step = 0.1, int flags = 0, const char * group = "")
Initialize the parameter as seconds.
Parameters
name The parameter's name
defaultVal The default value of the parameter
minVal The minimum value of the parameter
maxVal The maximum value of the parameter
step The step size of the parameter
flags The parameter's flags
See also
IParam::EFlags
Parameters
group The parameter's group
Definition at line 178 of file IPlugParameter.cpp.
References InitDouble().
Int()
int IParam::Int () const inline
Returns the parameter's value as an integer.
Returns
Current value of the parameter as an integer
Definition at line 345 of file IPlugParameter.h.
Referenced by IPluginBase::DumpMakePresetFromNamedParamsSrc(), and IPluginBase::DumpMakePresetSrc().
MapDisplayText()
bool IParam::MapDisplayText (const char * str, double * pValue) const
Get the value of a particular display text.
Parameters
str The display text to look up
pValue The value linked to the display text will be put here
Returns
true if str matched a display text
Definition at line 344 of file IPlugParameter.cpp.
Referenced by StringToValue().
NDisplayTexts()
int IParam::NDisplayTexts () const
Get the number of display texts for the parameter.
Returns
The number of display texts for the parameter
Definition at line 322 of file IPlugParameter.cpp.
Referenced by Init(), IGraphics::PromptUserInput(), and StringToValue().
PrintDetails()
void IParam::PrintDetails () const
Helper to print the parameter details to debug console in debug builds.
Definition at line 417 of file IPlugParameter.cpp.
References GetName(), and Value().
Referenced by IPluginBase::PrintParamValues().
Set()
void IParam::Set (double value) inline
Sets the parameter value.
Parameters
value Value to be set. Will be stepped and clamped between mMin and mMax
Definition at line 301 of file IPlugParameter.h.
References Constrain().
Referenced by InitDouble(), SetNormalized(), and IPluginBase::UnserializeParams().
SetDefault()
void IParam::SetDefault (double value) inline
Set the parameter's default value, and set the parameter to that default.
Parameters
value The new default value
Definition at line 316 of file IPlugParameter.h.
References SetToDefault().
SetDisplayFunc()
void IParam::SetDisplayFunc (DisplayFunc func) inline
Set the function to translate display values.
Parameters
func A function conforming to DisplayFunc
Definition at line 333 of file IPlugParameter.h.
SetDisplayPrecision()
void IParam::SetDisplayPrecision (int precision)
Set the parameters display precision.
Parameters
precision The display precision in digits
Definition at line 257 of file IPlugParameter.cpp.
SetDisplayText()
void IParam::SetDisplayText (double value, const char * str)
Set some text to display for a particular value, e.g.
-70dB could display "-inf"
Parameters
value The value for which to display the text
str CString text to display at value
Definition at line 248 of file IPlugParameter.cpp.
Referenced by Init(), InitBool(), InitEnum(), and InitPitch().
SetLabel()
void IParam::SetLabel (const char * label) inline
Set the parameters label after creation.
WARNING: if this is called after the host has queried plugin parameters, the host may display the label as it was previously
Parameters
label CString for the label
Definition at line 329 of file IPlugParameter.h.
SetNormalized()
void IParam::SetNormalized (double normalizedValue) inline
Sets the parameter value from a normalized range (usually coming from the linked IControl)
Parameters
normalizedValue The expected normalized value between 0. and 1.
Definition at line 305 of file IPlugParameter.h.
References FromNormalized(), and Set().
Referenced by IPluginBase::RandomiseParamValues(), and IEditorDelegate::SendParameterValueFromUI().
SetString()
void IParam::SetString (const char * str) inline
Set the parameter value using a textual representation.
Parameters
str The textual representations as a CString
Definition at line 309 of file IPlugParameter.h.
References StringToValue().
SetToDefault()
void IParam::SetToDefault () inline
Replaces the parameter's current value with the default one
Definition at line 312 of file IPlugParameter.h.
Referenced by IPluginBase::DefaultParamValues(), and SetDefault().
StringToValue()
double IParam::StringToValue (const char * str) const
Convert a textual representation of the parameter value to a double (real value)
Parameters
str CString textual representation of the parameter value
Returns
double The real value
Definition at line 358 of file IPlugParameter.cpp.
References Constrain(), kFlagNegateDisplay, MapDisplayText(), NDisplayTexts(), and Type().
Referenced by IGraphics::SetControlValueAfterTextEdit(), and SetString().
ToNormalized()
double IParam::ToNormalized (double nonNormalizedValue) const inline
Convert a real value to normalized value for this parameter.
Parameters
nonNormalizedValue The real input value
Returns
The corresponding normalized value, for this parameter
Definition at line 286 of file IPlugParameter.h.
References Clip(), and Constrain().
Referenced by ConstrainNormalized(), GetDefault(), GetNormalized(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), IGEditorDelegate::SendParameterValueFromDelegate(), and IGraphics::SetControlValueAfterTextEdit().
Type()
EParamType IParam::Type () const inline
Get the parameter's type.
Returns
EParamType Type of the parameter, kTypeNone if not initialized
See also
EParamType
Definition at line 423 of file IPlugParameter.h.
Referenced by IPluginBase::DumpMakePresetFromNamedParamsSrc(), IPluginBase::DumpMakePresetSrc(), GetJSON(), Init(), ITextEntryControl::OnKeyDown(), ICaptionControl::OnResize(), IGraphics::PromptUserInput(), and StringToValue().
Unit()
EParamUnit IParam::Unit () const inline
Get the parameter's unit.
Note
This is only used for AU plugins to determine the appearance of parameters, based on the kind of data they represent
Returns
EParamUnit
Definition at line 428 of file IPlugParameter.h.
Value()
double IParam::Value () const inline
Gets a readable value of the parameter.
Returns
double Current value of the parameter
Definition at line 337 of file IPlugParameter.h.
Referenced by IPluginBase::CloneParamRange(), IPluginBase::DumpMakePresetFromNamedParamsSrc(), IPluginBase::DumpMakePresetSrc(), PrintDetails(), IPluginBase::SerializeParams(), and IPluginBase::UnserializeParams().
The documentation for this class was generated from the following files:
IPlugParameter.h
IPlugParameter.cpp