iPlug2: IGraphicsLice Class Reference
IGraphicsLice Class Reference
IGraphics::DrawClasses
IGraphics draw class using Cockos' LICE.
#include <IGraphicsLice.h>
Public Member Functions
const char * GetDrawingAPIStr () override
IGraphicsLice (IGEditorDelegate &dlg, int w, int h, int fps, float scale)
void DrawResize () override
void DrawSVG (ISVG &svg, const IRECT &dest, const IBlend *pBlend) override
Draw an SVG image to the graphics context.
void DrawRotatedSVG (ISVG &svg, float destCtrX, float destCtrY, float width, float height, double angle, const IBlend *pBlend) override
Draw an SVG image to the graphics context with rotation.
void DrawBitmap (IBitmap &bitmap, const IRECT &dest, int srcX, int srcY, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context.
void DrawRotatedBitmap (IBitmap &bitmap, float destCtrX, float destCtrY, double angle, int yOffsetZeroDeg, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context with rotation.
void DrawRotatedMask (IBitmap &base, IBitmap &mask, IBitmap &top, float x, float y, double angle, const IBlend *pBlend) override
Draw a rotated, masked bitmap to the graphics context.
void DrawFittedBitmap (IBitmap &bitmap, const IRECT &bounds, const IBlend *pBlend) override
Draw a bitmap (raster) image to the graphics context, scaling the image to fit the bounds.
void DrawPoint (const IColor &color, float x, float y, const IBlend *pBlend) override
Fill a rectangle corresponding to a pixel on a 1:1 screen with a color.
void DrawLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend, float thickness) override
Draw a line to the graphics context.
void DrawDottedLine (const IColor &color, float x1, float y1, float x2, float y2, const IBlend *pBlend, float thickness, float dashLen) override
Draw a dotted line to the graphics context.
void DrawTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend, float thickness) override
Draw a triangle to the graphics context.
void DrawRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend, float thickness) override
Draw a rectangle to the graphics context.
void DrawRoundRect (const IColor &color, const IRECT &bounds, float cr, const IBlend *pBlend, float thickness) override
Draw a rounded rectangle to the graphics context.
void DrawConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend, float thickness) override
Draw a convex polygon to the graphics to the graphics context.
void DrawArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend, float thickness) override
Draw an arc to the graphics context.
void DrawCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend, float thickness) override
Draw a circle to the graphics context.
void DrawDottedRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend, float thickness, float dashLen) override
Draw a dotted rectangle to the graphics context.
void FillTriangle (const IColor &color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend *pBlend) override
Fill a triangle in the graphics context with a color.
void FillRect (const IColor &color, const IRECT &bounds, const IBlend *pBlend) override
Fill a rectangular region of the graphics context with a color.
void FillRoundRect (const IColor &color, const IRECT &bounds, float cr, const IBlend *pBlend) override
Fill a rounded rectangle in the graphics context with a color.
void FillConvexPolygon (const IColor &color, float *x, float *y, int npoints, const IBlend *pBlend) override
Fill a convex polygon in the graphics context with a color.
void FillArc (const IColor &color, float cx, float cy, float r, float aMin, float aMax, const IBlend *pBlend) override
Fill an arc segment in the graphics context with a color.
void FillCircle (const IColor &color, float cx, float cy, float r, const IBlend *pBlend) override
Fill a circle in the graphics context with a color.
IColor GetPoint (int x, int y) override
Get the color of a point in the graphics context.
void * GetDrawContext () override
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
LICE_SysBitmap * GetDrawBitmap () const
void DrawRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend, float thickness) override
Draw a rounded rectangle to the graphics context with individual corner roundness.
void DrawEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend, float thickness) override
Draw an ellipse within a rectangular region of the graphics context.
void DrawEllipse (const IColor &color, float x, float y, float r1, float r2, float angle, const IBlend *pBlend, float thickness) override
Draw an ellipse around a central point given two radii and an angle of orientation.
void FillRoundRect (const IColor &color, const IRECT &bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend *pBlend) override
Fill a rounded rectangle in the graphics context with a color.
void FillEllipse (const IColor &color, const IRECT &bounds, const IBlend *pBlend) override
Fill an ellipse within a rectangular region of the graphics context.
void FillEllipse (const IColor &color, float x, float y, float r1, float r2, float angle, const IBlend *pBlend) override
Fill an ellipse in the graphics context.
bool BitmapExtSupported (const char *ext) override
Checks a file extension and reports whether this drawing API supports loading that extension.
Public Member Functions inherited from IGraphics
virtual void BeginFrame ()
Called at the beginning of drawing.
virtual void OnViewInitialized (void *pContext)
Called after platform view initialization, so that drawing classes can e.g.
virtual void OnViewDestroyed ()
Called after a platform view is destroyed, so that drawing classes can e.g.
bool DrawText (const IText &text, const char *str, const IRECT &bounds, const IBlend *pBlend=0)
Draw some text to the graphics context in a specific rectangle.
bool DrawText (const IText &text, const char *str, float x, float y, const IBlend *pBlend=0)
Draw some text to the graphics context at a point.
virtual bool MeasureText (const IText &text, const char *str, IRECT &bounds)
Measure the rectangular region that some text will occupy.
virtual IBitmap ScaleBitmap (const IBitmap &srcbitmap, const char *cacheName, int targetScale)
virtual void RetainBitmap (const IBitmap &bitmap, const char *cacheName)
virtual void ReleaseBitmap (const IBitmap &bitmap)
IBitmap GetScaledBitmap (IBitmap &src)
void DrawBitmap (IBitmap &bitmap, const IRECT &bounds, int frame=1, const IBlend *pBlend=0)
Draws a bitmap into the graphics context.
void DrawBitmapedText (IBitmap &bitmap, IRECT &bounds, IText &text, IBlend *pBlend, const char *str, bool vCenter=true, bool multiline=false, int charWidth=6, int charHeight=12, int charOffset=0)
Draws mono spaced bitmap text.
void DrawVerticalLine (const IColor &color, const IRECT &bounds, float x, const IBlend *pBlend=0, float thickness=1.f)
Draw a vertical line, within a rectangular region of the graphics context.
void DrawHorizontalLine (const IColor &color, const IRECT &bounds, float y, const IBlend *pBlend=0, float thickness=1.f)
Draw a horizontal line, within a rectangular region of the graphics context.
void DrawVerticalLine (const IColor &color, float xi, float yLo, float yHi, const IBlend *pBlend=0, float thickness=1.f)
void DrawHorizontalLine (const IColor &color, float yi, float xLo, float xHi, const IBlend *pBlend=0, float thickness=1.f)
void DrawRadialLine (const IColor &color, float cx, float cy, float angle, float rMin, float rMax, const IBlend *pBlend=0, float thickness=1.f)
Draw a radial line to the graphics context, useful for pointers on dials.
virtual void DrawGrid (const IColor &color, const IRECT &bounds, float gridSizeH, float gridSizeV, const IBlend *pBlend=0, float thickness=1.f)
Draw a grid to the graphics context.
virtual void DrawData (const IColor &color, const IRECT &bounds, float *normYPoints, int nPoints, float *normXPoints=nullptr, const IBlend *pBlend=0, float thickness=1.f)
void StartLayer (const IRECT &r)
void ResumeLayer (ILayerPtr &layer)
ILayerPtr EndLayer ()
bool CheckLayer (const ILayerPtr &layer)
void DrawLayer (const ILayerPtr &layer, const IBlend *pBlend=nullptr)
void DrawRotatedLayer (const ILayerPtr &layer, double angle)
void ApplyLayerDropShadow (ILayerPtr &layer, const IShadow &shadow)
Applies a dropshadow directly onto a layer.
virtual bool HasPathSupport () const
virtual void PathClear ()
virtual void PathClose ()
void PathLine (float x1, float y1, float x2, float y2)
void PathRadialLine (float cx, float cy, float angle, float rMin, float rMax)
virtual void PathTriangle (float x1, float y1, float x2, float y2, float x3, float y3)
virtual void PathRect (const IRECT &bounds)
virtual void PathRoundRect (const IRECT &bounds, float ctl, float ctr, float cbl, float cbr)
virtual void PathRoundRect (const IRECT &bounds, float cr=5.f)
virtual void PathArc (float cx, float cy, float r, float aMin, float aMax)
virtual void PathCircle (float cx, float cy, float r)
virtual void PathEllipse (float x, float y, float r1, float r2, float angle=0.0)
virtual void PathEllipse (const IRECT &bounds)
virtual void PathConvexPolygon (float *x, float *y, int nPoints)
virtual void PathMoveTo (float x, float y)
virtual void PathLineTo (float x, float y)
virtual void PathCurveTo (float x1, float y1, float x2, float y2, float x3, float y3)
virtual void PathStroke (const IPattern &pattern, float thickness, const IStrokeOptions &options=IStrokeOptions(), const IBlend *pBlend=0)
virtual void PathFill (const IPattern &pattern, const IFillOptions &options=IFillOptions(), const IBlend *pBlend=0)
virtual void PathTransformSave ()
virtual void PathTransformRestore ()
virtual void PathTransformReset (bool clearStates=false)
virtual void PathTransformTranslate (float x, float y)
virtual void PathTransformScale (float scaleX, float scaleY)
virtual void PathTransformScale (float scale)
virtual void PathTransformRotate (float angle)
virtual void PathTransformSkew (float xAngle, float yAngle)
virtual void PathTransformMatrix (const IMatrix &matrix)
virtual void PathClipRegion (const IRECT r=IRECT())
virtual void HideMouseCursor (bool hide=true, bool lock=true)=0
Call to hide the mouse cursor.
virtual void MoveMouseCursor (float x, float y)=0
Force move the mouse cursor to a specific position in the graphics context.
virtual ECursor SetMouseCursor (ECursor cursorType=ECursor::ARROW)
Sets the mouse cursor to one of ECursor (implementations should return the result of the base implementation)
virtual void ForceEndUserEdit ()=0
Call to force end text entry (will cancel any half input text.
virtual void * OpenWindow (void *pParentWnd)=0
Open a new platform view for this graphics context.
virtual void CloseWindow ()=0
Close the platform view for this graphics context.
virtual void * GetWindow ()=0
Get a pointer to the platform view e.g.
virtual bool WindowIsOpen ()
virtual bool GetTextFromClipboard (WDL_String &str)=0
Get text from the clipboard.
virtual void UpdateTooltips ()=0
Call this if you modify control tool tips at runtime.
virtual int ShowMessageBox (const char *str, const char *caption, EMessageBoxType type)=0
Pop up a modal platform message box dialog.
void CreateTextEntry (IControl &control, const IText &text, const IRECT &bounds, const char *str="")
Create a text entry box.
virtual void PromptForFile (WDL_String &fileName, WDL_String &path, EFileAction action=kFileOpen, const char *extensions=0)=0
Create a platform file prompt dialog to choose a file/directory path for opening/saving a file/directory.
virtual void PromptForDirectory (WDL_String &dir)=0
Create a platform file prompt dialog to choose a directory path for opening/saving a directory.
virtual bool PromptForColor (IColor &color, const char *str="")=0
Create a platform color chooser dialog.
virtual void CreateWebView (const IRECT &bounds, const char *url)
virtual bool OpenURL (const char *url, const char *msgWindowTitle=0, const char *confirmMsg=0, const char *errMsgOnFailure=0)=0
Open a URL in the platforms default browser.
virtual const char * GetPlatformAPIStr ()
virtual bool RevealPathInExplorerOrFinder (WDL_String &path, bool select=false)
virtual void SetWinModuleHandle (void *pHinstance)
Used on Windows to set the HINSTANCE module handle, which allows graphics APIs to load resources from the binary.
virtual void * GetWinModuleHandle ()
virtual void SetPlatformContext (void *pContext)
Set the platform draw context Used in order to set the platform level draw context - CGContextRef context on macOS and the GDI HDC draw context handle on Windows.
void * GetPlatformContext ()
Get the platform level draw context - an HDC or CGContextRef.
virtual void ClientToScreen (float &x, float &y)
Convert an x, y position in the view to screen coordinates.
virtual EResourceLocation OSFindResource (const char *fileNameOrResID, const char *type, WDL_String &result)=0
Find the absolute path of a resource based on it's file name (e.g.
virtual const void * LoadWinResource (const char *resID, const char *type, int &sizeInBytes)
Load a resource from the binary (windows only).
virtual const char * GetBundleID ()
Get the bundle ID on macOS and iOS, returns emtpy string on other OSs.
IGraphics (IGEditorDelegate &dlg, int w, int h, int fps=0, float scale=1.)
void SetScreenScale (int scale)
Called by the platform IGraphics class XXXXX /todo and when moving to a new screen with different DPI.
bool IsDirty (IRECTList &rects)
Called repeatedly at frame rate by the platform class to check what the graphics context says is dirty.
void Draw (IRECTList &rects)
Called by the platform class when an area needs to be redrawn.
void UpdatePeers (IControl *pCaller)
This method is called after interacting with a control, so that any other controls linked to the same parameter index, will also be set dirty, and have their values updated.
void PromptUserInput (IControl &control, const IRECT &bounds)
Prompt for user input either using a text entry or pop up menu.
void SetControlValueFromStringAfterPrompt (IControl &control, const char *str)
Called by the platform class after returning from a prompt (typically a text entry) in order to update a control with a new value.
IPopupMenu * CreatePopupMenu (IPopupMenu &menu, const IRECT &bounds, IControl *pCaller=nullptr)
Shows a pop up/contextual menu in relation to a rectangular region of the graphics context.
IPopupMenu * CreatePopupMenu (IPopupMenu &menu, float x, float y, IControl *pCaller=nullptr)
Shows a pop up/contextual menu at point in the graphics context.
void SetScaleConstraints (float lo, float hi)
void SetSizeConstraints (int widthLo, int widthHi, int heightLo, int heightHi)
void Resize (int w, int h, float scale)
void SetStrictDrawing (bool strict)
Enables strict drawing mode.
void SetLayoutOnResize (bool layoutOnResize)
int Width () const
Gets the width of the graphics context.
int Height () const
Gets the height of the graphics context.
int WindowWidth () const
Gets the width of the graphics context including scaling (not display scaling!)
int WindowHeight () const
Gets the height of the graphics context including scaling (not display scaling!)
int FPS () const
Gets the drawing frame rate.
float GetDrawScale () const
Gets the graphics context scaling factor.
int GetScreenScale () const
Gets the display scaling factor.
IGEditorDelegate * GetDelegate ()
Gets a pointer to the delegate class that handles communication to and from this graphics context.
void AttachBackground (const char *fileName)
Attach an IBitmapControl as the lowest IControl in the control stack to be the background for the graphics context.
void AttachPanelBackground (const IColor &color)
Attach an IPanelControl as the lowest IControl in the control stack to fill the background with a solid color.
void AttachCornerResizer (EUIResizerMode sizeMode=EUIResizerMode::kUIResizerScale, bool layoutOnResize=false)
Attach the default control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachCornerResizer (ICornerResizerControl *pControl, EUIResizerMode sizeMode=EUIResizerMode::kUIResizerScale, bool layoutOnResize=false)
Attach your own control to scale or increase the UI size by dragging the plug-in bottom right-hand corner.
void AttachPopupMenuControl (const IText &text=DEFAULT_TEXT, const IRECT &bounds=IRECT())
Attach a control for pop-up menus, to override platform style menus.
void SetKeyHandlerFunc (std::function< bool(const IKeyPress &key)> keyHandlerFunc)
void ShowFPSDisplay (bool enable)
Shows a control to display the frame rate of drawing.
bool ShowingFPSDisplay ()
void AttachTextEntryControl ()
Attach a control for text entry, to override platform text entry.
int AttachControl (IControl *pControl, int controlTag=kNoTag, const char *group="")
Attach an IControl to the graphics context and add it to the top of the control stack.
IControl * GetControl (int idx)
IControl * GetControlWithTag (int controlTag)
IControl * GetCapturedControl ()
Get a pointer to the IControl that is currently captured i.e.
IControl * GetBackgroundControl ()
int NControls () const
void RemoveControls (int fromIdx)
Remove controls from the control list above a particular index, (frees memory).
void RemoveAllControls ()
Removes all regular IControls from the control list, as well as special controls (frees memory).
void HideControl (int paramIdx, bool hide)
void GrayOutControl (int paramIdx, bool gray)
void ClampControl (int paramIdx, double lo, double hi, bool normalized)
void ForControlWithParam (int paramIdx, std::function< void(IControl &control)> func)
void ForControlInGroup (const char *group, std::function< void(IControl &control)> func)
void SetAllControlsDirty ()
void SetAllControlsClean ()
void OnMouseDown (float x, float y, const IMouseMod &mod)
void OnMouseUp (float x, float y, const IMouseMod &mod)
void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
bool OnMouseDblClick (float x, float y, const IMouseMod &mod)
void OnMouseWheel (float x, float y, const IMouseMod &mod, float delta)
bool OnKeyDown (float x, float y, const IKeyPress &key)
bool OnMouseOver (float x, float y, const IMouseMod &mod)
void OnMouseOut ()
void OnSetCursor ()
void OnDrop (const char *str, float x, float y)
void OnGUIIdle ()
void OnResizeGesture (float x, float y)
void HandleMouseOver (bool canHandle)
void ReleaseMouseCapture ()
Used to tell the graphics context to stop tracking mouse interaction with a control.
void EnableTooltips (bool enable)
void AssignParamNameToolTips ()
Call this method in order to create tool tips for every IControl that show the associated parameter's name.
void ShowControlBounds (bool enable)
void ShowAreaDrawn (bool enable)
bool ShowAreaDrawnEnabled () const
bool ShowControlBoundsEnabled () const
void EnableLiveEdit (bool enable)
Live edit mode allows you to relocate controls at runtime in debug builds and save the locations to a predefined file (e.g.
bool LiveEditEnabled () const
IRECT GetBounds () const
Returns an IRECT that represents the entire UI bounds This is useful for programatically arranging UI elements by slicing up the IRECT using the various IRECT methods.
bool CanHandleMouseOver () const
int GetMouseOver () const
void GetMouseDownPoint (float &x, float &y) const
Get the x, y position in the graphics context of the last mouse down message.
IPopupMenu & GetPromptMenu ()
bool TooltipsEnabled () const
void SetTabletInput (bool tablet)
Set by the platform class if the mouse input is coming from a tablet/stylus.
EUIResizerMode GetResizerMode () const
IPopupMenuControl * GetPopupMenuControl ()
ITextEntryControl * GetTextEntryControl ()
void StyleAllVectorControls (bool drawFrame, bool drawShadow, bool emboss, float roundness, float frameThickness, float shadowOffset, const IVColorSpec &spec=DEFAULT_SPEC)
int GetParamIdxForPTAutomation (float x, float y)
[AAX only] This can be called by the ProTools API class (e.g.
int GetLastClickedParamForPTAutomation ()
[AAX only]
void SetPTParameterHighlight (int paramIdx, bool isHighlighted, int color)
[AAX only]
void PopupHostContextMenuForParam (int controlIdx, int paramIdx, float x, float y)
[VST3 primarily]
virtual IBitmap LoadBitmap (const char *fileNameOrResID, int nStates=1, bool framesAreHorizontal=false, int targetScale=0)
Load a bitmap image from disk or from windows resource.
virtual ISVG LoadSVG (const char *fileNameOrResID, const char *units="px", float dpi=72.f)
Load an SVG from disk or from windows resource.
virtual bool LoadFont (const char *fileNameOrResID)
Protected Member Functions
APIBitmap * LoadAPIBitmap (const char *fileNameOrResID, int scale, EResourceLocation location, const char *ext) override
APIBitmap * ScaleAPIBitmap (const APIBitmap *pBitmap, int scale) override
APIBitmap * CreateAPIBitmap (int width, int height) override
int AlphaChannel () const override
bool FlippedBitmap () const override
void GetLayerBitmapData (const ILayerPtr &layer, RawBitmapData &data) override
void ApplyShadowMask (ILayerPtr &layer, RawBitmapData &mask, const IShadow &shadow) override
bool DoDrawMeasureText (const IText &text, const char *str, IRECT &bounds, const IBlend *pBlend, bool measure) override
void EndFrame () override
Called by some drawing API classes to finally blit the draw bitmap onto the screen or perform other cleanup after drawing.
float GetBackingPixelScale () const override
Protected Member Functions inherited from IGraphics
virtual void CreatePlatformTextEntry (IControl &control, const IText &text, const IRECT &bounds, const char *str="")=0
virtual IPopupMenu * CreatePlatformPopupMenu (IPopupMenu &menu, const IRECT &bounds, IControl *pCaller=nullptr)=0
void PushLayer (ILayer *layer, bool clearTransforms)
ILayer * PopLayer (bool clearTransforms)
void SearchNextScale (int &sourceScale, int targetScale)
Utility used by SearchImageResource/SearchBitmapInCache.
EResourceLocation SearchImageResource (const char *fileName, const char *type, WDL_String &result, int targetScale, int &sourceScale)
Search for a bitmap image resource matching the target scale.
APIBitmap * SearchBitmapInCache (const char *fileName, int targetScale, int &sourceScale)
Search the static storage cache for a bitmap image resource matching the target scale.
void ForStandardControlsFunc (std::function< void(IControl &control)> func)
template<typename T , typename... Args>
void ForMatchingControls (T method, int paramIdx, Args...args)
Additional Inherited Members
Protected Types inherited from IGraphics
typedef WDL_TypedBuf< unsigned
char > RawBitmapData
Protected Attributes inherited from IGraphics
IGEditorDelegate * mDelegate = nullptr
void * mPlatformContext = nullptr
bool mCursorHidden = false
bool mCursorLock = false
bool mTabletInput = false
float mCursorX = -1.f
float mCursorY = -1.f
std::stack< ILayer * > mLayers
Detailed Description
IGraphics draw class using Cockos' LICE.
Definition at line 76 of file IGraphicsLice.h.
Member Function Documentation
void IGraphicsLice::DrawArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend, float thickness) override virtual
Draw an arc to the graphics context.
Parameters
color The color to draw the shape with
cx The X coordinate in the graphics context of the centre of the circle on which the arc lies
cy The Y coordinate in the graphics context of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
aMin the start angle of the arc at in degrees clockwise where 0 is up
aMax the end angle of the arc at in degrees clockwise where 0 is up
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 297 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
void IGraphicsLice::DrawBitmap (IBitmap & bitmap, const IRECT & bounds, int srcX, int srcY, const IBlend * pBlend) override virtual
Draw a bitmap (raster) image to the graphics context.
Parameters
bitmap The bitmap image to draw to the graphics context
bounds The rectangular region to draw the image in
srcX The X coordinate in the source image to draw from
Todo:
Parameters
srcY The Y coordinate in the source image to draw from
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 146 of file IGraphicsLice.cpp.
References IBitmap::GetAPIBitmap(), and IGraphics::GetScreenScale().
void IGraphicsLice::DrawCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend, float thickness) override virtual
Draw a circle to the graphics context.
Parameters
color The color to draw the shape with
cx The X coordinate in the graphics context of the centre of the circle
cy The Y coordinate in the graphics context of the centre of the circle
r The radius of the circle
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 306 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
void IGraphicsLice::DrawConvexPolygon (const IColor & color, float * x, float * y, int nPoints, const IBlend * pBlend, float thickness) override virtual
Draw a convex polygon to the graphics to the graphics context.
Parameters
color The color to draw the shape with
x Pointer to the first element in an array of X coordinates for the vertices of the polygon
y Pointer to the first element in an array of Y coordinates for the vertices of the polygon
nPoints The number of points in the coordinate arrays
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 281 of file IGraphicsLice.cpp.
References DrawLine().
void IGraphicsLice::DrawDottedLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend, float thickness, float dashLen) override virtual
Draw a dotted line to the graphics context.
Parameters
color The color to draw the shape with
x1 The X coordinate in the graphics context of the start of the line
y1 The Y coordinate in the graphics context of the start of the line
x2 The X coordinate in the graphics context of the end of the line
y2 The Y coordinate in the graphics context of the end of the line
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 232 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
Referenced by DrawDottedRect().
void IGraphicsLice::DrawDottedRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend, float thickness, float dashLen) override virtual
Draw a dotted rectangle to the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 315 of file IGraphicsLice.cpp.
References DrawDottedLine().
void IGraphicsLice::DrawEllipse (const IColor & color, const IRECT & bounds, const IBlend * pBlend, float thickness) inline override virtual
Draw an ellipse within a rectangular region of the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 118 of file IGraphicsLice.h.
void IGraphicsLice::DrawEllipse (const IColor & color, float x, float y, float r1, float r2, float angle, const IBlend * pBlend, float thickness) inline override virtual
Draw an ellipse around a central point given two radii and an angle of orientation.
Parameters
color The color to draw the shape with
x The X coordinate in the graphics context of the centre of the ellipse
y The Y coordinate in the graphics context of the centre of the ellipse
r1 The radius of the ellipse along the line found by rotating the x-axis by the angle
r2 The radius of the ellipse along the line found by rotating the y-axis by the angle
angle The angle rotates the radii r1 and r2 clockwise in degrees to adjust the orientation
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 119 of file IGraphicsLice.h.
void IGraphicsLice::DrawFittedBitmap (IBitmap & bitmap, const IRECT & bounds, const IBlend * pBlend) override virtual
Draw a bitmap (raster) image to the graphics context, scaling the image to fit the bounds.
Parameters
bitmap The bitmap image to draw to the graphics context
bounds The rectangular region to draw the image in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 206 of file IGraphicsLice.cpp.
References IBitmap::GetAPIBitmap().
void IGraphicsLice::DrawLine (const IColor & color, float x1, float y1, float x2, float y2, const IBlend * pBlend, float thickness) override virtual
Draw a line to the graphics context.
Parameters
color The color to draw the line with
x1 The X coordinate in the graphics context of the start of the line
y1 The Y coordinate in the graphics context of the start of the line
x2 The X coordinate in the graphics context of the end of the line
y2 The Y coordinate in the graphics context of the end of the line
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 222 of file IGraphicsLice.cpp.
Referenced by DrawConvexPolygon(), DrawRect(), and DrawTriangle().
void IGraphicsLice::DrawPoint (const IColor & color, float x, float y, const IBlend * pBlend) override virtual
Fill a rectangle corresponding to a pixel on a 1:1 screen with a color.
Parameters
color The color to fill the point with
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 215 of file IGraphicsLice.cpp.
void IGraphicsLice::DrawRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend, float thickness) override virtual
Draw a rectangle to the graphics context.
Parameters
bounds The rectangular area in which to draw the shape
color The color to draw the shape to draw the shape with
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 256 of file IGraphicsLice.cpp.
References DrawLine().
void IGraphicsLice::DrawRotatedBitmap (IBitmap & bitmap, float destCentreX, float destCentreY, double angle, int yOffsetZeroDeg, const IBlend * pBlend) override virtual
Draw a bitmap (raster) image to the graphics context with rotation.
Parameters
bitmap The bitmap image to draw to the graphics context
destCentreX The X coordinate in the graphics context of the centre point at which to rotate the image around.
Todo:
check this
Parameters
destCentreY The Y coordinate in the graphics context of the centre point at which to rotate the image around.
check this
Parameters
angle The angle of rotation in degrees
yOffsetZeroDeg
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 163 of file IGraphicsLice.cpp.
References IBitmap::GetAPIBitmap(), IGraphics::GetScreenScale(), IBitmap::H(), and IBitmap::W().
void IGraphicsLice::DrawRotatedMask (IBitmap & base, IBitmap & mask, IBitmap & top, float x, float y, double angle, const IBlend * pBlend) override virtual
Draw a rotated, masked bitmap to the graphics context.
Parameters
base The base bitmap image to draw to the graphics context
Todo:
explain base
Parameters
mask The mask bitmap image to draw to the graphics context
explain mask
Parameters
top The bitmap image to draw to the graphics context
explain top
Parameters
x The X coordinate in the graphics context at which to draw
y The Y coordinate in the graphics context at which to draw
angle The angle to rotate the bitmap mask at in degrees clockwise
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 176 of file IGraphicsLice.cpp.
References IBitmap::GetAPIBitmap(), IBitmap::H(), and IBitmap::W().
void IGraphicsLice::DrawRotatedSVG (ISVG & svg, float destCentreX, float destCentreY, float width, float height, double angle, const IBlend * pBlend) override virtual
Draw an SVG image to the graphics context with rotation.
Parameters
svg The SVG image to draw to the graphics context
destCentreX The X coordinate in the graphics context of the centre point at which to rotate the image around.
Todo:
check this
Parameters
destCentreY The Y coordinate in the graphics context of the centre point at which to rotate the image around.
check this
Parameters
width
height
angle The angle to rotate the bitmap mask at in degrees clockwise
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 140 of file IGraphicsLice.cpp.
References IGraphics::DrawText().
void IGraphicsLice::DrawRoundRect (const IColor & color, const IRECT & bounds, float cornerRadius, const IBlend * pBlend, float thickness) override virtual
Draw a rounded rectangle to the graphics context.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
cornerRadius The corner radius in pixels
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 270 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
void IGraphicsLice::DrawRoundRect (const IColor & color, const IRECT & bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend * pBlend, float thickness) inline override virtual
Draw a rounded rectangle to the graphics context with individual corner roundness.
Parameters
color The color to draw the shape with
bounds The rectangular region to draw the shape in
cRTL The top left corner radius in pixels
cRTR The top right corner radius in pixels
cRBR The bottom right corner radius in pixels
cRBL The bottom left corner radius in pixels
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 117 of file IGraphicsLice.h.
void IGraphicsLice::DrawSVG (ISVG & svg, const IRECT & bounds, const IBlend * pBlend) override virtual
Draw an SVG image to the graphics context.
Parameters
svg The SVG image to the graphics context
bounds The rectangular region to draw the image in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 135 of file IGraphicsLice.cpp.
References IGraphics::DrawText().
void IGraphicsLice::DrawTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend, float thickness) override virtual
Draw a triangle to the graphics context.
Parameters
color The color to draw the shape with
x1 The X coordinate in the graphics context of the first vertex
y1 The Y coordinate in the graphics context of the first vertex
x2 The X coordinate in the graphics context of the second vertex
y2 The Y coordinate in the graphics context of the second vertex
x3 The X coordinate in the graphics context of the third vertex
y3 The Y coordinate in the graphics context of the third vertex
pBlend Optional blend method, see IBlend documentation
thickness Optional line thickness
Implements IGraphics.
Definition at line 243 of file IGraphicsLice.cpp.
References DrawLine().
void IGraphicsLice::FillArc (const IColor & color, float cx, float cy, float r, float aMin, float aMax, const IBlend * pBlend) override virtual
Fill an arc segment in the graphics context with a color.
Parameters
color The color to fill the shape with
cx The X coordinate in the graphics context of the centre of the circle on which the arc lies
cy The Y coordinate in the graphics context of the centre of the circle on which the arc lies
r The radius of the circle on which the arc lies
aMin the start angle of the arc at in degrees clockwise where 0 is up
aMax the end angle of the arc at in degrees clockwise where 0 is up
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 424 of file IGraphicsLice.cpp.
References FillCircle(), and FillConvexPolygon().
void IGraphicsLice::FillCircle (const IColor & color, float cx, float cy, float r, const IBlend * pBlend) override virtual
Fill a circle in the graphics context with a color.
Parameters
color The color to fill the shape with
cx The X coordinate in the graphics context of the centre of the circle
cy The Y coordinate in the graphics context of the centre of the circle
r The radius of the circle
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 415 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
Referenced by FillArc().
void IGraphicsLice::FillConvexPolygon (const IColor & color, float * x, float * y, int nPoints, const IBlend * pBlend) override virtual
Fill a convex polygon in the graphics context with a color.
Parameters
color The color to fill the shape with
x Pointer to the first element in an array of X coordinates for the vertices of the polygon
y Pointer to the first element in an array of Y coordinates for the vertices of the polygon
nPoints The number of points in the coordinate arrays
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 386 of file IGraphicsLice.cpp.
Referenced by FillArc().
void IGraphicsLice::FillEllipse (const IColor & color, const IRECT & bounds, const IBlend * pBlend) inline override virtual
Fill an ellipse within a rectangular region of the graphics context.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 121 of file IGraphicsLice.h.
void IGraphicsLice::FillEllipse (const IColor & color, float x, float y, float r1, float r2, float angle, const IBlend * pBlend) inline override virtual
Fill an ellipse in the graphics context.
Parameters
color The color to draw the shape with
x The X coordinate in the graphics context of the centre of the ellipse
y The Y coordinate in the graphics context of the centre of the ellipse
r1 The radius of the ellipse along the line found by rotating the x-axis by the angle
r2 The radius of the ellipse along the line found by rotating the y-axis by the angle
angle The angle rotates the radii r1 and r2 clockwise in degrees to adjust the orientation
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 122 of file IGraphicsLice.h.
void IGraphicsLice::FillRect (const IColor & color, const IRECT & bounds, const IBlend * pBlend) override virtual
Fill a rectangular region of the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 338 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
void IGraphicsLice::FillRoundRect (const IColor & color, const IRECT & bounds, float cornerRadius, const IBlend * pBlend) override virtual
Fill a rounded rectangle in the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
cornerRadius The corner radius in pixels
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 346 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
void IGraphicsLice::FillRoundRect (const IColor & color, const IRECT & bounds, float cRTL, float cRTR, float cRBR, float cRBL, const IBlend * pBlend) inline override virtual
Fill a rounded rectangle in the graphics context with a color.
Parameters
color The color to fill the shape with
bounds The rectangular region to fill the shape in
cRTL The top left corner radius in pixels
cRTR The top right corner radius in pixels
cRBR The bottom right corner radius in pixels
cRBL The bottom left corner radius in pixels
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 120 of file IGraphicsLice.h.
void IGraphicsLice::FillTriangle (const IColor & color, float x1, float y1, float x2, float y2, float x3, float y3, const IBlend * pBlend) override virtual
Fill a triangle in the graphics context with a color.
Parameters
color The color to fill the shape with
x1 The X coordinate in the graphics context of the first vertex
y1 The Y coordinate in the graphics context of the first vertex
x2 The X coordinate in the graphics context of the second vertex
y2 The Y coordinate in the graphics context of the second vertex
x3 The X coordinate in the graphics context of the third vertex
y3 The Y coordinate in the graphics context of the third vertex
pBlend Optional blend method, see IBlend documentation
Implements IGraphics.
Definition at line 329 of file IGraphicsLice.cpp.
void* IGraphicsLice::GetDrawContext () inline override virtual
Gets a void pointer to IGraphics Draw Class context data (e.g raw framebuffer).
See draw class implementation headers (e.g. IGraphicsLice.h) for what you can cast the void pointer to
Implements IGraphics.
Definition at line 113 of file IGraphicsLice.h.
const char* IGraphicsLice::GetDrawingAPIStr () inline override virtual
Returns
A CString representing the Drawing API in use e.g. "LICE"
Implements IGraphics.
Definition at line 79 of file IGraphicsLice.h.
IColor IGraphicsLice::GetPoint (int x, int y) override virtual
Get the color of a point in the graphics context.
On a 1:1 screen this corresponds to a pixel.
Todo:
check this
Parameters
x The X coordinate in the graphics context of the pixel
y The Y coordinate in the graphics context of the pixel
Returns
An IColor specifiying the color of the pixel at x,y
Implements IGraphics.
Definition at line 469 of file IGraphicsLice.cpp.
References IGraphics::GetScreenScale().
The documentation for this class was generated from the following files:
IGraphicsLice.h
IGraphicsLice.cpp