iPlug 2: OSCInterface Class Reference
OSCInterface Class Reference
#include <IPlugOSC.h>
Public Member Functions
OSCInterface (OSCLogFunc logFunc=nullptr)
Construct a new OSCInterface object.
OSCInterface (const OSCInterface &)=delete
OSCInterface & operator= (const OSCInterface &)=delete
OSCDevice * CreateReceiver (WDL_String &log, int port=8000)
Create a Receiver object.
OSCDevice * CreateSender (WDL_String &log, const char *ip="127.0.0.1", int port=8000)
Create a Sender object.
virtual void OnOSCMessage (OscMessageRead &msg)
void SetLogFunc (OSCLogFunc logFunc)
Set the Log Func object.
Protected Attributes
OSCLogFunc mLogFunc
WDL_HeapBuf mIncomingEvents
WDL_Mutex mIncomingEvents_mutex
Static Protected Attributes
static std::unique_ptr< Timer > mTimer
static int sInstances = 0
Detailed Description
Todo:
Definition at line 97 of file IPlugOSC.h.
Constructor & Destructor Documentation
OSCInterface()
OSCInterface::OSCInterface (OSCLogFunc logFunc = nullptr)
Construct a new OSCInterface object.
Parameters
logFunc
Definition at line 290 of file IPlugOSC.cpp.
~OSCInterface()
OSCInterface::~OSCInterface () virtual
Definition at line 301 of file IPlugOSC.cpp.
Member Function Documentation
CreateReceiver()
OSCDevice * OSCInterface::CreateReceiver (WDL_String & log, int port = 8000)
Create a Receiver object.
Parameters
log
port
Returns
OSCDevice*
Definition at line 309 of file IPlugOSC.cpp.
References OSCDevice::AddInstance().
Referenced by OSCReceiver::SetReceivePort().
CreateSender()
OSCDevice * OSCInterface::CreateSender (WDL_String & log, const char * ip = "127.0.0.1", int port = 8000)
Create a Sender object.
Parameters
log
port
Returns
OSCDevice*
Definition at line 367 of file IPlugOSC.cpp.
References OSCDevice::AddInstance().
Referenced by OSCSender::SetDestination().
OnOSCMessage()
virtual void OSCInterface::OnOSCMessage (OscMessageRead & msg) inline virtual
Todo:
Parameters
msg
Reimplemented in OSCReceiver.
Definition at line 131 of file IPlugOSC.h.
SetLogFunc()
void OSCInterface::SetLogFunc (OSCLogFunc logFunc) inline
Set the Log Func object.
Parameters
logFunc
Definition at line 135 of file IPlugOSC.h.
Member Data Documentation
mIncomingEvents
WDL_HeapBuf OSCInterface::mIncomingEvents protected
Definition at line 149 of file IPlugOSC.h.
mIncomingEvents_mutex
WDL_Mutex OSCInterface::mIncomingEvents_mutex protected
Definition at line 150 of file IPlugOSC.h.
mLogFunc
OSCLogFunc OSCInterface::mLogFunc protected
Definition at line 146 of file IPlugOSC.h.
mTimer
std::unique_ptr< Timer > OSCInterface::mTimer static protected
Definition at line 147 of file IPlugOSC.h.
sInstances
int OSCInterface::sInstances = 0 static protected
Definition at line 148 of file IPlugOSC.h.
The documentation for this class was generated from the following files:
IPlugOSC.h
IPlugOSC.cpp