iPlug 2: IBitmapBase Class Reference
IBitmapBase Class Reference
IGraphics::IControls::BaseControls
A base interface to be combined with IControl for bitmap-based controls "IBControls", managing an IBitmap.
#include <IControl.h>
Public Member Functions
IBitmapBase (const IBitmap &bitmap)
IBitmapBase Constructor.
void AttachIControl (IControl *pControl)
Call in the constructor of your IBControl to link the IBitmapBase and IControl.
void DrawBitmap (IGraphics &g)
Draw a frame of a multi-frame bitmap based on the IControl value.
Protected Attributes
IBitmap mBitmap
IControl * mControl = nullptr
Detailed Description
A base interface to be combined with IControl for bitmap-based controls "IBControls", managing an IBitmap.
Definition at line 632 of file IControl.h.
Constructor & Destructor Documentation
IBitmapBase()
IBitmapBase::IBitmapBase (const IBitmap & bitmap) inline
IBitmapBase Constructor.
Parameters
The IBitmap to use in this IBControl
Definition at line 637 of file IControl.h.
~IBitmapBase()
virtual IBitmapBase::~IBitmapBase () inline virtual
Definition at line 642 of file IControl.h.
Member Function Documentation
AttachIControl()
void IBitmapBase::AttachIControl (IControl * pControl) inline
Call in the constructor of your IBControl to link the IBitmapBase and IControl.
Parameters
pControl Ptr to the control
Definition at line 646 of file IControl.h.
Referenced by IBitmapControl::IBitmapControl(), and IBSwitchControl::IBSwitchControl().
DrawBitmap()
void IBitmapBase::DrawBitmap (IGraphics & g) inline
Draw a frame of a multi-frame bitmap based on the IControl value.
Parameters
g The IGraphics context
Definition at line 650 of file IControl.h.
References Clip(), IGraphics::DrawBitmap(), IControl::GetBlend(), IRECT::GetCentredInside(), IControl::GetRECT(), IControl::GetValue(), and IBitmap::N().
Referenced by IBButtonControl::Draw(), IBSwitchControl::Draw(), IBKnobControl::Draw(), IBMeterControl::Draw(), and IBitmapControl::Draw().
Member Data Documentation
mBitmap
IBitmap IBitmapBase::mBitmap protected
Definition at line 664 of file IControl.h.
mControl
IControl* IBitmapBase::mControl = nullptr protected
Definition at line 665 of file IControl.h.
The documentation for this class was generated from the following file:
IControl.h