iPlug2: IPlugVST3Controller Class Reference
IPlugVST3Controller Class Reference
IPlug::APIClasses
VST3 Controller base class for a distributed IPlug VST3 plug-in.
#include <IPlugVST3_Controller.h>
Classes
struct IPlugInstanceInfo
Public Member Functions
IPlugVST3Controller (IPlugInstanceInfo instanceInfo, IPlugConfig c)
tresult PLUGIN_API initialize (FUnknown *context) override
IPlugView *PLUGIN_API createView (FIDString name) override
tresult PLUGIN_API setComponentState (IBStream *state) override
tresult PLUGIN_API setState (IBStream *state) override
tresult PLUGIN_API getState (IBStream *state) override
tresult PLUGIN_API setParamNormalized (ParamID tag, ParamValue value) override
ParamValue PLUGIN_API getParamNormalized (ParamID tag) override
ParamValue PLUGIN_API plainParamToNormalized (ParamID tag, ParamValue plainValue) override
ParamValue PLUGIN_API normalizedParamToPlain (ParamID tag, ParamValue valueNormalized) override
tresult PLUGIN_API getParamStringByValue (ParamID tag, ParamValue valueNormalized, String128 string) override
tresult PLUGIN_API getParamValueByString (ParamID tag, TChar *string, ParamValue &valueNormalized) override
tresult PLUGIN_API notify (IMessage *message) override
tresult PLUGIN_API getMidiControllerAssignment (int32 busIndex, int16 channel, CtrlNumber midiControllerNumber, ParamID &tag) override
tresult PLUGIN_API getProgramName (ProgramListID listId, int32 programIndex, String128 name) override
tresult PLUGIN_API queryInterface (const char *iid, void **obj) override
void BeginInformHostOfParamChange (int idx) override
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
void InformHostOfParamChange (int idx, double normalizedValue) override
Implemented by the API class, called by the UI via SetParameterValue() with the value of a parameter change gesture.
void EndInformHostOfParamChange (int idx) override
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
void InformHostOfProgramChange () override
Implemented by the API class, called by the UI (etc) when the plug-in initiates a program/preset change (not applicable to all APIs)
void EditorPropertiesChangedFromDelegate (int viewWidth, int viewHeight, const IByteChunk &data) override
Call this method from a delegate, for example if you wish to store graphics dimensions in your plug-in state in order to notify the API of a graphics resize or other layout change.
void DirtyParametersFromUI () override
When modifying a range of parameters in the editor, it can be necessary to broadcast that fact, for instance in a distributed plug-in.
void SendMidiMsgFromUI (const IMidiMsg &msg) override
SendMidiMsgFromUI (Abbreviation: SMMFUI) This method should be used when sending a MIDI message from the UI.
void SendSysexMsgFromUI (const ISysEx &msg) override
SendMidiMsgFromUI (Abbreviation: SSMFUI) If a plug-in can send Sysex data as a result of actions in the user interface, this method can be used.
void SendArbitraryMsgFromUI (int messageTag, int controlTag=kNoTag, int dataSize=0, const void *pData=nullptr) override
SendArbitraryMsgFromUI (Abbreviation: SAMFUI)
Vst::IComponentHandler * GetComponentHandler () const
IPlugVST3View * GetView () const
Public Member Functions inherited from IPlugAPIBase
IPlugAPIBase (IPlugConfig config, EAPI plugAPI)
virtual bool CompareState (const uint8_t *pIncomingState, int startPos) const
Override this method to implement a custom comparison of incoming state data with your plug-ins state data, in order to support the ProTools compare light when using custom state chunks.
virtual bool OnHostRequestingAboutBox ()
virtual bool OnHostRequestingProductHelp ()
virtual void OnHostIdentified ()
Implement this to do something specific when IPlug becomes aware of the particular host that is hosting the plug-in.
virtual void OnHostRequestingImportantParameters (int count, WDL_TypedBuf< int > &results)
Called by AUv3 plug-ins to get the "overview parameters".
virtual bool OnHostRequestingSupportedViewConfiguration (int width, int height)
Called by AUv3 plug-in hosts to query support for multiple UI sizes.
virtual void OnHostSelectedViewConfiguration (int width, int height)
Called by some AUv3 plug-in hosts when a particular UI size is selected.
virtual bool GetMidiNoteText (int noteNumber, char *str) const
Override this method to provide custom text linked to MIDI note numbers in API classes that support that (VST2) Typically this might be used for a drum machine plug-in, in order to label a certainty "kick drum" etc.
virtual void * GetAAXViewInterface ()
You need to implement this method if you are not using IGraphics and you want to support AAX's view interface functionality (special shortcuts to add automation for a parameter etc.)
virtual void OnIdle ()
Override this method to get an "idle"" call on the main thread.
virtual void PrintDebugInfo () const
Helper method, used to print some info to the console in debug builds.
void SetParameterValue (int paramIdx, double normalizedValue)
SetParameterValue is called from the UI in the middle of a parameter change gesture (possibly via delegate) in order to update a parameter's value.
virtual void GetTrackColor (int &r, int &g, int &b)
Get the color of the track that the plug-in is inserted on.
virtual void GetTrackName (WDL_String &str)
Get the name of the track that the plug-in is inserted on.
virtual void SendParameterValueFromAPI (int paramIdx, double value, bool normalized)
This is called from the plug-in API class in order to update UI controls linked to plug-in parameters, prior to calling OnParamChange() NOTE: It may be called on the high priority audio thread.
void SetHost (const char *host, int version)
Called to set the name of the current host, if known (calls on to HostSpecificInit() and OnHostIdentified()).
virtual void HostSpecificInit ()
This method is implemented in some API classes, in order to do specific initialisation for particular problematic hosts.
void BeginInformHostOfParamChangeFromUI (int paramIdx) override
Called by the UI at the beginning of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is going to be modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EndInformHostOfParamChangeFromUI (int paramIdx) override
Called by the user interface at the end of a parameter change gesture, in order to notify the host (via a call in the API class) that the parameter is no longer being modified The host may be trying to automate the parameter as well, so it needs to relinquish control when the user is modifying something in the user interface.
void EditorPropertiesChangedFromUI (int viewWidth, int viewHeight, const IByteChunk &data) override
If the editor changes UI dimensions or other state we need to call into the plug-in API to store state or resize the window in the plugin This method is implemented in various classes that inherit this interface to implement that behaviour.
void SendParameterValueFromUI (int paramIdx, double normalisedValue) override
SPVFUI Called by the UI during a parameter change gesture, in order to notify the host of the new value (via a call in the API class) If you override this method you should call the base class implementation to make sure OnParamChangeUI gets triggered.
void DeferMidiMsg (const IMidiMsg &msg) override
This method is needed, for remote editors to avoid a feedback loop.
void DeferSysexMsg (const ISysEx &msg) override
This method is needed, for remote editors to avoid a feedback loop.
void CreateTimer ()
Public Member Functions inherited from IPluginBase
IPluginBase (int nParams, int nPresets)
const char * GetPluginName () const
int GetPluginVersion (bool decimal) const
Get the plug-in version number.
void GetPluginVersionStr (WDL_String &str) const
Gets the plug-in version as a string.
const char * GetMfrName () const
Get the manufacturer name as a CString.
const char * GetProductName () const
Get the product name as a CString.
int GetUniqueID () const
int GetMfrID () const
EHost GetHost () const
int GetHostVersion (bool decimal) const
Get the host version number as an integer.
void GetHostVersionStr (WDL_String &str) const
Get the host version number as a string.
EAPI GetAPI () const
const char * GetAPIStr () const
const char * GetArchStr () const
void GetBuildInfoStr (WDL_String &str) const
Used to get the build date of the plug-in and architecture/api details in one string.
bool HasUI () const
const char * GetBundleID () const
int NParamGroups () const
int AddParamGroup (const char *name)
Called to add a parameter group name, when a unique group name is discovered.
const char * GetParamGroupName (int idx) const
Get the parameter group name as a particular index.
virtual void InformHostOfParameterDetailsChange ()
Implemented by the API class, call this if you update parameter labels and hopefully the host should update it's displays (not applicable to all APIs)
virtual void OnParamChange (int paramIdx, EParamSource source, int sampleOffset=-1)
Override this method to do something to your DSP when a parameter changes.
virtual void OnParamChange (int paramIdx)
Another version of the OnParamChange method without an EParamSource, for backwards compatibility / simplicity.
void OnParamReset (EParamSource source)
Calls OnParamChange() and OnParamChangeUI() for each parameter.
bool DoesStateChunks () const
bool SerializeParams (IByteChunk &chunk) const
Serializes the current double precision floating point, non-normalised values (IParam::mValue) of all parameters, into a binary byte chunk.
int UnserializeParams (const IByteChunk &chunk, int startPos)
Unserializes double precision floating point, non-normalised values from a byte chunk into mParams.
virtual bool SerializeState (IByteChunk &chunk) const
Override this method to serialize custom state data, if your plugin does state chunks.
virtual int UnserializeState (const IByteChunk &chunk, int startPos)
Override this method to unserialize custom state data, if your plugin does state chunks.
virtual bool SerializeVST3CtrlrState (IByteChunk &chunk) const
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
virtual int UnserializeVST3CtrlrState (const IByteChunk &chunk, int startPos)
VST3 ONLY! - THIS IS ONLY INCLUDED FOR COMPATIBILITY - NOONE ELSE SHOULD NEED IT!
int GetCurrentPresetIdx () const
Get the index of the current, active preset.
void SetCurrentPresetIdx (int idx)
Set the index of the current, active preset.
void ModifyCurrentPreset (const char *name=0)
int NPresets () const
bool RestorePreset (int idx)
bool RestorePreset (const char *name)
const char * GetPresetName (int idx) const
void MakeDefaultPreset (const char *name=0, int nPresets=1)
void MakePreset (const char *name,...)
void MakePresetFromNamedParams (const char *name, int nParamsNamed,...)
void MakePresetFromChunk (const char *name, IByteChunk &chunk)
void MakePresetFromBlob (const char *name, const char *blob, int sizeOfChunk)
void PruneUninitializedPresets ()
virtual void OnPresetsModified ()
void EnsureDefaultPreset ()
bool SerializePresets (IByteChunk &chunk) const
int UnserializePresets (IByteChunk &chunk, int startPos)
void DumpPresetSrcCode (const char *file, const char *paramEnumNames[]) const
void DumpPresetBlob (const char *file) const
void DumpAllPresetsBlob (const char *filename) const
void DumpBankBlob (const char *file) const
bool SaveProgramAsFXP (const char *file) const
bool SaveBankAsFXB (const char *file) const
bool LoadProgramFromFXP (const char *file)
bool LoadBankFromFXB (const char *file)
bool SaveBankAsFXPs (const char *path) const
void MakeVSTPresetChunk (IByteChunk &chunk, IByteChunk &componentState, IByteChunk &controllerState) const
bool SaveProgramAsVSTPreset (const char *file) const
bool LoadProgramFromVSTPreset (const char *file)
bool SaveBankAsVSTPresets (const char *path)
bool SaveProgramAsAUPreset (const char *name, const char *file) const
bool LoadProgramFromAUPreset (const char *file)
bool SaveBankAsAUPresets (const char *path)
bool SaveProgramAsProToolsPreset (const char *presetName, const char *file, unsigned long pluginID) const
bool LoadProgramFromProToolsPreset (const char *file)
bool SaveBankAsProToolsPresets (const char *bath, unsigned long pluginID)
void InitParamRange (int startIdx, int endIdx, int countStart, const char *nameFmtStr, double defaultVal, double minVal, double maxVal, double step, const char *label="", int flags=0, const char *group="", IParam::Shape *shape=nullptr, IParam::EParamUnit unit=IParam::kUnitCustom, IParam::DisplayFunc displayFunc=nullptr)
Initialise a range of parameters simultaneously.
void CloneParamRange (int cloneStartIdx, int cloneEndIdx, int startIdx, const char *searchStr="", const char *replaceStr="", const char *newGroup="")
Clone a range of parameters, optionally doing a string substitution on the parameter name.
void ForParamInRange (int startIdx, int endIdx, std::function< void(int paramIdx, IParam &param)> func)
Modify a range of parameters with a lamda function.
void ForParamInGroup (const char *paramGroup, std::function< void(int paramIdx, IParam &param)> func)
Modify a parameter group simulataneously.
void CopyParamValues (int startIdx, int destIdx, int nParams)
Copy a range of parameter values.
void CopyParamValues (const char *inGroup, const char *outGroup)
Copy a range of parameter values for a parameter group.
void RandomiseParamValues ()
Randomise all parameters.
void RandomiseParamValues (int startIdx, int endIdx)
Randomise parameter values within a range.
void RandomiseParamValues (const char *paramGroup)
Randomise parameter values for a parameter group.
void DefaultParamValues ()
Set all parameters to their default values.
void DefaultParamValues (int startIdx, int endIdx)
Default parameter values within a range.
void DefaultParamValues (const char *paramGroup)
Default parameter values for a parameter group.
void PrintParamValues ()
Default parameter values for a parameter group.
Public Member Functions inherited from IEditorDelegate
IEditorDelegate (int nParams)
IParam * AddParam ()
Adds an IParam to the parameters ptr list Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
void RemoveParam (int idx)
Remove an IParam at a particular index Note: This is only used in special circumstances, since most plug-in formats don't support dynamic parameters.
IParam * GetParam (int paramIdx)
Get a pointer to one of the delegate's IParam objects.
const IParam * GetParam (int paramIdx) const
Get a const pointer to one of the delegate's IParam objects (for const methods)
int NParams () const
void SendCurrentParamValuesFromDelegate ()
Loops through all parameters, calling SendParameterValueFromDelegate() with the current value of the parameter This is important when modifying groups of parameters, restoring state and opening the UI, in order to update it with the latest values.
virtual void * OpenWindow (void *pParent)
If you are not using IGraphics, you can implement this method to attach to the native parent view e.g.
virtual void CloseWindow ()
If you are not using IGraphics you can if you need to free resources etc when the window closes.
virtual void OnUIOpen ()
Override this method to do something before the UI is opened.
virtual void OnUIClose ()
Override this method to do something before the UI is closed.
virtual void OnParamChangeUI (int paramIdx, EParamSource source=kUnknown)
This is an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI.
virtual void OnMidiMsgUI (const IMidiMsg &msg)
Handle incoming MIDI messages sent to the user interface.
virtual void OnSysexMsgUI (const ISysEx &msg)
Handle incoming SysEx messages sent to the user interface.
virtual bool OnMessage (int messageTag, int controlTag, int dataSize, const void *pData)
This could be implemented in either DSP or EDITOR to receive a message from the other one.
virtual void OnRestoreState ()
This is called by API classes after restoring state and by IPluginBase::RestorePreset().
virtual void SendControlValueFromDelegate (int controlTag, double normalizedValue)
SendControlValueFromDelegate (Abbreviation: SCVFD) WARNING: should not be called on the realtime audio thread.
virtual void SendControlMsgFromDelegate (int controlTag, int messageTag, int dataSize=0, const void *pData=nullptr)
SendControlMsgFromDelegate (Abbreviation: SCMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendArbitraryMsgFromDelegate (int messageTag, int dataSize=0, const void *pData=nullptr)
SendArbitraryMsgFromDelegate (Abbreviation: SAMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendMidiMsgFromDelegate (const IMidiMsg &msg)
SendMidiMsgFromDelegate (Abbreviation: SMMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendSysexMsgFromDelegate (const ISysEx &msg)
SendSysexMsgFromDelegate (Abbreviation: SSMFD) WARNING: should not be called on the realtime audio thread.
virtual void SendParameterValueFromDelegate (int paramIdx, double value, bool normalized)
SendParameterValueFromDelegate (Abbreviation: SPVFD) WARNING: should not be called on the realtime audio thread.
int GetEditorWidth () const
int GetEditorHeight () const
const IByteChunk & GetEditorData () const
Additional Inherited Members
Protected Attributes inherited from IPlugAPIBase
WDL_String mParamDisplayStr
Timer * mTimer = nullptr
IPlugQueue< IParamChange > mParamChangeFromProcessor {PARAM_TRANSFER_SIZE}
IPlugQueue< IMidiMsg > mMidiMsgsFromEditor {MIDI_TRANSFER_SIZE}
IPlugQueue< IMidiMsg > mMidiMsgsFromProcessor {MIDI_TRANSFER_SIZE}
IPlugQueue< SysExData > mSysExDataFromEditor {SYSEX_TRANSFER_SIZE}
IPlugQueue< SysExData > mSysExDataFromProcessor {SYSEX_TRANSFER_SIZE}
SysExData mSysexBuf
Protected Attributes inherited from IPluginBase
int mCurrentPresetIdx = 0
bool mStateChunks = false
true if the plug-in does opaque state chunks.
WDL_String mPluginName
The name of this plug-in.
WDL_String mProductName
Product name: if the plug-in is part of collection of plug-ins it might be one product.
WDL_String mMfrName
Plug-in Manufacturer name.
int mUniqueID
int mMfrID
int mVersion
Plug-in version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
int mHostVersion = 0
Host version number stored as 0xVVVVRRMM: V = version, R = revision, M = minor revision.
EHost mHost = kHostUninit
Host that has been identified, see EHost enum.
EAPI mAPI
API of this instance.
WDL_String mBundleID
macOS/iOS bundle ID
WDL_String mVST3ProductCategory
Saving VST3 format presets requires this see SaveProgramAsVSTPreset.
WDL_String mVST3ProcessorUIDStr
Saving VST3 format presets requires this see SaveProgramAsVSTPreset.
WDL_String mVST3ControllerUIDStr
Saving VST3 format presets requires this see SaveProgramAsVSTPreset.
bool mHasUI = false
true if the plug-in has a user interface.
WDL_PtrList< const char > mParamGroups
A list of unique cstrings found specified as "parameter groups" when defining IParams.
WDL_PtrList< IPreset > mPresets
Protected Attributes inherited from IEditorDelegate
int mEditorWidth = 0
The width of the plug-in editor in pixels.
int mEditorHeight = 0
The height of the plug-in editor in pixels.
IByteChunk mEditorData
Any arbitrary data that the editor need to store (e.g.
WDL_PtrList< IParam > mParams
A list of IParam objects.
Detailed Description
VST3 Controller base class for a distributed IPlug VST3 plug-in.
Definition at line 32 of file IPlugVST3_Controller.h.
Member Function Documentation
void IPlugVST3Controller::BeginInformHostOfParamChange (int paramIdx) inline override virtual
Implemented by the API class, called by the UI (or by a delegate) at the beginning of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented from IPlugAPIBase.
Definition at line 72 of file IPlugVST3_Controller.h.
void IPlugVST3Controller::DirtyParametersFromUI () override virtual
When modifying a range of parameters in the editor, it can be necessary to broadcast that fact, for instance in a distributed plug-in.
You can use it if you restore a preset using a custom preset mechanism.
Reimplemented from IPlugAPIBase.
Definition at line 503 of file IPlugVST3_Controller.cpp.
References IPlugAPIBase::DirtyParametersFromUI().
void IPlugVST3Controller::EditorPropertiesChangedFromDelegate (int width, int height, const IByteChunk & data) override virtual
Call this method from a delegate, for example if you wish to store graphics dimensions in your plug-in state in order to notify the API of a graphics resize or other layout change.
If calling from a UI interaction use EditorPropertiesChangedFromUI() When this is overridden in subclasses the subclass should call this in order to update the member variables
Reimplemented from IPlugAPIBase.
Definition at line 494 of file IPlugVST3_Controller.cpp.
References IPlugAPIBase::EditorPropertiesChangedFromDelegate(), IEditorDelegate::GetEditorHeight(), IEditorDelegate::GetEditorWidth(), and IPluginBase::HasUI().
void IPlugVST3Controller::EndInformHostOfParamChange (int paramIdx) inline override virtual
Implemented by the API class, called by the UI (or by a delegate) at the end of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
Reimplemented from IPlugAPIBase.
Definition at line 74 of file IPlugVST3_Controller.h.
void IPlugVST3Controller::InformHostOfParamChange (int paramIdx, double normalizedValue) inline override virtual
Implemented by the API class, called by the UI via SetParameterValue() with the value of a parameter change gesture.
Parameters
paramIdx The parameter that is being changed
normalizedValue The new normalised value of the parameter being changed
Reimplemented from IPlugAPIBase.
Definition at line 73 of file IPlugVST3_Controller.h.
void IPlugVST3Controller::SendArbitraryMsgFromUI (int messageTag, int controlTag = kNoTag, int dataSize = 0, const void * pData = nullptr) override virtual
SendArbitraryMsgFromUI (Abbreviation: SAMFUI)
Parameters
messageTag A unique tag to identify the message
controlTag A unique tag to identify the control that sent the message, if desired
dataSize The size in bytes of the data payload pointed to by pData. Note: if this is nonzero, pData must be valid.
pData Ptr to the opaque data payload for the message
Reimplemented from IPlugAPIBase.
Definition at line 473 of file IPlugVST3_Controller.cpp.
void IPlugVST3Controller::SendMidiMsgFromUI (const IMidiMsg & msg) override virtual
SendMidiMsgFromUI (Abbreviation: SMMFUI) This method should be used when sending a MIDI message from the UI.
For example clicking on a key in a virtual keyboard. Eventually the MIDI message can be handled in IPlugProcessor::ProcessMidiMsg(), from where it can be used to trigger sound and or forwarded to the API's MIDI output.
Parameters
msg The MIDI message to send.
Reimplemented from IPlugAPIBase.
Definition at line 448 of file IPlugVST3_Controller.cpp.
void IPlugVST3Controller::SendSysexMsgFromUI (const ISysEx & msg) override virtual
SendMidiMsgFromUI (Abbreviation: SSMFUI) If a plug-in can send Sysex data as a result of actions in the user interface, this method can be used.
Unlike SendMidiMsgFromUI, Sysex messages will not be received in IPlugProcessor::ProcessSysex() Since it is extremely unlikely that you would want to use Sysex to communicate between editor and processor
Todo:
is this correct?
Parameters
msg The Sysex message to send.
Reimplemented from IPlugAPIBase.
Definition at line 460 of file IPlugVST3_Controller.cpp.
The documentation for this class was generated from the following files:
IPlugVST3_Controller.h
IPlugVST3_Controller.cpp