iPlug 2: IByteStream Class Reference
IByteStream Class Reference
IPlug::Structs
Manages a non-owned block of memory, for receiving arbitrary message byte streams.
#include <IPlugStructs.h>
Public Member Functions
IByteStream (const void *pData, int dataSize)
int GetBytes (void *pDst, int nBytesToCopy, int startPos) const
Copy raw bytes from the stream, returning the new position for subsequent calls.
template<class T >
int Get (T *pDst, int startPos) const
Get arbitary typed data from the stream.
int GetStr (WDL_String &str, int startPos) const
Get a string from the stream.
int Size () const
Returns the size of the stream.
bool IsEqual (IByteStream &otherStream) const
Compares the size & values of the data of another stream with this one.
const uint8_t * GetData ()
Gets a const ptr to the stream data.
Detailed Description
Manages a non-owned block of memory, for receiving arbitrary message byte streams.
Definition at line 267 of file IPlugStructs.h.
Constructor & Destructor Documentation
IByteStream()
IByteStream::IByteStream (const void * pData, int dataSize) inline
Definition at line 270 of file IPlugStructs.h.
~IByteStream()
IByteStream::~IByteStream () inline
Definition at line 271 of file IPlugStructs.h.
Member Function Documentation
Get()
template<class T > int IByteStream::Get (T * pDst, int startPos) const inline
Get arbitary typed data from the stream.
Template Parameters
T The type of data to be extracted
Parameters
pDst Ptr to the destination where the data will be extracted
startPos The starting position in bytes in the stream
Returns
int The end position in the stream (in bytes) after the copy, or -1 if the copy would have copied more data than in the stream
Definition at line 289 of file IPlugStructs.h.
References GetBytes().
Referenced by IBMeterControl::OnMsgFromDelegate(), IRTTextControl< MAXNC, T >::OnMsgFromDelegate(), IVDisplayControl::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVPeakAvgMeterControl< MAXNC >::OnMsgFromDelegate(), and IVScopeControl< MAXNC, MAXBUF >::OnMsgFromDelegate().
GetBytes()
int IByteStream::GetBytes (void * pDst, int nBytesToCopy, int startPos) const inline
Copy raw bytes from the stream, returning the new position for subsequent calls.
Parameters
pDst The destination buffer
nBytesToCopy The number of bytes to copy from the stream
startPos The starting position in bytes in the stream
Returns
int The end position in the stream (in bytes) after the copy, or -1 if the copy would have copied more data than in the stream
Definition at line 278 of file IPlugStructs.h.
References IByteGetter::GetBytes(), and Size().
Referenced by Get().
GetData()
const uint8_t * IByteStream::GetData () inline
Gets a const ptr to the stream data.
Returns
uint8_t* const ptr to the stream data
Definition at line 320 of file IPlugStructs.h.
GetStr()
int IByteStream::GetStr (WDL_String & str, int startPos) const inline
Get a string from the stream.
Parameters
str WDL_String to fill
startPos The starting position in bytes in the stream
Returns
int The end position in the stream (in bytes) after the copy, or -1 if the copy would have copied more data than in the stream
Definition at line 298 of file IPlugStructs.h.
References IByteGetter::GetStr(), and Size().
IsEqual()
bool IByteStream::IsEqual (IByteStream & otherStream) const inline
Compares the size & values of the data of another stream with this one.
Parameters
otherChunk The stream to compare with
Returns
true if the streams are equal
Definition at line 313 of file IPlugStructs.h.
References Size().
Size()
int IByteStream::Size () const inline
Returns the size of the stream.
Returns
size (in bytes)
Definition at line 305 of file IPlugStructs.h.
Referenced by GetBytes(), GetStr(), and IsEqual().
The documentation for this class was generated from the following file:
IPlugStructs.h