iPlug 2: IControl Class Reference
IControl Class Reference abstract
IGraphics::IControls::BaseControls
The lowest level base class of an IGraphics control.
#include <IControl.h>
Public Member Functions
IControl (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction actionFunc=nullptr)
Constructor.
IControl (const IRECT &bounds, const std::initializer_list< int > &params, IActionFunction actionFunc=nullptr)
Constructor (range of parameters)
IControl (const IRECT &bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
IControl (const IControl &)=delete
void operator= (const IControl &)=delete
virtual ~IControl ()
Destructor.
virtual void OnMouseDown (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse down event on this control.
virtual void OnMouseUp (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse up event on this control.
virtual void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
Implement this method to respond to a mouse drag event on this control.
virtual void OnMouseDblClick (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse double click event on this control.
virtual void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
Implement this method to respond to a mouse wheel event on this control.
virtual bool OnKeyDown (float x, float y, const IKeyPress &key)
Implement this method to respond to a key down event on this control.
virtual bool OnKeyUp (float x, float y, const IKeyPress &key)
Implement this method to respond to a key up event on this control.
virtual void OnMouseOver (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouseover event on this control.
virtual void OnMouseOut ()
Implement this method to respond to a mouseout event on this control.
virtual void OnTouchCancelled (float x, float y, const IMouseMod &mod)
Implement this method to respond to a touch cancel event on this control.
virtual void OnDrop (const char *str)
Implement to do something when something was drag 'n dropped onto this control.
virtual void OnRescale ()
Implement to do something when graphics is scaled globally (e.g.
virtual void OnResize ()
Called when IControl is constructed or resized using SetRect().
virtual void OnInit ()
Called just prior to when the control is attached, after its delegate and graphics member variable set.
virtual void OnAttached ()
Called after the control has been attached, and its delegate and graphics member variable set.
virtual void OnMsgFromDelegate (int msgTag, int dataSize, const void *pData)
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
virtual void OnMidi (const IMidiMsg &msg)
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
virtual bool OnGesture (const IGestureInfo &info)
virtual void CreateContextMenu (IPopupMenu &contextMenu)
Called by default when the user right clicks a control.
virtual void OnPopupMenuSelection (IPopupMenu *pSelectedMenu, int valIdx)
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControlPromptUserInput.
virtual void OnTextEntryCompletion (const char *str, int valIdx)
Implement this method to handle text input after IGraphics::CreateTextEntry/IControlPromptUserInput.
virtual void OnContextSelection (int itemSelected)
Implement this to respond to a menu selection from CreateContextMenu();.
virtual void Draw (IGraphics &g)=0
Draw the control to the graphics context.
virtual void DrawPTHighlight (IGraphics &g)
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
void PromptUserInput (int valIdx=0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
void PromptUserInput (const IRECT &bounds, int valIdx=0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter) specifying the bounds.
IControl * SetActionFunction (IActionFunction actionFunc)
Set an Action Function for this control.
IControl * SetAnimationEndActionFunction (IActionFunction actionFunc)
Set an Action Function to be called at the end of an animation.
void SetTooltip (const char *str)
Set a tooltip for the control.
const char * GetTooltip () const
int GetParamIdx (int valIdx=0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
virtual void SetParamIdx (int paramIdx, int valIdx=0)
Set the index of a parameter that the control is linked to If you are calling this "manually" to reuse a control for multiple parameters, you probably want to call IEditorDelegate::SendCurrentParamValuesFromDelegate() afterward, to update the control values.
int LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
int NVals () const
virtual int GetValIdxForPos (float x, float y) const
Check to see which of the control's values relates to this x and y coordinate.
const IParam * GetParam (int valIdx=0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
virtual void SetValueFromDelegate (double value, int valIdx=0)
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
virtual void SetValueFromUserInput (double value, int valIdx=0)
Set the control's value after user input.
virtual void SetValueToDefault (int valIdx=kNoValIdx)
Set one or all of the control's values to the default value of the associated parameter.
virtual void SetValue (double value, int valIdx=0)
Set one of the control's values.
double GetValue (int valIdx=0) const
Get the control's value.
void SetGroup (const char *groupName)
Assign the control to a control group.
const char * GetGroup () const
Get the group that the control belongs to, if any.
const IText & GetText () const
Get the Text object for the control.
virtual void SetText (const IText &txt)
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
void SetBlend (const IBlend &blend)
Set the Blend for this control.
IBlend GetBlend () const
Get the Blend for this control.
int GetTextEntryLength () const
Get the max number of characters that are allowed in text entry.
void SetTextEntryLength (int len)
Set the max number of characters that are allowed in text entry.
const IRECT & GetRECT () const
Get the rectangular draw area for this control, within the graphics context.
void SetRECT (const IRECT &bounds)
Set the rectangular draw area for this control, within the graphics context.
const IRECT & GetTargetRECT () const
Get the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetRECT (const IRECT &bounds)
Set the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetAndDrawRECTs (const IRECT &bounds)
Set BOTH the draw rect and the target area, within the graphics context for this control.
virtual void SetPosition (float x, float y)
Set the position of the control, preserving the width and height.
virtual void SetSize (float w, float h)
Set the size of the control, preserving the current position.
void SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
bool GetMouseDblAsSingleClick () const
Get double click as single click By default, mouse double click has its own handler.
virtual void Hide (bool hide)
Shows or hides the IControl.
bool IsHidden () const
virtual void SetDisabled (bool disable)
Sets disabled mode for the control, the default implementation modifies the mBlend member.
bool IsDisabled () const
void SetMouseOverWhenDisabled (bool allow)
Specify whether the control should respond to mouse overs when disabled.
void SetMouseEventsWhenDisabled (bool allow)
Specify whether the control should respond to other mouse events when disabled.
bool GetMouseOverWhenDisabled () const
bool GetMouseEventsWhenDisabled () const
bool GetIgnoreMouse () const
void SetIgnoreMouse (bool ignore)
Specify whether the control should respond to mouse events.
bool GetPromptShowsParamLabel () const
void SetPromptShowsParamLabel (bool enable)
Set if the control should show parameter labels/units e.g.
virtual bool IsHit (float x, float y) const
Hit test the control.
virtual void SetDirty (bool triggerAction=true, int valIdx=kNoValIdx)
Mark the control as dirty, i.e.
virtual void SetClean ()
void Animate ()
virtual bool IsDirty ()
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
void DisablePrompt (bool disable)
Disable/enable default prompt for user input.
virtual void OnGUIIdle ()
This is an idle timer tick call on the GUI thread, only active if USE_IDLE_CALLS is defined.
int GetTag () const
Get the control's tag.
void SetWantsMidi (bool enable=true)
Specify whether this control wants to know about MIDI messages sent to the UI.
bool GetWantsMidi () const
void SetWantsMultiTouch (bool enable=true)
Specify whether this control supports multiple touches.
bool GetWantsMultiTouch () const
IControl * AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
bool GetWantsGestures () const
EGestureType GetLastGesture () const
IGEditorDelegate * GetDelegate ()
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
void SetDelegate (IGEditorDelegate &dlg)
Used internally to set the mDelegate (and mGraphics) variables.
IContainerBase * GetParent () const
void SetParent (IContainerBase *pParent)
IGraphics * GetUI ()
const IGraphics * GetUI () const
bool GetMouseIsOver () const
This can be used in IControl::Draw() to check if the mouse is over the control, without implementing mouse over methods.
virtual void SnapToMouse (float x, float y, EDirection direction, const IRECT &bounds, int valIdx=-1, double minClip=0., double maxClip=1.)
Set control value based on x, y position within a rectangle.
virtual void OnEndAnimation ()
void StartAnimation (int duration)
void SetAnimation (IAnimationFunction func)
Set the animation function.
void SetAnimation (IAnimationFunction func, int duration)
Set the animation function and starts it.
IAnimationFunction GetAnimationFunction ()
Get the control's animation function, if it exists.
IActionFunction GetActionFunction ()
Get the control's action function, if it exists.
double GetAnimationProgress () const
Get the progress in a control's animation, in the range 0-1.
Milliseconds GetAnimationDuration () const
Get the duration of animations applied to the control.
template<class T >
T * As ()
Helper function to dynamic cast an IControl to a subclass.
Protected Member Functions
template<typename T , typename... Args>
void ForValIdx (int valIdx, T func, Args... args)
A helper template function to call a method for an individual value, or for all values.
void SetNVals (int nVals)
Protected Attributes
IRECT mRECT
IRECT mTargetRECT
WDL_String mGroup
Controls can be grouped for hiding and showing panels.
IText mText
IBlend mBlend
int mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN
bool mDirty = true
bool mHide = false
bool mDisabled = false
bool mDisablePrompt = true
bool mDblAsSingleClick = false
bool mMouseOverWhenDisabled = false
bool mMouseEventsWhenDisabled = false
bool mIgnoreMouse = false
bool mWantsMidi = false
bool mWantsMultiTouch = false
bool mPromptShowsParamLabel = false
bool mMouseIsOver = false
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
WDL_String mTooltip
IColor mPTHighlightColor = COLOR_RED
bool mPTisHighlighted = false
Detailed Description
The lowest level base class of an IGraphics control.
A control is anything on the GUI
Definition at line 44 of file IControl.h.
Constructor & Destructor Documentation
IControl() [1/3]
IControl::IControl (const IRECT & bounds, int paramIdx = kNoParameter, IActionFunction actionFunc = nullptr)
Constructor.
Creates an IControl NOTE: An IControl does not know about the delegate or graphics context to which it belongs in the constructor If you need to do something once those things are known, see IControl::OnInit()
Parameters
bounds The rectangular area that the control occupies
paramIdx If this is > -1 (kNoParameter) this control will be associated with a plugin parameter
actionFunc pass in a lambda function to provide custom functionality when the control "action" happens (usually mouse down).
Definition at line 83 of file IControl.cpp.
IControl() [2/3]
IControl::IControl (const IRECT & bounds, const std::initializer_list< int > & params, IActionFunction actionFunc = nullptr)
Constructor (range of parameters)
Creates an IControl which is linked to multiple parameters NOTE: An IControl does not know about the delegate or graphics context to which it belongs in the constructor If you need to do something once those things are known, see IControl::OnInit()
Parameters
bounds The rectangular area that the control occupies
params An initializer list of valid integer parameter indexes
actionFunc pass in a lambda function to provide custom functionality when the control "action" happens (usually mouse down).
Definition at line 91 of file IControl.cpp.
IControl() [3/3]
IControl::IControl (const IRECT & bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
Creates an IControl which is not linked to a parameter NOTE: An IControl does not know about the delegate or graphics context to which it belongs in the constructor If you need to do something once those things are known, see IControl::OnInit()
Parameters
bounds The rectangular area that the control occupies
actionFunc pass in a lambda function to provide custom functionality when the control "action" happens (usually mouse down).
Definition at line 102 of file IControl.cpp.
~IControl()
virtual IControl::~IControl () inline virtual
Destructor.
Clean up any resources that your control owns.
Definition at line 81 of file IControl.h.
Member Function Documentation
Animate()
void IControl::Animate ()
Definition at line 225 of file IControl.cpp.
As()
template<class T > T * IControl::As () inline
Helper function to dynamic cast an IControl to a subclass.
Definition at line 509 of file IControl.h.
Referenced by SplashAnimationFunc(), and SplashClickActionFunc().
AttachGestureRecognizer()
IControl * IControl::AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
Parameters
type The type of gesture to recognize on this control
func the function to trigger
Definition at line 311 of file IControl.cpp.
References IGraphics::AttachGestureRecognizer(), and GetUI().
Referenced by TestGesturesControl::OnInit().
CreateContextMenu()
virtual void IControl::CreateContextMenu (IPopupMenu & contextMenu) inline virtual
Called by default when the user right clicks a control.
If IGRAPHICS_NO_CONTEXT_MENU is enabled as a preprocessor macro right clicking control will mean IControl::CreateContextMenu() and IControl::OnContextSelection() do not function on right clicking control. VST3 provides contextual menu support which is hard wired to right click controls by default. You can add custom items to the menu by implementing IControl::CreateContextMenu() and handle them in IControl::OnContextSelection(). In non-VST 3 hosts right clicking will still create the menu, but it will not feature entries added by the host.
Definition at line 168 of file IControl.h.
Referenced by IGraphics::PopupHostContextMenuForParam().
DisablePrompt()
void IControl::DisablePrompt (bool disable) inline
Disable/enable default prompt for user input.
Parameters
disable Set true to disable prompt
Definition at line 411 of file IControl.h.
Draw()
virtual void IControl::Draw (IGraphics & g) pure virtual
Draw the control to the graphics context.
Parameters
g The graphics context to which this control belongs.
Implemented in IBubbleControl, IColorPickerControl, IVLabelControl, IVButtonControl, IVSwitchControl, IVSlideSwitchControl, IVTabSwitchControl, IVKnobControl, IVSliderControl, IVRangeSliderControl, IVXYPadControl, IVPlotControl, IVGroupControl, IVPanelControl, IVColorSwatchControl, ISVGKnobControl, ISVGButtonControl, ISVGToggleControl, ISVGSwitchControl, ISVGSliderControl, IBButtonControl, IBSwitchControl, IBKnobControl, IBKnobRotaterControl, IBSliderControl, IBTextControl, IBMeterControl, ICornerResizerControl, IFPSDisplayControl, ILEDControl, IPopupMenuControl, IShaderControl, ITextEntryControl, IVDisplayControl, IVKeyboardControl, IWheelControl, IVMeterControl< MAXNC >, IVMeterControl< MAXNC >, IVMeterControl< 1 >, IVMultiSliderControl< MAXNC >, IVMultiSliderControl< 1 >, IVNumberBoxControl, IVBakedPresetManagerControl, IVDiskPresetManagerControl, IVScopeControl< MAXNC, MAXBUF >, IWebViewControl, ISkLottieControl, ISkParagraphControl, TestAnimationControl, TestArcControl, TestBezierControl, TestBlendControl, TestColorControl, TestCursorControl, TestCustomShaderControl, TestDirBrowseControl, TestDrawContextControl, TestDropShadowControl, TestFlexBoxControl, TestFontControl, TestGesturesControl, GFXLabelControl, TestGradientControl, TestImageControl, TestKeyboardControl, TestLayerControl, TestMaskControl, TestMPSControl, TestMultiPathControl, TestMTControl, TestPolyControl, TestShadowGradientControl, TestSizeControl, TestSVGControl, TestTextControl, TestTextOrientationControl, TestTextSizeControl, IContainerBase, IPanelControl, ILambdaControl, IBitmapControl, ISVGControl, ITextControl, IURLControl, ICaptionControl, PlaceHolder, and IGraphicsLiveEdit.
DrawPTHighlight()
void IControl::DrawPTHighlight (IGraphics & g) virtual
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
Parameters
g The graphics context to which this control belongs.
Definition at line 389 of file IControl.cpp.
References IGraphics::FillCircle(), IRECT::R, and IRECT::T.
ForValIdx()
template<typename T , typename... Args> void IControl::ForValIdx (int valIdx, T func, Args... args) inline protected
A helper template function to call a method for an individual value, or for all values.
Parameters
valIdx If this is > kNoValIdx execute the function for an individual value. If equal to kNoValIdx call the function for all values
func A function that takes a single integer argument, the value index
args Arguments to the function
Definition at line 523 of file IControl.h.
References NVals().
Referenced by SetDirty(), SetValueToDefault(), and SnapToMouse().
GetActionFunction()
IActionFunction IControl::GetActionFunction () inline
Get the control's action function, if it exists.
Definition at line 499 of file IControl.h.
GetAnimationDuration()
Milliseconds IControl::GetAnimationDuration () const inline
Get the duration of animations applied to the control.
Definition at line 505 of file IControl.h.
GetAnimationFunction()
IAnimationFunction IControl::GetAnimationFunction () inline
Get the control's animation function, if it exists.
Definition at line 496 of file IControl.h.
Referenced by IVSlideSwitchControl::Draw(), ISkLottieControl::Draw(), TestKeyboardControl::Draw(), IVectorBase::DrawPressableEllipse(), IVectorBase::DrawPressableRectangle(), IVectorBase::DrawPressableTriangle(), IsDirty(), and IVSlideSwitchControl::SetDirty().
GetAnimationProgress()
double IControl::GetAnimationProgress () const
Get the progress in a control's animation, in the range 0-1.
Definition at line 431 of file IControl.cpp.
Referenced by DefaultAnimationFunc(), IPopupMenuControl::IPopupMenuControl(), IWheelControl::OnMouseUp(), and SplashAnimationFunc().
GetBlend()
IBlend IControl::GetBlend () const inline
Get the Blend for this control.
Definition at line 295 of file IControl.h.
Referenced by IVectorBase::DrawBackground(), IBitmapBase::DrawBitmap(), IVectorBase::DrawLabel(), IVectorBase::DrawPressableEllipse(), IVectorBase::DrawPressableRectangle(), IVectorBase::DrawPressableTriangle(), and IVectorBase::DrawValue().
GetDelegate()
IGEditorDelegate * IControl::GetDelegate () inline
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
If you need to call other methods on that class, you can use static_cast<PLUG_CLASS_NAME>(GetDelegate();
Returns
The class implementing the IEditorDelegate interface that handles communication to/from from this IGraphics instance.
Definition at line 445 of file IControl.h.
Referenced by IWheelControl::IWheelControl(), IVNumberBoxControl::OnMouseDown(), IVNumberBoxControl::OnMouseUp(), IVBakedPresetManagerControl::OnPopupMenuSelection(), IWheelControl::OnPopupMenuSelection(), SetDirty(), and IVTrackControlBase::SetParamsByGroup().
GetGroup()
const char * IControl::GetGroup () const inline
Get the group that the control belongs to, if any.
Returns
A CString indicating the control group that this control belongs to (may be empty)
Definition at line 280 of file IControl.h.
References mGroup.
Referenced by IGraphics::ForControlInGroup().
GetIgnoreMouse()
bool IControl::GetIgnoreMouse () const inline
Returns
true if the control ignores mouse events
Definition at line 375 of file IControl.h.
GetLastGesture()
EGestureType IControl::GetLastGesture () const inline
Returns
the last recognized gesture
Definition at line 440 of file IControl.h.
GetMouseDblAsSingleClick()
bool IControl::GetMouseDblAsSingleClick () const inline
Get double click as single click By default, mouse double click has its own handler.
A control can set mDblAsSingleClick to true which maps double click to single click for this control (and also causes the mouse to be captured by the control on double click).
Returns
/c true if double clicks should be mapped to single clicks
Definition at line 344 of file IControl.h.
Referenced by IGraphics::OnMouseDblClick().
GetMouseEventsWhenDisabled()
bool IControl::GetMouseEventsWhenDisabled () const inline
Returns
true if the control responds to other mouse events when disabled
Definition at line 372 of file IControl.h.
GetMouseIsOver()
bool IControl::GetMouseIsOver () const inline
This can be used in IControl::Draw() to check if the mouse is over the control, without implementing mouse over methods.
Note that this method is only enabled if IGraphics::EnableMouseOver() is set to true
Returns
\true if the mouse is over this control.
Definition at line 470 of file IControl.h.
References mMouseIsOver.
Referenced by ICornerResizerControl::Draw(), and ICaptionControl::Draw().
GetMouseOverWhenDisabled()
bool IControl::GetMouseOverWhenDisabled () const inline
Returns
true if the control responds to mouse overs when disabled
Definition at line 369 of file IControl.h.
GetParam()
const IParam * IControl::GetParam (int valIdx = 0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
Returns
const pointer to an IParam or nullptr if the control is not associated with a parameter
Definition at line 122 of file IControl.cpp.
References IEditorDelegate::GetParam(), and GetParamIdx().
Referenced by ICaptionControl::Draw(), IVSwitchControl::OnInit(), IVTabSwitchControl::OnInit(), IVKnobControl::OnInit(), IVSliderControl::OnInit(), IVNumberBoxControl::OnInit(), ISwitchControlBase::OnInit(), ITextEntryControl::OnKeyDown(), IVNumberBoxControl::OnMouseDown(), ISliderControlBase::OnMouseDown(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IVNumberBoxControl::OnMouseUp(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), OnPopupMenuSelection(), ICaptionControl::OnResize(), IGraphics::PromptUserInput(), PromptUserInput(), IGraphics::SetControlValueAfterTextEdit(), IVSwitchControl::SetDirty(), IVKnobControl::SetDirty(), IVSliderControl::SetDirty(), IVTrackControlBase::SetParams(), IVNumberBoxControl::SetValueFromDelegate(), IVNumberBoxControl::SetValueFromUserInput(), SetValueToDefault(), ShowBubbleHorizontalActionFunc(), and ShowBubbleVerticalActionFunc().
GetParamIdx()
int IControl::GetParamIdx (int valIdx = 0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
Parameters
valIdx An index to choose which of the control's linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Returns
Parameter index, or kNoParameter if there is no parameter linked with this control at valIdx
Definition at line 109 of file IControl.cpp.
References NVals().
Referenced by IGraphics::CreateTextEntry(), GetParam(), IGraphics::GetParamIdxForPTAutomation(), ISwitchControlBase::OnInit(), IGraphics::OnMouseDown(), IVNumberBoxControl::OnMouseDown(), IGraphics::OnMouseUp(), IVNumberBoxControl::OnMouseUp(), OnPopupMenuSelection(), PromptUserInput(), IGEditorDelegate::SendParameterValueFromDelegate(), IGraphics::SetControlValueAfterPopupMenu(), SetDirty(), and IGraphics::UpdatePeers().
GetParent()
IContainerBase * IControl::GetParent () const inline
Returns
A pointer to the parent container, if the control is a sub control
Definition at line 458 of file IControl.h.
Referenced by IGraphicsLiveEdit::Draw(), and IGraphics::IsDirty().
GetPromptShowsParamLabel()
bool IControl::GetPromptShowsParamLabel () const inline
Returns
true if the control should show parameter labels/units e.g. "Hz" in text entry prompts
Definition at line 382 of file IControl.h.
Referenced by IGraphics::PromptUserInput().
GetRECT()
const IRECT & IControl::GetRECT () const inline
Get the rectangular draw area for this control, within the graphics context.
Returns
The control's bounds
Definition at line 307 of file IControl.h.
Referenced by IVNumberBoxControl::Draw(), IGraphicsLiveEdit::Draw(), IBitmapBase::DrawBitmap(), IGraphics::IsDirty(), IVNumberBoxControl::OnMouseDblClick(), IGraphicsLiveEdit::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), IGraphicsLiveEdit::OnMouseOver(), IGraphicsLiveEdit::OnMouseUp(), IVNumberBoxControl::OnResize(), ShowBubbleHorizontalActionFunc(), ShowBubbleVerticalActionFunc(), and IGraphics::StartLayer().
GetTag()
int IControl::GetTag () const inline
Get the control's tag.
See also
Control Tags
Definition at line 417 of file IControl.h.
References IGraphics::GetControlTag(), and GetUI().
Referenced by IWheelControl::OnPopupMenuSelection(), IGraphics::RemoveControl(), and IGraphics::RemoveControls().
GetTargetRECT()
const IRECT & IControl::GetTargetRECT () const inline
Get the rectangular mouse tracking target area, within the graphics context for this control.
Returns
The control's target bounds within the graphics context
Definition at line 315 of file IControl.h.
Referenced by IGraphicsLiveEdit::OnMouseDown().
GetText()
const IText & IControl::GetText () const inline
Get the Text object for the control.
Returns
const IText& The control's mText object, typically used to determine font/layout/size etc of the main text in a control.
Definition at line 284 of file IControl.h.
Referenced by IGraphics::PromptUserInput().
GetTextEntryLength()
int IControl::GetTextEntryLength () const inline
Get the max number of characters that are allowed in text entry.
Returns
int The max number of characters allowed in text entry
Definition at line 299 of file IControl.h.
Referenced by IGraphics::CreateTextEntry().
GetTooltip()
const char * IControl::GetTooltip () const inline
Returns
Currently set tooltip text
Definition at line 215 of file IControl.h.
GetUI() [1/2]
IGraphics * IControl::GetUI () inline
Returns
A pointer to the IGraphics context that owns this control
Definition at line 463 of file IControl.h.
Referenced by AttachGestureRecognizer(), IPopupMenuControl::CreatePopupMenu(), ICornerResizerControl::Draw(), GetTag(), IBubbleControl::IBubbleControl(), IVectorBase::MakeRects(), IWebViewControl::OnAttached(), TestDropShadowControl::OnDrop(), TestSVGControl::OnDrop(), IGraphicsLiveEdit::OnInit(), ITextEntryControl::OnKeyDown(), IGraphicsLiveEdit::OnKeyDown(), ICornerResizerControl::OnMouseDblClick(), IVNumberBoxControl::OnMouseDblClick(), TestTextControl::OnMouseDblClick(), PlaceHolder::OnMouseDblClick(), IVXYPadControl::OnMouseDown(), IVColorSwatchControl::OnMouseDown(), ICornerResizerControl::OnMouseDown(), ITextEntryControl::OnMouseDown(), IWheelControl::OnMouseDown(), IVNumberBoxControl::OnMouseDown(), ISkLottieControl::OnMouseDown(), TestArcControl::OnMouseDown(), TestCursorControl::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), TestFlexBoxControl::OnMouseDown(), TestImageControl::OnMouseDown(), TestPolyControl::OnMouseDown(), TestSVGControl::OnMouseDown(), IKnobControlBase::OnMouseDown(), ISliderControlBase::OnMouseDown(), IEditableTextControl::OnMouseDown(), IURLControl::OnMouseDown(), IGraphicsLiveEdit::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), ICornerResizerControl::OnMouseOut(), TestCursorControl::OnMouseOut(), IURLControl::OnMouseOut(), ICornerResizerControl::OnMouseOver(), IURLControl::OnMouseOver(), IGraphicsLiveEdit::OnMouseOver(), IVXYPadControl::OnMouseUp(), IVNumberBoxControl::OnMouseUp(), TestArcControl::OnMouseUp(), TestPolyControl::OnMouseUp(), IKnobControlBase::OnMouseUp(), ISliderControlBase::OnMouseUp(), IGraphicsLiveEdit::OnMouseUp(), IGraphicsLiveEdit::OnPopupMenuSelection(), IBButtonControl::OnRescale(), IBSwitchControl::OnRescale(), IBKnobControl::OnRescale(), IBSliderControl::OnRescale(), IBTextControl::OnRescale(), IBMeterControl::OnRescale(), ICornerResizerControl::OnRescale(), IBitmapControl::OnRescale(), TestSizeControl::OnResize(), IGraphicsLiveEdit::OnResize(), PromptUserInput(), ITextControl::SetBoundsBasedOnStr(), SetDirty(), SetValueFromDelegate(), ShowBubbleHorizontalActionFunc(), ShowBubbleVerticalActionFunc(), and SplashClickActionFunc().
GetUI() [2/2]
const IGraphics * IControl::GetUI () const inline
Returns
A const pointer to the IGraphics context that owns this control
Definition at line 466 of file IControl.h.
GetValIdxForPos()
virtual int IControl::GetValIdxForPos (float x, float y) const inline virtual
Check to see which of the control's values relates to this x and y coordinate.
Parameters
x x coordinate to check
y x coordinate to check
Returns
An integer specifying which value matches the x, y coordinates, or kNoValIdx if the position is not linked to a value.
Reimplemented in IVTrackControlBase.
Definition at line 241 of file IControl.h.
Referenced by OnMouseDblClick(), IVKnobControl::OnMouseDblClick(), IVSliderControl::OnMouseDblClick(), IGraphics::OnMouseDown(), and OnMouseDown().
GetValue()
double IControl::GetValue (int valIdx = 0) const
Get the control's value.
Returns
Value of the control, normalized in the range 0-1
Parameters
valIdx The index of the value to set, which should be between 0 and NVals()
Definition at line 153 of file IControl.cpp.
References NVals().
Referenced by ISVGKnobControl::Draw(), ISVGButtonControl::Draw(), ISVGToggleControl::Draw(), ISVGSliderControl::Draw(), IBKnobRotaterControl::Draw(), ILEDControl::Draw(), IWheelControl::Draw(), TestArcControl::Draw(), TestBlendControl::Draw(), TestGradientControl::Draw(), TestLayerControl::Draw(), TestMultiPathControl::Draw(), TestPolyControl::Draw(), TestTextOrientationControl::Draw(), TestTextSizeControl::Draw(), IBitmapBase::DrawBitmap(), IVToggleControl::DrawValue(), IVButtonControl::DrawWidget(), IVToggleControl::DrawWidget(), IVKnobControl::DrawWidget(), IVSliderControl::DrawWidget(), IVRangeSliderControl::DrawWidget(), IVXYPadControl::DrawWidget(), IWheelControl::IWheelControl(), IBSwitchControl::OnMouseDown(), IVMultiSliderControl< MAXNC >::OnMouseDown(), IKnobControlBase::OnMouseDown(), ISliderControlBase::OnMouseDown(), ISwitchControlBase::OnMouseDown(), ITextToggleControl::OnMouseDown(), IVRangeSliderControl::OnMouseDrag(), IWheelControl::OnMouseUp(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), ITextToggleControl::SetDirty(), SetDirty(), SetValueFromDelegate(), SetValueFromUserInput(), IVMultiSliderControl< MAXNC >::SnapToMouse(), and IGraphics::UpdatePeers().
GetWantsGestures()
bool IControl::GetWantsGestures () const inline
Returns
/c true if this control supports multiple gestures
Definition at line 437 of file IControl.h.
Referenced by IGraphics::OnGestureRecognized(), and IGraphics::RespondsToGesture().
GetWantsMidi()
bool IControl::GetWantsMidi () const inline
Returns
/c true if this control wants to know about MIDI messages send to the UI. See OnMIDIMsg()
Definition at line 423 of file IControl.h.
Referenced by IGEditorDelegate::SendMidiMsgFromDelegate().
GetWantsMultiTouch()
bool IControl::GetWantsMultiTouch () const inline
Returns
/c true if this control supports multiple touches
Definition at line 429 of file IControl.h.
Hide()
void IControl::Hide (bool hide) virtual
Shows or hides the IControl.
Parameters
hide Set to true to hide the control
Reimplemented in IContainerBase.
Definition at line 239 of file IControl.cpp.
References SetDirty().
Referenced by IContainerBase::Hide(), IGraphics::HideControl(), and IBubbleControl::IBubbleControl().
IsDirty()
bool IControl::IsDirty () virtual
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
Returns
true if the control is marked dirty.
Reimplemented in IFPSDisplayControl, TestMTControl, and IGraphicsLiveEdit.
Definition at line 231 of file IControl.cpp.
References GetAnimationFunction().
Referenced by TestMTControl::IsDirty(), and IGraphics::IsDirty().
IsDisabled()
bool IControl::IsDisabled () const inline
Returns
true if the control is disabled
Definition at line 358 of file IControl.h.
Referenced by IVLabelControl::Draw(), IVKeyboardControl::Draw(), IGraphicsLiveEdit::Draw(), IVButtonControl::DrawWidget(), IVSwitchControl::DrawWidget(), IVToggleControl::DrawWidget(), IVTabSwitchControl::DrawWidget(), IVRadioButtonControl::DrawWidget(), IVKnobControl::DrawWidget(), IVNumberBoxControl::OnMouseDblClick(), IBMeterControl::OnMsgFromDelegate(), IRTTextControl< MAXNC, T >::OnMsgFromDelegate(), IVDisplayControl::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVPeakAvgMeterControl< MAXNC >::OnMsgFromDelegate(), IVMultiSliderControl< MAXNC >::OnMsgFromDelegate(), and IVScopeControl< MAXNC, MAXBUF >::OnMsgFromDelegate().
IsHidden()
bool IControl::IsHidden () const inline
Returns
true if the control is hidden.
Definition at line 351 of file IControl.h.
Referenced by IGraphicsLiveEdit::Draw(), IGraphics::SetControlBounds(), IGraphics::SetControlPosition(), and IGraphics::SetControlSize().
IsHit()
virtual bool IControl::IsHit (float x, float y) const inline virtual
Hit test the control.
Override this method if you want the control to be hit only if a visible part of it is hit, or whatever.
Parameters
x The X coordinate within the control to test
y The y coordinate within the control to test
Returns
Return true if the control was hit.
Reimplemented in IVButtonControl, IVSwitchControl, IVTabSwitchControl, IVKnobControl, and IVSliderControl.
Definition at line 391 of file IControl.h.
References IRECT::Contains().
LinkedToParam()
int IControl::LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
Parameters
paramIdx The paramIdx to test
Returns
the valIdx if linked, or kNoValIdx if not
Definition at line 132 of file IControl.cpp.
References NVals().
Referenced by IGraphics::ForControlWithParam(), and IGraphics::GetControlWithParamIdx().
NVals()
int IControl::NVals () const inline
Returns
The number of values for this control
Definition at line 235 of file IControl.h.
Referenced by IVRangeSliderControl::DrawWidget(), IVTrackControlBase::DrawWidget(), ForValIdx(), GetParamIdx(), IVTrackControlBase::GetValIdxForPos(), GetValue(), LinkedToParam(), IGraphics::OnMouseDown(), IVRangeSliderControl::OnMouseDrag(), IVRangeSliderControl::OnMouseOver(), IGraphics::OnMouseUp(), IGEditorDelegate::SendParameterValueFromDelegate(), IGraphics::SetControlValueAfterPopupMenu(), SetDirty(), SetParamIdx(), SetValue(), SetValueToDefault(), and IVMultiSliderControl< MAXNC >::SnapToMouse().
OnAttached()
virtual void IControl::OnAttached () inline virtual
Called after the control has been attached, and its delegate and graphics member variable set.
Use this method for controls that might need to attach sub controls that should be above their parent in the stack
Reimplemented in IVPanelControl, IVNumberBoxControl, IVBakedPresetManagerControl, IVDiskPresetManagerControl, IWebViewControl, and IContainerBase.
Definition at line 156 of file IControl.h.
Referenced by IGraphics::AttachControl().
OnContextSelection()
virtual void IControl::OnContextSelection (int itemSelected) inline virtual
Implement this to respond to a menu selection from CreateContextMenu();.
See also
CreateContextMenu()
Definition at line 181 of file IControl.h.
Referenced by IGraphics::SetControlValueAfterPopupMenu().
OnDrop()
virtual void IControl::OnDrop (const char * str) inline virtual
Implement to do something when something was drag 'n dropped onto this control.
Reimplemented in TestDropShadowControl, TestImageControl, and TestSVGControl.
Definition at line 144 of file IControl.h.
Referenced by IGraphics::OnDrop().
OnEndAnimation()
void IControl::OnEndAnimation () virtual
Definition at line 416 of file IControl.cpp.
OnGesture()
bool IControl::OnGesture (const IGestureInfo & info) virtual
Returns
true if supports this gesture
Definition at line 320 of file IControl.cpp.
Referenced by IGraphics::OnGestureRecognized().
OnGUIIdle()
virtual void IControl::OnGUIIdle () inline virtual
This is an idle timer tick call on the GUI thread, only active if USE_IDLE_CALLS is defined.
Definition at line 414 of file IControl.h.
Referenced by IGraphics::OnGUIIdle().
OnInit()
virtual void IControl::OnInit () inline virtual
Called just prior to when the control is attached, after its delegate and graphics member variable set.
Reimplemented in IVSwitchControl, IVTabSwitchControl, IVKnobControl, IVSliderControl, IVGroupControl, IVNumberBoxControl, TestGesturesControl, ISwitchControlBase, ITextControl, and IGraphicsLiveEdit.
Definition at line 153 of file IControl.h.
Referenced by SetDelegate().
OnKeyDown()
virtual bool IControl::OnKeyDown (float x, float y, const IKeyPress & key) inline virtual
Implement this method to respond to a key down event on this control.
Parameters
x The X coordinate of the mouse at the time of this key down event
y The Y coordinate of the mouse at the time of this key down event
key Info about the keypress
Reimplemented in ITextEntryControl, TestKeyboardControl, and IGraphicsLiveEdit.
Definition at line 120 of file IControl.h.
Referenced by IGraphics::OnKeyDown().
OnKeyUp()
virtual bool IControl::OnKeyUp (float x, float y, const IKeyPress & key) inline virtual
Implement this method to respond to a key up event on this control.
Parameters
x The X coordinate of the mouse at the time of this key down event
y The Y coordinate of the mouse at the time of this key down event
key Info about the keypress
Definition at line 126 of file IControl.h.
Referenced by IGraphics::OnKeyUp().
OnMidi()
virtual void IControl::OnMidi (const IMidiMsg & msg) inline virtual
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
Reimplemented in IVKeyboardControl, and IWheelControl.
Definition at line 162 of file IControl.h.
Referenced by IGEditorDelegate::SendMidiMsgFromDelegate().
OnMouseDblClick()
void IControl::OnMouseDblClick (float x, float y, const IMouseMod & mod) virtual
Implement this method to respond to a mouse double click event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IVKnobControl, IVSliderControl, ICornerResizerControl, ITextEntryControl, IVNumberBoxControl, TestTextControl, PlaceHolder, and IGraphicsLiveEdit.
Definition at line 258 of file IControl.cpp.
References GetValIdxForPos(), PromptUserInput(), and SetValueToDefault().
Referenced by IGraphics::OnMouseDblClick().
OnMouseDown()
void IControl::OnMouseDown (float x, float y, const IMouseMod & mod) virtual
Implement this method to respond to a mouse down event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IColorPickerControl, IVTabSwitchControl, IVKnobControl, IVSliderControl, IVRangeSliderControl, IVXYPadControl, IVColorSwatchControl, IBSwitchControl, ICornerResizerControl, IFPSDisplayControl, IPopupMenuControl, IShaderControl, ITextEntryControl, IVKeyboardControl, IWheelControl, IVMultiSliderControl< MAXNC >, IVMultiSliderControl< 1 >, IVNumberBoxControl, ISkLottieControl, TestAnimationControl, TestArcControl, TestBezierControl, TestCursorControl, TestDirBrowseControl, TestFlexBoxControl, TestFontControl, TestGradientControl, TestImageControl, TestKeyboardControl, TestLayerControl, TestMultiPathControl, TestMTControl, TestPolyControl, TestSVGControl, TestTextControl, TestTextOrientationControl, TestTextSizeControl, IKnobControlBase, ISliderControlBase, IButtonControlBase, ISwitchControlBase, ILambdaControl, IEditableTextControl, IURLControl, ITextToggleControl, ICaptionControl, and IGraphicsLiveEdit.
Definition at line 252 of file IControl.cpp.
References GetValIdxForPos(), and PromptUserInput().
Referenced by IGraphics::OnMouseDown(), IPopupMenuControl::OnMouseDown(), IKnobControlBase::OnMouseDown(), and ISliderControlBase::OnMouseDown().
OnMouseDrag()
virtual void IControl::OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod & mod) inline virtual
Implement this method to respond to a mouse drag event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
dX The X delta (difference) since the last event
dY The Y delta (difference) since the last event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IVRangeSliderControl, IVXYPadControl, IPopupMenuControl, IShaderControl, ITextEntryControl, IVKeyboardControl, IVMultiSliderControl< MAXNC >, IVMultiSliderControl< 1 >, IVNumberBoxControl, TestMTControl, TestTextOrientationControl, TestTextSizeControl, IKnobControlBase, ISliderControlBase, ILambdaControl, IGraphicsLiveEdit, and TestBezierControl.
Definition at line 101 of file IControl.h.
Referenced by IGraphics::OnMouseDrag().
OnMouseOut()
void IControl::OnMouseOut () virtual
Implement this method to respond to a mouseout event on this control.
Implementations should call base class, if you wish to use mMouseIsOver.
Reimplemented in IVSwitchControl, IVTabSwitchControl, IVKnobControl, IVSliderControl, IVRangeSliderControl, IVColorSwatchControl, ICornerResizerControl, IPopupMenuControl, IVKeyboardControl, TestCursorControl, IVTrackControlBase, and IURLControl.
Definition at line 275 of file IControl.cpp.
References mMouseIsOver, and SetDirty().
Referenced by IGraphics::OnMouseOut(), IVSwitchControl::OnMouseOut(), IVTabSwitchControl::OnMouseOut(), IVKnobControl::OnMouseOut(), IVSliderControl::OnMouseOut(), ICornerResizerControl::OnMouseOut(), TestCursorControl::OnMouseOut(), IURLControl::OnMouseOut(), and IGraphics::OnMouseOver().
OnMouseOver()
void IControl::OnMouseOver (float x, float y, const IMouseMod & mod) virtual
Implement this method to respond to a mouseover event on this control.
Implementations should call base class, if you wish to use mMouseIsOver.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IVTabSwitchControl, IVKnobControl, IVSliderControl, IVRangeSliderControl, IVColorSwatchControl, ICornerResizerControl, IPopupMenuControl, IVKeyboardControl, TestBezierControl, IVTrackControlBase, IURLControl, and IGraphicsLiveEdit.
Definition at line 267 of file IControl.cpp.
References mMouseIsOver, and SetDirty().
Referenced by IGraphics::OnMouseOver(), IVTabSwitchControl::OnMouseOver(), IVKnobControl::OnMouseOver(), IVSliderControl::OnMouseOver(), ICornerResizerControl::OnMouseOver(), and IURLControl::OnMouseOver().
OnMouseUp()
virtual void IControl::OnMouseUp (float x, float y, const IMouseMod & mod) inline virtual
Implement this method to respond to a mouse up event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IVKnobControl, IVSliderControl, IVRangeSliderControl, IVXYPadControl, IShaderControl, ITextEntryControl, IVKeyboardControl, IWheelControl, IVNumberBoxControl, TestArcControl, TestBezierControl, TestKeyboardControl, TestMTControl, TestPolyControl, TestTextOrientationControl, TestTextSizeControl, IKnobControlBase, ISliderControlBase, ISwitchControlBase, ILambdaControl, and IGraphicsLiveEdit.
Definition at line 93 of file IControl.h.
Referenced by IGraphics::OnMouseUp().
OnMouseWheel()
virtual void IControl::OnMouseWheel (float x, float y, const IMouseMod & mod, float d) inline virtual
Implement this method to respond to a mouse wheel event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
d The delta value (difference) since the last mouse wheel event
Reimplemented in IPopupMenuControl, IWheelControl, IVNumberBoxControl, IKnobControlBase, and ISliderControlBase.
Definition at line 114 of file IControl.h.
Referenced by IGraphics::OnMouseWheel().
OnMsgFromDelegate()
virtual void IControl::OnMsgFromDelegate (int msgTag, int dataSize, const void * pData) inline virtual
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
Reimplemented in IBMeterControl, IRTTextControl< MAXNC, T >, IVDisplayControl, IVMeterControl< MAXNC >, IVMeterControl< MAXNC >, IVMeterControl< 1 >, IVPeakAvgMeterControl< MAXNC >, IVPeakAvgMeterControl< 1 >, IVMultiSliderControl< MAXNC >, IVMultiSliderControl< 1 >, and IVScopeControl< MAXNC, MAXBUF >.
Definition at line 159 of file IControl.h.
Referenced by IGEditorDelegate::SendControlMsgFromDelegate().
OnPopupMenuSelection()
void IControl::OnPopupMenuSelection (IPopupMenu * pSelectedMenu, int valIdx) virtual
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControlPromptUserInput.
Parameters
pSelectedMenu If pSelectedMenu is invalid it means the user didn't select anything
valIdx An index that indicates which of the control's vals the menu relates to
Reimplemented in TestDirBrowseControl, IVBakedPresetManagerControl, IVDiskPresetManagerControl, IGraphicsLiveEdit, IWheelControl, and TestFlexBoxControl.
Definition at line 283 of file IControl.cpp.
References GetParam(), GetParamIdx(), and SetValueFromUserInput().
Referenced by IGraphics::SetControlValueAfterPopupMenu().
OnRescale()
virtual void IControl::OnRescale () inline virtual
Implement to do something when graphics is scaled globally (e.g.
moves to different DPI screen)
Reimplemented in IBButtonControl, IBSwitchControl, IBKnobControl, IBSliderControl, IBTextControl, IBMeterControl, ICornerResizerControl, IWebViewControl, TestSizeControl, and IBitmapControl.
Definition at line 147 of file IControl.h.
Referenced by SetDelegate(), and IGraphics::SetScreenScale().
OnResize()
virtual void IControl::OnResize () inline virtual
Called when IControl is constructed or resized using SetRect().
NOTE: if you call SetDirty() in this method, you should call SetDirty(false) to avoid triggering parameter changes
Reimplemented in IVButtonControl, IVSwitchControl, IVSlideSwitchControl, IVTabSwitchControl, IVKnobControl, IVSliderControl, IVXYPadControl, IVPlotControl, IVGroupControl, IVPanelControl, IVColorSwatchControl, ISVGSliderControl, IBSliderControl, IShaderControl, IVDisplayControl, IVKeyboardControl, IVNumberBoxControl, IVBakedPresetManagerControl, IVScopeControl< MAXNC, MAXBUF >, IWebViewControl, TestColorControl, TestDirBrowseControl, TestFlexBoxControl, TestGradientControl, TestSizeControl, IContainerBase, ISliderControlBase, IVTrackControlBase, ICaptionControl, PlaceHolder, and IGraphicsLiveEdit.
Definition at line 150 of file IControl.h.
Referenced by IGraphics::Resize(), SetDelegate(), SetRECT(), and SetTargetAndDrawRECTs().
OnTextEntryCompletion()
virtual void IControl::OnTextEntryCompletion (const char * str, int valIdx) inline virtual
Implement this method to handle text input after IGraphics::CreateTextEntry/IControlPromptUserInput.
Parameters
str A CString with the inputted text
valIdx An index that indicates which of the control's values the text completion relates to
Reimplemented in IVNumberBoxControl, IEditableTextControl, and PlaceHolder.
Definition at line 178 of file IControl.h.
Referenced by IGraphics::SetControlValueAfterTextEdit().
OnTouchCancelled()
virtual void IControl::OnTouchCancelled (float x, float y, const IMouseMod & mod) inline virtual
Implement this method to respond to a touch cancel event on this control.
Parameters
x The X coordinate of the mouse event
y The Y coordinate of the mouse event
mod A struct indicating which modifier keys are held for the event
Reimplemented in IVKeyboardControl, and TestMTControl.
Definition at line 141 of file IControl.h.
Referenced by IGraphics::OnTouchCancelled().
PromptUserInput() [1/2]
void IControl::PromptUserInput (const IRECT & bounds, int valIdx = 0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter) specifying the bounds.
Parameters
bounds The rectangle for the text entry. Pop-up menu's will appear below the rectangle.
valIdx An index to choose which of the control's linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Definition at line 357 of file IControl.cpp.
References GetParamIdx(), GetUI(), and IGraphics::PromptUserInput().
PromptUserInput() [2/2]
void IControl::PromptUserInput (int valIdx = 0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
Parameters
valIdx An index to choose which of the control's linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Definition at line 334 of file IControl.cpp.
References GetParam(), GetParamIdx(), GetUI(), IRECT::MH(), IRECT::MW(), IGraphics::PromptUserInput(), and SetDirty().
Referenced by OnMouseDblClick(), IVKnobControl::OnMouseDblClick(), IVSliderControl::OnMouseDblClick(), OnMouseDown(), IVKnobControl::OnMouseDown(), IVSliderControl::OnMouseDown(), and ICaptionControl::OnMouseDown().
SetActionFunction()
IControl * IControl::SetActionFunction (IActionFunction actionFunc) inline
Set an Action Function for this control.
Parameters
actionFunc A std::function conforming to IActionFunction
Returns
Ptr to this control, for chaining
Definition at line 203 of file IControl.h.
Referenced by IBubbleControl::IBubbleControl(), IPopupMenuControl::IPopupMenuControl(), and IWheelControl::IWheelControl().
SetAnimation() [1/2]
void IControl::SetAnimation (IAnimationFunction func) inline
Set the animation function.
Parameters
func A std::function conforming to IAnimationFunction
Definition at line 488 of file IControl.h.
Referenced by DefaultClickActionFunc(), IBubbleControl::IBubbleControl(), IPopupMenuControl::IPopupMenuControl(), ILambdaControl::OnMouseDown(), IWheelControl::OnMouseUp(), and SplashClickActionFunc().
SetAnimation() [2/2]
void IControl::SetAnimation (IAnimationFunction func, int duration) inline
Set the animation function and starts it.
Parameters
func A std::function conforming to IAnimationFunction
duration Duration in milliseconds for the animation
Definition at line 493 of file IControl.h.
References StartAnimation().
SetAnimationEndActionFunction()
IControl * IControl::SetAnimationEndActionFunction (IActionFunction actionFunc) inline
Set an Action Function to be called at the end of an animation.
Parameters
actionFunc A std::function conforming to IActionFunction
Returns
Ptr to this control, for chaining
Definition at line 208 of file IControl.h.
Referenced by IBubbleControl::IBubbleControl(), IVNumberBoxControl::OnAttached(), IVBakedPresetManagerControl::OnAttached(), and IVDiskPresetManagerControl::OnAttached().
SetBlend()
void IControl::SetBlend (const IBlend & blend) inline
Set the Blend for this control.
This can be used differently by different controls, or not at all. By default it is used to change the opacity of controls when they are disabled
Definition at line 292 of file IControl.h.
SetClean()
virtual void IControl::SetClean () inline virtual
Definition at line 400 of file IControl.h.
SetDelegate()
void IControl::SetDelegate (IGEditorDelegate & dlg) inline
Used internally to set the mDelegate (and mGraphics) variables.
Definition at line 448 of file IControl.h.
References IGEditorDelegate::GetUI(), OnInit(), OnRescale(), and OnResize().
Referenced by IGraphics::AttachBackground(), IGraphics::AttachBubbleControl(), IGraphics::AttachControl(), IGraphics::AttachPanelBackground(), and IGraphics::AttachSVGBackground().
SetDirty()
void IControl::SetDirty (bool triggerAction = true, int valIdx = kNoValIdx) virtual
Mark the control as dirty, i.e.
it should be redrawn on the next display refresh
Parameters
triggerAction If this is true and the control is linked to a parameter notify the class implementing the IEditorDelegate interface that the parameter changed. If this control has an ActionFunction, that can also be triggered. NOTE: it is easy to forget that this method always sets the control dirty, the argument refers to whether a consecutive action should be performed
Reimplemented in ITextToggleControl, IVSwitchControl, IVSlideSwitchControl, IVKnobControl, and IVSliderControl.
Definition at line 198 of file IControl.cpp.
References Clip(), ForValIdx(), GetDelegate(), GetParamIdx(), GetUI(), GetValue(), NVals(), IEditorDelegate::SendParameterValueFromUI(), SetValue(), and IGraphics::UpdatePeers().
Referenced by IVPlotControl::AddPlotFunc(), IPopupMenuControl::CalculateMenuPanels(), IGraphics::CreateTextEntry(), Hide(), IBubbleControl::IBubbleControl(), TestDropShadowControl::OnDrop(), TestSVGControl::OnDrop(), TestGesturesControl::OnInit(), IVKeyboardControl::OnMidi(), IWheelControl::OnMidi(), TestTextControl::OnMouseDblClick(), IVTabSwitchControl::OnMouseDown(), IBSwitchControl::OnMouseDown(), IVKeyboardControl::OnMouseDown(), IVMultiSliderControl< MAXNC >::OnMouseDown(), ISkLottieControl::OnMouseDown(), TestAnimationControl::OnMouseDown(), TestCursorControl::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), TestFontControl::OnMouseDown(), TestGradientControl::OnMouseDown(), TestLayerControl::OnMouseDown(), TestMultiPathControl::OnMouseDown(), TestSVGControl::OnMouseDown(), TestTextControl::OnMouseDown(), IButtonControlBase::OnMouseDown(), ISwitchControlBase::OnMouseDown(), IVXYPadControl::OnMouseDrag(), IPopupMenuControl::OnMouseDrag(), IShaderControl::OnMouseDrag(), IVKeyboardControl::OnMouseDrag(), TestMTControl::OnMouseDrag(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), ILambdaControl::OnMouseDrag(), TestBezierControl::OnMouseDrag(), OnMouseOut(), IVTabSwitchControl::OnMouseOut(), IVColorSwatchControl::OnMouseOut(), IVKeyboardControl::OnMouseOut(), IVTrackControlBase::OnMouseOut(), OnMouseOver(), IVTabSwitchControl::OnMouseOver(), IVRangeSliderControl::OnMouseOver(), IVColorSwatchControl::OnMouseOver(), IPopupMenuControl::OnMouseOver(), IVKeyboardControl::OnMouseOver(), TestBezierControl::OnMouseOver(), IVTrackControlBase::OnMouseOver(), IVXYPadControl::OnMouseUp(), IShaderControl::OnMouseUp(), ITextEntryControl::OnMouseUp(), IVKeyboardControl::OnMouseUp(), IVNumberBoxControl::OnMouseUp(), TestMTControl::OnMouseUp(), TestTextOrientationControl::OnMouseUp(), TestTextSizeControl::OnMouseUp(), IKnobControlBase::OnMouseUp(), ISliderControlBase::OnMouseUp(), ISwitchControlBase::OnMouseUp(), ILambdaControl::OnMouseUp(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), IBMeterControl::OnMsgFromDelegate(), IRTTextControl< MAXNC, T >::OnMsgFromDelegate(), IVDisplayControl::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVPeakAvgMeterControl< MAXNC >::OnMsgFromDelegate(), IVScopeControl< MAXNC, MAXBUF >::OnMsgFromDelegate(), TestDirBrowseControl::OnPopupMenuSelection(), TestFlexBoxControl::OnPopupMenuSelection(), IVButtonControl::OnResize(), IVTabSwitchControl::OnResize(), IVXYPadControl::OnResize(), IVPlotControl::OnResize(), IVGroupControl::OnResize(), IVColorSwatchControl::OnResize(), ISVGSliderControl::OnResize(), IBSliderControl::OnResize(), IVDisplayControl::OnResize(), IVKeyboardControl::OnResize(), IVScopeControl< MAXNC, MAXBUF >::OnResize(), ISliderControlBase::OnResize(), IVTrackControlBase::OnResize(), IEditableTextControl::OnTextEntryCompletion(), IVKeyboardControl::OnTouchCancelled(), PromptUserInput(), IGraphics::SetAllControlsDirty(), IURLControl::SetCLColor(), IVectorBase::SetColor(), ITextToggleControl::SetDirty(), IVSwitchControl::SetDirty(), IVKnobControl::SetDirty(), IVSliderControl::SetDirty(), SetDisabled(), IURLControl::SetMOColor(), SetParamIdx(), SetPTParameterHighlight(), ITextControl::SetStr(), ITextControl::SetStrFmt(), SetValueFromDelegate(), SetValueFromUserInput(), SetValueToDefault(), SnapToMouse(), IVMultiSliderControl< MAXNC >::SnapToMouse(), and SplashAnimationFunc().
SetDisabled()
void IControl::SetDisabled (bool disable) virtual
Sets disabled mode for the control, the default implementation modifies the mBlend member.
Parameters
disable true for disabled
Reimplemented in IContainerBase.
Definition at line 245 of file IControl.cpp.
References SetDirty().
Referenced by IGraphics::DisableControl(), and IContainerBase::SetDisabled().
SetGroup()
void IControl::SetGroup (const char * groupName) inline
Assign the control to a control group.
See also
Control Groups
Parameters
groupName A CString indicating the control group that this control should belong to
Definition at line 276 of file IControl.h.
References mGroup.
Referenced by IGraphics::AttachControl().
SetIgnoreMouse()
void IControl::SetIgnoreMouse (bool ignore) inline
Specify whether the control should respond to mouse events.
Parameters
ignore true if it should ignore mouse events
Definition at line 379 of file IControl.h.
SetMouseEventsWhenDisabled()
void IControl::SetMouseEventsWhenDisabled (bool allow) inline
Specify whether the control should respond to other mouse events when disabled.
Parameters
allow true if it should respond to other mouse events when disabled (false by default)
Definition at line 366 of file IControl.h.
SetMouseOverWhenDisabled()
void IControl::SetMouseOverWhenDisabled (bool allow) inline
Specify whether the control should respond to mouse overs when disabled.
Parameters
allow true if it should respond to mouse overs when disabled (false by default)
Definition at line 362 of file IControl.h.
SetNVals()
void IControl::SetNVals (int nVals) inline protected
Definition at line 562 of file IControl.h.
SetParamIdx()
void IControl::SetParamIdx (int paramIdx, int valIdx = 0) virtual
Set the index of a parameter that the control is linked to If you are calling this "manually" to reuse a control for multiple parameters, you probably want to call IEditorDelegate::SendCurrentParamValuesFromDelegate() afterward, to update the control values.
Parameters
paramIdx Parameter index, or kNoParameter if there is no parameter linked with this control at valIdx
valIdx An index to choose which of the control's values to set
Definition at line 115 of file IControl.cpp.
References NVals(), and SetDirty().
Referenced by ICaptionControl::ICaptionControl(), and IVTrackControlBase::SetParams().
SetParent()
void IControl::SetParent (IContainerBase * pParent) inline
Definition at line 460 of file IControl.h.
SetPosition()
void IControl::SetPosition (float x, float y) virtual
Set the position of the control, preserving the width and height.
This may need to be overriden if you maintain custom positioning data in your control
Parameters
x the new x coordinate of the top left corner of the control
y the new y coordinate of the top left corner of the control
Definition at line 291 of file IControl.cpp.
References IRECT::H(), IRECT::L, SetRECT(), SetTargetRECT(), IRECT::T, and IRECT::W().
Referenced by IGraphics::SetControlPosition().
SetPromptShowsParamLabel()
void IControl::SetPromptShowsParamLabel (bool enable) inline
Set if the control should show parameter labels/units e.g.
"Hz" in text entry prompts
Definition at line 385 of file IControl.h.
SetPTParameterHighlight()
void IControl::SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
Parameters
isHighlighted /c true if the control should be highlighted
color An integer representing one of three colors that ProTools assigns automated controls
Definition at line 365 of file IControl.cpp.
References SetDirty().
Referenced by IGraphics::SetPTParameterHighlight().
SetRECT()
void IControl::SetRECT (const IRECT & bounds) inline
Set the rectangular draw area for this control, within the graphics context.
Parameters
bounds The control's bounds
Definition at line 311 of file IControl.h.
References mMouseIsOver, and OnResize().
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphicsLiveEdit::OnMouseUp(), and SetPosition().
SetSize()
void IControl::SetSize (float w, float h) virtual
Set the size of the control, preserving the current position.
This may need to be overriden if you maintain custom positioning data in your control, or if your TargetRECT is not the same as the main RECT.
Parameters
w the new width of the control
h the new height of the control
Definition at line 303 of file IControl.cpp.
References IRECT::L, SetTargetAndDrawRECTs(), and IRECT::T.
Referenced by IGraphics::SetControlSize().
SetTargetAndDrawRECTs()
void IControl::SetTargetAndDrawRECTs (const IRECT & bounds) inline
Set BOTH the draw rect and the target area, within the graphics context for this control.
Parameters
bounds The control's new draw and target bounds within the graphics context
Definition at line 323 of file IControl.h.
References mMouseIsOver, and OnResize().
Referenced by ICornerResizerControl::OnRescale(), IVNumberBoxControl::OnResize(), IVBakedPresetManagerControl::OnResize(), IBubbleControl::ResetBounds(), ITextControl::SetBoundsBasedOnStr(), IGraphics::SetControlBounds(), and SetSize().
SetTargetRECT()
void IControl::SetTargetRECT (const IRECT & bounds) inline
Set the rectangular mouse tracking target area, within the graphics context for this control.
Parameters
bounds The control's new target bounds within the graphics context
Definition at line 319 of file IControl.h.
References mMouseIsOver.
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphicsLiveEdit::OnMouseUp(), IVButtonControl::OnResize(), IVSwitchControl::OnResize(), IVTabSwitchControl::OnResize(), IVKnobControl::OnResize(), IVSliderControl::OnResize(), IVXYPadControl::OnResize(), IVPlotControl::OnResize(), IVGroupControl::OnResize(), IVPanelControl::OnResize(), IVColorSwatchControl::OnResize(), IVDisplayControl::OnResize(), IVNumberBoxControl::OnResize(), IVScopeControl< MAXNC, MAXBUF >::OnResize(), ISliderControlBase::OnResize(), IVTrackControlBase::OnResize(), IGraphicsLiveEdit::OnResize(), and SetPosition().
SetText()
virtual void IControl::SetText (const IText & txt) inline virtual
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
Parameters
txt An IText struct with the desired formatting
Reimplemented in IURLControl.
Definition at line 288 of file IControl.h.
SetTextEntryLength()
void IControl::SetTextEntryLength (int len) inline
Set the max number of characters that are allowed in text entry.
Parameters
len The max number of characters allowed in text entry
Definition at line 303 of file IControl.h.
SetTooltip()
void IControl::SetTooltip (const char * str) inline
Set a tooltip for the control.
Parameters
str CString tooltip to be displayed
Definition at line 212 of file IControl.h.
SetValue()
void IControl::SetValue (double value, int valIdx = 0) virtual
Set one of the control's values.
Parameters
value The normalized 0-1 value
valIdx The index of the value to set, which should be between 0 and NVals()
Definition at line 147 of file IControl.cpp.
References NVals().
Referenced by IWheelControl::IWheelControl(), IWheelControl::OnMidi(), IVTabSwitchControl::OnMouseDown(), IBSwitchControl::OnMouseDown(), IVMultiSliderControl< MAXNC >::OnMouseDown(), IButtonControlBase::OnMouseDown(), ISwitchControlBase::OnMouseDown(), ITextToggleControl::OnMouseDown(), IVXYPadControl::OnMouseDrag(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IWheelControl::OnMouseUp(), IKnobControlBase::OnMouseWheel(), ISliderControlBase::OnMouseWheel(), IBMeterControl::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVPeakAvgMeterControl< MAXNC >::OnMsgFromDelegate(), SetDirty(), SetValueFromDelegate(), SetValueFromUserInput(), SetValueToDefault(), SnapToMouse(), and IVMultiSliderControl< MAXNC >::SnapToMouse().
SetValueFromDelegate()
void IControl::SetValueFromDelegate (double value, int valIdx = 0) virtual
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
Parameters
value Normalised incoming value
valIdx The index of the value to set, which should be between 0 and NVals()
Reimplemented in IVNumberBoxControl.
Definition at line 159 of file IControl.cpp.
References GetUI(), GetValue(), SetDirty(), and SetValue().
Referenced by IGEditorDelegate::SendControlValueFromDelegate(), IGEditorDelegate::SendParameterValueFromDelegate(), and IVNumberBoxControl::SetValueFromDelegate().
SetValueFromUserInput()
void IControl::SetValueFromUserInput (double value, int valIdx = 0) virtual
Set the control's value after user input.
This method is called after a text entry or popup menu prompt triggered by PromptUserInput(), calling SetDirty(true), which will mean that the new value gets sent back to the delegate
Parameters
value the normalised value after user input via text entry or pop-up menu
valIdx An index to choose which of the control's linked parameters to retrieve. NOTE: since controls usually have only 1 parameter you can omit this argument and use the default index of 0
Reimplemented in IVNumberBoxControl.
Definition at line 174 of file IControl.cpp.
References GetValue(), SetDirty(), and SetValue().
Referenced by OnPopupMenuSelection(), IGraphics::SetControlValueAfterTextEdit(), and IVNumberBoxControl::SetValueFromUserInput().
SetValueToDefault()
void IControl::SetValueToDefault (int valIdx = kNoValIdx) virtual
Set one or all of the control's values to the default value of the associated parameter.
Parameters
valIdx either an integer > -1 (kNoValIdx) in order to set an individual value to the default value of the associated parameter, or kNoValIdx to default all values This method will call through to SetDirty(true, valIdx), which will mean that the new value gets sent back to the delegate
Definition at line 183 of file IControl.cpp.
References ForValIdx(), IParam::GetDefault(), GetParam(), NVals(), SetDirty(), and SetValue().
Referenced by OnMouseDblClick(), IVKnobControl::OnMouseDblClick(), and IVSliderControl::OnMouseDblClick().
SetWantsMidi()
void IControl::SetWantsMidi (bool enable = true) inline
Specify whether this control wants to know about MIDI messages sent to the UI.
See OnMIDIMsg()
Definition at line 420 of file IControl.h.
Referenced by IWheelControl::IWheelControl().
SetWantsMultiTouch()
void IControl::SetWantsMultiTouch (bool enable = true) inline
Specify whether this control supports multiple touches.
Definition at line 426 of file IControl.h.
SnapToMouse()
void IControl::SnapToMouse (float x, float y, EDirection direction, const IRECT & bounds, int valIdx = -1, double minClip = 0., double maxClip = 1.) virtual
Set control value based on x, y position within a rectangle.
Commonly used for slider/fader controls.
Parameters
x The X coordinate for snapping
y The Y coordinate for snapping
direction The direction of the control's travel- horizontal or vertical fader
bounds The area in which the track of e.g. a slider should be snapped
valIdx The value that the current mouse gesture should snap
Reimplemented in IVMultiSliderControl< MAXNC >, and IVMultiSliderControl< 1 >.
Definition at line 397 of file IControl.cpp.
References Clip(), IRECT::Constrain(), ForValIdx(), IRECT::H(), IRECT::L, SetDirty(), SetValue(), IRECT::T, and IRECT::W().
Referenced by ISliderControlBase::OnMouseDown(), IVRangeSliderControl::OnMouseDrag(), and ISliderControlBase::OnMouseDrag().
StartAnimation()
void IControl::StartAnimation (int duration)
Parameters
duration Duration in milliseconds for the animation
Definition at line 425 of file IControl.cpp.
Referenced by SetAnimation().
Member Data Documentation
mBlend
IBlend IControl::mBlend protected
Definition at line 542 of file IControl.h.
mDblAsSingleClick
bool IControl::mDblAsSingleClick = false protected
Definition at line 548 of file IControl.h.
mDirty
bool IControl::mDirty = true protected
Definition at line 544 of file IControl.h.
mDisabled
bool IControl::mDisabled = false protected
Definition at line 546 of file IControl.h.
mDisablePrompt
bool IControl::mDisablePrompt = true protected
Definition at line 547 of file IControl.h.
mGroup
WDL_String IControl::mGroup protected
Controls can be grouped for hiding and showing panels.
Definition at line 539 of file IControl.h.
Referenced by GetGroup(), and SetGroup().
mHide
bool IControl::mHide = false protected
Definition at line 545 of file IControl.h.
mIgnoreMouse
bool IControl::mIgnoreMouse = false protected
Definition at line 551 of file IControl.h.
mMouseEventsWhenDisabled
bool IControl::mMouseEventsWhenDisabled = false protected
Definition at line 550 of file IControl.h.
mMouseIsOver
bool IControl::mMouseIsOver = false protected
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
If you need finer grained control of mouseovers, you can override OnMouseOver() and OnMouseOut()
Definition at line 556 of file IControl.h.
Referenced by IVPanelControl::Draw(), ISVGButtonControl::Draw(), ISVGToggleControl::Draw(), IVNumberBoxControl::Draw(), TestAnimationControl::Draw(), TestCursorControl::Draw(), TestDirBrowseControl::Draw(), TestImageControl::Draw(), TestSVGControl::Draw(), IURLControl::Draw(), ICaptionControl::Draw(), IVButtonControl::DrawWidget(), IVSwitchControl::DrawWidget(), IVToggleControl::DrawWidget(), IVKnobControl::DrawWidget(), GetMouseIsOver(), OnMouseOut(), OnMouseOver(), SetRECT(), SetTargetAndDrawRECTs(), and SetTargetRECT().
mMouseOverWhenDisabled
bool IControl::mMouseOverWhenDisabled = false protected
Definition at line 549 of file IControl.h.
mPromptShowsParamLabel
bool IControl::mPromptShowsParamLabel = false protected
Definition at line 554 of file IControl.h.
mPTHighlightColor
IColor IControl::mPTHighlightColor = COLOR_RED protected
Definition at line 559 of file IControl.h.
mPTisHighlighted
bool IControl::mPTisHighlighted = false protected
Definition at line 560 of file IControl.h.
mRECT
IRECT IControl::mRECT protected
Definition at line 535 of file IControl.h.
mTargetRECT
IRECT IControl::mTargetRECT protected
Definition at line 536 of file IControl.h.
mText
IText IControl::mText protected
Definition at line 541 of file IControl.h.
mTextEntryLength
int IControl::mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN protected
Definition at line 543 of file IControl.h.
mTooltip
WDL_String IControl::mTooltip protected
Definition at line 557 of file IControl.h.
mWantsMidi
bool IControl::mWantsMidi = false protected
Definition at line 552 of file IControl.h.
mWantsMultiTouch
bool IControl::mWantsMultiTouch = false protected
Definition at line 553 of file IControl.h.
The documentation for this class was generated from the following files:
IControl.h
IControl.cpp