iPlug 2: IVSlideSwitchControl Class Reference
IVSlideSwitchControl Class Reference
IGraphics::IControls
A switch with a slide animation when clicked.
#include <IControls.h>
Public Member Functions
IVSlideSwitchControl (const IRECT &bounds, int paramIdx=kNoParameter, const char *label="", const IVStyle &style=DEFAULT_STYLE, bool valueInButton=false, EDirection direction=EDirection::Horizontal)
IVSlideSwitchControl (const IRECT &bounds, IActionFunction aF=EmptyClickActionFunc, const char *label="", const IVStyle &style=DEFAULT_STYLE, bool valueInButton=false, EDirection direction=EDirection::Horizontal, int numStates=2, int initialState=0)
void Draw (IGraphics &g) override
Draw the control to the graphics context.
virtual void DrawWidget (IGraphics &g) override
Draw the IVControl main widget (override)
virtual void DrawHandle (IGraphics &g, const IRECT &filledArea)
virtual void DrawTrack (IGraphics &g, const IRECT &filledArea)
void OnResize () override
Called when IControl is constructed or resized using SetRect().
void OnEndAnimation () override
void SetDirty (bool push, int valIdx=kNoValIdx) override
Mark the control as dirty, i.e.
Public Member Functions inherited from IVSwitchControl
IVSwitchControl (const IRECT &bounds, int paramIdx=kNoParameter, const char *label="", const IVStyle &style=DEFAULT_STYLE, bool valueInButton=true)
IVSwitchControl (const IRECT &bounds, IActionFunction aF=SplashClickActionFunc, const char *label="", const IVStyle &style=DEFAULT_STYLE, int numStates=2, bool valueInButton=true)
void Draw (IGraphics &g) override
Draw the control to the graphics context.
virtual void DrawWidget (IGraphics &g) override
Draw the IVControl main widget (override)
void OnMouseOut () override
Implement this method to respond to a mouseout event on this control.
bool IsHit (float x, float y) const override
Hit test the control.
void SetDirty (bool push, int valIdx=kNoValIdx) override
Mark the control as dirty, i.e.
void OnResize () override
Called when IControl is constructed or resized using SetRect().
void OnInit () override
Called just prior to when the control is attached, after its delegate and graphics member variable set.
Public Member Functions inherited from ISwitchControlBase
ISwitchControlBase (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction aF=nullptr, int numStates=2)
void OnInit () override
Called just prior to when the control is attached, after its delegate and graphics member variable set.
void OnMouseDown (float x, float y, const IMouseMod &mod) override
Implement this method to respond to a mouse down event on this control.
void OnMouseUp (float x, float y, const IMouseMod &mod) override
Implement this method to respond to a mouse up event on this control.
int GetSelectedIdx () const
void SetStateDisabled (int stateIdx, bool disabled)
void SetAllStatesDisabled (bool disabled)
bool GetStateDisabled (int stateIdx) const
Public Member Functions inherited from IControl
IControl (const IRECT &bounds, int paramIdx=kNoParameter, IActionFunction actionFunc=nullptr)
Constructor.
IControl (const IRECT &bounds, const std::initializer_list< int > &params, IActionFunction actionFunc=nullptr)
Constructor (range of parameters)
IControl (const IRECT &bounds, IActionFunction actionFunc)
Constructor (no paramIdx)
IControl (const IControl &)=delete
void operator= (const IControl &)=delete
virtual ~IControl ()
Destructor.
virtual void OnMouseDown (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse down event on this control.
virtual void OnMouseUp (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse up event on this control.
virtual void OnMouseDrag (float x, float y, float dX, float dY, const IMouseMod &mod)
Implement this method to respond to a mouse drag event on this control.
virtual void OnMouseDblClick (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouse double click event on this control.
virtual void OnMouseWheel (float x, float y, const IMouseMod &mod, float d)
Implement this method to respond to a mouse wheel event on this control.
virtual bool OnKeyDown (float x, float y, const IKeyPress &key)
Implement this method to respond to a key down event on this control.
virtual bool OnKeyUp (float x, float y, const IKeyPress &key)
Implement this method to respond to a key up event on this control.
virtual void OnMouseOver (float x, float y, const IMouseMod &mod)
Implement this method to respond to a mouseover event on this control.
virtual void OnMouseOut ()
Implement this method to respond to a mouseout event on this control.
virtual void OnTouchCancelled (float x, float y, const IMouseMod &mod)
Implement this method to respond to a touch cancel event on this control.
virtual void OnDrop (const char *str)
Implement to do something when something was drag 'n dropped onto this control.
virtual void OnDropMultiple (const std::vector< const char * > &paths)
Implement to handle multiple items drag 'n dropped onto this control.
virtual void OnRescale ()
Implement to do something when graphics is scaled globally (e.g.
virtual void OnResize ()
Called when IControl is constructed or resized using SetRect().
virtual void OnInit ()
Called just prior to when the control is attached, after its delegate and graphics member variable set.
virtual void OnAttached ()
Called after the control has been attached, and its delegate and graphics member variable set.
virtual void OnMsgFromDelegate (int msgTag, int dataSize, const void *pData)
Implement to receive messages sent to the control, see IEditorDelegate:SendControlMsgFromDelegate()
virtual void OnMidi (const IMidiMsg &msg)
Implement to receive MIDI messages sent to the control if mWantsMidi == true, see IEditorDelegate:SendMidiMsgFromDelegate()
virtual bool OnGesture (const IGestureInfo &info)
virtual void CreateContextMenu (IPopupMenu &contextMenu)
Called by default when the user right clicks a control.
virtual void OnPopupMenuSelection (IPopupMenu *pSelectedMenu, int valIdx)
Implement this method to handle popup menu selection after IGraphics::CreatePopupMenu/IControlPromptUserInput.
virtual void OnTextEntryCompletion (const char *str, int valIdx)
Implement this method to handle text input after IGraphics::CreateTextEntry/IControlPromptUserInput.
virtual void OnContextSelection (int itemSelected)
Implement this to respond to a menu selection from CreateContextMenu();.
virtual void Draw (IGraphics &g)=0
Draw the control to the graphics context.
virtual void DrawPTHighlight (IGraphics &g)
Implement this to customise how a colored highlight is drawn on the control in ProTools (AAX format only), when a control is linked to a parameter that is automated.
void PromptUserInput (int valIdx=0)
Call this method in response to a mouse event to create an edit box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter)
void PromptUserInput (const IRECT &bounds, int valIdx=0)
Create a text entry box so the user can enter a value, or pop up a pop-up menu, if the control is linked to a parameter (mParamIdx > kNoParameter) specifying the bounds.
IControl * SetActionFunction (IActionFunction actionFunc)
Set an Action Function for this control.
IControl * SetAnimationEndActionFunction (IActionFunction actionFunc)
Set an Action Function to be called at the end of an animation.
void SetTooltip (const char *str)
Set a tooltip for the control.
const char * GetTooltip () const
int GetParamIdx (int valIdx=0) const
Get the index of a parameter that the control is linked to Normaly controls are either linked to a single parameter or no parameter but some may be linked to multiple parameters.
virtual void SetParamIdx (int paramIdx, int valIdx=0)
Set the index of a parameter that the control is linked to If you are calling this "manually" to reuse a control for multiple parameters, you probably want to call IEditorDelegate::SendCurrentParamValuesFromDelegate() afterward, to update the control values.
int LinkedToParam (int paramIdx) const
Check if the control is linked to a particular parameter.
int NVals () const
virtual int GetValIdxForPos (float x, float y) const
Check to see which of the control's values relates to this x and y coordinate.
const IParam * GetParam (int valIdx=0) const
Get a const pointer to the IParam object (owned by the editor delegate class), associated with this control.
virtual void SetValueFromDelegate (double value, int valIdx=0)
Set the control's value from the delegate This method is called from the class implementing the IEditorDelegate interface in order to update a control's value members and set it to be marked dirty for redraw.
virtual void SetValueFromUserInput (double value, int valIdx=0)
Set the control's value after user input.
virtual void SetValueToDefault (int valIdx=kNoValIdx)
Set one or all of the control's values to the default value of the associated parameter.
virtual void SetValue (double value, int valIdx=0)
Set one of the control's values.
double GetValue (int valIdx=0) const
Get the control's value.
void SetGroup (const char *groupName)
Assign the control to a control group.
const char * GetGroup () const
Get the group that the control belongs to, if any.
const IText & GetText () const
Get the Text object for the control.
virtual void SetText (const IText &txt)
Set the Text object typically used to determine font/layout/size etc of the main text in a control.
void SetBlend (const IBlend &blend)
Set the Blend for this control.
IBlend GetBlend () const
Get the Blend for this control.
int GetTextEntryLength () const
Get the max number of characters that are allowed in text entry.
void SetTextEntryLength (int len)
Set the max number of characters that are allowed in text entry.
const IRECT & GetRECT () const
Get the rectangular draw area for this control, within the graphics context.
void SetRECT (const IRECT &bounds)
Set the rectangular draw area for this control, within the graphics context.
const IRECT & GetTargetRECT () const
Get the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetRECT (const IRECT &bounds)
Set the rectangular mouse tracking target area, within the graphics context for this control.
void SetTargetAndDrawRECTs (const IRECT &bounds)
Set BOTH the draw rect and the target area, within the graphics context for this control.
virtual void SetPosition (float x, float y)
Set the position of the control, preserving the width and height.
virtual void SetSize (float w, float h)
Set the size of the control, preserving the current position.
void SetPTParameterHighlight (bool isHighlighted, int color)
Used internally by the AAX wrapper view interface to set the control parmeter highlight.
bool GetMouseDblAsSingleClick () const
Get double click as single click By default, mouse double click has its own handler.
virtual void Hide (bool hide)
Shows or hides the IControl.
bool IsHidden () const
virtual void SetDisabled (bool disable)
Sets disabled mode for the control, the default implementation modifies the mBlend member.
bool IsDisabled () const
void SetMouseOverWhenDisabled (bool allow)
Specify whether the control should respond to mouse overs when disabled.
void SetMouseEventsWhenDisabled (bool allow)
Specify whether the control should respond to other mouse events when disabled.
bool GetMouseOverWhenDisabled () const
bool GetMouseEventsWhenDisabled () const
bool GetIgnoreMouse () const
void SetIgnoreMouse (bool ignore)
Specify whether the control should respond to mouse events.
bool GetPromptShowsParamLabel () const
void SetPromptShowsParamLabel (bool enable)
Set if the control should show parameter labels/units e.g.
virtual bool IsHit (float x, float y) const
Hit test the control.
virtual void SetDirty (bool triggerAction=true, int valIdx=kNoValIdx)
Mark the control as dirty, i.e.
virtual void SetClean ()
void Animate ()
virtual bool IsDirty ()
Called at each display refresh by the IGraphics draw loop, after IControl::Animate(), to determine if the control is marked as dirty.
void DisablePrompt (bool disable)
Disable/enable default prompt for user input.
virtual void OnGUIIdle ()
This is an idle timer tick call on the GUI thread, only active if USE_IDLE_CALLS is defined.
int GetTag () const
Get the control's tag.
void SetWantsMidi (bool enable=true)
Specify whether this control wants to know about MIDI messages sent to the UI.
bool GetWantsMidi () const
void SetWantsMultiTouch (bool enable=true)
Specify whether this control supports multiple touches.
bool GetWantsMultiTouch () const
IControl * AttachGestureRecognizer (EGestureType type, IGestureFunc func)
Add a IGestureFunc that should be triggered in response to a certain type of gesture.
bool GetWantsGestures () const
EGestureType GetLastGesture () const
IGEditorDelegate * GetDelegate ()
Gets a pointer to the class implementing the IEditorDelegate interface that handles parameter changes from this IGraphics instance.
void SetDelegate (IGEditorDelegate &dlg)
Used internally to set the mDelegate (and mGraphics) variables.
IContainerBase * GetParent () const
void SetParent (IContainerBase *pParent)
IGraphics * GetUI ()
const IGraphics * GetUI () const
bool GetMouseIsOver () const
This can be used in IControl::Draw() to check if the mouse is over the control, without implementing mouse over methods.
virtual void SnapToMouse (float x, float y, EDirection direction, const IRECT &bounds, int valIdx=-1, double minClip=0., double maxClip=1.)
Set control value based on x, y position within a rectangle.
virtual void OnEndAnimation ()
void StartAnimation (int duration)
void SetAnimation (IAnimationFunction func)
Set the animation function.
void SetAnimation (IAnimationFunction func, int duration)
Set the animation function and starts it.
IAnimationFunction GetAnimationFunction ()
Get the control's animation function, if it exists.
IActionFunction GetActionFunction ()
Get the control's action function, if it exists.
double GetAnimationProgress () const
Get the progress in a control's animation, in the range 0-1.
Milliseconds GetAnimationDuration () const
Get the duration of animations applied to the control.
template<class T >
T * As ()
Helper function to dynamic cast an IControl to a subclass.
Public Member Functions inherited from IVectorBase
IVectorBase (const IVStyle &style, bool labelInWidget=false, bool valueInWidget=false)
IVectorBase Constructor.
void AttachIControl (IControl *pControl, const char *label)
Call in the constructor of your IVControl to link the IVectorBase and IControl.
virtual void OnStyleChanged ()
Implement if extra changes are required in response to style changing.
void SetColor (EVColor colorIdx, const IColor &color)
Set one of the IVColors that style the IVControl.
void SetColors (const IVColorSpec &spec)
Set the colors of this IVControl.
const IColor & GetColor (EVColor color) const
Get value of a specific EVColor in the IVControl.
void SetLabelStr (const char *label)
const char * GetLabelStr () const
void SetValueStr (const char *value)
void SetWidgetFrac (float frac)
void SetAngle (float angle)
void SetShowLabel (bool show)
void SetShowValue (bool show)
void SetRoundness (float roundness)
void SetDrawFrame (bool draw)
void SetDrawShadows (bool draw)
void SetEmboss (bool draw)
void SetShadowOffset (float offset)
void SetFrameThickness (float thickness)
void SetSplashRadius (float radius)
void SetSplashPoint (float x, float y)
void SetShape (EVShape shape)
virtual void SetStyle (const IVStyle &style)
Set the Style of this IVControl.
IVStyle GetStyle () const
Get the style of this IVControl.
IRECT GetAdjustedHandleBounds (IRECT handleBounds) const
Get the adjusted bounds for the widget handle, based on the style settings.
float GetRoundedCornerRadius (const IRECT &bounds) const
Get the radius of rounded corners for a rectangle, based on the style roundness factor.
IRECT GetWidgetBounds () const
IRECT GetLabelBounds () const
IRECT GetValueBounds () const
void DrawSplash (IGraphics &g, const IRECT &clipRegion=IRECT())
Draw a splash effect when a widget handle is clicked (via SplashClickAnimationFunc)
virtual void DrawBackground (IGraphics &g, const IRECT &rect)
Draw the IVControl background (usually transparent)
virtual void DrawWidget (IGraphics &g)
Draw the IVControl main widget (override)
virtual void DrawLabel (IGraphics &g)
Draw the IVControl label text.
virtual void DrawValue (IGraphics &g, bool mouseOver)
Draw the IVControl value text.
virtual void DrawPressableShape (IGraphics &g, EVShape shape, const IRECT &bounds, bool pressed, bool mouseOver, bool disabled)
Call one of the DrawPressableShape methods.
void DrawPressableEllipse (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, bool disabled)
Draw an ellipse-shaped vector button.
IRECT DrawPressableRectangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, bool disabled, bool rtl=true, bool rtr=true, bool rbl=true, bool rbr=true)
Draw a rectangle-shaped vector button.
IRECT DrawPressableTriangle (IGraphics &g, const IRECT &bounds, bool pressed, bool mouseOver, float angle, bool disabled)
Draw a triangle-shaped vector button.
IRECT MakeRects (const IRECT &parent, bool hasHandle=false)
Calculate the rectangles for the various areas, depending on the style.
Protected Member Functions
void UpdateRects ()
Protected Member Functions inherited from IControl
template<typename T , typename... Args>
void ForValIdx (int valIdx, T func, Args... args)
A helper template function to call a method for an individual value, or for all values.
void SetNVals (int nVals)
Protected Attributes
IRECT mStartRect
IRECT mEndRect
IRECT mHandleBounds
EDirection mDirection
Protected Attributes inherited from ISwitchControlBase
int mNumStates
WDL_TypedBuf< bool > mDisabledState
bool mMouseDown = false
Protected Attributes inherited from IControl
IRECT mRECT
IRECT mTargetRECT
WDL_String mGroup
Controls can be grouped for hiding and showing panels.
IText mText
IBlend mBlend
int mTextEntryLength = DEFAULT_TEXT_ENTRY_LEN
bool mDirty = true
bool mHide = false
bool mDisabled = false
bool mDisablePrompt = true
bool mDblAsSingleClick = false
bool mMouseOverWhenDisabled = false
bool mMouseEventsWhenDisabled = false
bool mIgnoreMouse = false
bool mWantsMidi = false
bool mWantsMultiTouch = false
bool mPromptShowsParamLabel = false
bool mMouseIsOver = false
if mGraphics::mHandleMouseOver = true, this will be true when the mouse is over control.
WDL_String mTooltip
IColor mPTHighlightColor = COLOR_RED
bool mPTisHighlighted = false
Protected Attributes inherited from IVectorBase
IControl * mControl = nullptr
IVStyle mStyle
bool mLabelInWidget = false
bool mValueInWidget = false
float mSplashRadius = 0.f
IVec2 mSplashPoint = {0.f, 0.f}
float mMaxSplashRadius = 50.f
float mTrackSize = 2.f
float mValueDisplayFrac = 0.66f
IRECT mWidgetBounds
IRECT mLabelBounds
IRECT mValueBounds
WDL_String mLabelStr
WDL_String mValueStr
EVShape mShape = EVShape::Rectangle
Detailed Description
A switch with a slide animation when clicked.
Definition at line 105 of file IControls.h.
Constructor & Destructor Documentation
IVSlideSwitchControl() [1/2]
IVSlideSwitchControl::IVSlideSwitchControl (const IRECT & bounds, int paramIdx = kNoParameter, const char * label = "", const IVStyle & style = DEFAULT_STYLE, bool valueInButton = false, EDirection direction = EDirection::Horizontal)
Definition at line 192 of file IControls.cpp.
IVSlideSwitchControl() [2/2]
IVSlideSwitchControl::IVSlideSwitchControl (const IRECT & bounds, IActionFunction aF = EmptyClickActionFunc, const char * label = "", const IVStyle & style = DEFAULT_STYLE, bool valueInButton = false, EDirection direction = EDirection::Horizontal, int numStates = 2, int initialState = 0)
Definition at line 214 of file IControls.cpp.
Member Function Documentation
Draw()
void IVSlideSwitchControl::Draw (IGraphics & g) override virtual
Draw the control to the graphics context.
Parameters
g The graphics context to which this control belongs.
Reimplemented from IVSwitchControl.
Definition at line 263 of file IControls.cpp.
References IVectorBase::DrawBackground(), IVectorBase::DrawLabel(), IVectorBase::DrawValue(), DrawWidget(), and IControl::GetAnimationFunction().
DrawHandle()
void IVSlideSwitchControl::DrawHandle (IGraphics & g, const IRECT & filledArea) virtual
Definition at line 285 of file IControls.cpp.
DrawTrack()
void IVSlideSwitchControl::DrawTrack (IGraphics & g, const IRECT & filledArea) virtual
Definition at line 279 of file IControls.cpp.
DrawWidget()
void IVSlideSwitchControl::DrawWidget (IGraphics & g) override virtual
Draw the IVControl main widget (override)
Reimplemented from IVSwitchControl.
Definition at line 273 of file IControls.cpp.
Referenced by Draw().
OnEndAnimation()
void IVSlideSwitchControl::OnEndAnimation () override virtual
Reimplemented from IControl.
Definition at line 256 of file IControls.cpp.
OnResize()
void IVSlideSwitchControl::OnResize () override virtual
Called when IControl is constructed or resized using SetRect().
NOTE: if you call SetDirty() in this method, you should call SetDirty(false) to avoid triggering parameter changes
Reimplemented from IVSwitchControl.
Definition at line 250 of file IControls.cpp.
References IVSwitchControl::OnResize().
SetDirty()
void IVSlideSwitchControl::SetDirty (bool triggerAction, int valIdx = kNoValIdx) override virtual
Mark the control as dirty, i.e.
it should be redrawn on the next display refresh
Parameters
triggerAction If this is true and the control is linked to a parameter notify the class implementing the IEditorDelegate interface that the parameter changed. If this control has an ActionFunction, that can also be triggered. NOTE: it is easy to forget that this method always sets the control dirty, the argument refers to whether a consecutive action should be performed
Reimplemented from IVSwitchControl.
Definition at line 290 of file IControls.cpp.
References IControl::GetAnimationFunction(), and IVSwitchControl::SetDirty().
UpdateRects()
void IVSlideSwitchControl::UpdateRects () protected
Definition at line 241 of file IControls.cpp.
Member Data Documentation
mDirection
EDirection IVSlideSwitchControl::mDirection protected
Definition at line 125 of file IControls.h.
mEndRect
IRECT IVSlideSwitchControl::mEndRect protected
Definition at line 123 of file IControls.h.
mHandleBounds
IRECT IVSlideSwitchControl::mHandleBounds protected
Definition at line 124 of file IControls.h.
mStartRect
IRECT IVSlideSwitchControl::mStartRect protected
Definition at line 123 of file IControls.h.
The documentation for this class was generated from the following files:
IControls.h
IControls.cpp