iPlug 2: IPlug::Utilities
IPlug::Utilities
Utility functions and macros.
Classes
class IMidiQueueBase< T >
A class to help with queuing timestamped MIDI messages.
Macros
#define MAKE_QUOTE(str) #str
#define MAKE_STR(str) MAKE_QUOTE(str)
#define GET_PARAM_FROM_VARARG(paramType, vp, v)
Enumerations
enum EDOMVirtualKey {
DOM_VK_BACK_SPACE = 0x08 , DOM_VK_TAB = 0x09 , DOM_VK_RETURN = 0x0D , DOM_VK_SHIFT = 0x10 ,
DOM_VK_CONTROL = 0x11 , DOM_VK_ALT = 0x12 , DOM_VK_PAUSE = 0x13 , DOM_VK_CAPS_LOCK = 0x14 ,
DOM_VK_ESCAPE = 0x1B , DOM_VK_SPACE = 0x20 , DOM_VK_PAGE_UP = 0x21 , DOM_VK_PAGE_DOWN = 0x22 ,
DOM_VK_END = 0x23 , DOM_VK_HOME = 0x24 , DOM_VK_LEFT = 0x25 , DOM_VK_UP = 0x26 ,
DOM_VK_RIGHT = 0x27 , DOM_VK_DOWN = 0x28 , DOM_VK_INSERT = 0x2D , DOM_VK_DELETE = 0x2E ,
DOM_VK_F1 = 0x70 , DOM_VK_F2 = 0x71 , DOM_VK_F3 = 0x72 , DOM_VK_F4 = 0x73 ,
DOM_VK_F5 = 0x74 , DOM_VK_F6 = 0x75 , DOM_VK_F7 = 0x76 , DOM_VK_F8 = 0x77 ,
DOM_VK_F9 = 0x78 , DOM_VK_F10 = 0x79 , DOM_VK_F11 = 0x7A , DOM_VK_F12 = 0x7B ,
DOM_VK_NUMPAD0 = 0x60 , DOM_VK_NUMPAD1 = 0x61 , DOM_VK_NUMPAD2 = 0x62 , DOM_VK_NUMPAD3 = 0x63 ,
DOM_VK_NUMPAD4 = 0x64 , DOM_VK_NUMPAD5 = 0x65 , DOM_VK_NUMPAD6 = 0x66 , DOM_VK_NUMPAD7 = 0x67 ,
DOM_VK_NUMPAD8 = 0x68 , DOM_VK_NUMPAD9 = 0x69
}
Functions
template<typename T >
BEGIN_IPLUG_NAMESPACE T Clip (T x, T lo, T hi)
Clips the value x between lo and hi.
template<typename T >
T Lerp (T a, T b, T f)
Linear interpolate between values a and b.
static bool CStringHasContents (const char *str)
static double DBToAmp (double dB)
Calculates gain from a given dB value.
static double AmpToDB (double amp)
static void GetVersionParts (int versionInteger, int &maj, int &min, int &pat)
Helper function to unpack the version number parts as individual integers.
static int GetDecimalVersion (int versionInteger)
Helper function to get the version number as a decimal integer.
static void GetVersionStr (int versionInteger, WDL_String &str)
Helper function to get the semantic version number as a string from an integer.
template<class SRC , class DEST >
void CastCopy (DEST *pDest, SRC *pSrc, int n)
Helper function to loop through a buffer of samples copying and casting from e.g float to double.
static void ToLower (char *cDest, const char *cSrc)
static EHost LookUpHost (const char *inHost)
Gets the host ID from a human-readable name.
static void GetHostNameStr (EHost host, WDL_String &str)
Gets a human-readable name from host identifier.
static void MidiNoteName (double midiPitch, WDL_String &noteName, bool cents=false, bool middleCisC4=false)
static FILE * fopenUTF8 (const char *path, const char *mode)
int DOMKeyToVirtualKey (uint32_t domKeyCode)
Converts a DOM virtual key code to an iPlug2 virtual key code.
Detailed Description
Utility functions and macros.
Macro Definition Documentation
GET_PARAM_FROM_VARARG
#define GET_PARAM_FROM_VARARG (paramType, vp, v)
Definition at line 64 of file IPlugUtilities.h.
MAKE_QUOTE
#define MAKE_QUOTE (str) #str
Definition at line 60 of file IPlugUtilities.h.
MAKE_STR
#define MAKE_STR (str) MAKE_QUOTE(str)
Definition at line 61 of file IPlugUtilities.h.
Enumeration Type Documentation
EDOMVirtualKey
enum EDOMVirtualKey
Definition at line 429 of file IPlugUtilities.h.
Function Documentation
AmpToDB()
static double AmpToDB (double amp) inline static
Returns
dB calculated as an approximation of \(20*log_{10}(x) \)
See also
AMP_DB
Definition at line 105 of file IPlugUtilities.h.
References AMP_DB.
Referenced by IBMeterControl::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), and IVPeakAvgMeterControl< MAXNC >::OnMsgFromDelegate().
CastCopy()
template<class SRC , class DEST > void CastCopy (DEST * pDest, SRC * pSrc, int n)
Helper function to loop through a buffer of samples copying and casting from e.g float to double.
Template Parameters
SRC The source type
DEST The destination type
Parameters
pDest Ptr to the destination buffer
pSrc Ptr to the source buffer
n The number of or elements in the buffer
Definition at line 149 of file IPlugUtilities.h.
Clip()
template<typename T > BEGIN_IPLUG_NAMESPACE T Clip (T x, T lo, T hi)
Clips the value x between lo and hi.
Parameters
x Input value
lo Minimum value to be allowed
hi Maximum value to be allowed If x is outside given range, it will be set to one of the boundaries
Definition at line 49 of file IPlugUtilities.h.
Referenced by IColor::Clamp(), IParam::Constrain(), IEditorDelegate::ConstrainEditorResize(), IColor::Contrast(), IGraphics::DrawBitmap(), IGraphicsSkia::DrawBitmap(), IBitmapBase::DrawBitmap(), IGraphicsNanoVG::DrawDottedRect(), IGraphics::DrawHorizontalLine(), IGraphics::DrawVerticalLine(), IColor::FromHSLA(), IShaderControl::OnMouseDrag(), IKnobControlBase::OnMouseDrag(), ISliderControlBase::OnMouseDrag(), IShaderControl::OnMouseUp(), IWheelControl::OnMouseUp(), IBMeterControl::OnMsgFromDelegate(), IVMeterControl< MAXNC >::OnMsgFromDelegate(), IVPeakAvgMeterControl< MAXNC >::OnMsgFromDelegate(), IGraphics::Resize(), IControl::SetDirty(), IColor::SetOpacity(), IGraphics::SetQwertyMidiKeyHandlerFunc(), ADSREnvelope< T >::SetStageTime(), IControl::SnapToMouse(), IVMultiSliderControl< MAXNC >::SnapToMouse(), and IParam::ToNormalized().
CStringHasContents()
static bool CStringHasContents (const char * str) inline static
Definition at line 58 of file IPlugUtilities.h.
DBToAmp()
static double DBToAmp (double dB) inline static
Calculates gain from a given dB value.
Parameters
dB Value in dB
Returns
Gain calculated as an approximation of \(10^{\frac{x}{20}} \)
See also
IAMP_DB
Definition at line 97 of file IPlugUtilities.h.
References IAMP_DB.
DOMKeyToVirtualKey()
int DOMKeyToVirtualKey (uint32_t domKeyCode) inline
Converts a DOM virtual key code to an iPlug2 virtual key code.
Parameters
domKeyCode The DOM virtual key code to convert
Returns
The corresponding iPlug2 virtual key code, or 0 if no mapping exists
Definition at line 479 of file IPlugUtilities.h.
fopenUTF8()
static FILE * fopenUTF8 (const char * path, const char * mode) static
Definition at line 412 of file IPlugUtilities.h.
GetDecimalVersion()
static int GetDecimalVersion (int versionInteger) inline static
Helper function to get the version number as a decimal integer.
Parameters
versionInteger The version number packed into an integer
Returns
int Decimal version
Definition at line 125 of file IPlugUtilities.h.
References GetVersionParts().
Referenced by IPluginBase::GetHostVersion(), and IPluginBase::GetPluginVersion().
GetHostNameStr()
static void GetHostNameStr (EHost host, WDL_String & str) static
Gets a human-readable name from host identifier.
Parameters
host Host identifier (see EHost)
str WDL_String to set
int hostID = EHost::kHostAbletonLive;
WDL_String hostName;
GetHostNameStr(hostID, hostName);
Definition at line 238 of file IPlugUtilities.h.
Referenced by IPluginBase::GetHostStr().
GetVersionParts()
static void GetVersionParts (int versionInteger, int & maj, int & min, int & pat) inline static
Helper function to unpack the version number parts as individual integers.
Parameters
versionInteger The version number packed into an integer
maj The major version
min The minor version
pat The patch version
Definition at line 115 of file IPlugUtilities.h.
Referenced by GetDecimalVersion(), and GetVersionStr().
GetVersionStr()
static void GetVersionStr (int versionInteger, WDL_String & str) inline static
Helper function to get the semantic version number as a string from an integer.
Parameters
versionInteger The version number packed into an integer
str WDL_String to be populated with the version number in MAJOR.MINOR.PATCH format as a string
Definition at line 135 of file IPlugUtilities.h.
References GetVersionParts().
Referenced by IPluginBase::GetHostVersionStr(), IPluginBase::GetPluginVersionStr(), and IPlugAPIBase::SetHost().
Lerp()
template<typename T > T Lerp (T a, T b, T f) inline
Linear interpolate between values a and b.
Parameters
a Low value
b High value
f Value betweeen 0-1 for interpolation
Definition at line 56 of file IPlugUtilities.h.
LookUpHost()
static EHost LookUpHost (const char * inHost) static
Gets the host ID from a human-readable name.
Parameters
inHost Host name to search for
Returns
Identifier of the host (see EHost)
Definition at line 173 of file IPlugUtilities.h.
References ToLower().
Referenced by IPlugAPIBase::SetHost().
MidiNoteName()
static void MidiNoteName (double midiPitch, WDL_String & noteName, bool cents = false, bool middleCisC4 = false) static
Todo:
Parameters
midiPitch
Todo:
Parameters
noteName
Todo:
Parameters
cents
Todo:
Parameters
middleCisC4
Todo:
Definition at line 298 of file IPlugUtilities.h.
Referenced by IParam::InitPitch().
ToLower()
static void ToLower (char * cDest, const char * cSrc) static
Todo:
Parameters
cDest
Todo:
Parameters
cSrc
Todo:
Definition at line 160 of file IPlugUtilities.h.
Referenced by IGraphicsCanvas::BitmapExtSupported(), IGraphicsNanoVG::BitmapExtSupported(), IGraphicsSkia::BitmapExtSupported(), and LookUpHost().