iPlug 2: IOConfig Struct Reference
IOConfig Struct Reference
IPlug::Structs
An IOConfig is used to store bus info for each input/output configuration defined in the channel io string.
#include <IPlugStructs.h>
Public Member Functions
void AddBusInfo (ERoute direction, int NChans)
const IBusInfo * GetBusInfo (ERoute direction, int index) const
int NChansOnBusSAFE (ERoute direction, int index) const
int NBuses (ERoute direction) const
int GetTotalNChannels (ERoute direction) const
Get the total number of channels across all direction buses for this IOConfig.
bool ContainsWildcard (ERoute direction) const
Public Attributes
WDL_PtrList< IBusInfo > mBusInfo [2]
Detailed Description
An IOConfig is used to store bus info for each input/output configuration defined in the channel io string.
Definition at line 467 of file IPlugStructs.h.
Constructor & Destructor Documentation
~IOConfig()
IOConfig::~IOConfig () inline
Definition at line 471 of file IPlugStructs.h.
Member Function Documentation
AddBusInfo()
void IOConfig::AddBusInfo (ERoute direction, int NChans) inline
Todo:
Parameters
direction
Todo:
Parameters
NChans
Todo:
Parameters
label
Todo:
Definition at line 481 of file IPlugStructs.h.
ContainsWildcard()
bool IOConfig::ContainsWildcard (ERoute direction) const inline
Todo:
Parameters
direction
Todo:
Returns
true
Todo:
Returns
false
Todo:
Definition at line 529 of file IPlugStructs.h.
GetBusInfo()
const IBusInfo * IOConfig::GetBusInfo (ERoute direction, int index) const inline
Todo:
Parameters
direction
Todo:
Parameters
index
Todo:
Returns
IBusInfo*
Todo:
Definition at line 487 of file IPlugStructs.h.
Referenced by IPlugProcessor::GetIOConfigWithChanCounts().
GetTotalNChannels()
int IOConfig::GetTotalNChannels (ERoute direction) const inline
Get the total number of channels across all direction buses for this IOConfig.
Parameters
direction
Todo:
Returns
int
Todo:
Definition at line 515 of file IPlugStructs.h.
Referenced by IPlugProcessor::LegalIO().
NBuses()
int IOConfig::NBuses (ERoute direction) const inline
Todo:
Parameters
direction
Todo:
Returns
int
Todo:
Definition at line 510 of file IPlugStructs.h.
Referenced by IPlugProcessor::GetIOConfigWithChanCounts(), and IPlugProcessor::MaxNBuses().
NChansOnBusSAFE()
int IOConfig::NChansOnBusSAFE (ERoute direction, int index) const inline
Todo:
Parameters
direction
Todo:
Parameters
index
Todo:
Returns
int
Todo:
Definition at line 497 of file IPlugStructs.h.
Referenced by IPlugProcessor::MaxNChannelsForBus(), and IPlugProcessor::ParseChannelIOStr().
Member Data Documentation
mBusInfo
WDL_PtrList<IBusInfo> IOConfig::mBusInfo[2]
Definition at line 469 of file IPlugStructs.h.
The documentation for this struct was generated from the following file:
IPlugStructs.h