iPlug 2: IPattern Struct Reference
IPattern Struct Reference
IGraphics::Structs
Used to store pattern information for gradients.
#include <IGraphicsStructs.h>
Public Member Functions
IPattern (EPatternType type)
Create an IPattern.
IPattern (const IColor &color)
Create an IPattern with a solid color fill.
int NStops () const
const IColorStop & GetStop (int idx) const
Get the IColorStop at a particular index (will crash if out of bounds)
void AddStop (IColor color, float offset)
Add an IColorStop to the IPattern.
void SetTransform (float xx, float yx, float xy, float yy, float tx, float ty)
Set the affine transform for the IPattern with values.
void SetTransform (const IMatrix &transform)
Set the affine transform for the IPattern with an IMatrix.
Static Public Member Functions
static IPattern CreateLinearGradient (float x1, float y1, float x2, float y2, const std::initializer_list< IColorStop > &stops={})
Create a linear gradient IPattern.
static IPattern CreateLinearGradient (const IRECT &bounds, EDirection direction, const std::initializer_list< IColorStop > &stops={})
Create a linear gradient IPattern across a rectangular area.
static IPattern CreateRadialGradient (float x1, float y1, float r, const std::initializer_list< IColorStop > &stops={})
Create a radial gradient IPattern.
static IPattern CreateSweepGradient (float x1, float y1, const std::initializer_list< IColorStop > &stops={}, float angleStart=0.f, float angleEnd=360.f)
Create a sweep gradient IPattern (SKIA only)
Public Attributes
EPatternType mType
EPatternExtend mExtend
IColorStop mStops [16]
int mNStops
IMatrix mTransform
Detailed Description
Used to store pattern information for gradients.
Definition at line 2147 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IPattern() [1/2]
IPattern::IPattern (EPatternType type) inline
Create an IPattern.
Parameters
type The type of pattern, one of EPatternType
Definition at line 2157 of file IGraphicsStructs.h.
IPattern() [2/2]
IPattern::IPattern (const IColor & color) inline
Create an IPattern with a solid color fill.
Parameters
color The color for the single stop
Definition at line 2163 of file IGraphicsStructs.h.
Member Function Documentation
AddStop()
void IPattern::AddStop (IColor color, float offset) inline
Add an IColorStop to the IPattern.
Parameters
color The IColor
offset The offset
Definition at line 2296 of file IGraphicsStructs.h.
References GetStop().
Referenced by TestShadowGradientControl::Draw(), and TestColorControl::OnResize().
CreateLinearGradient() [1/2]
static IPattern IPattern::CreateLinearGradient (const IRECT & bounds, EDirection direction, const std::initializer_list< IColorStop > & stops = {}) inline static
Create a linear gradient IPattern across a rectangular area.
Parameters
bounds The rectangular area
direction If the gradient should be horizontal or vertical
stops An initializer list of IColorStops for the stops
Returns
IPattern The new IPattern
Definition at line 2209 of file IGraphicsStructs.h.
CreateLinearGradient() [2/2]
static IPattern IPattern::CreateLinearGradient (float x1, float y1, float x2, float y2, const std::initializer_list< IColorStop > & stops = {}) inline static
Create a linear gradient IPattern.
Parameters
x1 The start x position
y1 The start y position
x2 The end x position
y2 The end y position
stops An initializer list of IColorStops for the stops
Returns
IPattern The new IPattern
Definition at line 2176 of file IGraphicsStructs.h.
Referenced by IWheelControl::Draw(), TestShadowGradientControl::Draw(), IVDisplayControl::DrawWidget(), and TestColorControl::OnResize().
CreateRadialGradient()
static IPattern IPattern::CreateRadialGradient (float x1, float y1, float r, const std::initializer_list< IColorStop > & stops = {}) inline static
Create a radial gradient IPattern.
Parameters
x1 The x position of the centre
y1 The y position of the centre
r The radius of the gradient
stops An initializer list of IColorStops for the stops
Returns
IPattern The new IPattern
Definition at line 2235 of file IGraphicsStructs.h.
Referenced by ILEDControl::Draw(), and TestMaskControl::Draw().
CreateSweepGradient()
static IPattern IPattern::CreateSweepGradient (float x1, float y1, const std::initializer_list< IColorStop > & stops = {}, float angleStart = 0.f, float angleEnd = 360.f) inline static
Create a sweep gradient IPattern (SKIA only)
Parameters
x1 The x position of the centre
y1 The y position of the centre
stops An initializer list of IColorStops for the stops
angleStart the start angle of the sweep at in degrees clockwise where 0 is up
angleEnd the end angle of the sweep at in degrees clockwise where 0 is up
Returns
IPattern The new IPattern
Definition at line 2256 of file IGraphicsStructs.h.
GetStop()
const IColorStop & IPattern::GetStop (int idx) const inline
Get the IColorStop at a particular index (will crash if out of bounds)
Parameters
idx The index of the stop
Returns
const IColorStop& The stop
Definition at line 2288 of file IGraphicsStructs.h.
Referenced by AddStop(), IGraphicsSkia::ApplyLayerDropShadow(), IGraphicsNanoVG::PathFill(), and IGraphicsNanoVG::PathStroke().
NStops()
int IPattern::NStops () const inline
Returns
int The number of IColorStops in the IPattern
Definition at line 2280 of file IGraphicsStructs.h.
SetTransform() [1/2]
void IPattern::SetTransform (const IMatrix & transform) inline
Set the affine transform for the IPattern with an IMatrix.
Parameters
transform The affine transform matrix
Definition at line 2318 of file IGraphicsStructs.h.
SetTransform() [2/2]
void IPattern::SetTransform (float xx, float yx, float xy, float yy, float tx, float ty) inline
Set the affine transform for the IPattern with values.
Parameters
xx xx component of the affine transformation
yx yx component of the affine transformation
xy xy component of the affine transformation
yy yy component of the affine transformation
tx X translation component of the affine transformation
ty Y translation component of the affine transformation
Definition at line 2311 of file IGraphicsStructs.h.
Member Data Documentation
mExtend
EPatternExtend IPattern::mExtend
Definition at line 2150 of file IGraphicsStructs.h.
mNStops
int IPattern::mNStops
Definition at line 2152 of file IGraphicsStructs.h.
mStops
IColorStop IPattern::mStops[16]
Definition at line 2151 of file IGraphicsStructs.h.
mTransform
IMatrix IPattern::mTransform
Definition at line 2153 of file IGraphicsStructs.h.
mType
EPatternType IPattern::mType
Definition at line 2149 of file IGraphicsStructs.h.
The documentation for this struct was generated from the following file:
IGraphicsStructs.h