iPlug 2: ISVG Struct Reference
ISVG Struct Reference
IGraphics::Structs
User-facing SVG abstraction that you use to manage SVG data ISVG doesn't actually own the image data.
#include <IGraphicsStructs.h>
Public Member Functions
ISVG (NSVGimage *pImage)
float W () const
float H () const
bool IsValid () const
Public Attributes
NSVGimage * mImage = nullptr
Detailed Description
User-facing SVG abstraction that you use to manage SVG data ISVG doesn't actually own the image data.
Definition at line 193 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
ISVG()
ISVG::ISVG (NSVGimage * pImage) inline
Definition at line 195 of file IGraphicsStructs.h.
Member Function Documentation
H()
float ISVG::H () const inline
Returns
The height of the SVG
Definition at line 208 of file IGraphicsStructs.h.
Referenced by IGraphics::DrawSVG(), and ISVGSliderControl::OnResize().
IsValid()
bool ISVG::IsValid () const inline
Returns
\true if the SVG has valid data
Definition at line 215 of file IGraphicsStructs.h.
W()
float ISVG::W () const inline
Returns
The width of the SVG
Definition at line 201 of file IGraphicsStructs.h.
Referenced by IGraphics::DrawSVG(), and ISVGSliderControl::OnResize().
Member Data Documentation
mImage
NSVGimage* ISVG::mImage = nullptr
Definition at line 217 of file IGraphicsStructs.h.
The documentation for this struct was generated from the following file:
IGraphicsStructs.h