iPlug 2: IMatrix Struct Reference
IMatrix Struct Reference
IGraphics::Structs
Used to store transformation matrices.
#include <IGraphicsStructs.h>
Public Member Functions
IMatrix (double xx, double yx, double xy, double yy, double tx, double ty)
Create an IMatrix, specifying the values.
IMatrix ()
Create an identity matrix.
IMatrix & Translate (float x, float y)
Set the matrix for a translation transform.
IMatrix & Scale (float x, float y)
Set the matrix for a scale transform.
IMatrix & Rotate (float a)
Set the matrix for a rotation transform.
IMatrix & Skew (float xa, float ya)
Set the matrix for a skew transform.
void TransformPoint (double &x, double &y, double x0, double y0) const
Transforms the point x, y.
void TransformPoint (double &x, double &y) const
Transforms the point x, y with the matrix.
IMatrix & Transform (const IRECT &before, const IRECT &after)
IMatrix & Transform (const IMatrix &m)
Transform this matrix with another.
IMatrix & Invert ()
Changes the matrix to be the inverse of its original value.
Public Attributes
double mXX
double mYX
double mXY
double mYY
double mTX
double mTY
Detailed Description
Used to store transformation matrices.
Definition at line 1986 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IMatrix() [1/2]
IMatrix::IMatrix (double xx, double yx, double xy, double yy, double tx, double ty) inline
Create an IMatrix, specifying the values.
Parameters
xx xx component of the affine transformation
yx yx component of the affine transformation
xy xy component of the affine transformation
yy yy component of the affine transformation
tx X translation component of the affine transformation
ty Y translation component of the affine transformation
Definition at line 1995 of file IGraphicsStructs.h.
IMatrix() [2/2]
IMatrix::IMatrix () inline
Create an identity matrix.
Definition at line 2000 of file IGraphicsStructs.h.
Referenced by Rotate(), Scale(), Skew(), Transform(), and Translate().
Member Function Documentation
Invert()
IMatrix & IMatrix::Invert () inline
Changes the matrix to be the inverse of its original value.
Returns
IMatrix& The changed matrix
Definition at line 2094 of file IGraphicsStructs.h.
Rotate()
IMatrix & IMatrix::Rotate (float a) inline
Set the matrix for a rotation transform.
Parameters
a The angle of rotation in degrees
Returns
IMatrix& The matrix
Definition at line 2024 of file IGraphicsStructs.h.
References IMatrix(), and Transform().
Referenced by IGraphics::CalculateTextRotation(), and IGraphics::PathTransformRotate().
Scale()
IMatrix & IMatrix::Scale (float x, float y) inline
Set the matrix for a scale transform.
Parameters
x The scale for x
y The scale for y
Returns
IMatrix& The matrix
Definition at line 2016 of file IGraphicsStructs.h.
References IMatrix(), and Transform().
Referenced by IGraphics::PathTransformScale().
Skew()
IMatrix & IMatrix::Skew (float xa, float ya) inline
Set the matrix for a skew transform.
Parameters
xa The angle to skew x coordinates in degrees
ya The angle to skew y coordinates in degrees
Returns
IMatrix& The matrix
Definition at line 2037 of file IGraphicsStructs.h.
References IMatrix(), and Transform().
Referenced by IGraphics::PathTransformSkew().
Transform() [1/2]
IMatrix & IMatrix::Transform (const IMatrix & m) inline
Transform this matrix with another.
Parameters
m The matrix with which to transform this one
Returns
IMatrix& The result of the transform
Definition at line 2078 of file IGraphicsStructs.h.
Transform() [2/2]
IMatrix & IMatrix::Transform (const IRECT & before, const IRECT & after) inline
Todo:
Parameters
before
Todo:
Parameters
after
Todo:
Returns
IMatrix& The result of the transform
Definition at line 2065 of file IGraphicsStructs.h.
References IRECT::H(), IMatrix(), and IRECT::W().
Referenced by IGraphics::PathTransformMatrix(), Rotate(), Scale(), Skew(), and Translate().
TransformPoint() [1/2]
void IMatrix::TransformPoint (double & x, double & y) const inline
Transforms the point x, y with the matrix.
Parameters
x The x coordinate to transform
y The y coordinate to transform
Definition at line 2056 of file IGraphicsStructs.h.
References TransformPoint().
TransformPoint() [2/2]
void IMatrix::TransformPoint (double & x, double & y, double x0, double y0) const inline
Transforms the point x, y.
Todo:
Parameters
x The x coordinate to transform
y The y coordinate to transform
x0
Todo:
Parameters
y0
Todo:
Definition at line 2047 of file IGraphicsStructs.h.
Referenced by IGraphics::CalculateTextRotation(), and TransformPoint().
Translate()
IMatrix & IMatrix::Translate (float x, float y) inline
Set the matrix for a translation transform.
Parameters
x The translation for x values
y The translation for y values
Returns
IMatrix& The matrix
Definition at line 2007 of file IGraphicsStructs.h.
References IMatrix(), and Transform().
Referenced by IGraphics::PathTransformTranslate().
Member Data Documentation
mTX
double IMatrix::mTX
Definition at line 2110 of file IGraphicsStructs.h.
mTY
double IMatrix::mTY
Definition at line 2110 of file IGraphicsStructs.h.
mXX
double IMatrix::mXX
Definition at line 2110 of file IGraphicsStructs.h.
mXY
double IMatrix::mXY
Definition at line 2110 of file IGraphicsStructs.h.
mYX
double IMatrix::mYX
Definition at line 2110 of file IGraphicsStructs.h.
mYY
double IMatrix::mYY
Definition at line 2110 of file IGraphicsStructs.h.
The documentation for this struct was generated from the following file:
IGraphicsStructs.h