iPlug 2: IVColorSpec Struct Reference
IVColorSpec Struct Reference
IGraphics::Structs
Contains a set of 9 colors used to theme IVControls.
#include <IGraphicsStructs.h>
Public Member Functions
const IColor & GetColor (EVColor color) const
IVColorSpec ()
Create a new IVColorSpec object with default colors.
IVColorSpec (const std::initializer_list< IColor > &colors)
Create a new IVColorSpec object specifying the colors.
void ResetColors ()
Reset the colors to the defaults.
Static Public Member Functions
static const IColor & GetDefaultColor (EVColor idx)
Public Attributes
IColor mColors [kNumVColors]
Detailed Description
Contains a set of 9 colors used to theme IVControls.
Definition at line 2391 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IVColorSpec() [1/2]
IVColorSpec::IVColorSpec () inline
Create a new IVColorSpec object with default colors.
Definition at line 2421 of file IGraphicsStructs.h.
References ResetColors().
IVColorSpec() [2/2]
IVColorSpec::IVColorSpec (const std::initializer_list< IColor > & colors) inline
Create a new IVColorSpec object specifying the colors.
Parameters
colors Initializer list of IColors
Definition at line 2428 of file IGraphicsStructs.h.
References GetDefaultColor().
Member Function Documentation
GetColor()
const IColor & IVColorSpec::GetColor (EVColor color) const inline
Returns
The IColor for the EVColor in this ColorSpec
Definition at line 2396 of file IGraphicsStructs.h.
Referenced by IVectorBase::GetColor().
GetDefaultColor()
static const IColor & IVColorSpec::GetDefaultColor (EVColor idx) inline static
Returns
The default IColor for an EVColor
Definition at line 2402 of file IGraphicsStructs.h.
Referenced by IVColorSpec(), and ResetColors().
ResetColors()
void IVColorSpec::ResetColors () inline
Reset the colors to the defaults.
Definition at line 2446 of file IGraphicsStructs.h.
References GetDefaultColor().
Referenced by IVColorSpec().
Member Data Documentation
mColors
IColor IVColorSpec::mColors[kNumVColors]
Definition at line 2393 of file IGraphicsStructs.h.
The documentation for this struct was generated from the following file:
IGraphicsStructs.h