iPlug 2: IRECT Struct Reference
IRECT Struct Reference
IGraphics::Structs
Used to manage a rectangular area, independent of draw class/platform.
#include <IGraphicsStructs.h>
Public Member Functions
IRECT ()
Construct an empty IRECT
IRECT (float l, float t, float r, float b)
Construct a new IRECT with dimensions.
IRECT (float x, float y, const IBitmap &bitmap)
Construct a new IRECT at the given position and with the same size as the bitmap.
bool Empty () const
void Clear ()
Set all fields of this IRECT to 0.
bool operator== (const IRECT &rhs) const
bool operator!= (const IRECT &rhs) const
float W () const
float H () const
float MW () const
float MH () const
float Area () const
IRECT Union (const IRECT &rhs) const
Create a new IRECT that is a union of this IRECT and rhs.
IRECT Intersect (const IRECT &rhs) const
Create a new IRECT that is the intersection of this IRECT and rhs.
bool Intersects (const IRECT &rhs) const
Returns true if this IRECT shares any common pixels with rhs, false otherwise.
bool Contains (const IRECT &rhs) const
Returns true if this IRECT completely contains rhs.
bool Contains (float x, float y) const
Returns true if this IRECT completely contains the point (x,y).
bool ContainsEdge (float x, float y) const
Returns true if the point (x,y) is either contained in this IRECT or on an edge.
void Constrain (float &x, float &y) const
Ensure the point (x,y) is inside this IRECT.
IRECT Inset (const IRECT &rhs) const
Offsets the input IRECT based on the parent.
bool Mergeable (const IRECT &rhs) const
Return if this IRECT and rhs may be merged.
IRECT FracRect (EDirection layoutDir, float frac, bool fromTopOrRight=false) const
Get a new rectangle which is a fraction of this rectangle.
IRECT FracRectHorizontal (float frac, bool rhs=false) const
Returns a new IRECT with a width that is multiplied by frac.
IRECT FracRectVertical (float frac, bool fromTop=false) const
Returns a new IRECT with a height that is multiplied by frac.
IRECT SubRectVertical (int numSlices, int sliceIdx) const
Returns a new IRECT which is a horizontal "slice" of this IRECT.
IRECT SubRectHorizontal (int numSlices, int sliceIdx) const
Returns a new IRECT which is a vertical "slice" of this IRECT.
IRECT SubRect (EDirection layoutDir, int numSlices, int sliceIdx) const
Get a new rectangle which is a "slice" of this rectangle.
IRECT GetFromTLHC (float w, float h) const
Get a subrect of this IRECT expanding from the top-left corner.
IRECT GetFromBLHC (float w, float h) const
Get a subrect of this IRECT expanding from the bottom-left corner.
IRECT GetFromTRHC (float w, float h) const
Get a subrect of this IRECT expanding from the top-right corner.
IRECT GetFromBRHC (float w, float h) const
Get a subrect of this IRECT expanding from the bottom-right corner.
IRECT GetFromTop (float amount) const
Get a subrect of this IRECT bounded in Y by the top edge and 'amount'.
IRECT GetFromBottom (float amount) const
Get a subrect of this IRECT bounded in Y by 'amount' and the bottom edge.
IRECT GetFromLeft (float amount) const
Get a subrect of this IRECT bounded in X by the left edge and 'amount'.
IRECT GetFromRight (float amount) const
Get a subrect of this IRECT bounded in X by 'amount' and the right edge.
IRECT GetReducedFromTop (float amount) const
Get a subrect of this IRECT reduced in height from the top edge by 'amount'.
IRECT GetReducedFromBottom (float amount) const
Get a subrect of this IRECT reduced in height from the bottom edge by 'amount'.
IRECT GetReducedFromLeft (float amount) const
Get a subrect of this IRECT reduced in width from the left edge by 'amount'.
IRECT GetReducedFromRight (float amount) const
Get a subrect of this IRECT reduced in width from the right edge by 'amount'.
IRECT ReduceFromTop (float amount)
Reduce in height from the top edge by 'amount' and return the removed region.
IRECT ReduceFromBottom (float amount)
Reduce in height from the bottom edge by 'amount' and return the removed region.
IRECT ReduceFromLeft (float amount)
Reduce in width from the left edge by 'amount' and return the removed region.
IRECT ReduceFromRight (float amount)
Reduce in width from the right edge by 'amount' and return the removed region.
IRECT GetGridCell (int row, int col, int nRows, int nColumns) const
Get a subrect (by row, column) of this IRECT which is a cell in a grid of size (nRows * nColumns)
IRECT GetGridCell (int cellIndex, int nRows, int nColumns, EDirection dir=EDirection::Horizontal, int nCells=1) const
Get a subrect (by index) of this IRECT which is a cell (or union of nCells sequential cells on same row/column) in a grid of size (nRows * nColumns)
bool IsPixelAligned () const
bool IsPixelAligned (float scale) const
Return true if, when scaled by scale, this IRECT is pixel aligned When scaling this mutliples each value of the IRECT, it does not scale from the center.
void PixelAlign ()
Pixel aligns the rect in an inclusive manner (moves all points outwards)
void PixelAlign (float scale)
Pixel-align this IRECT at the given scale factor then scale it back down When scaling this mutliples each value of the IRECT, it does not scale from the center.
IRECT GetPixelAligned () const
Get a copy of this IRECT with PixelAlign() called.
IRECT GetPixelAligned (float scale) const
Get a copy of this IRECT with PixelAlign(scale) called.
void PixelSnap ()
Pixel aligns to nearest pixels This may make the IRECT smaller, unlike PixelAlign().
void PixelSnap (float scale)
Pixel align a scaled version of this IRECT.
IRECT GetPixelSnapped () const
IRECT GetPixelSnapped (float scale) const
Get a copy of this IRECT with PixelSnap(scale) called.
void Pad (float padding)
Pad this IRECT N.B.
void Pad (float padL, float padT, float padR, float padB)
Pad this IRECT N.B.
void HPad (float padding)
Pad this IRECT in the X-axis N.B.
void VPad (float padding)
Pad this IRECT in the Y-axis N.B.
void MidHPad (float padding)
Set the width of this IRECT to 2*padding without changing it's center point on the X-axis.
void MidVPad (float padding)
Set the height of this IRECT to 2*padding without changing it's center point on the Y-axis.
IRECT GetPadded (float padding) const
Get a copy of this IRECT with each value padded by padding N.B.
IRECT GetPadded (float padL, float padT, float padR, float padB) const
Get a copy of this IRECT with the values padded N.B.
IRECT GetHPadded (float padding) const
Get a copy of this IRECT padded in the X-axis N.B.
IRECT GetVPadded (float padding) const
Get a copy of this IRECT padded in the Y-axis N.B.
IRECT GetMidHPadded (float padding) const
Get a copy of this IRECT where its width = 2 * padding but the center point on the X-axis has not changed.
IRECT GetMidVPadded (float padding) const
Get a copy of this IRECT where its height = 2 * padding but the center point on the Y-axis has not changed.
IRECT GetHSliced (float w, bool rhs=false) const
Get a copy of this IRECT with a new width.
IRECT GetVSliced (float h, bool bot=false) const
Get a copy of this IRECT with a new height.
void Clank (const IRECT &rhs)
Clank will limit this IRECT's bounds based on the boundaries of the IRECT passed in as an argument.
void Scale (float scale)
Multiply each field of this IRECT by scale.
void ScaleAboutCentre (float scale)
Scale the width and height of this IRECT by scale without changing the center point.
IRECT GetScaled (float scale) const
Get a copy of this IRECT with all values multiplied by scale.
IRECT GetScaledAboutCentre (float scale) const
Get a copy of this IRECT where the width and height are multiplied by scale without changing the center point.
void GetRandomPoint (float &x, float &y) const
Get a random point within this rectangle.
IRECT GetRandomSubRect () const
void Offset (float l, float t, float r, float b)
Offset each field of the rectangle.
IRECT GetOffset (float l, float t, float r, float b) const
Get a copy of this rectangle where each field is offset by a specified amount.
void Translate (float x, float y)
Translate this rectangle.
IRECT GetTranslated (float x, float y) const
Get a translated copy of this rectangle.
IRECT GetHShifted (float x) const
Get a copy of this rectangle translated on the X axis.
IRECT GetVShifted (float y) const
Get a copy of this rectangle translated on the Y axis.
IRECT GetCentredInside (const IRECT &sr) const
Get a rectangle the size of sr but with the same center point as this rectangle.
IRECT GetCentredInside (float w, float h=0.f) const
Get a rectangle with the same center point as this rectangle and the given size.
IRECT GetCentredInside (const IBitmap &bitmap) const
Get a rectangle with the same center point as this rectangle and the size of the bitmap.
void VAlignTo (const IRECT &sr, EVAlign align)
Vertically align this rect to the reference IRECT.
void HAlignTo (const IRECT &sr, EAlign align)
Horizontally align this rect to the reference IRECT.
IRECT GetVAlignedTo (const IRECT &sr, EVAlign align) const
Get a rectangle the same dimensions as this one, vertically aligned to the reference IRECT.
float GetLengthOfShortestSide () const
IRECT GetHAlignedTo (const IRECT &sr, EAlign align) const
Get a rectangle the same dimensions as this one, horizontally aligned to the reference IRECT.
void DBGPrint ()
Print the IRECT's details to the console in Debug builds.
Static Public Member Functions
static IRECT MakeXYWH (float l, float t, float w, float h)
Create a new IRECT with the given position and size.
static IRECT MakeMidXYWH (float x, float y, float w, float h)
Create a new IRECT of size (y,h) centred at the given position (x,y)
static IRECT LinearInterpolateBetween (const IRECT &start, const IRECT &dest, float progress)
Get a rectangle that is a linear interpolation between start and dest
Public Attributes
float L
float T
float R
float B
Detailed Description
Used to manage a rectangular area, independent of draw class/platform.
An IRECT is always specified in 1:1 pixels, any scaling for high DPI happens in the drawing class. In IGraphics 0,0 is top left.
Definition at line 748 of file IGraphicsStructs.h.
Constructor & Destructor Documentation
IRECT() [1/3]
IRECT::IRECT () inline
Construct an empty IRECT
Definition at line 753 of file IGraphicsStructs.h.
Referenced by FracRectHorizontal(), FracRectVertical(), GetFromBLHC(), GetFromBottom(), GetFromBRHC(), GetFromLeft(), GetFromRight(), GetFromTLHC(), GetFromTop(), GetFromTRHC(), GetHPadded(), GetHSliced(), GetMidHPadded(), GetMidVPadded(), GetOffset(), GetPadded(), GetRandomSubRect(), GetReducedFromBottom(), GetReducedFromLeft(), GetReducedFromRight(), GetReducedFromTop(), GetTranslated(), GetVPadded(), GetVSliced(), Inset(), Intersect(), MakeMidXYWH(), MakeXYWH(), SubRectHorizontal(), SubRectVertical(), and Union().
IRECT() [2/3]
IRECT::IRECT (float l, float t, float r, float b) inline
Construct a new IRECT with dimensions.
Parameters
l Left
t Top
r Right
b Bottom
Definition at line 763 of file IGraphicsStructs.h.
IRECT() [3/3]
IRECT::IRECT (float x, float y, const IBitmap & bitmap) inline
Construct a new IRECT at the given position and with the same size as the bitmap.
Parameters
x Top
y Left
bitmap Bitmap for the size
Definition at line 771 of file IGraphicsStructs.h.
References IBitmap::FH(), and IBitmap::FW().
Member Function Documentation
Area()
float IRECT::Area () const inline
Returns
float the area of this IRECT
Definition at line 836 of file IGraphicsStructs.h.
References H(), and W().
Clank()
void IRECT::Clank (const IRECT & rhs) inline
Clank will limit this IRECT's bounds based on the boundaries of the IRECT passed in as an argument.
Parameters
rhs The rectangle to limit with
Definition at line 1417 of file IGraphicsStructs.h.
Referenced by IGraphics::IsDirty().
Clear()
void IRECT::Clear () inline
Set all fields of this IRECT to 0.
Definition at line 808 of file IGraphicsStructs.h.
Constrain()
void IRECT::Constrain (float & x, float & y) const inline
Ensure the point (x,y) is inside this IRECT.
Parameters
x point X, will be modified if it's outside this IRECT
y point Y, will be modified if it's outside this IRECT
Definition at line 903 of file IGraphicsStructs.h.
Referenced by IVXYPadControl::OnMouseDrag(), IControl::SnapToMouse(), and IVMultiSliderControl< MAXNC >::SnapToMouse().
Contains() [1/2]
bool IRECT::Contains (const IRECT & rhs) const inline
Returns true if this IRECT completely contains rhs.
Parameters
rhs another IRECT
Returns
true if this IRECT completely contains rhs
false if any part of rhs is outside this IRECT
Definition at line 874 of file IGraphicsStructs.h.
References Empty().
Referenced by IRECTList::Find(), IControl::IsHit(), IVButtonControl::IsHit(), IVSwitchControl::IsHit(), IVKnobControl::IsHit(), IVSliderControl::IsHit(), IVNumberBoxControl::OnMouseDblClick(), IVKnobControl::OnMouseDown(), IVSliderControl::OnMouseDown(), ITextEntryControl::OnMouseDown(), TestDirBrowseControl::OnMouseDown(), IGraphicsLiveEdit::OnMouseDrag(), IVKnobControl::OnMouseOver(), IVSliderControl::OnMouseOver(), IVRangeSliderControl::OnMouseOver(), TestBezierControl::OnMouseOver(), IGraphicsLiveEdit::OnMouseOver(), and IRECTList::Optimize().
Contains() [2/2]
bool IRECT::Contains (float x, float y) const inline
Returns true if this IRECT completely contains the point (x,y).
Parameters
x point X
y point Y
Returns
true the point (x,y) is inside this IRECT
false the point (x,y) is outside this IRECT
Definition at line 884 of file IGraphicsStructs.h.
References Empty().
ContainsEdge()
bool IRECT::ContainsEdge (float x, float y) const inline
Returns true if the point (x,y) is either contained in this IRECT or on an edge.
Unlike Contains(x,y) this method includes right-most and bottom-most pixels.
Parameters
x point X
y point Y
Returns
true the point (x,y) is inside this IRECT
false the point (x,y) is outside this IRECT
Definition at line 895 of file IGraphicsStructs.h.
References Empty().
DBGPrint()
void IRECT::DBGPrint () inline
Print the IRECT's details to the console in Debug builds.
Definition at line 1691 of file IGraphicsStructs.h.
References H(), and W().
Empty()
bool IRECT::Empty () const inline
Returns
bool true if all the fields of this IRECT are 0
Definition at line 802 of file IGraphicsStructs.h.
Referenced by Contains(), ContainsEdge(), IGraphicsLiveEdit::Draw(), IVGroupControl::DrawWidget(), Intersects(), IVectorBase::MakeRects(), Mergeable(), IGraphics::PathClipRegion(), and Union().
FracRect()
IRECT IRECT::FracRect (EDirection layoutDir, float frac, bool fromTopOrRight = false) const inline
Get a new rectangle which is a fraction of this rectangle.
Parameters
layoutDir EDirection::Vertical or EDirection::Horizontal
frac Fractional multiplier
fromTopOrRight If true the new rectangle will expand from the top (Vertical) or right (Horizontal) otherwise it will expand from the bottom (Vertical) or left (Horizontal)
Returns
IRECT the new rectangle
Definition at line 939 of file IGraphicsStructs.h.
References FracRectHorizontal(), and FracRectVertical().
Referenced by IVSliderControl::DrawWidget().
FracRectHorizontal()
IRECT IRECT::FracRectHorizontal (float frac, bool rhs = false) const inline
Returns a new IRECT with a width that is multiplied by frac.
Parameters
frac width multiplier
rhs if true, the new IRECT will expand/contract from the right, otherwise it will come from the left
Returns
IRECT the new IRECT
Definition at line 951 of file IGraphicsStructs.h.
References IRECT(), and W().
Referenced by IVColorSwatchControl::DrawWidget(), FracRect(), and IRECTList::GetFracGrid().
FracRectVertical()
IRECT IRECT::FracRectVertical (float frac, bool fromTop = false) const inline
Returns a new IRECT with a height that is multiplied by frac.
Parameters
frac height multiplier
fromTop if true, the new IRECT will expand/contract from the top, otherwise it will come from the bottom
Returns
IRECT the new IRECT
Definition at line 965 of file IGraphicsStructs.h.
References H(), and IRECT().
Referenced by IWheelControl::Draw(), IVScopeControl< MAXNC, MAXBUF >::DrawWidget(), FracRect(), IRECTList::GetFracGrid(), IVNumberBoxControl::OnAttached(), and IVNumberBoxControl::OnResize().
GetCentredInside() [1/3]
IRECT IRECT::GetCentredInside (const IBitmap & bitmap) const inline
Get a rectangle with the same center point as this rectangle and the size of the bitmap.
Parameters
bitmap Bitmap used to size the new rectangle
Returns
IRECT the new rectangle
Definition at line 1620 of file IGraphicsStructs.h.
References IBitmap::FH(), IBitmap::FW(), MH(), and MW().
GetCentredInside() [2/3]
IRECT IRECT::GetCentredInside (const IRECT & sr) const inline
Get a rectangle the size of sr but with the same center point as this rectangle.
Parameters
sr Size rectangle
Returns
IRECT the new rectangle
Definition at line 1586 of file IGraphicsStructs.h.
References H(), MH(), MW(), and W().
Referenced by IBSliderControl::Draw(), ILEDControl::Draw(), TestBezierControl::Draw(), TestDrawContextControl::Draw(), TestFlexBoxControl::Draw(), TestFontControl::Draw(), TestMaskControl::Draw(), IBitmapBase::DrawBitmap(), IPopupMenuControl::DrawCellText(), IPopupMenuControl::DrawTick(), IVRadioButtonControl::DrawWidget(), IVKnobControl::DrawWidget(), IVKnobControl::GetKnobDragBounds(), IVectorBase::MakeRects(), ISVGSliderControl::OnResize(), IBSliderControl::OnResize(), TestDirBrowseControl::OnResize(), and ICaptionControl::OnResize().
GetCentredInside() [3/3]
IRECT IRECT::GetCentredInside (float w, float h = 0.f) const inline
Get a rectangle with the same center point as this rectangle and the given size.
Parameters
w Width of the new rectangle (minimum 1.0)
h Height of the new rectangle (a value of 0 will make it the same as w, thus a square)
Returns
IRECT the new rectangle
Definition at line 1601 of file IGraphicsStructs.h.
References MH(), and MW().
GetFromBLHC()
IRECT IRECT::GetFromBLHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the bottom-left corner.
Parameters
w Width of the desired IRECT
h Height of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1028 of file IGraphicsStructs.h.
References IRECT().
GetFromBottom()
IRECT IRECT::GetFromBottom (float amount) const inline
Get a subrect of this IRECT bounded in Y by 'amount' and the bottom edge.
Parameters
amount Size in Y of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1050 of file IGraphicsStructs.h.
References IRECT().
Referenced by IWheelControl::Draw(), TestFontControl::Draw(), IVectorBase::MakeRects(), TestDirBrowseControl::OnResize(), and ReduceFromBottom().
GetFromBRHC()
IRECT IRECT::GetFromBRHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the bottom-right corner.
Parameters
w Width of the desired IRECT
h Height of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1040 of file IGraphicsStructs.h.
References IRECT().
Referenced by ICornerResizerControl::OnRescale().
GetFromLeft()
IRECT IRECT::GetFromLeft (float amount) const inline
Get a subrect of this IRECT bounded in X by the left edge and 'amount'.
Parameters
amount Size in X of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1055 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVRadioButtonControl::DrawWidget(), IVectorBase::MakeRects(), ICaptionControl::OnResize(), and ReduceFromLeft().
GetFromRight()
IRECT IRECT::GetFromRight (float amount) const inline
Get a subrect of this IRECT bounded in X by 'amount' and the right edge.
Parameters
amount Size in X of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1060 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVRadioButtonControl::DrawWidget(), IVectorBase::MakeRects(), TestDirBrowseControl::OnResize(), ICaptionControl::OnResize(), and ReduceFromRight().
GetFromTLHC()
IRECT IRECT::GetFromTLHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the top-left corner.
Parameters
w Width of the desired IRECT
h Weight of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1022 of file IGraphicsStructs.h.
References IRECT().
GetFromTop()
IRECT IRECT::GetFromTop (float amount) const inline
Get a subrect of this IRECT bounded in Y by the top edge and 'amount'.
Parameters
amount Size in Y of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1045 of file IGraphicsStructs.h.
References IRECT().
Referenced by TestDragAndDropControl::Draw(), TestFontControl::Draw(), IVectorBase::MakeRects(), and ReduceFromTop().
GetFromTRHC()
IRECT IRECT::GetFromTRHC (float w, float h) const inline
Get a subrect of this IRECT expanding from the top-right corner.
Parameters
w Width of the desired IRECT
h Height of the desired IRECT
Returns
IRECT The resulting subrect
Definition at line 1034 of file IGraphicsStructs.h.
References IRECT().
GetGridCell() [1/2]
IRECT IRECT::GetGridCell (int cellIndex, int nRows, int nColumns, EDirection dir = EDirection::Horizontal, int nCells = 1) const inline
Get a subrect (by index) of this IRECT which is a cell (or union of nCells sequential cells on same row/column) in a grid of size (nRows * nColumns)
Parameters
cellIndex Index of the desired cell in the cell grid
nRows Number of rows in the cell grid
nColumns Number of columns in the cell grid
dir Desired direction of indexing, by row (EDirection::Horizontal) or by column (EDirection::Vertical)
nCells Number of desired sequential cells to join (on same row/column)
Returns
IRECT The resulting subrect
Definition at line 1123 of file IGraphicsStructs.h.
References SubRectHorizontal(), SubRectVertical(), and Union().
GetGridCell() [2/2]
IRECT IRECT::GetGridCell (int row, int col, int nRows, int nColumns) const inline
Get a subrect (by row, column) of this IRECT which is a cell in a grid of size (nRows * nColumns)
Parameters
row Row index of the desired subrect
col Column index of the desired subrect
nRows Number of rows in the cell grid
nColumns Number of columns in the cell grid
Returns
IRECT The resulting subrect
Definition at line 1108 of file IGraphicsStructs.h.
References SubRectHorizontal(), and SubRectVertical().
Referenced by TestBlendControl::Draw(), and IVColorSwatchControl::OnResize().
GetHAlignedTo()
IRECT IRECT::GetHAlignedTo (const IRECT & sr, EAlign align) const inline
Get a rectangle the same dimensions as this one, horizontally aligned to the reference IRECT.
Parameters
sr the IRECT to use as reference
align the horizontal alignment
Returns
the new rectangle
Definition at line 1683 of file IGraphicsStructs.h.
References HAlignTo().
GetHPadded()
IRECT IRECT::GetHPadded (float padding) const inline
Get a copy of this IRECT padded in the X-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Left and right padding
Returns
IRECT the new rectangle
Definition at line 1361 of file IGraphicsStructs.h.
References IRECT().
Referenced by IPopupMenuControl::DrawCellBackground().
GetHShifted()
IRECT IRECT::GetHShifted (float x) const inline
Get a copy of this rectangle translated on the X axis.
Parameters
x Offset
Returns
IRECT the new rectangle
Definition at line 1570 of file IGraphicsStructs.h.
References GetTranslated().
GetHSliced()
IRECT IRECT::GetHSliced (float w, bool rhs = false) const inline
Get a copy of this IRECT with a new width.
Parameters
w Width of the new rectangle
rhs If true the new rectangle will expand from the right side, otherwise it will expand from the left
Returns
IRECT the new rectangle
Definition at line 1395 of file IGraphicsStructs.h.
References IRECT().
GetLengthOfShortestSide()
float IRECT::GetLengthOfShortestSide () const inline
Returns
float Either the width or the height of the rectangle, whichever is less
Definition at line 1671 of file IGraphicsStructs.h.
References H(), and W().
GetMidHPadded()
IRECT IRECT::GetMidHPadded (float padding) const inline
Get a copy of this IRECT where its width = 2 * padding but the center point on the X-axis has not changed.
Parameters
padding Left and right padding (1/2 the new width)
Returns
IRECT the new rectangle
Definition at line 1378 of file IGraphicsStructs.h.
References IRECT(), and MW().
Referenced by IVectorBase::MakeRects(), IVSliderControl::OnResize(), and IBSliderControl::OnResize().
GetMidVPadded()
IRECT IRECT::GetMidVPadded (float padding) const inline
Get a copy of this IRECT where its height = 2 * padding but the center point on the Y-axis has not changed.
Parameters
padding Top and bottom padding (1/2 the new height)
Returns
IRECT the new rectangle
Definition at line 1386 of file IGraphicsStructs.h.
References IRECT(), and MH().
Referenced by IWheelControl::Draw(), IVectorBase::MakeRects(), IVSliderControl::OnResize(), and IBSliderControl::OnResize().
GetOffset()
IRECT IRECT::GetOffset (float l, float t, float r, float b) const inline
Get a copy of this rectangle where each field is offset by a specified amount.
Parameters
l Left offset
t Top offset
r Right offset
b Bottom offset
Returns
IRECT the new rectangle
Definition at line 1542 of file IGraphicsStructs.h.
References IRECT().
GetPadded() [1/2]
IRECT IRECT::GetPadded (float padding) const inline
Get a copy of this IRECT with each value padded by padding N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Padding amount
Returns
IRECT the new rectangle
Definition at line 1340 of file IGraphicsStructs.h.
References IRECT().
Referenced by IBubbleControl::Draw(), IFPSDisplayControl::Draw(), IWheelControl::Draw(), IVNumberBoxControl::Draw(), TestArcControl::Draw(), TestBlendControl::Draw(), TestDirBrowseControl::Draw(), TestGradientControl::Draw(), TestLayerControl::Draw(), TestMultiPathControl::Draw(), TestPolyControl::Draw(), IPopupMenuControl::DrawPanelShadow(), IVectorBase::DrawPressableEllipse(), IVectorBase::DrawPressableRectangle(), IVXYPadControl::DrawWidget(), IVGroupControl::DrawWidget(), IVColorSwatchControl::DrawWidget(), IVScopeControl< MAXNC, MAXBUF >::DrawWidget(), IGraphics::IsDirty(), IVNumberBoxControl::OnAttached(), IVSliderControl::OnResize(), IVColorSwatchControl::OnResize(), ISVGSliderControl::OnResize(), IVDisplayControl::OnResize(), IVNumberBoxControl::OnResize(), TestDirBrowseControl::OnResize(), and IVGroupControl::SetBoundsBasedOnGroup().
GetPadded() [2/2]
IRECT IRECT::GetPadded (float padL, float padT, float padR, float padB) const inline
Get a copy of this IRECT with the values padded N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padL Left-padding
padT Top-padding
padR Right-padding
padB Bottom-padding
Returns
IRECT the new rectangle
Definition at line 1352 of file IGraphicsStructs.h.
References IRECT().
GetPixelAligned() [1/2]
IRECT IRECT::GetPixelAligned () const inline
Get a copy of this IRECT with PixelAlign() called.
Returns
IRECT the new rectangle
Definition at line 1220 of file IGraphicsStructs.h.
References PixelAlign().
Referenced by IGraphics::StartLayer().
GetPixelAligned() [2/2]
IRECT IRECT::GetPixelAligned (float scale) const inline
Get a copy of this IRECT with PixelAlign(scale) called.
Parameters
scale Scaling factor for the alignment
Returns
IRECT the new rectangle
Definition at line 1230 of file IGraphicsStructs.h.
References PixelAlign().
GetPixelSnapped() [1/2]
IRECT IRECT::GetPixelSnapped () const inline
Returns
IRECT A copy of this IRECT with PixelSnap() called
Definition at line 1258 of file IGraphicsStructs.h.
References PixelSnap().
Referenced by IGraphics::GetPixelSnapped().
GetPixelSnapped() [2/2]
IRECT IRECT::GetPixelSnapped (float scale) const inline
Get a copy of this IRECT with PixelSnap(scale) called.
Parameters
Scaling factor for the alignment
Returns
IRECT the new rectangle
Definition at line 1268 of file IGraphicsStructs.h.
References PixelSnap().
GetRandomPoint()
void IRECT::GetRandomPoint (float & x, float & y) const inline
Get a random point within this rectangle.
Parameters
x OUT output X value of point
y OUT output Y value of point
Definition at line 1503 of file IGraphicsStructs.h.
References H(), and W().
Referenced by GetRandomSubRect().
GetRandomSubRect()
IRECT IRECT::GetRandomSubRect () const inline
Returns
IRECT A random rectangle inside this IRECT
Definition at line 1513 of file IGraphicsStructs.h.
References GetRandomPoint(), and IRECT().
Referenced by TestAnimationControl::OnMouseDown().
GetReducedFromBottom()
IRECT IRECT::GetReducedFromBottom (float amount) const inline
Get a subrect of this IRECT reduced in height from the bottom edge by 'amount'.
Parameters
amount Size in Y to reduce by
Returns
IRECT The resulting subrect
Definition at line 1070 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVectorBase::MakeRects().
GetReducedFromLeft()
IRECT IRECT::GetReducedFromLeft (float amount) const inline
Get a subrect of this IRECT reduced in width from the left edge by 'amount'.
Parameters
amount Size in X to reduce by
Returns
IRECT The resulting subrect
Definition at line 1075 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVectorBase::MakeRects().
GetReducedFromRight()
IRECT IRECT::GetReducedFromRight (float amount) const inline
Get a subrect of this IRECT reduced in width from the right edge by 'amount'.
Parameters
amount Size in X to reduce by
Returns
IRECT The resulting subrect
Definition at line 1080 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVectorBase::MakeRects().
GetReducedFromTop()
IRECT IRECT::GetReducedFromTop (float amount) const inline
Get a subrect of this IRECT reduced in height from the top edge by 'amount'.
Parameters
amount Size in Y to reduce by
Returns
IRECT The resulting subrect
Definition at line 1065 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVectorBase::MakeRects().
GetScaled()
IRECT IRECT::GetScaled (float scale) const inline
Get a copy of this IRECT with all values multiplied by scale.
Parameters
scale The amount to multiply each value by
Returns
IRECT the resulting rectangle
Definition at line 1468 of file IGraphicsStructs.h.
References Scale().
GetScaledAboutCentre()
IRECT IRECT::GetScaledAboutCentre (float scale) const inline
Get a copy of this IRECT where the width and height are multiplied by scale without changing the center point.
Parameters
scale Scaling factor
Returns
IRECT the resulting rectangle
Definition at line 1478 of file IGraphicsStructs.h.
References ScaleAboutCentre().
Referenced by ILEDControl::Draw(), and IVectorBase::MakeRects().
GetTranslated()
IRECT IRECT::GetTranslated (float x, float y) const inline
Get a translated copy of this rectangle.
Parameters
x Offset in the X axis
y Offset in the Y axis
Returns
IRECT the new rectangle
Definition at line 1562 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVLabelControl::Draw(), IWheelControl::Draw(), PlaceHolder::Draw(), IGraphicsSkia::DrawFastDropShadow(), IVectorBase::DrawPressableEllipse(), IVectorBase::DrawPressableRectangle(), IVectorBase::DrawPressableTriangle(), IRECTList::GetFracGrid(), GetHShifted(), and GetVShifted().
GetVAlignedTo()
IRECT IRECT::GetVAlignedTo (const IRECT & sr, EVAlign align) const inline
Get a rectangle the same dimensions as this one, vertically aligned to the reference IRECT.
Parameters
sr the source IRECT to use as reference
align the vertical alignment
Returns
the new rectangle
Definition at line 1663 of file IGraphicsStructs.h.
References VAlignTo().
GetVPadded()
IRECT IRECT::GetVPadded (float padding) const inline
Get a copy of this IRECT padded in the Y-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Top and bottom padding
Returns
IRECT the new rectangle
Definition at line 1370 of file IGraphicsStructs.h.
References IRECT().
Referenced by IVPlotControl::Draw(), ITextEntryControl::Draw(), and IVGroupControl::SetBoundsBasedOnGroup().
GetVShifted()
IRECT IRECT::GetVShifted (float y) const inline
Get a copy of this rectangle translated on the Y axis.
Parameters
y Offset
Returns
IRECT the new rectangle
Definition at line 1578 of file IGraphicsStructs.h.
References GetTranslated().
GetVSliced()
IRECT IRECT::GetVSliced (float h, bool bot = false) const inline
Get a copy of this IRECT with a new height.
Parameters
h Height of the new rectangle
bot If true the new rectangle will expand from the bottom, otherwise it will expand from the top
Returns
IRECT the new rectangle
Definition at line 1407 of file IGraphicsStructs.h.
References IRECT().
H()
float IRECT::H () const inline
Returns
float the height of this IRECT
Definition at line 827 of file IGraphicsStructs.h.
Referenced by Area(), DBGPrint(), IColorPickerControl::Draw(), IVPlotControl::Draw(), ISVGKnobControl::Draw(), IFPSDisplayControl::Draw(), IVKeyboardControl::Draw(), IWheelControl::Draw(), ISkLottieControl::Draw(), TestDrawContextControl::Draw(), TestGradientControl::Draw(), TestLayerControl::Draw(), TestMultiPathControl::Draw(), TestShadowGradientControl::Draw(), IURLControl::Draw(), IGraphicsCanvas::DrawBitmap(), IGraphicsNanoVG::DrawBitmap(), IGraphics::DrawBitmapedText(), IPopupMenuControl::DrawCalloutArrow(), IGraphics::DrawData(), IGraphicsNanoVG::DrawDottedRect(), IPopupMenuControl::DrawDownArrow(), IGraphicsNanoVG::DrawFastDropShadow(), IGraphics::DrawFittedBitmap(), IGraphics::DrawFittedLayer(), IVectorBase::DrawLabel(), IGraphicsSkia::DrawMultiLineText(), IVectorBase::DrawPressableTriangle(), IPopupMenuControl::DrawSubMenuArrow(), IPopupMenuControl::DrawSubMenuCalloutArrow(), IGraphics::DrawSVG(), IPopupMenuControl::DrawUpArrow(), IVXYPadControl::DrawWidget(), IVDisplayControl::DrawWidget(), FracRectVertical(), GetCentredInside(), IRECTList::GetFracGrid(), IVKnobControl::GetKnobDragBounds(), GetLengthOfShortestSide(), GetRandomPoint(), IVectorBase::GetRoundedCornerRadius(), IFlexBox::Init(), IVectorBase::MakeRects(), IPlatformViewControl::OnAttached(), IWebViewControl::OnAttached(), ICornerResizerControl::OnMouseDblClick(), IVMultiSliderControl< MAXNC >::OnMouseDown(), IVXYPadControl::OnMouseDrag(), IShaderControl::OnMouseDrag(), IGraphicsLiveEdit::OnMouseDrag(), IShaderControl::OnMouseUp(), IVGroupControl::OnResize(), ISVGSliderControl::OnResize(), TestSizeControl::OnResize(), PlaceHolder::OnResize(), IGraphics::PathEllipse(), IGraphics::PathRoundRect(), ScaleAboutCentre(), IVGroupControl::SetBoundsBasedOnGroup(), ITextControl::SetBoundsBasedOnStr(), IControl::SetPosition(), IControl::SnapToMouse(), IVMultiSliderControl< MAXNC >::SnapToMouse(), IGraphics::StartLayer(), SubRectVertical(), IMatrix::Transform(), and VAlignTo().
HAlignTo()
void IRECT::HAlignTo (const IRECT & sr, EAlign align) inline
Horizontally align this rect to the reference IRECT.
Parameters
sr the IRECT to use as reference
align the horizontal alignment
Definition at line 1648 of file IGraphicsStructs.h.
References W().
Referenced by GetHAlignedTo().
HPad()
void IRECT::HPad (float padding) inline
Pad this IRECT in the X-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Left and right padding
Definition at line 1303 of file IGraphicsStructs.h.
Referenced by IVGroupControl::OnResize().
Inset()
IRECT IRECT::Inset (const IRECT & rhs) const inline
Offsets the input IRECT based on the parent.
Parameters
rhs IRECT to offset
Definition at line 914 of file IGraphicsStructs.h.
References IRECT().
Intersect()
IRECT IRECT::Intersect (const IRECT & rhs) const inline
Create a new IRECT that is the intersection of this IRECT and rhs.
The resulting IRECT will have the maximum L and T values and minimum R and B values of the inputs.
Parameters
rhs another IRECT
Returns
IRECT the new IRECT
Definition at line 853 of file IGraphicsStructs.h.
References Intersects(), and IRECT().
Referenced by IRECTList::GetFracGrid(), IRECTList::Optimize(), and IGraphics::PathClipRegion().
Intersects()
bool IRECT::Intersects (const IRECT & rhs) const inline
Returns true if this IRECT shares any common pixels with rhs, false otherwise.
Parameters
rhs another IRECT
Returns
true this IRECT shares any common space with rhs
false this IRECT and rhs are completely separate
Definition at line 865 of file IGraphicsStructs.h.
References Empty().
Referenced by Intersect(), and IRECTList::Optimize().
IsPixelAligned() [1/2]
bool IRECT::IsPixelAligned () const inline
Returns
true If all the values of this IRECT are within 1/1000th of being an integer
Definition at line 1178 of file IGraphicsStructs.h.
Referenced by IsPixelAligned().
IsPixelAligned() [2/2]
bool IRECT::IsPixelAligned (float scale) const inline
Return true if, when scaled by scale, this IRECT is pixel aligned When scaling this mutliples each value of the IRECT, it does not scale from the center.
Parameters
scale Scale value for the test
Returns
true The scaled IRECT is pixel-aligned
Definition at line 1191 of file IGraphicsStructs.h.
References IsPixelAligned(), and Scale().
LinearInterpolateBetween()
static IRECT IRECT::LinearInterpolateBetween (const IRECT & start, const IRECT & dest, float progress) inline static
Get a rectangle that is a linear interpolation between start and dest
Parameters
start Starting rectangle
dest Ending rectangle
progress Interpolation point
Returns
IRECT the new rectangle
Definition at line 1490 of file IGraphicsStructs.h.
Referenced by IVSlideSwitchControl::IVSlideSwitchControl().
MakeMidXYWH()
static IRECT IRECT::MakeMidXYWH (float x, float y, float w, float h) inline static
Create a new IRECT of size (y,h) centred at the given position (x,y)
Parameters
x Mid horizontal point of new IRECT
y Mid vertical point of new IRECT
w Width of new IRECT
h Height of new IRECT
Returns
the new IRECT
Definition at line 796 of file IGraphicsStructs.h.
References IRECT().
MakeXYWH()
static IRECT IRECT::MakeXYWH (float l, float t, float w, float h) inline static
Create a new IRECT with the given position and size.
Parameters
l Left/X of new IRECT
t Top/Y of new IRECT
w Width of new IRECT
h Height of new IRECT
Returns
the new IRECT
Definition at line 785 of file IGraphicsStructs.h.
References IRECT().
Mergeable()
bool IRECT::Mergeable (const IRECT & rhs) const inline
Return if this IRECT and rhs may be merged.
The two rects cover exactly the area returned by Union()
Parameters
rhs another IRECT
Returns
true this IRECT wholly contains rhs or rhs wholly contains this IRECT
false any part of these IRECTs does not overlap
Definition at line 924 of file IGraphicsStructs.h.
References Empty().
Referenced by IRECTList::Optimize().
MH()
float IRECT::MH () const inline
Returns
float the midpoint of this IRECT on the y-axis (middle-height)
Definition at line 833 of file IGraphicsStructs.h.
Referenced by IPopupMenuControl::CalculateMenuPanels(), IGraphics::CalculateTextRotation(), ISVGKnobControl::Draw(), IBKnobRotaterControl::Draw(), ILEDControl::Draw(), TestArcControl::Draw(), TestBezierControl::Draw(), TestDrawContextControl::Draw(), TestGesturesControl::Draw(), TestLayerControl::Draw(), TestMaskControl::Draw(), TestMultiPathControl::Draw(), TestPolyControl::Draw(), IURLControl::Draw(), PlaceHolder::Draw(), IPopupMenuControl::DrawCalloutArrow(), IPopupMenuControl::DrawDownArrow(), IGraphicsNanoVG::DrawMultiLineText(), IGraphics::DrawRotatedLayer(), IPopupMenuControl::DrawSubMenuArrow(), IPopupMenuControl::DrawSubMenuCalloutArrow(), IPopupMenuControl::DrawUpArrow(), IVKnobControl::DrawWidget(), IVSliderControl::DrawWidget(), GetCentredInside(), GetMidVPadded(), MidVPad(), ISVGSliderControl::OnResize(), TestColorControl::OnResize(), IGraphics::PathEllipse(), IControl::PromptUserInput(), ScaleAboutCentre(), ITextControl::SetBoundsBasedOnStr(), and ShowBubbleHorizontalActionFunc().
MidHPad()
void IRECT::MidHPad (float padding) inline
Set the width of this IRECT to 2*padding without changing it's center point on the X-axis.
Parameters
padding Left and right padding (1/2 the new width)
Definition at line 1320 of file IGraphicsStructs.h.
References MW().
MidVPad()
void IRECT::MidVPad (float padding) inline
Set the height of this IRECT to 2*padding without changing it's center point on the Y-axis.
Parameters
padding Top and bottom padding (1/2 the new height)
Definition at line 1329 of file IGraphicsStructs.h.
References MH().
MW()
float IRECT::MW () const inline
Returns
float the midpoint of this IRECT on the x-axis (middle-width)
Definition at line 830 of file IGraphicsStructs.h.
Referenced by IGraphics::CalculateTextRotation(), ISVGKnobControl::Draw(), IBKnobRotaterControl::Draw(), ILEDControl::Draw(), TestArcControl::Draw(), TestBezierControl::Draw(), TestDirBrowseControl::Draw(), TestDrawContextControl::Draw(), TestGesturesControl::Draw(), TestLayerControl::Draw(), TestMaskControl::Draw(), TestMultiPathControl::Draw(), TestPolyControl::Draw(), IURLControl::Draw(), ICaptionControl::Draw(), PlaceHolder::Draw(), IPopupMenuControl::DrawCalloutArrow(), IPopupMenuControl::DrawDownArrow(), IGraphicsNanoVG::DrawMultiLineText(), IVectorBase::DrawPressableTriangle(), IGraphics::DrawRotatedLayer(), IPopupMenuControl::DrawSubMenuCalloutArrow(), IPopupMenuControl::DrawUpArrow(), IVKnobControl::DrawWidget(), IVSliderControl::DrawWidget(), IVGroupControl::DrawWidget(), GetCentredInside(), GetMidHPadded(), MidHPad(), IGraphics::PathEllipse(), IControl::PromptUserInput(), ScaleAboutCentre(), ITextControl::SetBoundsBasedOnStr(), and ShowBubbleVerticalActionFunc().
Offset()
void IRECT::Offset (float l, float t, float r, float b) inline
Offset each field of the rectangle.
Parameters
l Left offset
t Top offset
r Right offset
b Bottom offset
Definition at line 1528 of file IGraphicsStructs.h.
Referenced by IVectorBase::GetAdjustedHandleBounds(), and IVGroupControl::OnResize().
operator!=()
bool IRECT::operator!= (const IRECT & rhs) const inline
Definition at line 818 of file IGraphicsStructs.h.
operator==()
bool IRECT::operator== (const IRECT & rhs) const inline
Definition at line 813 of file IGraphicsStructs.h.
Pad() [1/2]
void IRECT::Pad (float padding) inline
Pad this IRECT N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Padding amount
Definition at line 1278 of file IGraphicsStructs.h.
Referenced by GFXLabelControl::Draw(), IVectorBase::GetAdjustedHandleBounds(), IVNumberBoxControl::OnAttached(), and IVNumberBoxControl::OnResize().
Pad() [2/2]
void IRECT::Pad (float padL, float padT, float padR, float padB) inline
Pad this IRECT N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padL Left-padding
padT Top-padding
padR Right-padding
padB Bottom-padding
Definition at line 1292 of file IGraphicsStructs.h.
PixelAlign() [1/2]
void IRECT::PixelAlign () inline
Pixel aligns the rect in an inclusive manner (moves all points outwards)
Definition at line 1199 of file IGraphicsStructs.h.
Referenced by IGraphics::Draw(), GetPixelAligned(), IRECTList::PixelAlign(), and PixelAlign().
PixelAlign() [2/2]
void IRECT::PixelAlign (float scale) inline
Pixel-align this IRECT at the given scale factor then scale it back down When scaling this mutliples each value of the IRECT, it does not scale from the center.
Parameters
scale Scale value for the alignment
Definition at line 1210 of file IGraphicsStructs.h.
References PixelAlign(), and Scale().
PixelSnap() [1/2]
void IRECT::PixelSnap () inline
Pixel aligns to nearest pixels This may make the IRECT smaller, unlike PixelAlign().
Definition at line 1239 of file IGraphicsStructs.h.
Referenced by GetPixelSnapped(), and PixelSnap().
PixelSnap() [2/2]
void IRECT::PixelSnap (float scale) inline
Pixel align a scaled version of this IRECT.
Parameters
scale Scaling factor for the alignment
Definition at line 1249 of file IGraphicsStructs.h.
References PixelSnap(), and Scale().
ReduceFromBottom()
IRECT IRECT::ReduceFromBottom (float amount) inline
Reduce in height from the bottom edge by 'amount' and return the removed region.
Parameters
amount Size in Y to reduce by
Returns
IRECT The removed subrect
Definition at line 1090 of file IGraphicsStructs.h.
References GetFromBottom().
Referenced by IVectorBase::DrawPressableEllipse(), and IVectorBase::DrawPressableRectangle().
ReduceFromLeft()
IRECT IRECT::ReduceFromLeft (float amount) inline
Reduce in width from the left edge by 'amount' and return the removed region.
Parameters
amount Size in X to reduce by
Returns
IRECT The removed subrect
Definition at line 1095 of file IGraphicsStructs.h.
References GetFromLeft().
Referenced by IVNumberBoxControl::OnAttached(), and IVNumberBoxControl::OnResize().
ReduceFromRight()
IRECT IRECT::ReduceFromRight (float amount) inline
Reduce in width from the right edge by 'amount' and return the removed region.
Parameters
amount Size in X to reduce by
Returns
IRECT The removed subrect
Definition at line 1100 of file IGraphicsStructs.h.
References GetFromRight().
Referenced by IVectorBase::DrawPressableEllipse(), and IVectorBase::DrawPressableRectangle().
ReduceFromTop()
IRECT IRECT::ReduceFromTop (float amount) inline
Reduce in height from the top edge by 'amount' and return the removed region.
Parameters
amount Size in Y to reduce by
Returns
IRECT The removed subrect
Definition at line 1085 of file IGraphicsStructs.h.
References GetFromTop().
Scale()
void IRECT::Scale (float scale) inline
Multiply each field of this IRECT by scale.
Parameters
scale The amount to multiply each field by
Definition at line 1443 of file IGraphicsStructs.h.
Referenced by IGraphicsCanvas::DrawBitmap(), GetScaled(), IsPixelAligned(), PixelAlign(), and PixelSnap().
ScaleAboutCentre()
void IRECT::ScaleAboutCentre (float scale) inline
Scale the width and height of this IRECT by scale without changing the center point.
Parameters
scale The scaling factor
Definition at line 1453 of file IGraphicsStructs.h.
References H(), MH(), MW(), and W().
Referenced by GetScaledAboutCentre().
SubRect()
IRECT IRECT::SubRect (EDirection layoutDir, int numSlices, int sliceIdx) const inline
Get a new rectangle which is a "slice" of this rectangle.
Parameters
layoutDir EDirection::Vertical or EDirection::Horizontal
numSlices Number of equal-sized parts to divide this IRECT into
sliceIdx Which "slice" to return
Returns
IRECT the new rectangle
Definition at line 1010 of file IGraphicsStructs.h.
References SubRectHorizontal(), and SubRectVertical().
Referenced by IVTabSwitchControl::OnResize().
SubRectHorizontal()
IRECT IRECT::SubRectHorizontal (int numSlices, int sliceIdx) const inline
Returns a new IRECT which is a vertical "slice" of this IRECT.
First divide the current width into numSlices equal parts, then return the n'th "slice" where "n" is sliceIdx. The returned IRECT will have the same height as this IRECT.
Parameters
numSlices number of equal-sized parts to divide this IRECT into
sliceIdx which "slice" to select
Returns
IRECT the new IRECT
Definition at line 997 of file IGraphicsStructs.h.
References IRECT(), and W().
Referenced by GetGridCell(), and SubRect().
SubRectVertical()
IRECT IRECT::SubRectVertical (int numSlices, int sliceIdx) const inline
Returns a new IRECT which is a horizontal "slice" of this IRECT.
First divide the current height into numSlices equal parts, then return the n'th "slice" where "n" is sliceIdx. The returned IRECT will have the same width as this IRECT.
Parameters
numSlices number of equal-sized parts to divide this IRECT into
sliceIdx which "slice" to select
Returns
IRECT the new IRECT
Definition at line 982 of file IGraphicsStructs.h.
References H(), and IRECT().
Referenced by GetGridCell(), and SubRect().
Translate()
void IRECT::Translate (float x, float y) inline
Translate this rectangle.
Parameters
x Offset in the X axis
y Offset in the Y axis
Definition at line 1550 of file IGraphicsStructs.h.
Referenced by IGraphicsNanoVG::ApplyShadowMask(), IGraphics::DoMeasureTextRotation(), and IVGroupControl::OnResize().
Union()
IRECT IRECT::Union (const IRECT & rhs) const inline
Create a new IRECT that is a union of this IRECT and rhs.
The resulting IRECT will have the minimim L and T values and maximum R and B values of the inputs.
Parameters
rhs another IRECT
Returns
IRECT the new IRECT
Definition at line 842 of file IGraphicsStructs.h.
References Empty(), and IRECT().
Referenced by IRECTList::Bounds(), IPopupMenuControl::CalculateMenuPanels(), IGraphics::CalculateTextRotation(), and GetGridCell().
VAlignTo()
void IRECT::VAlignTo (const IRECT & sr, EVAlign align) inline
Vertically align this rect to the reference IRECT.
Parameters
sr the source IRECT to use as reference
align the vertical alignment
Definition at line 1634 of file IGraphicsStructs.h.
References H().
Referenced by GetVAlignedTo().
VPad()
void IRECT::VPad (float padding) inline
Pad this IRECT in the Y-axis N.B.
Using a positive padding value will expand the IRECT, a negative value will contract it
Parameters
padding Top and bottom padding
Definition at line 1312 of file IGraphicsStructs.h.
W()
float IRECT::W () const inline
Returns
float the width of this IRECT
Definition at line 824 of file IGraphicsStructs.h.
Referenced by Area(), IPopupMenuControl::CreatePopupMenu(), DBGPrint(), IGraphicsCanvas::DoMeasureText(), IGraphicsNanoVG::DoMeasureText(), IGraphicsSkia::DoMeasureText(), IColorPickerControl::Draw(), IVPlotControl::Draw(), ISVGKnobControl::Draw(), IFPSDisplayControl::Draw(), ILEDControl::Draw(), IVKeyboardControl::Draw(), IWheelControl::Draw(), ISkLottieControl::Draw(), TestArcControl::Draw(), TestDrawContextControl::Draw(), TestFontControl::Draw(), TestLayerControl::Draw(), TestMaskControl::Draw(), TestMultiPathControl::Draw(), TestPolyControl::Draw(), TestShadowGradientControl::Draw(), IURLControl::Draw(), ICaptionControl::Draw(), IGraphicsCanvas::DrawBitmap(), IGraphicsNanoVG::DrawBitmap(), IGraphics::DrawBitmapedText(), IGraphics::DrawData(), IGraphicsNanoVG::DrawDottedRect(), IGraphicsNanoVG::DrawFastDropShadow(), IGraphics::DrawFittedBitmap(), IGraphics::DrawFittedLayer(), IGraphicsNanoVG::DrawMultiLineText(), IGraphicsSkia::DrawMultiLineText(), IVectorBase::DrawPressableTriangle(), IGraphics::DrawSVG(), IVRadioButtonControl::DrawWidget(), IVKnobControl::DrawWidget(), IVXYPadControl::DrawWidget(), IVDisplayControl::DrawWidget(), FracRectHorizontal(), GetCentredInside(), IRECTList::GetFracGrid(), IVKnobControl::GetKnobDragBounds(), GetLengthOfShortestSide(), GetRandomPoint(), IVectorBase::GetRoundedCornerRadius(), HAlignTo(), IFlexBox::Init(), IVectorBase::MakeRects(), IPlatformViewControl::OnAttached(), IVNumberBoxControl::OnAttached(), IWebViewControl::OnAttached(), ICornerResizerControl::OnMouseDblClick(), IVXYPadControl::OnMouseDrag(), IShaderControl::OnMouseDrag(), IGraphicsLiveEdit::OnMouseDrag(), IShaderControl::OnMouseUp(), ISVGSliderControl::OnResize(), IVKeyboardControl::OnResize(), IVNumberBoxControl::OnResize(), TestDirBrowseControl::OnResize(), TestSizeControl::OnResize(), PlaceHolder::OnResize(), IGraphics::PathEllipse(), IGraphics::PathRoundRect(), ScaleAboutCentre(), ITextControl::SetBoundsBasedOnStr(), IControl::SetPosition(), IControl::SnapToMouse(), IVMultiSliderControl< MAXNC >::SnapToMouse(), IGraphics::StartLayer(), SubRectHorizontal(), and IMatrix::Transform().
Member Data Documentation
B
float IRECT::B
Definition at line 750 of file IGraphicsStructs.h.
L
float IRECT::L
Definition at line 750 of file IGraphicsStructs.h.
R
float IRECT::R
Definition at line 750 of file IGraphicsStructs.h.
T
float IRECT::T
Definition at line 750 of file IGraphicsStructs.h.
The documentation for this struct was generated from the following file:
IGraphicsStructs.h