iPlug 2: IParam::ShapePowCurve Struct Reference
IParam::ShapePowCurve Struct Reference
PowCurve parameter shaping.
#include <IPlugParameter.h>
Public Member Functions
ShapePowCurve (double shape)
Shape * Clone () const override
IParam::EDisplayType GetDisplayType () const override
double NormalizedToValue (double value, const IParam &param) const override
Returns the real value from a normalized input, based on an IParam's settings.
double ValueToNormalized (double value, const IParam &param) const override
Returns the normalized value from a real value, based on an IParam's settings.
Public Member Functions inherited from IParam::Shape
virtual Shape * Clone () const =0
virtual void Init (const IParam &param)
Initializes the shape instance.
virtual EDisplayType GetDisplayType () const =0
virtual double NormalizedToValue (double value, const IParam &param) const =0
Returns the real value from a normalized input, based on an IParam's settings.
virtual double ValueToNormalized (double value, const IParam &param) const =0
Returns the normalized value from a real value, based on an IParam's settings.
Public Attributes
double mShape
Detailed Description
PowCurve parameter shaping.
Definition at line 114 of file IPlugParameter.h.
Constructor & Destructor Documentation
ShapePowCurve()
IParam::ShapePowCurve::ShapePowCurve (double shape)
Definition at line 36 of file IPlugParameter.cpp.
Member Function Documentation
Clone()
Shape * IParam::ShapePowCurve::Clone () const inline override virtual
Returns
A new instance of this Shape struct
Implements IParam::Shape.
Definition at line 117 of file IPlugParameter.h.
GetDisplayType()
IParam::EDisplayType IParam::ShapePowCurve::GetDisplayType () const override virtual
Returns
EDisplayType, used by AudioUnit plugins to determine the mapping of parameters
Implements IParam::Shape.
Definition at line 41 of file IPlugParameter.cpp.
NormalizedToValue()
double IParam::ShapePowCurve::NormalizedToValue (double value, const IParam & param) const override virtual
Returns the real value from a normalized input, based on an IParam's settings.
Parameters
value The normalized value as a double to be converted
param The IParam to do the calculation against
Returns
double The real value
Implements IParam::Shape.
Definition at line 51 of file IPlugParameter.cpp.
References IParam::GetMax(), and IParam::GetMin().
ValueToNormalized()
double IParam::ShapePowCurve::ValueToNormalized (double value, const IParam & param) const override virtual
Returns the normalized value from a real value, based on an IParam's settings.
Parameters
value The real value as a double to be converted
param The IParam to do the calculation against
Returns
double The normalized value
Implements IParam::Shape.
Definition at line 56 of file IPlugParameter.cpp.
References IParam::GetMax(), and IParam::GetMin().
Member Data Documentation
mShape
double IParam::ShapePowCurve::mShape
Definition at line 122 of file IPlugParameter.h.
The documentation for this struct was generated from the following files:
IPlugParameter.h
IPlugParameter.cpp